gem5: mem/ruby/common/Address.hh File Reference
mem/ruby/common/Address.hh File Reference
#include <cassert>
#include <iomanip>
#include <iostream>
#include "base/hashmap.hh"
#include "mem/ruby/common/TypeDefines.hh"
Classes
class Address
struct hash< Address >
struct std::equal_to< Address >
Namespaces
namespace std
Typedefs
typedef Address PhysAddress
typedef Address VirtAddress
Functions
Address line_address (const Address &addr)
bool operator< (const Address &obj1, const Address &obj2)
std::ostream & operator<< (std::ostream &out, const Address &obj)
bool operator== (const Address &obj1, const Address &obj2)
bool operator!= (const Address &obj1, const Address &obj2)
Address next_stride_address (const Address &addr, int stride)
Address page_address (const Address &addr)
Variables
const uint32_t ADDRESS_WIDTH = 64
Typedef Documentation
typedef Address PhysAddress
Definition at line 41 of file Address.hh.
typedef Address VirtAddress
Definition at line 43 of file Address.hh.
Function Documentation
Address line_address (const Address & addr) [inline]
Definition at line 97 of file Address.hh.
References Address::makeLineAddress().
Referenced by Prefetcher::accessNonunitFilter(), Prefetcher::accessUnitFilter(), SparseMemory::add(), CacheMemory::addressToCacheSet(), PerfectCacheMemory< ENTRY >::allocate(), CacheMemory::allocate(), CacheMemory::cacheAvail(), CacheMemory::cacheProbe(), PerfectCacheMemory< ENTRY >::changePermission(), CacheMemory::clearLocked(), PersistentTable::countReadStarvingForAddress(), PersistentTable::countStarvingForAddress(), PerfectCacheMemory< ENTRY >::deallocate(), CacheMemory::deallocate(), SparseMemory::exist(), PersistentTable::findSmallest(), CacheMemory::findTagInSet(), CacheMemory::findTagInSetIgnorePermissions(), PerfectCacheMemory< ENTRY >::getPermission(), Prefetcher::initializeStream(), PersistentTable::isLocked(), CacheMemory::isLocked(), TBETable< ENTRY >::isPresent(), DMASequencer::issueNext(), PerfectCacheMemory< ENTRY >::isTagPresent(), CacheMemory::isTagPresent(), SparseMemory::lookup(), PerfectCacheMemory< ENTRY >::lookup(), CacheMemory::lookup(), DMASequencer::makeRequest(), PersistentTable::markEntries(), Prefetcher::observeMiss(), PersistentTable::okToIssueStarving(), PersistentTable::persistentRequestLock(), PersistentTable::persistentRequestUnlock(), Sequencer::readCallback(), RubyPort::M5Port::recvFunctional(), SparseMemory::remove(), TimerTable::set(), CacheMemory::setLocked(), CacheMemory::testCacheAccess(), CacheMemory::tryCacheAccess(), PersistentTable::typeOfSmallest(), TimerTable::unset(), and Sequencer::writeCallback().
Address next_stride_address (const Address & addr, int stride)
Definition at line 154 of file Address.cc.
References Address::makeNextStrideAddress().
Referenced by Prefetcher::accessUnitFilter(), Prefetcher::getPrefetchEntry(), Prefetcher::initializeStream(), and Prefetcher::issueNextPrefetch().
bool operator!= (const Address & obj1, const Address & obj2) [inline]
Definition at line 125 of file Address.hh.
References Address::getAddress().
bool operator< (const Address & obj1, const Address & obj2) [inline]
Definition at line 105 of file Address.hh.
References Address::getAddress().
std::ostream& operator<< (std::ostream & out, const Address & obj) [inline]
Definition at line 111 of file Address.hh.
References Address::print().
bool operator== (const Address & obj1, const Address & obj2) [inline]
Definition at line 119 of file Address.hh.
References Address::getAddress().
Address page_address (const Address & addr)
Definition at line 146 of file Address.cc.
References Address::makePageAddress().
Referenced by Prefetcher::accessNonunitFilter(), Prefetcher::initializeStream(), and Prefetcher::issueNextPrefetch().
Variable Documentation
const uint32_t ADDRESS_WIDTH = 64
Definition at line 39 of file Address.hh.
Referenced by Address::bitRemove(), Address::bitSelect(), Address::getLineAddress(), Address::maskHighOrderBits(), Address::maskLowOrderBits(), and Address::memoryModuleIndex().