gem5: arch/power/linux/process.cc File Reference
arch/power/linux/process.cc File Reference
#include "arch/power/linux/linux.hh"
#include "arch/power/linux/process.hh"
#include "arch/power/isa_traits.hh"
#include "base/trace.hh"
#include "cpu/thread_context.hh"
#include "kern/linux/linux.hh"
#include "sim/process.hh"
#include "sim/syscall_emul.hh"
#include "sim/system.hh"
Functions
static SyscallReturn unameFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target uname() handler.
Function Documentation
static SyscallReturn unameFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [static]
Target uname() handler.
Definition at line 50 of file process.cc.
References ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and name().