gem5: arch/x86/process.cc File Reference
arch/x86/process.cc File Reference
#include "arch/x86/regs/misc.hh"
#include "arch/x86/regs/segment.hh"
#include "arch/x86/isa_traits.hh"
#include "arch/x86/process.hh"
#include "arch/x86/types.hh"
#include "base/loader/elf_object.hh"
#include "base/loader/object_file.hh"
#include "base/misc.hh"
#include "base/trace.hh"
#include "cpu/thread_context.hh"
#include "debug/Stack.hh"
#include "mem/page_table.hh"
#include "sim/process_impl.hh"
#include "sim/syscall_emul.hh"
#include "sim/system.hh"
Variables
static const int ArgumentReg []
static const int NumArgumentRegs = sizeof(ArgumentReg) / sizeof(const int)
static const int ArgumentReg32 []
static const int NumArgumentRegs32 = sizeof(ArgumentReg) / sizeof(const int)
Variable Documentation
const int ArgumentReg[] [static]
Initial value:
 {
    INTREG_RDI,
    INTREG_RSI,
    INTREG_RDX,
    INTREG_R10W,
    INTREG_R8W,
    INTREG_R9W
}
Definition at line 63 of file process.cc.
Referenced by X86ISA::I386LiveProcess::getSyscallArg(), X86ISA::X86_64LiveProcess::getSyscallArg(), X86ISA::I386LiveProcess::setSyscallArg(), and X86ISA::X86_64LiveProcess::setSyscallArg().
const int ArgumentReg32[] [static]
Initial value:
 {
    INTREG_EBX,
    INTREG_ECX,
    INTREG_EDX,
    INTREG_ESI,
    INTREG_EDI,
}
Definition at line 74 of file process.cc.
Referenced by X86ISA::I386LiveProcess::getSyscallArg().
const int NumArgumentRegs = sizeof(ArgumentReg) / sizeof(const int) [static]
Definition at line 73 of file process.cc.
Referenced by X86ISA::I386LiveProcess::getSyscallArg(), X86ISA::X86_64LiveProcess::getSyscallArg(), X86ISA::I386LiveProcess::setSyscallArg(), and X86ISA::X86_64LiveProcess::setSyscallArg().
const int NumArgumentRegs32 = sizeof(ArgumentReg) / sizeof(const int) [static]
Definition at line 81 of file process.cc.
Referenced by X86ISA::I386LiveProcess::getSyscallArg().