gem5: arch/x86/system.cc File Reference
arch/x86/system.cc File Reference
#include "arch/x86/bios/intelmp.hh"
#include "arch/x86/bios/smbios.hh"
#include "arch/x86/regs/misc.hh"
#include "arch/x86/isa_traits.hh"
#include "arch/x86/system.hh"
#include "arch/vtophys.hh"
#include "base/loader/object_file.hh"
#include "base/loader/symtab.hh"
#include "base/intmath.hh"
#include "base/trace.hh"
#include "cpu/thread_context.hh"
#include "mem/port_proxy.hh"
#include "params/X86System.hh"
#include "sim/byteswap.hh"
Functions
static void installSegDesc (ThreadContext *tc, SegmentRegIndex seg, SegDescriptor desc, bool longmode)
Function Documentation
static void installSegDesc (ThreadContext * tc, SegmentRegIndex seg, SegDescriptor desc, bool longmode) [static]
Definition at line 67 of file system.cc.
References X86ISA::base, X86ISA::MISCREG_SEG_ATTR(), X86ISA::MISCREG_SEG_BASE(), X86ISA::MISCREG_SEG_EFF_BASE(), X86ISA::MISCREG_SEG_LIMIT(), X86ISA::SEGMENT_REG_FS, X86ISA::SEGMENT_REG_GS, X86ISA::SEGMENT_REG_TSL, and ThreadContext::setMiscReg().
Referenced by X86System::initState().