gem5: arch/alpha/tru64/process.cc File Reference
arch/alpha/tru64/process.cc File Reference
#include "arch/alpha/tru64/process.hh"
#include "arch/alpha/tru64/tru64.hh"
#include "arch/alpha/isa_traits.hh"
#include "cpu/thread_context.hh"
#include "kern/tru64/tru64.hh"
#include "sim/byteswap.hh"
#include "sim/process.hh"
#include "sim/syscall_emul.hh"
Functions
static SyscallReturn unameFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target uname() handler.
static SyscallReturn getsysinfoFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target getsysyinfo() handler.
static SyscallReturn setsysinfoFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target setsysyinfo() handler.
static SyscallReturn tableFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target table() handler.
Function Documentation
static SyscallReturn getsysinfoFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [static]
Target getsysyinfo() handler.
Definition at line 64 of file process.cc.
References BufferArg::bufferPtr(), BaseBufferArg::copyOut(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), AlphaTru64::GSI_CLK_TCK, AlphaTru64::GSI_CPU_INFO, AlphaTru64::GSI_CPUS_IN_BOX, AlphaTru64::GSI_MAX_CPU, AlphaTru64::GSI_PHYSMEM, AlphaTru64::GSI_PLATFORM_NAME, AlphaTru64::GSI_PROC_TYPE, BigEndianGuest::htog(), MipsISA::index, Process::numCpus(), X86ISA::op, and warn.
static SyscallReturn setsysinfoFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [static]
Target setsysyinfo() handler.
Definition at line 145 of file process.cc.
References LiveProcess::getSyscallArg(), MipsISA::index, X86ISA::op, AlphaTru64::SSI_IEEE_FP_CONTROL, and warn.
static SyscallReturn tableFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [static]
Target table() handler.
Definition at line 167 of file process.cc.
References BaseBufferArg::copyOut(), curTick(), SimClock::Frequency, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), BigEndianGuest::htog(), MipsISA::index, Process::numCpus(), one_million, seconds_since_epoch, and AlphaTru64::TBL_SYSINFO.
static SyscallReturn unameFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [static]
Target uname() handler.
Definition at line 46 of file process.cc.
References ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), MipsISA::index, and name().