gem5: base/remote_gdb.cc File Reference
base/remote_gdb.cc File Reference
#include <signal.h>
#include <sys/signal.h>
#include <unistd.h>
#include <cstdio>
#include <string>
#include "arch/vtophys.hh"
#include "base/intmath.hh"
#include "base/remote_gdb.hh"
#include "base/socket.hh"
#include "base/trace.hh"
#include "config/the_isa.hh"
#include "cpu/static_inst.hh"
#include "cpu/thread_context.hh"
#include "debug/GDBAll.hh"
#include "mem/port.hh"
#include "mem/fs_translating_port_proxy.hh"
#include "mem/se_translating_port_proxy.hh"
#include "sim/full_system.hh"
#include "sim/system.hh"
Functions
void debugger ()
Variables
vector< BaseRemoteGDB * > debuggers
Function Documentation
void debugger ()
Definition at line 149 of file remote_gdb.cc.
References GDBListener::accept(), debuggers, BaseRemoteGDB::isattached(), BaseRemoteGDB::listener, and BaseRemoteGDB::trap().
Variable Documentation
vector<BaseRemoteGDB *> debuggers
Definition at line 146 of file remote_gdb.cc.
Referenced by debugger(), and GDBListener::listen().