gem5: sim/byteswap.hh File Reference
sim/byteswap.hh File Reference
#include "base/bigint.hh"
#include "base/misc.hh"
#include "base/types.hh"
#include <machine/endian.h>
Namespaces
namespace BigEndianGuest
namespace LittleEndianGuest
Enumerations
enum ByteOrder { BigEndianByteOrder, LittleEndianByteOrder }
Functions
uint64_t swap_byte64 (uint64_t x)
uint32_t swap_byte32 (uint32_t x)
uint16_t swap_byte16 (uint16_t x)
template<typename T >
T swap_byte (T x)
template<>
Twin64_t swap_byte< Twin64_t > (Twin64_t x)
template<>
Twin32_t swap_byte< Twin32_t > (Twin32_t x)
template<typename T >
T betole (T value)
template<typename T >
T letobe (T value)
template<typename T >
T htole (T value)
template<typename T >
T letoh (T value)
template<typename T >
T htobe (T value)
template<typename T >
T betoh (T value)
template<typename T >
T BigEndianGuest::gtole (T value)
template<typename T >
T BigEndianGuest::letog (T value)
template<typename T >
T BigEndianGuest::gtobe (T value)
template<typename T >
T BigEndianGuest::betog (T value)
template<typename T >
T BigEndianGuest::htog (T value)
template<typename T >
T BigEndianGuest::gtoh (T value)
template<typename T >
T LittleEndianGuest::gtole (T value)
template<typename T >
T LittleEndianGuest::letog (T value)
template<typename T >
T LittleEndianGuest::gtobe (T value)
template<typename T >
T LittleEndianGuest::betog (T value)
template<typename T >
T LittleEndianGuest::htog (T value)
template<typename T >
T LittleEndianGuest::gtoh (T value)
Variables
const ByteOrder HostByteOrder = BigEndianByteOrder
const ByteOrder BigEndianGuest::GuestByteOrder = BigEndianByteOrder
const ByteOrder LittleEndianGuest::GuestByteOrder = LittleEndianByteOrder
Enumeration Type Documentation
enum ByteOrder
Enumerator:
BigEndianByteOrder
LittleEndianByteOrder
Definition at line 61 of file byteswap.hh.
Function Documentation
template<typename T > T betoh (T value) [inline]
Definition at line 157 of file byteswap.hh.
Referenced by BigEndianGuest::gtoh(), VncServer::recvCutText(), VncServer::recvKeyboardInput(), VncServer::recvPointerInput(), VncServer::requestFbUpdate(), VncServer::setEncodings(), and VncServer::setPixelFormat().
template<typename T > T betole (T value) [inline]
Definition at line 147 of file byteswap.hh.
References swap_byte().
Referenced by LittleEndianGuest::betog(), and BigEndianGuest::gtole().
template<typename T > T htobe (T value) [inline]
Definition at line 156 of file byteswap.hh.
Referenced by VncServer::checkProtocolVersion(), VncServer::checkSecurity(), SparcISA::RemoteGDB::getregs(), BigEndianGuest::htog(), IGbE::IGbE(), MmDisk::read(), VncServer::sendFrameBufferResized(), VncServer::sendFrameBufferUpdate(), VncServer::sendServerInit(), and MmDisk::write().
template<typename T > T htole (T value) [inline]
Definition at line 154 of file byteswap.hh.
References swap_byte().
Referenced by LittleEndianGuest::htog(), IdeController::IdeController(), PciDev::PciDev(), IGbE::RxDescCache::pktComplete(), IdeController::readConfig(), PciDev::writeConfig(), IdeController::writeConfig(), and IGbE::RxDescCache::writePacket().
template<typename T > T letobe (T value) [inline]
Definition at line 148 of file byteswap.hh.
References swap_byte().
Referenced by LittleEndianGuest::gtobe(), and BigEndianGuest::letog().
template<typename T > T letoh (T value) [inline]
Definition at line 155 of file byteswap.hh.
References swap_byte().
Referenced by LittleEndianGuest::gtoh(), PciDev::interruptLine(), PciDev::intrClear(), PciDev::intrPost(), PciDev::PciDev(), SafeReadSwap(), SafeWriteSwap(), and PciDev::writeConfig().
template<typename T > T swap_byte (T x) [inline]
Definition at line 116 of file byteswap.hh.
References panic, swap_byte16(), swap_byte32(), and swap_byte64().
Referenced by betole(), htole(), letobe(), and letoh().
uint16_t swap_byte16 (uint16_t x) [inline]
Definition at line 99 of file byteswap.hh.
Referenced by swap_byte().
uint32_t swap_byte32 (uint32_t x) [inline]
Definition at line 85 of file byteswap.hh.
Referenced by swap_byte().
uint64_t swap_byte64 (uint64_t x) [inline]
Definition at line 66 of file byteswap.hh.
Referenced by swap_byte().
template<> Twin32_t swap_byte< Twin32_t > (Twin32_t x) [inline]
template<> Twin64_t swap_byte< Twin64_t > (Twin64_t x) [inline]
Variable Documentation
const ByteOrder HostByteOrder = BigEndianByteOrder
Definition at line 153 of file byteswap.hh.