gem5: base/cast.hh File Reference
base/cast.hh File Reference
#include <cassert>
Functions
template<class T , class U >
T safe_cast (U ptr)
Function Documentation
template<class T , class U > T safe_cast (U ptr) [inline]
Definition at line 61 of file cast.hh.
Referenced by RubyMemoryControl::enqueue(), NetworkInterface::flitisizeMessage(), NetworkInterface_d::flitisizeMessage(), GarnetNetwork::GarnetNetwork(), GarnetNetwork_d::GarnetNetwork_d(), Sequencer::hitCallback(), Stats::DataWrap< SparseHistogram, SparseHistInfoProxy >::info(), GarnetNetwork::init(), GarnetNetwork_d::init(), GarnetNetwork::makeInLink(), GarnetNetwork_d::makeInLink(), SimpleNetwork::makeInternalLink(), GarnetNetwork::makeInternalLink(), GarnetNetwork_d::makeInternalLink(), SimpleNetwork::makeOutLink(), GarnetNetwork::makeOutLink(), GarnetNetwork_d::makeOutLink(), Packet::popLabel(), Stats::AvgSampleStor::prepare(), Stats::SampleStor::prepare(), Stats::HistStor::prepare(), Stats::DistStor::prepare(), Packet::pushLabel(), RubyPort::M5Port::recvTimingReq(), RubyPort::PioPort::recvTimingResp(), RubyTester::CpuPort::recvTimingResp(), Stats::HistStor::reset(), Stats::DistStor::reset(), Router::routeCompute(), RoutingUnit_d::routeCompute(), RubyPort::ruby_hit_callback(), SimpleNetwork::SimpleNetwork(), Throttle::wakeup(), and PerfectSwitch::wakeup().