gem5: MipsISA::ProcessInfo Class Reference
MipsISA::ProcessInfo Class Reference
#include <stacktrace.hh>
Public Member Functions
ProcessInfo (ThreadContext *_tc)
Addr task (Addr ksp) const
int pid (Addr ksp) const
std::string name (Addr ksp) const
Private Attributes
ThreadContext * tc
int thread_info_size
int task_struct_size
int task_off
int pid_off
int name_off
Detailed Description
Definition at line 43 of file stacktrace.hh.
Constructor & Destructor Documentation
ProcessInfo::ProcessInfo (ThreadContext * _tc)
Definition at line 46 of file stacktrace.cc.
Member Function Documentation
string ProcessInfo::name (Addr ksp) const
Definition at line 80 of file stacktrace.cc.
References CopyStringOut(), name_off, task(), and tc.
int ProcessInfo::pid (Addr ksp) const
Definition at line 65 of file stacktrace.cc.
References ThreadContext::getVirtProxy(), pid_off, task(), and tc.
Addr ProcessInfo::task (Addr ksp) const
Definition at line 50 of file stacktrace.cc.
References X86ISA::base, ThreadContext::getVirtProxy(), task_off, tc, and ULL.
Referenced by name(), and pid().
Member Data Documentation
int MipsISA::ProcessInfo::name_off [private]
Definition at line 52 of file stacktrace.hh.
Referenced by name().
int MipsISA::ProcessInfo::pid_off [private]
Definition at line 51 of file stacktrace.hh.
Referenced by pid().
int MipsISA::ProcessInfo::task_off [private]
Definition at line 50 of file stacktrace.hh.
Referenced by task().
int MipsISA::ProcessInfo::task_struct_size [private]
Definition at line 49 of file stacktrace.hh.
ThreadContext* MipsISA::ProcessInfo::tc [private]
Definition at line 46 of file stacktrace.hh.
Referenced by name(), pid(), and task().
int MipsISA::ProcessInfo::thread_info_size [private]
Definition at line 48 of file stacktrace.hh.
The documentation for this class was generated from the following files:
arch/mips/stacktrace.hh
arch/mips/stacktrace.cc