gem5: SubBlock Class Reference
SubBlock Class Reference
#include <SubBlock.hh>
Public Member Functions
SubBlock ()
SubBlock (const Address &addr, int size)
~SubBlock ()
const Address & getAddress () const
void setAddress (const Address &addr)
int getSize () const
void resize (int size)
uint8_t getByte (int offset) const
void setByte (int offset, uint8_t data)
uint8_t readByte () const
void writeByte (uint8_t data)
void mergeTo (DataBlock &data) const
void mergeFrom (const DataBlock &data)
void print (std::ostream &out) const
Private Member Functions
void internalMergeTo (DataBlock &data) const
void internalMergeFrom (const DataBlock &data)
Private Attributes
Address m_address
std::vector< uint8_t > m_data
Detailed Description
Definition at line 39 of file SubBlock.hh.
Constructor & Destructor Documentation
SubBlock::SubBlock () [inline]
Definition at line 42 of file SubBlock.hh.
SubBlock::SubBlock (const Address & addr, int size)
Definition at line 34 of file SubBlock.cc.
References ArmISA::i, m_address, resize(), and setByte().
SubBlock::~SubBlock () [inline]
Definition at line 44 of file SubBlock.hh.
Member Function Documentation
const Address& SubBlock::getAddress () const [inline]
Definition at line 46 of file SubBlock.hh.
References m_address.
Referenced by RubyTester::hitCallback(), and Check::performCallback().
uint8_t SubBlock::getByte (int offset) const [inline]
Definition at line 51 of file SubBlock.hh.
References m_data.
Referenced by RubyTester::hitCallback(), internalMergeTo(), Check::performCallback(), and readByte().
int SubBlock::getSize () const [inline]
Definition at line 49 of file SubBlock.hh.
References m_data.
Referenced by RubyTester::hitCallback(), internalMergeFrom(), internalMergeTo(), and print().
void SubBlock::internalMergeFrom (const DataBlock & data) [private]
Definition at line 44 of file SubBlock.cc.
References DataBlock::getByte(), Address::getOffset(), getSize(), ArmISA::i, m_address, ArmISA::offset, and setByte().
Referenced by mergeFrom().
void SubBlock::internalMergeTo (DataBlock & data) const [private]
Definition at line 55 of file SubBlock.cc.
References getByte(), Address::getOffset(), getSize(), ArmISA::i, m_address, ArmISA::offset, and DataBlock::setByte().
Referenced by mergeTo().
void SubBlock::mergeFrom (const DataBlock & data) [inline]
Definition at line 61 of file SubBlock.hh.
References internalMergeFrom().
void SubBlock::mergeTo (DataBlock & data) const [inline]
Definition at line 60 of file SubBlock.hh.
References internalMergeTo().
void SubBlock::print (std::ostream & out) const
Definition at line 67 of file SubBlock.cc.
References getSize(), m_address, and m_data.
Referenced by operator<<().
uint8_t SubBlock::readByte () const [inline]
Definition at line 55 of file SubBlock.hh.
References getByte().
void SubBlock::resize (int size) [inline]
Definition at line 50 of file SubBlock.hh.
References m_data.
Referenced by SubBlock().
void SubBlock::setAddress (const Address & addr) [inline]
Definition at line 47 of file SubBlock.hh.
References m_address.
void SubBlock::setByte (int offset, uint8_t data) [inline]
Definition at line 52 of file SubBlock.hh.
References m_data.
Referenced by internalMergeFrom(), Check::performCallback(), SubBlock(), and writeByte().
void SubBlock::writeByte (uint8_t data) [inline]
Definition at line 56 of file SubBlock.hh.
References setByte().
Member Data Documentation
Address SubBlock::m_address [private]
Definition at line 70 of file SubBlock.hh.
Referenced by getAddress(), internalMergeFrom(), internalMergeTo(), print(), setAddress(), and SubBlock().
std::vector<uint8_t> SubBlock::m_data [private]
Definition at line 71 of file SubBlock.hh.
Referenced by getByte(), getSize(), print(), resize(), and setByte().
The documentation for this class was generated from the following files:
mem/ruby/common/SubBlock.hh
mem/ruby/common/SubBlock.cc