gem5: PioPort Class Reference
PioPort Class Reference
The PioPort class is a programmed i/o port that all devices that are sensitive to an address range use.
#include <io_device.hh>