gem5: AddressProfiler Class Reference
AddressProfiler Class Reference
#include <AddressProfiler.hh>
Public Types
typedef m5::hash_map< Address,
AccessTraceForAddress > AddressMap
Public Member Functions
AddressProfiler (int num_of_sequencers)
~AddressProfiler ()
void printStats (std::ostream &out) const
void clearStats ()
void addTraceSample (Address data_addr, Address pc_addr, RubyRequestType type, RubyAccessMode access_mode, NodeID id, bool sharing_miss)
void profileRetry (const Address &data_addr, AccessType type, int count)
void profileGetX (const Address &datablock, const Address &PC, const Set &owner, const Set &sharers, NodeID requestor)
void profileGetS (const Address &datablock, const Address &PC, const Set &owner, const Set &sharers, NodeID requestor)
void print (std::ostream &out) const
void setHotLines (bool hot_lines)
void setAllInstructions (bool all_instructions)
Private Member Functions
AddressProfiler (const AddressProfiler &obj)
AddressProfiler & operator= (const AddressProfiler &obj)
Private Attributes
int64 m_sharing_miss_counter
AddressMap m_dataAccessTrace
AddressMap m_macroBlockAccessTrace
AddressMap m_programCounterAccessTrace
AddressMap m_retryProfileMap
Histogram m_retryProfileHisto
Histogram m_retryProfileHistoWrite
Histogram m_retryProfileHistoRead
Histogram m_getx_sharing_histogram
Histogram m_gets_sharing_histogram
bool m_hot_lines
bool m_all_instructions
int m_num_of_sequencers
Detailed Description
Definition at line 44 of file AddressProfiler.hh.
Member Typedef Documentation
typedef m5::hash_map<Address, AccessTraceForAddress> AddressProfiler::AddressMap
Definition at line 47 of file AddressProfiler.hh.
Constructor & Destructor Documentation
AddressProfiler::AddressProfiler (int num_of_sequencers)
Definition at line 146 of file AddressProfiler.cc.
References clearStats(), and m_num_of_sequencers.
AddressProfiler::~AddressProfiler ()
Definition at line 152 of file AddressProfiler.cc.
AddressProfiler::AddressProfiler (const AddressProfiler & obj) [private]
Member Function Documentation
void AddressProfiler::addTraceSample (Address data_addr, Address pc_addr, RubyRequestType type, RubyAccessMode access_mode, NodeID id, bool sharing_miss)
Definition at line 282 of file AddressProfiler.cc.
References lookupTraceForAddress(), m_all_instructions, m_dataAccessTrace, m_macroBlockAccessTrace, m_programCounterAccessTrace, m_sharing_miss_counter, Address::makeLineAddress(), and Address::maskLowOrderBits().
Referenced by profileGetS(), and profileGetX().
void AddressProfiler::clearStats ()
Definition at line 231 of file AddressProfiler.cc.
References Histogram::clear(), m_dataAccessTrace, m_gets_sharing_histogram, m_getx_sharing_histogram, m_macroBlockAccessTrace, m_programCounterAccessTrace, m_retryProfileHisto, m_retryProfileHistoRead, m_retryProfileHistoWrite, m_retryProfileMap, and m_sharing_miss_counter.
Referenced by AddressProfiler().
AddressProfiler& AddressProfiler::operator= (const AddressProfiler & obj) [private]
void AddressProfiler::print (std::ostream & out) const
Referenced by operator<<().
void AddressProfiler::printStats (std::ostream & out) const
Referenced by Profiler::wakeup().
void AddressProfiler::profileGetS (const Address & datablock, const Address & PC, const Set & owner, const Set & sharers, NodeID requestor)
Definition at line 265 of file AddressProfiler.cc.
References Histogram::add(), Set::addSet(), addTraceSample(), Set::count(), m_gets_sharing_histogram, and Set::remove().
void AddressProfiler::profileGetX (const Address & datablock, const Address & PC, const Set & owner, const Set & sharers, NodeID requestor)
Definition at line 247 of file AddressProfiler.cc.
References Histogram::add(), Set::addSet(), addTraceSample(), Set::count(), m_getx_sharing_histogram, and Set::remove().
void AddressProfiler::profileRetry (const Address & data_addr, AccessType type, int count)
Definition at line 319 of file AddressProfiler.cc.
References Histogram::add(), AccessTraceForAddress::addSample(), lookupTraceForAddress(), m_retryProfileHisto, m_retryProfileHistoRead, m_retryProfileHistoWrite, and m_retryProfileMap.
void AddressProfiler::setAllInstructions (bool all_instructions)
Definition at line 163 of file AddressProfiler.cc.
References m_all_instructions.
Referenced by Profiler::Profiler().
void AddressProfiler::setHotLines (bool hot_lines)
Definition at line 157 of file AddressProfiler.cc.
References m_hot_lines.
Referenced by Profiler::Profiler().
Member Data Documentation
bool AddressProfiler::m_all_instructions [private]
Definition at line 90 of file AddressProfiler.hh.
Referenced by addTraceSample(), and setAllInstructions().
AddressMap AddressProfiler::m_dataAccessTrace [private]
Definition at line 78 of file AddressProfiler.hh.
Referenced by addTraceSample(), and clearStats().
Histogram AddressProfiler::m_gets_sharing_histogram [private]
Definition at line 86 of file AddressProfiler.hh.
Referenced by clearStats(), and profileGetS().
Histogram AddressProfiler::m_getx_sharing_histogram [private]
Definition at line 85 of file AddressProfiler.hh.
Referenced by clearStats(), and profileGetX().
bool AddressProfiler::m_hot_lines [private]
Definition at line 89 of file AddressProfiler.hh.
Referenced by setHotLines().
AddressMap AddressProfiler::m_macroBlockAccessTrace [private]
Definition at line 79 of file AddressProfiler.hh.
Referenced by addTraceSample(), and clearStats().
int AddressProfiler::m_num_of_sequencers [private]
Definition at line 92 of file AddressProfiler.hh.
Referenced by AddressProfiler().
AddressMap AddressProfiler::m_programCounterAccessTrace [private]
Definition at line 80 of file AddressProfiler.hh.
Referenced by addTraceSample(), and clearStats().
Histogram AddressProfiler::m_retryProfileHisto [private]
Definition at line 82 of file AddressProfiler.hh.
Referenced by clearStats(), and profileRetry().
Histogram AddressProfiler::m_retryProfileHistoRead [private]
Definition at line 84 of file AddressProfiler.hh.
Referenced by clearStats(), and profileRetry().
Histogram AddressProfiler::m_retryProfileHistoWrite [private]
Definition at line 83 of file AddressProfiler.hh.
Referenced by clearStats(), and profileRetry().
AddressMap AddressProfiler::m_retryProfileMap [private]
Definition at line 81 of file AddressProfiler.hh.
Referenced by clearStats(), and profileRetry().
int64 AddressProfiler::m_sharing_miss_counter [private]
Definition at line 76 of file AddressProfiler.hh.
Referenced by addTraceSample(), and clearStats().
The documentation for this class was generated from the following files:
mem/ruby/profiler/AddressProfiler.hh
mem/ruby/profiler/AddressProfiler.cc