gem5: BranchPredictor Class Reference
BranchPredictor Class Reference
#include <branch_predictor.hh>