gem5: Cycles Class Reference
Cycles Class Reference
Cycles is a wrapper class for representing cycle counts, i.e.
#include <types.hh>
Public Member Functions
Cycles (uint64_t _c)
Explicit constructor assigning a value.
Cycles ()
Default constructor for parameter classes.
operator uint64_t () const
Converting back to the value type.
Cycles & operator++ ()
Prefix increment operator.
Cycles & operator-- ()
Prefix decrement operator.
const Cycles & operator+= (const Cycles &cc)
In-place addition of cycles.
bool operator> (const Cycles &cc) const
Greater than comparison used for > Cycles(0).
const Cycles operator+ (const Cycles &b) const
const Cycles operator- (const Cycles &b) const
const Cycles operator<< (const int32_t shift)
const Cycles operator>> (const int32_t shift)
Private Attributes
uint64_t c
Member holding the actual value.
Friends
std::ostream & operator<< (std::ostream &out, const Cycles &cycles)
Detailed Description
Cycles is a wrapper class for representing cycle counts, i.e.
a relative difference between two points in time, expressed in a number of clock cycles.
The Cycles wrapper class is a type-safe alternative to a typedef, aiming to avoid unintentional mixing of cycles and ticks in the code base.
Operators are defined inside an ifndef block to avoid swig touching them. Note that there is no overloading of the bool operator as the compiler is allowed to turn booleans into integers and this causes a whole range of issues in a handful locations. The solution to this problem would be to use the safe bool idiom, but for now we make do without the test and use the more elaborate comparison > Cycles(0).
Definition at line 80 of file types.hh.
Constructor & Destructor Documentation
Cycles::Cycles (uint64_t _c) [inline, explicit]
Explicit constructor assigning a value.
Definition at line 91 of file types.hh.
Cycles::Cycles () [inline]
Default constructor for parameter classes.
Definition at line 94 of file types.hh.
Referenced by operator+(), operator-(), operator<<(), and operator>>().
Member Function Documentation
Cycles::operator uint64_t () const [inline]
Converting back to the value type.
Definition at line 99 of file types.hh.
References c.
const Cycles Cycles::operator+ (const Cycles & b) const [inline]
Definition at line 117 of file types.hh.
References c, and Cycles().
Cycles& Cycles::operator++ () [inline]
Prefix increment operator.
Definition at line 102 of file types.hh.
References c.
const Cycles& Cycles::operator+= (const Cycles & cc) [inline]
In-place addition of cycles.
Definition at line 110 of file types.hh.
References c.
const Cycles Cycles::operator- (const Cycles & b) const [inline]
Definition at line 120 of file types.hh.
References c, and Cycles().
Cycles& Cycles::operator-- () [inline]
Prefix decrement operator.
Is only temporarily used in the O3 CPU.
Definition at line 106 of file types.hh.
References c.
const Cycles Cycles::operator<< (const int32_t shift) [inline]
Definition at line 123 of file types.hh.
References c, and Cycles().
bool Cycles::operator> (const Cycles & cc) const [inline]
Greater than comparison used for > Cycles(0).
Definition at line 114 of file types.hh.
References c.
const Cycles Cycles::operator>> (const int32_t shift) [inline]
Definition at line 126 of file types.hh.
References c, and Cycles().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Cycles & cycles) [friend]
Definition at line 36 of file types.cc.
Member Data Documentation
uint64_t Cycles::c [private]
Member holding the actual value.
Definition at line 86 of file types.hh.
Referenced by operator uint64_t(), operator+(), operator++(), operator+=(), operator-(), operator--(), operator<<(), operator<<(), operator>(), and operator>>().
The documentation for this class was generated from the following file:
base/types.hh