gem5: DtbObject Class Reference
DtbObject Class Reference
#include <dtb_object.hh>