gem5: X86ISA::FpOp Class Reference
X86ISA::FpOp Class Reference
Base classes for FpOps which provides a generateDisassembly method.
#include <microfpop.hh>