gem5: TrafficGen::StateGraph Class Reference
TrafficGen::StateGraph Class Reference
The state graph is responsible for instantiating and keeping track of the various generator states and also perform the transitions and call the appropriate functions when entering, executing and exiting a state.
#include <traffic_gen.hh>
Classes
class BaseGen
Base class for all generator states.
class IdleGen
The idle generator does nothing.
class LinearGen
The linear generator generates sequential requests from a start to an end address, with a fixed block size.
class RandomGen
The random generator is similar to the linear one, but does not generate sequential addresses.
class TraceGen
The trace replay generator reads a trace file and plays back the transactions.
struct Transition
Struct to represent a probabilistic transition during parsing.
Public Member Functions
StateGraph (TrafficGen &_owner, QueuedMasterPort &_port, const std::string &file_name, MasterID master_id)
Create a state graph from an input file.
std::string name () const
Get the name, used for DPRINTFs.
void update ()
Either perform a state transition or execute the current state, depending on the current time.
void transition ()
Determine next state and perform the transition.
void enterState (uint32_t newState)
Enter a new state.
Tick nextEventTick ()
Get the tick of the next event, either an execution or a transition.
Public Attributes
Tick nextTransitionTick
Time of next transition.
uint32_t currState
Index of the current state.
m5::hash_map< uint32_t, BaseGen * > states
Map of states.
Private Member Functions
void parseConfig (const std::string &file_name, MasterID master_id)
Parse the config file and build the state map and transition matrix.
Private Attributes
TrafficGen & owner
Pointer to owner of request handler.
QueuedMasterPort & port
Pointer to request handler.
std::vector< std::vector
< double > > transitionMatrix
State transition matrix.
Detailed Description
The state graph is responsible for instantiating and keeping track of the various generator states and also perform the transitions and call the appropriate functions when entering, executing and exiting a state.
Definition at line 83 of file traffic_gen.hh.
Constructor & Destructor Documentation
TrafficGen::StateGraph::StateGraph (TrafficGen & _owner, QueuedMasterPort & _port, const std::string & file_name, MasterID master_id) [inline]
Create a state graph from an input file.
Parameters:
_owner used solely for the name
_port port used to send requests
file_name configuration description to read in
master_id the unique id used for all requests
Definition at line 96 of file traffic_gen.hh.
References parseConfig().
Member Function Documentation
void TrafficGen::StateGraph::enterState (uint32_t newState)
Enter a new state.
Parameters:
newState identifier of state to enter
Definition at line 338 of file traffic_gen.cc.
References currState, DPRINTF, nextTransitionTick, and states.
Referenced by TrafficGen::init(), and transition().
std::string TrafficGen::StateGraph::name () const [inline]
Get the name, used for DPRINTFs.
Returns:
the owner's name
Definition at line 108 of file traffic_gen.hh.
References SimObject::name(), and owner.
Tick TrafficGen::StateGraph::nextEventTick () [inline]
Get the tick of the next event, either an execution or a transition.
Returns:
tick of the next state graph event
Definition at line 134 of file traffic_gen.hh.
References currState, nextTransitionTick, and states.
Referenced by TrafficGen::initState(), and TrafficGen::updateStateGraph().
void TrafficGen::StateGraph::parseConfig (const std::string & file_name, MasterID master_id) [private]
Parse the config file and build the state map and transition matrix.
Parameters:
file_name Config file name to parse
master_id MasterID to use for generated requests
Referenced by StateGraph().
void TrafficGen::StateGraph::transition ()
Determine next state and perform the transition.
Definition at line 319 of file traffic_gen.cc.
References currState, enterState(), Random::gen_real1(), ArmISA::i, MipsISA::p, random_mt, states, and transitionMatrix.
Referenced by update().
void TrafficGen::StateGraph::update ()
Either perform a state transition or execute the current state, depending on the current time.
Definition at line 306 of file traffic_gen.cc.
References currState, curTick(), nextTransitionTick, states, and transition().
Referenced by TrafficGen::updateStateGraph().
Member Data Documentation
uint32_t TrafficGen::StateGraph::currState
Index of the current state.
Definition at line 565 of file traffic_gen.hh.
Referenced by enterState(), TrafficGen::init(), nextEventTick(), transition(), and update().
Tick TrafficGen::StateGraph::nextTransitionTick
Time of next transition.
Definition at line 142 of file traffic_gen.hh.
Referenced by enterState(), nextEventTick(), and update().
TrafficGen& TrafficGen::StateGraph::owner [private]
Pointer to owner of request handler.
Definition at line 554 of file traffic_gen.hh.
Referenced by name().
QueuedMasterPort& TrafficGen::StateGraph::port [private]
Pointer to request handler.
Definition at line 557 of file traffic_gen.hh.
m5::hash_map<uint32_t, BaseGen*> TrafficGen::StateGraph::states
Map of states.
Definition at line 568 of file traffic_gen.hh.
Referenced by enterState(), nextEventTick(), transition(), and update().
std::vector<std::vector<double> > TrafficGen::StateGraph::transitionMatrix [private]
State transition matrix.
Definition at line 560 of file traffic_gen.hh.
Referenced by transition().
The documentation for this class was generated from the following files:
cpu/testers/traffic_gen/traffic_gen.hh
cpu/testers/traffic_gen/traffic_gen.cc