gem5: flit Class Reference
flit Class Reference
#include <flit.hh>
Public Member Functions
flit (int id, int vc, int vnet, int size, MsgPtr msg_ptr, Cycles curTime)
int get_size ()
int get_id ()
Cycles get_time ()
Cycles get_enqueue_time ()
void set_time (Cycles time)
int get_vnet ()
int get_vc ()
void set_vc (int vc)
MsgPtr & get_msg_ptr ()
flit_type get_type ()
void set_delay (Cycles delay)
Cycles get_delay ()
void print (std::ostream &out) const
bool functionalRead (Packet *pkt)
bool functionalWrite (Packet *pkt)
Static Public Member Functions
static bool greater (flit *n1, flit *n2)
Private Attributes
int m_id
int m_vnet
int m_vc
int m_size
Cycles m_enqueue_time
Cycles m_time
flit_type m_type
MsgPtr m_msg_ptr
Cycles src_delay
Detailed Description
Definition at line 41 of file flit.hh.
Constructor & Destructor Documentation
flit::flit (int id, int vc, int vnet, int size, MsgPtr msg_ptr, Cycles curTime)
Definition at line 33 of file flit.cc.
References m_enqueue_time, m_id, m_msg_ptr, m_size, m_time, m_type, m_vc, and m_vnet.
Member Function Documentation
bool flit::functionalRead (Packet * pkt)
Definition at line 140 of file flit.cc.
References Message::functionalRead(), RefCountingPtr< T >::get(), and m_msg_ptr.
bool flit::functionalWrite (Packet * pkt)
Definition at line 147 of file flit.cc.
References Message::functionalWrite(), RefCountingPtr< T >::get(), and m_msg_ptr.
Cycles flit::get_delay ()
Definition at line 122 of file flit.cc.
References src_delay.
Referenced by NetworkInterface::wakeup().
Cycles flit::get_enqueue_time ()
Definition at line 74 of file flit.cc.
References m_enqueue_time.
Referenced by NetworkInterface::wakeup().
int flit::get_id ()
Definition at line 62 of file flit.cc.
References m_id.
Referenced by greater().
MsgPtr & flit::get_msg_ptr ()
Definition at line 104 of file flit.cc.
References m_msg_ptr.
Referenced by Router::routeCompute(), and NetworkInterface::wakeup().
int flit::get_size ()
Definition at line 56 of file flit.cc.
References m_size.
Cycles flit::get_time ()
Definition at line 68 of file flit.cc.
References m_time.
Referenced by greater(), flitBuffer::isReady(), and flitBuffer::isReadyForNext().
flit_type flit::get_type ()
Definition at line 110 of file flit.cc.
References m_type.
Referenced by Router::routeCompute(), and NetworkInterface::wakeup().
int flit::get_vc ()
Definition at line 92 of file flit.cc.
References m_vc.
Referenced by Router::routeCompute(), NetworkLink::wakeup(), and NetworkInterface::wakeup().
int flit::get_vnet ()
Definition at line 86 of file flit.cc.
References m_vnet.
Referenced by NetworkInterface::wakeup().
static bool flit::greater (flit * n1, flit * n2) [inline, static]
Definition at line 61 of file flit.hh.
References get_id(), and get_time().
void flit::print (std::ostream & out) const
Definition at line 128 of file flit.cc.
References m_enqueue_time, m_id, m_type, m_vc, and m_vnet.
Referenced by operator<<().
void flit::set_delay (Cycles delay)
Definition at line 116 of file flit.cc.
References src_delay.
Referenced by NetworkInterface::flitisizeMessage().
void flit::set_time (Cycles time)
Definition at line 80 of file flit.cc.
References m_time.
Referenced by Router::routeCompute(), NetworkInterface::scheduleOutputLink(), Router::scheduleOutputLinks(), and NetworkLink::wakeup().
void flit::set_vc (int vc)
Definition at line 98 of file flit.cc.
References m_vc.
Referenced by Router::routeCompute().
Member Data Documentation
Cycles flit::m_enqueue_time [private]
Definition at line 78 of file flit.hh.
Referenced by flit(), get_enqueue_time(), and print().
int flit::m_id [private]
Definition at line 74 of file flit.hh.
Referenced by flit(), get_id(), and print().
MsgPtr flit::m_msg_ptr [private]
Definition at line 80 of file flit.hh.
Referenced by flit(), functionalRead(), functionalWrite(), and get_msg_ptr().
int flit::m_size [private]
Definition at line 77 of file flit.hh.
Referenced by flit(), and get_size().
Cycles flit::m_time [private]
Definition at line 78 of file flit.hh.
Referenced by flit(), get_time(), and set_time().
flit_type flit::m_type [private]
Definition at line 79 of file flit.hh.
Referenced by flit(), get_type(), and print().
int flit::m_vc [private]
Definition at line 76 of file flit.hh.
Referenced by flit(), get_vc(), print(), and set_vc().
int flit::m_vnet [private]
Definition at line 75 of file flit.hh.
Referenced by flit(), get_vnet(), and print().
Cycles flit::src_delay [private]
Definition at line 81 of file flit.hh.
Referenced by get_delay(), and set_delay().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet/flexible-pipeline/flit.hh
mem/ruby/network/garnet/flexible-pipeline/flit.cc