gem5: SimpleThread Class Reference
SimpleThread Class Reference
The SimpleThread object provides a combination of the ThreadState object and the ThreadContext interface.
#include <simple_thread.hh>