gem5: Bitmap Class Reference
Bitmap Class Reference
#include <bitmap.hh>
Classes
struct Header
struct Info
struct Magic
Public Member Functions
Bitmap (VideoConvert::Mode mode, uint16_t w, uint16_t h, uint8_t *d)
Create a Bitmap creator that takes data in the given mode & size and outputs to an fstream.
~Bitmap ()
Destructor.
void rawData (uint8_t *d)
Provide the converter with the data that should be output.
void write (std::ostream *bmp) const
Write the provided data into the fstream provided.
uint64_t getHash () const
Gets a hash over the bitmap for quick comparisons to other bitmaps.
Private Attributes
VideoConvert::Mode mode
uint16_t height
uint16_t width
uint8_t * data
VideoConvert vc
char * headerBuffer
Static Private Attributes
static const size_t sizeofHeaderBuffer
Detailed Description
Definition at line 54 of file bitmap.hh.
Constructor & Destructor Documentation
Bitmap::Bitmap (VideoConvert::Mode mode, uint16_t w, uint16_t h, uint8_t * d)
Create a Bitmap creator that takes data in the given mode & size and outputs to an fstream.
Parameters:
mode the type of data that is being provided
h the hight of the image
w the width of the image
d the data for the image in mode
Definition at line 51 of file bitmap.cc.
Bitmap::~Bitmap ()
Destructor.
Definition at line 57 of file bitmap.cc.
References headerBuffer.
Member Function Documentation
uint64_t Bitmap::getHash () const [inline]
Gets a hash over the bitmap for quick comparisons to other bitmaps.
Returns:
hash of the bitmap
Definition at line 83 of file bitmap.hh.
References data, VideoConvert::getHash(), and vc.
Referenced by VncInput::captureFrameBuffer().
void Bitmap::rawData (uint8_t * d) [inline]
Provide the converter with the data that should be output.
It will be converted into rgb8888 and write out when write() is called.
Parameters:
d the data
Definition at line 73 of file bitmap.hh.
References data.
void Bitmap::write (std::ostream * bmp) const
Write the provided data into the fstream provided.
Parameters:
bmp stream to write to
Definition at line 63 of file bitmap.cc.
References VideoConvert::convert(), data, headerBuffer, height, ArmISA::i, ArmISA::j, MipsISA::p, sizeofHeaderBuffer, vc, and width.
Referenced by VncInput::captureFrameBuffer(), and Pl111::dmaDone().
Member Data Documentation
uint8_t* Bitmap::data [private]
Definition at line 90 of file bitmap.hh.
Referenced by getHash(), rawData(), and write().
char* Bitmap::headerBuffer [mutable, private]
Definition at line 94 of file bitmap.hh.
Referenced by write(), and ~Bitmap().
uint16_t Bitmap::height [private]
Definition at line 88 of file bitmap.hh.
Referenced by write().
VideoConvert::Mode Bitmap::mode [private]
Definition at line 87 of file bitmap.hh.
const size_t Bitmap::sizeofHeaderBuffer [static, private]
Initial value:
 sizeof(Magic) + sizeof(Header) +
                                        sizeof(Info)
Definition at line 95 of file bitmap.hh.
Referenced by write().
VideoConvert Bitmap::vc [private]
Definition at line 92 of file bitmap.hh.
Referenced by getHash(), and write().
uint16_t Bitmap::width [private]
Definition at line 89 of file bitmap.hh.
Referenced by write().
The documentation for this class was generated from the following files:
base/bitmap.hh
base/bitmap.cc