gem5: AlphaISA::Kernel::Statistics Class Reference
AlphaISA::Kernel::Statistics Class Reference
#include <kernel_stats.hh>