gem5: RubySystem Class Reference
RubySystem Class Reference
#include <System.hh>