gem5: SRAM Class Reference
SRAM Class Reference
#include <SRAM.hh>
Public Member Functions
SRAM (uint32_t num_entry_, uint32_t line_width_, bool is_fifo_, bool is_outdrv_, uint32_t num_read_port_, uint32_t num_write_port_, uint32_t num_data_end_, const string &rowdec_model_str_, const string &wl_model_str_, const string &bl_pre_model_str_, const string &mem_model_str_, const string &bl_model_str_, const string &amp_model_str_, const string &outdrv_model_str_, const TechParameter *tech_param_ptr_)
~SRAM ()
uint32_t get_line_width () const
uint32_t get_num_data_end () const
uint32_t get_num_read_port () const
uint32_t get_num_write_port () const
uint32_t get_num_port () const
bool get_is_outdrv () const
uint32_t get_num_row () const
uint32_t get_num_col () const
double calc_e_read (bool is_max_) const
double calc_e_write (bool is_max_) const
double calc_i_static () const
Private Member Functions
void init ()
Private Attributes
uint32_t m_num_entry
uint32_t m_line_width
bool m_is_fifo
bool m_is_outdrv
string m_rowdec_model_str
string m_wl_model_str
string m_bl_pre_model_str
string m_mem_model_str
string m_bl_model_str
string m_amp_model_str
string m_outdrv_model_str
const TechParameter * m_tech_param_ptr
OutdrvUnit * m_outdrv_unit_ptr
AmpUnit * m_amp_unit_ptr
BitlineUnit * m_bl_unit_ptr
MemUnit * m_mem_unit_ptr
PrechargeUnit * m_bl_pre_unit_ptr
WordlineUnit * m_wl_unit_ptr
DecoderUnit * m_rowdec_unit_ptr
uint32_t m_num_read_port
uint32_t m_num_write_port
uint32_t m_num_data_end
uint32_t m_rowdec_width
Detailed Description
Definition at line 51 of file SRAM.hh.
Constructor & Destructor Documentation
SRAM::SRAM (uint32_t num_entry_, uint32_t line_width_, bool is_fifo_, bool is_outdrv_, uint32_t num_read_port_, uint32_t num_write_port_, uint32_t num_data_end_, const string & rowdec_model_str_, const string & wl_model_str_, const string & bl_pre_model_str_, const string & mem_model_str_, const string & bl_model_str_, const string & amp_model_str_, const string & outdrv_model_str_, const TechParameter * tech_param_ptr_)
Definition at line 51 of file SRAM.cc.
References init(), m_amp_model_str, m_bl_model_str, m_bl_pre_model_str, m_is_fifo, m_is_outdrv, m_line_width, m_mem_model_str, m_num_data_end, m_num_entry, m_num_read_port, m_num_write_port, m_outdrv_model_str, m_rowdec_model_str, m_tech_param_ptr, and m_wl_model_str.
SRAM::~SRAM ()
Definition at line 96 of file SRAM.cc.
References m_amp_unit_ptr, m_bl_pre_unit_ptr, m_bl_unit_ptr, m_mem_unit_ptr, m_outdrv_unit_ptr, m_rowdec_unit_ptr, and m_wl_unit_ptr.
Member Function Documentation
double SRAM::calc_e_read (bool is_max_) const
Definition at line 107 of file SRAM.cc.
References DecoderUnit::get_dec_width(), AmpUnit::get_e_access(), PrechargeUnit::get_e_charge_drain(), PrechargeUnit::get_e_charge_gate(), DecoderUnit::get_e_chg_addr(), OutdrvUnit::get_e_chg_data(), DecoderUnit::get_e_chg_l1(), DecoderUnit::get_e_chg_output(), BitlineUnit::get_e_col_read(), OutdrvUnit::get_e_out_0(), OutdrvUnit::get_e_out_1(), WordlineUnit::get_e_read(), OutdrvUnit::get_e_select(), DecoderUnit::get_num_in_2nd(), m_amp_unit_ptr, m_bl_pre_unit_ptr, m_bl_unit_ptr, m_line_width, m_num_data_end, m_outdrv_unit_ptr, m_rowdec_unit_ptr, and m_wl_unit_ptr.
Referenced by Buffer::get_dynamic_energy().
double SRAM::calc_e_write (bool is_max_) const
Definition at line 179 of file SRAM.cc.
References DecoderUnit::get_dec_width(), DecoderUnit::get_e_chg_addr(), DecoderUnit::get_e_chg_l1(), DecoderUnit::get_e_chg_output(), BitlineUnit::get_e_col_wrtie(), MemUnit::get_e_switch(), WordlineUnit::get_e_write(), DecoderUnit::get_num_in_2nd(), m_bl_unit_ptr, m_line_width, m_mem_unit_ptr, m_rowdec_unit_ptr, and m_wl_unit_ptr.
Referenced by Buffer::get_dynamic_energy().
double SRAM::calc_i_static () const
Definition at line 211 of file SRAM.cc.
References WordlineUnit::get_i_static(), PrechargeUnit::get_i_static(), MemUnit::get_i_static(), BitlineUnit::get_i_static(), m_bl_pre_unit_ptr, m_bl_unit_ptr, m_line_width, m_mem_unit_ptr, m_num_entry, m_num_read_port, m_num_write_port, and m_wl_unit_ptr.
Referenced by Buffer::get_static_power().
bool SRAM::get_is_outdrv () const [inline]
Definition at line 79 of file SRAM.hh.
References m_is_outdrv.
Referenced by BitlineUnit::calc_col_read_cap().
uint32_t SRAM::get_line_width () const [inline]
Definition at line 74 of file SRAM.hh.
References m_line_width.
Referenced by OutdrvUnit::calc_select_cap().
uint32_t SRAM::get_num_col () const [inline]
Definition at line 81 of file SRAM.hh.
References m_line_width.
Referenced by WordlineUnit::init().
uint32_t SRAM::get_num_data_end () const [inline]
Definition at line 75 of file SRAM.hh.
References m_num_data_end.
Referenced by BitlineUnit::calc_col_read_cap(), MemUnit::calc_i_static(), MemUnit::calc_mem_cap(), WordlineUnit::init(), PrechargeUnit::init(), and BitlineUnit::init().
uint32_t SRAM::get_num_port () const [inline]
Definition at line 78 of file SRAM.hh.
References m_num_read_port, and m_num_write_port.
Referenced by WordlineUnit::init(), and BitlineUnit::init().
uint32_t SRAM::get_num_read_port () const [inline]
Definition at line 76 of file SRAM.hh.
References m_num_read_port.
Referenced by MemUnit::calc_i_static(), MemUnit::calc_mem_cap(), and WordlineUnit::init().
uint32_t SRAM::get_num_row () const [inline]
Definition at line 80 of file SRAM.hh.
References m_num_entry.
Referenced by BitlineUnit::calc_col_read_cap(), BitlineUnit::calc_col_write_cap(), and BitlineUnit::init().
uint32_t SRAM::get_num_write_port () const [inline]
Definition at line 77 of file SRAM.hh.
References m_num_write_port.
Referenced by MemUnit::calc_i_static(), and MemUnit::calc_mem_cap().
void SRAM::init () [private]
Definition at line 223 of file SRAM.cc.
References BitlineUnit::get_pre_unit_load(), m_amp_model_str, m_amp_unit_ptr, m_bl_model_str, m_bl_pre_model_str, m_bl_pre_unit_ptr, m_bl_unit_ptr, m_is_fifo, m_is_outdrv, m_mem_model_str, m_mem_unit_ptr, m_num_data_end, m_num_entry, m_outdrv_model_str, m_outdrv_unit_ptr, m_rowdec_model_str, m_rowdec_unit_ptr, m_rowdec_width, m_tech_param_ptr, m_wl_model_str, and m_wl_unit_ptr.
Referenced by SRAM().
Member Data Documentation
string SRAM::m_amp_model_str [private]
Definition at line 100 of file SRAM.hh.
Referenced by init(), and SRAM().
AmpUnit* SRAM::m_amp_unit_ptr [private]
Definition at line 105 of file SRAM.hh.
Referenced by calc_e_read(), init(), and ~SRAM().
string SRAM::m_bl_model_str [private]
Definition at line 99 of file SRAM.hh.
Referenced by init(), and SRAM().
string SRAM::m_bl_pre_model_str [private]
Definition at line 97 of file SRAM.hh.
Referenced by init(), and SRAM().
PrechargeUnit* SRAM::m_bl_pre_unit_ptr [private]
Definition at line 108 of file SRAM.hh.
Referenced by calc_e_read(), calc_i_static(), init(), and ~SRAM().
BitlineUnit* SRAM::m_bl_unit_ptr [private]
Definition at line 106 of file SRAM.hh.
Referenced by calc_e_read(), calc_e_write(), calc_i_static(), init(), and ~SRAM().
bool SRAM::m_is_fifo [private]
Definition at line 93 of file SRAM.hh.
Referenced by init(), and SRAM().
bool SRAM::m_is_outdrv [private]
Definition at line 94 of file SRAM.hh.
Referenced by get_is_outdrv(), init(), and SRAM().
uint32_t SRAM::m_line_width [private]
Definition at line 92 of file SRAM.hh.
Referenced by calc_e_read(), calc_e_write(), calc_i_static(), get_line_width(), get_num_col(), and SRAM().
string SRAM::m_mem_model_str [private]
Definition at line 98 of file SRAM.hh.
Referenced by init(), and SRAM().
MemUnit* SRAM::m_mem_unit_ptr [private]
Definition at line 107 of file SRAM.hh.
Referenced by calc_e_write(), calc_i_static(), init(), and ~SRAM().
uint32_t SRAM::m_num_data_end [private]
Definition at line 114 of file SRAM.hh.
Referenced by calc_e_read(), get_num_data_end(), init(), and SRAM().
uint32_t SRAM::m_num_entry [private]
Definition at line 91 of file SRAM.hh.
Referenced by calc_i_static(), get_num_row(), init(), and SRAM().
uint32_t SRAM::m_num_read_port [private]
Definition at line 112 of file SRAM.hh.
Referenced by calc_i_static(), get_num_port(), get_num_read_port(), and SRAM().
uint32_t SRAM::m_num_write_port [private]
Definition at line 113 of file SRAM.hh.
Referenced by calc_i_static(), get_num_port(), get_num_write_port(), and SRAM().
string SRAM::m_outdrv_model_str [private]
Definition at line 101 of file SRAM.hh.
Referenced by init(), and SRAM().
OutdrvUnit* SRAM::m_outdrv_unit_ptr [private]
Definition at line 104 of file SRAM.hh.
Referenced by calc_e_read(), init(), and ~SRAM().
string SRAM::m_rowdec_model_str [private]
Definition at line 95 of file SRAM.hh.
Referenced by init(), and SRAM().
DecoderUnit* SRAM::m_rowdec_unit_ptr [private]
Definition at line 110 of file SRAM.hh.
Referenced by calc_e_read(), calc_e_write(), init(), and ~SRAM().
uint32_t SRAM::m_rowdec_width [private]
Definition at line 116 of file SRAM.hh.
Referenced by init().
const TechParameter* SRAM::m_tech_param_ptr [private]
Definition at line 102 of file SRAM.hh.
Referenced by init(), and SRAM().
string SRAM::m_wl_model_str [private]
Definition at line 96 of file SRAM.hh.
Referenced by init(), and SRAM().
WordlineUnit* SRAM::m_wl_unit_ptr [private]
Definition at line 109 of file SRAM.hh.
Referenced by calc_e_read(), calc_e_write(), calc_i_static(), init(), and ~SRAM().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/Buffer/SRAM.hh
mem/ruby/network/orion/Buffer/SRAM.cc