gem5: BaseBus Class Reference
BaseBus Class Reference
The base bus contains the common elements of the non-coherent and coherent bus.
#include <bus.hh>