gem5: NoncoherentBus::NoncoherentBusMasterPort Class Reference
NoncoherentBus::NoncoherentBusMasterPort Class Reference
Declaration of the bus master port type, one will be instantiated for each of the slave ports connecting to the bus.
#include <noncoherent_bus.hh>