gem5: SimpleTimingPort Class Reference
SimpleTimingPort Class Reference
The simple timing port uses a queued port to implement recvFunctional and recvTimingReq through recvAtomic.
#include <tport.hh>