gem5: RegImmRegOp Class Reference
RegImmRegOp Class Reference
#include <misc.hh>