gem5: PCEventQueue Class Reference
PCEventQueue Class Reference
#include <pc_event.hh>
Classes
class MapCompare
Public Types
typedef map_t::iterator iterator
typedef map_t::const_iterator const_iterator
Public Member Functions
PCEventQueue ()
~PCEventQueue ()
bool remove (PCEvent *event)
bool schedule (PCEvent *event)
bool service (ThreadContext *tc)
range_t equal_range (Addr pc)
range_t equal_range (PCEvent *event)
void dump () const
Protected Types
typedef PCEvent * record_t
typedef std::vector< record_t > map_t
typedef std::pair< iterator,
iterator > range_t
typedef std::pair
< const_iterator,
const_iterator > const_range_t
Protected Member Functions
bool doService (ThreadContext *tc)
Protected Attributes
map_t pc_map
Detailed Description
Definition at line 66 of file pc_event.hh.
Member Typedef Documentation
typedef map_t::const_iterator PCEventQueue::const_iterator
Definition at line 86 of file pc_event.hh.
typedef std::pair<const_iterator, const_iterator> PCEventQueue::const_range_t [protected]
Definition at line 90 of file pc_event.hh.
typedef map_t::iterator PCEventQueue::iterator
Definition at line 85 of file pc_event.hh.
typedef std::vector<record_t> PCEventQueue::map_t [protected]
Definition at line 82 of file pc_event.hh.
typedef std::pair<iterator, iterator> PCEventQueue::range_t [protected]
Definition at line 89 of file pc_event.hh.
typedef PCEvent* PCEventQueue::record_t [protected]
Definition at line 69 of file pc_event.hh.
Constructor & Destructor Documentation
PCEventQueue::PCEventQueue ()
Definition at line 47 of file pc_event.cc.
PCEventQueue::~PCEventQueue ()
Definition at line 50 of file pc_event.cc.
Member Function Documentation
bool PCEventQueue::doService (ThreadContext * tc) [protected]
Definition at line 88 of file pc_event.cc.
References DPRINTF, equal_range(), ArmISA::i, ThreadContext::instAddr(), and MipsISA::pc.
Referenced by service().
void PCEventQueue::dump () const
Definition at line 114 of file pc_event.cc.
References cprintf(), curTick(), ArmISA::e, ArmISA::i, and pc_map.
PCEventQueue::range_t PCEventQueue::equal_range (Addr pc)
Definition at line 125 of file pc_event.cc.
References pc_map.
Referenced by doService(), and remove().
range_t PCEventQueue::equal_range (PCEvent * event) [inline]
Definition at line 112 of file pc_event.hh.
References equal_range(), and PCEvent::pc().
Referenced by equal_range().
bool PCEventQueue::remove (PCEvent * event)
Definition at line 54 of file pc_event.cc.
References DPRINTF, equal_range(), ArmISA::i, PCEvent::pc(), and pc_map.
Referenced by PCEvent::remove().
bool PCEventQueue::schedule (PCEvent * event)
Definition at line 76 of file pc_event.cc.
References DPRINTF, PCEvent::pc(), and pc_map.
Referenced by PCEvent::PCEvent().
bool PCEventQueue::service (ThreadContext * tc) [inline]
Definition at line 103 of file pc_event.hh.
References doService(), and pc_map.
Referenced by BaseSimpleCPU::checkPcEventQueue(), and Checker< Impl >::verify().
Member Data Documentation
map_t PCEventQueue::pc_map [protected]
Definition at line 93 of file pc_event.hh.
Referenced by dump(), equal_range(), remove(), schedule(), and service().
The documentation for this class was generated from the following files:
cpu/pc_event.hh
cpu/pc_event.cc