gem5: CircleBuf Class Reference
CircleBuf Class Reference
#include <circlebuf.hh>
Public Member Functions
CircleBuf (int l)
~CircleBuf ()
bool empty () const
int size () const
void dump ()
void flush ()
void read (char *b, int len)
void read (int fd, int len)
void read (int fd)
void read (std::ostream &out)
void readall (int fd)
void write (char b)
void write (const char *b)
void write (const char *b, int len)
Protected Attributes
char * _buf
bool _rollover
int _buflen
int _size
int _start
int _stop
Detailed Description
Definition at line 36 of file circlebuf.hh.
Constructor & Destructor Documentation
CircleBuf::CircleBuf (int l) [explicit]
Definition at line 43 of file circlebuf.cc.
References _buf, and _buflen.
CircleBuf::~CircleBuf ()
Definition at line 49 of file circlebuf.cc.
References _buf.
Member Function Documentation
void CircleBuf::dump ()
Definition at line 56 of file circlebuf.cc.
References _buf, _buflen, _start, _stop, atomic_write(), and cprintf().
bool CircleBuf::empty () const [inline]
Definition at line 50 of file circlebuf.hh.
References _size.
Referenced by Terminal::console_in(), Terminal::dataAvailable(), and Terminal::in().
void CircleBuf::flush ()
Definition at line 66 of file circlebuf.cc.
References _rollover, _start, and _stop.
Referenced by main().
void CircleBuf::read (std::ostream & out)
void CircleBuf::read (char * b, int len)
Definition at line 74 of file circlebuf.cc.
References _buf, _buflen, _size, _start, and _stop.
Referenced by Terminal::in(), and main().
void CircleBuf::read (int fd, int len)
Definition at line 100 of file circlebuf.cc.
References _buf, _buflen, _size, _start, _stop, and atomic_write().
void CircleBuf::read (int fd)
Definition at line 126 of file circlebuf.cc.
References _buf, _buflen, _size, _start, _stop, and atomic_write().
void CircleBuf::readall (int fd)
Definition at line 158 of file circlebuf.cc.
References _buf, _buflen, _rollover, _start, _stop, and atomic_write().
Referenced by Terminal::accept().
int CircleBuf::size () const [inline]
Definition at line 51 of file circlebuf.hh.
References _size.
void CircleBuf::write (const char * b, int len)
Definition at line 180 of file circlebuf.cc.
References _buf, _buflen, _rollover, _size, _start, and _stop.
void CircleBuf::write (const char * b)
Definition at line 174 of file circlebuf.cc.
References write().
void CircleBuf::write (char b)
Definition at line 168 of file circlebuf.cc.
Referenced by Terminal::data(), main(), Terminal::out(), and write().
Member Data Documentation
char* CircleBuf::_buf [protected]
Definition at line 39 of file circlebuf.hh.
Referenced by CircleBuf(), dump(), read(), readall(), write(), and ~CircleBuf().
int CircleBuf::_buflen [protected]
Definition at line 41 of file circlebuf.hh.
Referenced by CircleBuf(), dump(), read(), readall(), and write().
bool CircleBuf::_rollover [protected]
Definition at line 40 of file circlebuf.hh.
Referenced by flush(), readall(), and write().
int CircleBuf::_size [protected]
Definition at line 42 of file circlebuf.hh.
Referenced by empty(), read(), size(), and write().
int CircleBuf::_start [protected]
Definition at line 43 of file circlebuf.hh.
Referenced by dump(), flush(), read(), readall(), and write().
int CircleBuf::_stop [protected]
Definition at line 44 of file circlebuf.hh.
Referenced by dump(), flush(), read(), readall(), and write().
The documentation for this class was generated from the following files:
base/circlebuf.hh
base/circlebuf.cc