gem5: Cache< TagStore >::MemSidePacketQueue Class Reference
Cache< TagStore >::MemSidePacketQueue Class Reference
Override the default behaviour of sendDeferredPacket to enable the memory-side cache port to also send requests based on the current MSHR status.
#include <cache.hh>