gem5: RawObject Class Reference
RawObject Class Reference
#include <raw_object.hh>