gem5: CoherentBus Class Reference
CoherentBus Class Reference
A coherent bus connects a number of (potentially) snooping masters and slaves, and routes the request and response packets based on the address, and also forwards all requests to the snoopers and deals with the snoop responses.
#include <coherent_bus.hh>