gem5: FaultBase Class Reference
FaultBase Class Reference
#include <faults.hh>