gem5: Router Class Reference
Router Class Reference
#include <Router.hh>