gem5: TechParameter Class Reference
TechParameter Class Reference
#include <TechParameter.hh>
Public Types
enum TransistorType { LVT = 0, NVT, HVT, NUM_TRANSISTOR_TYPE }
enum WireLayerType { LOCAL = 0, INTERMEDIATE, GLOBAL, NUM_WIRE_LAYER_TYPE }
enum ChannelType { NCH, PCH }
Public Member Functions
TechParameter (const OrionConfig *orion_cfg_ptr_)
~TechParameter ()
double calc_gatecap (double width_, double wirelength_) const
double calc_gatecappass (double width_, double wirelength_) const
double calc_draincap (double width_, ChannelType ch_, uint32_t num_stack_) const
double calc_restowidth (double res_, ChannelType ch_) const
double calc_driver_psize (double cap_, double rise_time_) const
bool is_trans_type_hvt () const
bool is_trans_type_nvt () const
bool is_trans_type_lvt () const
double get_tech_node () const
double get_vdd () const
double get_freq () const
double get_period () const
double get_amp_idsat () const
double get_SCALE_S () const
double get_MSCALE () const
double get_Lamda () const
double get_Cmetal () const
double get_CM2metal () const
double get_CM3metal () const
double get_CCmetal () const
double get_CCM2metal () const
double get_CCM3metal () const
double get_CC2metal () const
double get_CC2M2metal () const
double get_CC2M3metal () const
double get_CC3metal () const
double get_CC3M2metal () const
double get_CC3M3metal () const
double get_EnergyFactor () const
double get_SenseEnergyFactor () const
double get_Woutdrvseln () const
double get_Woutdrvselp () const
double get_Woutdrvnandn () const
double get_Woutdrvnandp () const
double get_Woutdrvnorn () const
double get_Woutdrvnorp () const
double get_Woutdrivern () const
double get_Woutdriverp () const
double get_WsenseQ1to4 () const
double get_Wbitmuxn () const
double get_Wmemcellr () const
double get_Wmemcellw () const
double get_Wmemcella () const
double get_Wmemcellbscale () const
double get_RegCellHeight () const
double get_RegCellWidth () const
double get_WordlineSpacing () const
double get_BitlineSpacing () const
double get_BitWidth () const
double get_Wdecinvn () const
double get_Wdecinvp () const
double get_Wdec3to8n () const
double get_Wdec3to8p () const
double get_WdecNORn () const
double get_WdecNORp () const
double get_Wdecdriven () const
double get_Wdecdrivep () const
double get_CrsbarCellWidth () const
double get_CrsbarCellHeight () const
double get_Wdff () const
double get_WireMinWidth () const
double get_WireMinSpacing () const
double get_WireBarrierThickness () const
double get_WireMetalThickness () const
double get_WireDielectricThickness () const
double get_WireDielectricConstant () const
double get_BufferDriveResistance () const
double get_BufferInputCapacitance () const
double get_BufferNMOSOffCurrent () const
double get_BufferPMOSOffCurrent () const
double get_ClockCap () const
double get_Clockwire () const
double get_Reswire () const
double get_NMOS_TAB (uint32_t idx) const
double get_PMOS_TAB (uint32_t idx) const
double get_NAND2_TAB (uint32_t idx) const
double get_NOR2_TAB (uint32_t idx) const
double get_DFF_TAB (uint32_t idx) const
Private Member Functions
void init ()
void init_tech_110_800 ()
void init_tech_32_90 ()
void init_tech_90 ()
Private Attributes
const OrionConfig * m_orion_cfg_ptr
unsigned int m_tech_node
TransistorType m_transistor_type
double m_vdd
double m_freq
double m_period
WireLayerType m_wire_layer_type
double m_af
uint32_t m_max_n
uint32_t m_max_subarrays
uint32_t m_max_spd
double m_vth_outdr_nor
double m_vth_comp_inv
uint32_t m_bit_out
uint32_t m_ruu_issue_width
double m_amp_idsat
double m_vs_inv
double m_gen_power_factor
double m_vth_nand_60x90
double m_fudge_factor
double m_vth_outdrive
double m_vth_muxdrv1
double m_vth_muxdrv2
double m_normalize_scale
double m_vth_muxdrv3
uint32_t m_address_bits
uint32_t m_ruu_size
double m_vth_nor_12x4x1
double m_vth_nor_12x4x2
double m_vth_outdr_inv
double m_vth_nor_12x4x3
double m_vth_eval_inv
double m_vth_nor_12x4x4
uint32_t m_res_ialu
double m_vth_outdr_nand
double m_vth_inv_100x60
double m_Cpdiffarea
double m_Cpdiffside
double m_Cpoverlap
double m_Cndiffarea
double m_Cndiffside
double m_Cnoverlap
double m_Cgatepass
double m_Cgate
double m_Cpdiffovlp
double m_Cndiffovlp
double m_Cpoxideovlp
double m_Cnoxideovlp
double m_Vbitpre
double m_Vbitsense
double m_EnergyFactor
double m_SenseEnergyFactor
double m_SenseEnergyFactor3
double m_SenseEnergyFactor2
double m_SCALE_T
double m_SCALE_M
double m_SCALE_S
double m_SCALE_W
double m_SCALE_H
double m_SCALE_BW
double m_SCALE_Crs
double m_LSCALE
double m_MSCALE
double m_BitWidth
double m_BitHeight
double m_BitlineSpacing
double m_WordlineSpacing
double m_RegCellWidth
double m_RegCellHeight
double m_Cout
double m_Cwordmetal
double m_Cbitmetal
double m_Cmetal
double m_CM2metal
double m_CM3metal
double m_CCmetal
double m_CCM2metal
double m_CCM3metal
double m_CC2metal
double m_CC2M2metal
double m_CC2M3metal
double m_CC3metal
double m_CC3M2metal
double m_CC3M3metal
double m_Clockwire
double m_Reswire
double m_invCap
double m_Resout
double m_Leff
double m_Lamda
double m_Cpolywire
double m_Rnchannelstatic
double m_Rpchannelstatic
double m_Rnchannelon
double m_Rpchannelon
double m_Rbitmetal
double m_Rwordmetal
double m_Vt
double m_Wdecdrivep
double m_Wdecdriven
double m_Wdec3to8n
double m_Wdec3to8p
double m_WdecNORn
double m_WdecNORp
double m_Wdecinvn
double m_Wdecinvp
double m_Wdff
double m_Wworddrivemax
double m_Wmemcella
double m_Wmemcellr
double m_Wmemcellw
double m_Wmemcellbscale
double m_Wbitpreequ
double m_Wbitmuxn
double m_WsenseQ1to4
double m_Wcompinvp1
double m_Wcompinvn1
double m_Wcompinvp2
double m_Wcompinvn2
double m_Wcompinvp3
double m_Wcompinvn3
double m_Wevalinvp
double m_Wevalinvn
double m_Wcompn
double m_Wcompp
double m_Wcomppreequ
double m_Wmuxdrv12n
double m_Wmuxdrv12p
double m_WmuxdrvNANDn
double m_WmuxdrvNANDp
double m_WmuxdrvNORn
double m_WmuxdrvNORp
double m_Wmuxdrv3n
double m_Wmuxdrv3p
double m_Woutdrvseln
double m_Woutdrvselp
double m_Woutdrvnandn
double m_Woutdrvnandp
double m_Woutdrvnorn
double m_Woutdrvnorp
double m_Woutdrivern
double m_Woutdriverp
double m_Wbusdrvn
double m_Wbusdrvp
double m_Wcompcellpd2
double m_Wcompdrivern
double m_Wcompdriverp
double m_Wcomparen2
double m_Wcomparen1
double m_Wmatchpchg
double m_Wmatchinvn
double m_Wmatchinvp
double m_Wmatchnandn
double m_Wmatchnandp
double m_Wmatchnorn
double m_Wmatchnorp
double m_WSelORn
double m_WSelORprequ
double m_WSelPn
double m_WSelPp
double m_WSelEnn
double m_WSelEnp
double m_Wsenseextdrv1p
double m_Wsenseextdrv1n
double m_Wsenseextdrv2p
double m_Wsenseextdrv2n
double m_CamCellHeight
double m_CamCellWidth
double m_MatchlineSpacing
double m_TaglineSpacing
double m_CrsbarCellHeight
double m_CrsbarCellWidth
double m_krise
double m_tsensedata
double m_tsensetag
double m_tfalldata
double m_tfalltag
double m_WireMinWidth
double m_WireMinSpacing
double m_WireMetalThickness
double m_WireBarrierThickness
double m_WireDielectricThickness
double m_WireDielectricConstant
double m_BufferDriveResistance
double m_BufferIntrinsicDelay
double m_BufferInputCapacitance
double m_BufferPMOSOffCurrent
double m_BufferNMOSOffCurrent
double m_ClockCap
double m_AreaNOR
double m_AreaINV
double m_AreaAND
double m_AreaDFF
double m_AreaMUX2
double m_AreaMUX3
double m_AreaMUX4
double m_NMOS_TAB [1]
double m_PMOS_TAB [1]
double m_NAND2_TAB [4]
double m_NOR2_TAB [4]
double m_DFF_TAB [1]
Detailed Description
Definition at line 45 of file TechParameter.hh.
Member Enumeration Documentation
enum TechParameter::ChannelType
Enumerator:
NCH
PCH
Definition at line 62 of file TechParameter.hh.
enum TechParameter::TransistorType
Enumerator:
LVT
NVT
HVT
NUM_TRANSISTOR_TYPE
Definition at line 48 of file TechParameter.hh.
enum TechParameter::WireLayerType
Enumerator:
LOCAL
INTERMEDIATE
GLOBAL
NUM_WIRE_LAYER_TYPE
Definition at line 55 of file TechParameter.hh.
Constructor & Destructor Documentation
TechParameter::TechParameter (const OrionConfig * orion_cfg_ptr_)
Definition at line 46 of file TechParameter.cc.
References X86ISA::exit, OrionConfig::get(), init(), m_freq, m_orion_cfg_ptr, m_period, m_tech_node, m_transistor_type, m_vdd, and m_wire_layer_type.
TechParameter::~TechParameter ()
Definition at line 116 of file TechParameter.cc.
Member Function Documentation
double TechParameter::calc_draincap (double width_, ChannelType ch_, uint32_t num_stack_) const
Definition at line 1407 of file TechParameter.cc.
References m_Cndiffarea, m_Cndiffside, m_Cnoverlap, m_Cpdiffarea, m_Cpdiffside, m_Cpoverlap, m_Leff, m_SCALE_T, and NCH.
Referenced by RRArbiter::calc_carry_cap(), RRArbiter::calc_carry_in_cap(), DecoderUnit::calc_chgaddr_cap(), DecoderUnit::calc_chgl1_cap(), BitlineUnit::calc_col_read_cap(), BitlineUnit::calc_col_write_cap(), Crossbar::calc_ctr_cap(), RRArbiter::calc_grant_cap(), MatrixArbiter::calc_grant_cap(), Crossbar::calc_in_cap(), Crossbar::calc_int_cap(), MatrixArbiter::calc_int_cap(), MemUnit::calc_mem_cap(), FlipFlop::calc_node_cap(), Crossbar::calc_out_cap(), OutdrvUnit::calc_outdata_cap(), RRArbiter::calc_req_cap(), MatrixArbiter::calc_req_cap(), OutdrvUnit::calc_select_cap(), DecoderUnit::calc_select_cap(), WordlineUnit::calc_wordline_cap(), and PrechargeUnit::init().
double TechParameter::calc_driver_psize (double cap_, double rise_time_) const
Definition at line 1454 of file TechParameter.cc.
References calc_restowidth(), m_LSCALE, m_vs_inv, m_Wworddrivemax, and PCH.
Referenced by BitlineUnit::calc_col_write_cap(), Crossbar::calc_in_cap(), WordlineUnit::calc_wordline_cap(), and PrechargeUnit::init().
double TechParameter::calc_gatecap (double width_, double wirelength_) const
Definition at line 1383 of file TechParameter.cc.
References m_Cgate, m_Cpolywire, m_Leff, and m_SCALE_T.
Referenced by RRArbiter::calc_carry_cap(), RRArbiter::calc_carry_in_cap(), DecoderUnit::calc_chgaddr_cap(), OutdrvUnit::calc_chgdata_cap(), DecoderUnit::calc_chgl1_cap(), FlipFlop::calc_clock_cap(), BitlineUnit::calc_col_read_cap(), BitlineUnit::calc_col_select_cap(), BitlineUnit::calc_col_write_cap(), Crossbar::calc_ctr_cap(), calc_gatecappass(), Crossbar::calc_in_cap(), Crossbar::calc_int_cap(), MatrixArbiter::calc_int_cap(), MemUnit::calc_mem_cap(), FlipFlop::calc_node_cap(), Crossbar::calc_out_cap(), OutdrvUnit::calc_outdata_cap(), PrechargeUnit::calc_pre_cap(), RRArbiter::calc_pri_cap(), MatrixArbiter::calc_pri_cap(), RRArbiter::calc_req_cap(), MatrixArbiter::calc_req_cap(), OutdrvUnit::calc_select_cap(), DecoderUnit::calc_select_cap(), and WordlineUnit::calc_wordline_cap().
double TechParameter::calc_gatecappass (double width_, double wirelength_) const
Definition at line 1391 of file TechParameter.cc.
References calc_gatecap().
Referenced by WordlineUnit::calc_wordline_cap().
double TechParameter::calc_restowidth (double res_, ChannelType ch_) const
Definition at line 1442 of file TechParameter.cc.
References m_Rnchannelon, and m_Rpchannelon.
Referenced by calc_driver_psize().
double TechParameter::get_amp_idsat () const [inline]
Definition at line 87 of file TechParameter.hh.
References m_amp_idsat.
Referenced by AmpUnit::init().
double TechParameter::get_BitlineSpacing () const [inline]
Definition at line 129 of file TechParameter.hh.
References m_BitlineSpacing.
Referenced by WordlineUnit::init().
double TechParameter::get_BitWidth () const [inline]
Definition at line 130 of file TechParameter.hh.
References m_BitWidth.
Referenced by WordlineUnit::calc_wordline_cap().
double TechParameter::get_BufferDriveResistance () const [inline]
Definition at line 152 of file TechParameter.hh.
References m_BufferDriveResistance.
Referenced by Wire::calc_opt_buffering().
double TechParameter::get_BufferInputCapacitance () const [inline]
Definition at line 153 of file TechParameter.hh.
References m_BufferInputCapacitance.
Referenced by Wire::calc_dynamic_energy(), and Wire::calc_opt_buffering().
double TechParameter::get_BufferNMOSOffCurrent () const [inline]
Definition at line 154 of file TechParameter.hh.
References m_BufferNMOSOffCurrent.
Referenced by Wire::calc_static_power(), and Clock::init().
double TechParameter::get_BufferPMOSOffCurrent () const [inline]
Definition at line 155 of file TechParameter.hh.
References m_BufferPMOSOffCurrent.
Referenced by Wire::calc_static_power(), and Clock::init().
double TechParameter::get_CC2M2metal () const [inline]
Definition at line 101 of file TechParameter.hh.
References m_CC2M2metal.
double TechParameter::get_CC2M3metal () const [inline]
Definition at line 102 of file TechParameter.hh.
References m_CC2M3metal.
double TechParameter::get_CC2metal () const [inline]
Definition at line 100 of file TechParameter.hh.
References m_CC2metal.
double TechParameter::get_CC3M2metal () const [inline]
Definition at line 104 of file TechParameter.hh.
References m_CC3M2metal.
Referenced by BitlineUnit::init().
double TechParameter::get_CC3M3metal () const [inline]
Definition at line 105 of file TechParameter.hh.
References m_CC3M3metal.
Referenced by WordlineUnit::init().
double TechParameter::get_CC3metal () const [inline]
Definition at line 103 of file TechParameter.hh.
References m_CC3metal.
Referenced by MultreeCrossbar::init(), and MatrixCrossbar::init().
double TechParameter::get_CCM2metal () const [inline]
Definition at line 98 of file TechParameter.hh.
References m_CCM2metal.
double TechParameter::get_CCM3metal () const [inline]
Definition at line 99 of file TechParameter.hh.
References m_CCM3metal.
double TechParameter::get_CCmetal () const [inline]
Definition at line 97 of file TechParameter.hh.
References m_CCmetal.
Referenced by MultreeCrossbar::init().
double TechParameter::get_ClockCap () const [inline]
Definition at line 156 of file TechParameter.hh.
References m_ClockCap.
Referenced by Clock::init().
double TechParameter::get_Clockwire () const [inline]
Definition at line 157 of file TechParameter.hh.
References m_Clockwire.
double TechParameter::get_CM2metal () const [inline]
Definition at line 95 of file TechParameter.hh.
References m_CM2metal.
Referenced by BitlineUnit::init().
double TechParameter::get_CM3metal () const [inline]
Definition at line 96 of file TechParameter.hh.
References m_CM3metal.
Referenced by WordlineUnit::init().
double TechParameter::get_Cmetal () const [inline]
Definition at line 94 of file TechParameter.hh.
References m_Cmetal.
Referenced by RRArbiter::calc_req_cap(), MatrixArbiter::calc_req_cap(), MultreeCrossbar::init(), and MatrixCrossbar::init().
double TechParameter::get_CrsbarCellHeight () const [inline]
Definition at line 142 of file TechParameter.hh.
References m_CrsbarCellHeight.
Referenced by MatrixCrossbar::init().
double TechParameter::get_CrsbarCellWidth () const [inline]
Definition at line 141 of file TechParameter.hh.
References m_CrsbarCellWidth.
Referenced by MultreeCrossbar::init(), and MatrixCrossbar::init().
double TechParameter::get_DFF_TAB (uint32_t idx) const [inline]
Definition at line 164 of file TechParameter.hh.
References m_DFF_TAB.
Referenced by RRArbiter::calc_i_static(), MatrixArbiter::calc_i_static(), and Clock::init().
double TechParameter::get_EnergyFactor () const [inline]
Definition at line 107 of file TechParameter.hh.
References m_EnergyFactor.
Referenced by Wire::calc_dynamic_energy(), FlipFlop::init(), MultreeCrossbar::init(), MatrixCrossbar::init(), Clock::init(), WordlineUnit::init(), PrechargeUnit::init(), OutdrvUnit::init(), MemUnit::init(), BitlineUnit::init(), RRArbiter::init(), and MatrixArbiter::init().
double TechParameter::get_freq () const [inline]
Definition at line 85 of file TechParameter.hh.
References m_freq.
double TechParameter::get_Lamda () const [inline]
Definition at line 92 of file TechParameter.hh.
References m_Lamda.
Referenced by MultreeCrossbar::init().
double TechParameter::get_MSCALE () const [inline]
Definition at line 90 of file TechParameter.hh.
References m_MSCALE.
Referenced by BitlineUnit::calc_col_read_cap().
double TechParameter::get_NAND2_TAB (uint32_t idx) const [inline]
Definition at line 162 of file TechParameter.hh.
References m_NAND2_TAB.
Referenced by MatrixCrossbar::calc_i_static().
double TechParameter::get_NMOS_TAB (uint32_t idx) const [inline]
Definition at line 160 of file TechParameter.hh.
References m_NMOS_TAB.
Referenced by MultreeCrossbar::calc_i_static(), MatrixCrossbar::calc_i_static(), MemUnit::calc_i_static(), BitlineUnit::calc_i_static(), RRArbiter::calc_i_static(), MatrixArbiter::calc_i_static(), and WordlineUnit::init().
double TechParameter::get_NOR2_TAB (uint32_t idx) const [inline]
Definition at line 163 of file TechParameter.hh.
References m_NOR2_TAB.
Referenced by FlipFlop::calc_i_static(), MultreeCrossbar::calc_i_static(), MatrixCrossbar::calc_i_static(), RRArbiter::calc_i_static(), and MatrixArbiter::calc_i_static().
double TechParameter::get_period () const [inline]
Definition at line 86 of file TechParameter.hh.
References m_period.
Referenced by BitlineUnit::calc_col_write_cap(), Crossbar::calc_in_cap(), WordlineUnit::calc_wordline_cap(), PrechargeUnit::init(), and AmpUnit::init().
double TechParameter::get_PMOS_TAB (uint32_t idx) const [inline]
Definition at line 161 of file TechParameter.hh.
References m_PMOS_TAB.
Referenced by MultreeCrossbar::calc_i_static(), MatrixCrossbar::calc_i_static(), MemUnit::calc_i_static(), BitlineUnit::calc_i_static(), RRArbiter::calc_i_static(), MatrixArbiter::calc_i_static(), WordlineUnit::init(), and PrechargeUnit::init().
double TechParameter::get_RegCellHeight () const [inline]
Definition at line 126 of file TechParameter.hh.
References m_RegCellHeight.
Referenced by BitlineUnit::init().
double TechParameter::get_RegCellWidth () const [inline]
Definition at line 127 of file TechParameter.hh.
References m_RegCellWidth.
Referenced by WordlineUnit::init().
double TechParameter::get_Reswire () const [inline]
Definition at line 158 of file TechParameter.hh.
References m_Reswire.
double TechParameter::get_SCALE_S () const [inline]
Definition at line 89 of file TechParameter.hh.
References m_SCALE_S.
Referenced by Crossbar::get_static_power(), Buffer::get_static_power(), Arbiter::get_static_power(), and Clock::init().
double TechParameter::get_SenseEnergyFactor () const [inline]
Definition at line 108 of file TechParameter.hh.
References m_SenseEnergyFactor.
Referenced by PrechargeUnit::init(), and BitlineUnit::init().
double TechParameter::get_tech_node () const [inline]
Definition at line 83 of file TechParameter.hh.
References m_tech_node.
Referenced by Wire::Wire().
double TechParameter::get_vdd () const [inline]
Definition at line 84 of file TechParameter.hh.
References m_vdd.
Referenced by Wire::calc_static_power(), Crossbar::get_static_power(), Clock::get_static_power(), Buffer::get_static_power(), Arbiter::get_static_power(), DecoderUnit::init(), and AmpUnit::init().
double TechParameter::get_Wbitmuxn () const [inline]
Definition at line 120 of file TechParameter.hh.
References m_Wbitmuxn.
Referenced by BitlineUnit::calc_col_select_cap().
double TechParameter::get_Wdec3to8n () const [inline]
Definition at line 134 of file TechParameter.hh.
References m_Wdec3to8n.
Referenced by DecoderUnit::calc_chgaddr_cap(), and DecoderUnit::calc_chgl1_cap().
double TechParameter::get_Wdec3to8p () const [inline]
Definition at line 135 of file TechParameter.hh.
References m_Wdec3to8p.
Referenced by DecoderUnit::calc_chgaddr_cap(), and DecoderUnit::calc_chgl1_cap().
double TechParameter::get_Wdecdriven () const [inline]
Definition at line 138 of file TechParameter.hh.
References m_Wdecdriven.
Referenced by DecoderUnit::calc_chgaddr_cap().
double TechParameter::get_Wdecdrivep () const [inline]
Definition at line 139 of file TechParameter.hh.
References m_Wdecdrivep.
Referenced by DecoderUnit::calc_chgaddr_cap().
double TechParameter::get_Wdecinvn () const [inline]
Definition at line 132 of file TechParameter.hh.
References m_Wdecinvn.
Referenced by DecoderUnit::calc_chgaddr_cap(), BitlineUnit::calc_col_write_cap(), Crossbar::calc_ctr_cap(), MultreeCrossbar::calc_i_static(), MatrixCrossbar::calc_i_static(), BitlineUnit::calc_i_static(), RRArbiter::calc_i_static(), MatrixArbiter::calc_i_static(), Crossbar::calc_in_cap(), Crossbar::calc_int_cap(), Crossbar::calc_out_cap(), RRArbiter::calc_req_cap(), MatrixArbiter::calc_req_cap(), DecoderUnit::calc_select_cap(), WordlineUnit::calc_wordline_cap(), and PrechargeUnit::init().
double TechParameter::get_Wdecinvp () const [inline]
Definition at line 133 of file TechParameter.hh.
References m_Wdecinvp.
Referenced by DecoderUnit::calc_chgaddr_cap(), BitlineUnit::calc_col_write_cap(), Crossbar::calc_ctr_cap(), MultreeCrossbar::calc_i_static(), MatrixCrossbar::calc_i_static(), BitlineUnit::calc_i_static(), RRArbiter::calc_i_static(), MatrixArbiter::calc_i_static(), Crossbar::calc_in_cap(), Crossbar::calc_int_cap(), Crossbar::calc_out_cap(), RRArbiter::calc_req_cap(), MatrixArbiter::calc_req_cap(), DecoderUnit::calc_select_cap(), WordlineUnit::calc_wordline_cap(), and PrechargeUnit::init().
double TechParameter::get_WdecNORn () const [inline]
Definition at line 136 of file TechParameter.hh.
References m_WdecNORn.
Referenced by RRArbiter::calc_carry_cap(), RRArbiter::calc_carry_in_cap(), DecoderUnit::calc_chgl1_cap(), FlipFlop::calc_clock_cap(), Crossbar::calc_ctr_cap(), RRArbiter::calc_grant_cap(), MatrixArbiter::calc_grant_cap(), FlipFlop::calc_i_static(), MultreeCrossbar::calc_i_static(), RRArbiter::calc_i_static(), MatrixArbiter::calc_i_static(), MatrixArbiter::calc_int_cap(), FlipFlop::calc_node_cap(), RRArbiter::calc_pri_cap(), MatrixArbiter::calc_pri_cap(), RRArbiter::calc_req_cap(), MatrixArbiter::calc_req_cap(), and DecoderUnit::calc_select_cap().
double TechParameter::get_WdecNORp () const [inline]
Definition at line 137 of file TechParameter.hh.
References m_WdecNORp.
Referenced by RRArbiter::calc_carry_cap(), RRArbiter::calc_carry_in_cap(), DecoderUnit::calc_chgl1_cap(), FlipFlop::calc_clock_cap(), Crossbar::calc_ctr_cap(), RRArbiter::calc_grant_cap(), MatrixArbiter::calc_grant_cap(), FlipFlop::calc_i_static(), MultreeCrossbar::calc_i_static(), RRArbiter::calc_i_static(), MatrixArbiter::calc_i_static(), MatrixArbiter::calc_int_cap(), FlipFlop::calc_node_cap(), RRArbiter::calc_pri_cap(), MatrixArbiter::calc_pri_cap(), RRArbiter::calc_req_cap(), MatrixArbiter::calc_req_cap(), and DecoderUnit::calc_select_cap().
double TechParameter::get_Wdff () const [inline]
Definition at line 144 of file TechParameter.hh.
References m_Wdff.
Referenced by RRArbiter::calc_i_static(), MatrixArbiter::calc_i_static(), and Clock::init().
double TechParameter::get_WireBarrierThickness () const [inline]
Definition at line 148 of file TechParameter.hh.
References m_WireBarrierThickness.
Referenced by Wire::calc_res_unit_len().
double TechParameter::get_WireDielectricConstant () const [inline]
Definition at line 151 of file TechParameter.hh.
References m_WireDielectricConstant.
Referenced by Wire::calc_couple_cap_unit_len(), and Wire::calc_gnd_cap_unit_len().
double TechParameter::get_WireDielectricThickness () const [inline]
Definition at line 150 of file TechParameter.hh.
References m_WireDielectricThickness.
Referenced by Wire::calc_couple_cap_unit_len(), and Wire::calc_gnd_cap_unit_len().
double TechParameter::get_WireMetalThickness () const [inline]
Definition at line 149 of file TechParameter.hh.
References m_WireMetalThickness.
Referenced by Wire::calc_couple_cap_unit_len(), Wire::calc_gnd_cap_unit_len(), and Wire::calc_res_unit_len().
double TechParameter::get_WireMinSpacing () const [inline]
Definition at line 147 of file TechParameter.hh.
References m_WireMinSpacing.
Referenced by Wire::calc_couple_cap_unit_len(), and Wire::calc_gnd_cap_unit_len().
double TechParameter::get_WireMinWidth () const [inline]
Definition at line 146 of file TechParameter.hh.
References m_WireMinWidth.
Referenced by Wire::calc_couple_cap_unit_len(), Wire::calc_gnd_cap_unit_len(), and Wire::calc_res_unit_len().
double TechParameter::get_Wmemcella () const [inline]
Definition at line 123 of file TechParameter.hh.
References m_Wmemcella.
Referenced by MemUnit::calc_i_static(), and MemUnit::calc_mem_cap().
double TechParameter::get_Wmemcellbscale () const [inline]
Definition at line 124 of file TechParameter.hh.
References m_Wmemcellbscale.
Referenced by MemUnit::calc_i_static(), and MemUnit::calc_mem_cap().
double TechParameter::get_Wmemcellr () const [inline]
Definition at line 121 of file TechParameter.hh.
References m_Wmemcellr.
Referenced by BitlineUnit::calc_col_read_cap(), Crossbar::calc_ctr_cap(), MemUnit::calc_i_static(), Crossbar::calc_in_cap(), Crossbar::calc_int_cap(), MemUnit::calc_mem_cap(), Crossbar::calc_out_cap(), and WordlineUnit::init().
double TechParameter::get_Wmemcellw () const [inline]
Definition at line 122 of file TechParameter.hh.
References m_Wmemcellw.
Referenced by BitlineUnit::calc_col_write_cap(), MemUnit::calc_i_static(), MemUnit::calc_mem_cap(), and WordlineUnit::init().
double TechParameter::get_WordlineSpacing () const [inline]
Definition at line 128 of file TechParameter.hh.
References m_WordlineSpacing.
Referenced by BitlineUnit::init().
double TechParameter::get_Woutdrivern () const [inline]
Definition at line 116 of file TechParameter.hh.
References m_Woutdrivern.
Referenced by MultreeCrossbar::calc_i_static(), MatrixCrossbar::calc_i_static(), Crossbar::calc_in_cap(), Crossbar::calc_int_cap(), Crossbar::calc_out_cap(), OutdrvUnit::calc_outdata_cap(), and WordlineUnit::init().
double TechParameter::get_Woutdriverp () const [inline]
Definition at line 117 of file TechParameter.hh.
References m_Woutdriverp.
Referenced by MultreeCrossbar::calc_i_static(), MatrixCrossbar::calc_i_static(), Crossbar::calc_in_cap(), Crossbar::calc_int_cap(), Crossbar::calc_out_cap(), OutdrvUnit::calc_outdata_cap(), and WordlineUnit::init().
double TechParameter::get_Woutdrvnandn () const [inline]
Definition at line 112 of file TechParameter.hh.
References m_Woutdrvnandn.
Referenced by OutdrvUnit::calc_chgdata_cap(), BitlineUnit::calc_col_read_cap(), Crossbar::calc_ctr_cap(), MatrixCrossbar::calc_i_static(), Crossbar::calc_in_cap(), Crossbar::calc_int_cap(), Crossbar::calc_out_cap(), OutdrvUnit::calc_outdata_cap(), and OutdrvUnit::calc_select_cap().
double TechParameter::get_Woutdrvnandp () const [inline]
Definition at line 113 of file TechParameter.hh.
References m_Woutdrvnandp.
Referenced by OutdrvUnit::calc_chgdata_cap(), BitlineUnit::calc_col_read_cap(), Crossbar::calc_ctr_cap(), MatrixCrossbar::calc_i_static(), Crossbar::calc_in_cap(), Crossbar::calc_int_cap(), Crossbar::calc_out_cap(), OutdrvUnit::calc_outdata_cap(), and OutdrvUnit::calc_select_cap().
double TechParameter::get_Woutdrvnorn () const [inline]
Definition at line 114 of file TechParameter.hh.
References m_Woutdrvnorn.
Referenced by OutdrvUnit::calc_chgdata_cap(), BitlineUnit::calc_col_read_cap(), Crossbar::calc_ctr_cap(), MatrixCrossbar::calc_i_static(), Crossbar::calc_in_cap(), Crossbar::calc_int_cap(), Crossbar::calc_out_cap(), OutdrvUnit::calc_outdata_cap(), and OutdrvUnit::calc_select_cap().
double TechParameter::get_Woutdrvnorp () const [inline]
Definition at line 115 of file TechParameter.hh.
References m_Woutdrvnorp.
Referenced by OutdrvUnit::calc_chgdata_cap(), BitlineUnit::calc_col_read_cap(), Crossbar::calc_ctr_cap(), MatrixCrossbar::calc_i_static(), Crossbar::calc_in_cap(), Crossbar::calc_int_cap(), Crossbar::calc_out_cap(), OutdrvUnit::calc_outdata_cap(), and OutdrvUnit::calc_select_cap().
double TechParameter::get_Woutdrvseln () const [inline]
Definition at line 110 of file TechParameter.hh.
References m_Woutdrvseln.
Referenced by OutdrvUnit::calc_select_cap().
double TechParameter::get_Woutdrvselp () const [inline]
Definition at line 111 of file TechParameter.hh.
References m_Woutdrvselp.
Referenced by OutdrvUnit::calc_select_cap().
double TechParameter::get_WsenseQ1to4 () const [inline]
Definition at line 119 of file TechParameter.hh.
References m_WsenseQ1to4.
Referenced by BitlineUnit::calc_col_read_cap().
void TechParameter::init () [private]
Definition at line 119 of file TechParameter.cc.
References init_tech_110_800(), init_tech_32_90(), m_address_bits, m_af, m_amp_idsat, m_bit_out, m_fudge_factor, m_gen_power_factor, m_max_n, m_max_spd, m_max_subarrays, m_normalize_scale, m_res_ialu, m_ruu_issue_width, m_ruu_size, m_tech_node, m_vs_inv, m_vth_comp_inv, m_vth_eval_inv, m_vth_inv_100x60, m_vth_muxdrv1, m_vth_muxdrv2, m_vth_muxdrv3, m_vth_nand_60x90, m_vth_nor_12x4x1, m_vth_nor_12x4x2, m_vth_nor_12x4x3, m_vth_nor_12x4x4, m_vth_outdr_inv, m_vth_outdr_nand, m_vth_outdr_nor, and m_vth_outdrive.
Referenced by TechParameter().
void TechParameter::init_tech_110_800 () [private]
Definition at line 162 of file TechParameter.cc.
References m_Cgate, m_Cgatepass, m_Cndiffarea, m_Cndiffovlp, m_Cndiffside, m_Cnoverlap, m_Cnoxideovlp, m_Cpdiffarea, m_Cpdiffovlp, m_Cpdiffside, m_Cpoverlap, and m_Cpoxideovlp.
Referenced by init().
void TechParameter::init_tech_32_90 () [private]
Definition at line 181 of file TechParameter.cc.
References ArmISA::e, X86ISA::exit, GLOBAL, HVT, INTERMEDIATE, LOCAL, LVT, m_AreaAND, m_AreaDFF, m_AreaINV, m_AreaMUX2, m_AreaMUX3, m_AreaMUX4, m_AreaNOR, m_BitHeight, m_BitlineSpacing, m_BitWidth, m_BufferDriveResistance, m_BufferInputCapacitance, m_BufferIntrinsicDelay, m_BufferNMOSOffCurrent, m_BufferPMOSOffCurrent, m_CamCellHeight, m_CamCellWidth, m_Cbitmetal, m_CC2M2metal, m_CC2M3metal, m_CC2metal, m_CC3M2metal, m_CC3M3metal, m_CC3metal, m_CCM2metal, m_CCM3metal, m_CCmetal, m_Cgate, m_Cgatepass, m_ClockCap, m_Clockwire, m_CM2metal, m_CM3metal, m_Cmetal, m_Cndiffarea, m_Cndiffovlp, m_Cndiffside, m_Cnoverlap, m_Cnoxideovlp, m_Cout, m_Cpdiffarea, m_Cpdiffovlp, m_Cpdiffside, m_Cpolywire, m_Cpoverlap, m_Cpoxideovlp, m_CrsbarCellHeight, m_CrsbarCellWidth, m_Cwordmetal, m_DFF_TAB, m_EnergyFactor, m_invCap, m_krise, m_Lamda, m_Leff, m_LSCALE, m_MatchlineSpacing, m_MSCALE, m_NAND2_TAB, m_NMOS_TAB, m_NOR2_TAB, m_PMOS_TAB, m_Rbitmetal, m_RegCellHeight, m_RegCellWidth, m_Resout, m_Reswire, m_Rnchannelon, m_Rnchannelstatic, m_Rpchannelon, m_Rpchannelstatic, m_Rwordmetal, m_SCALE_BW, m_SCALE_Crs, m_SCALE_H, m_SCALE_M, m_SCALE_S, m_SCALE_T, m_SCALE_W, m_SenseEnergyFactor, m_SenseEnergyFactor2, m_SenseEnergyFactor3, m_TaglineSpacing, m_tech_node, m_tfalldata, m_tfalltag, m_transistor_type, m_tsensedata, m_tsensetag, m_Vbitpre, m_Vbitsense, m_vdd, m_Vt, m_Wbitmuxn, m_Wbitpreequ, m_Wbusdrvn, m_Wbusdrvp, m_Wcomparen1, m_Wcomparen2, m_Wcompcellpd2, m_Wcompdrivern, m_Wcompdriverp, m_Wcompinvn1, m_Wcompinvn2, m_Wcompinvn3, m_Wcompinvp1, m_Wcompinvp2, m_Wcompinvp3, m_Wcompn, m_Wcompp, m_Wcomppreequ, m_Wdec3to8n, m_Wdec3to8p, m_Wdecdriven, m_Wdecdrivep, m_Wdecinvn, m_Wdecinvp, m_WdecNORn, m_WdecNORp, m_Wdff, m_Wevalinvn, m_Wevalinvp, m_wire_layer_type, m_WireBarrierThickness, m_WireDielectricConstant, m_WireDielectricThickness, m_WireMetalThickness, m_WireMinSpacing, m_WireMinWidth, m_Wmatchinvn, m_Wmatchinvp, m_Wmatchnandn, m_Wmatchnandp, m_Wmatchnorn, m_Wmatchnorp, m_Wmatchpchg, m_Wmemcella, m_Wmemcellbscale, m_Wmemcellr, m_Wmemcellw, m_Wmuxdrv12n, m_Wmuxdrv12p, m_Wmuxdrv3n, m_Wmuxdrv3p, m_WmuxdrvNANDn, m_WmuxdrvNANDp, m_WmuxdrvNORn, m_WmuxdrvNORp, m_WordlineSpacing, m_Woutdrivern, m_Woutdriverp, m_Woutdrvnandn, m_Woutdrvnandp, m_Woutdrvnorn, m_Woutdrvnorp, m_Woutdrvseln, m_Woutdrvselp, m_WSelEnn, m_WSelEnp, m_WSelORn, m_WSelORprequ, m_WSelPn, m_WSelPp, m_Wsenseextdrv1n, m_Wsenseextdrv1p, m_Wsenseextdrv2n, m_Wsenseextdrv2p, m_WsenseQ1to4, m_Wworddrivemax, and NVT.
Referenced by init().
void TechParameter::init_tech_90 () [private]
bool TechParameter::is_trans_type_hvt () const [inline]
Definition at line 80 of file TechParameter.hh.
References HVT, and m_transistor_type.
Referenced by Clock::init().
bool TechParameter::is_trans_type_lvt () const [inline]
Definition at line 82 of file TechParameter.hh.
References LVT, and m_transistor_type.
bool TechParameter::is_trans_type_nvt () const [inline]
Definition at line 81 of file TechParameter.hh.
References m_transistor_type, and NVT.
Referenced by Clock::init().
Member Data Documentation
uint32_t TechParameter::m_address_bits [private]
Definition at line 199 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_af [private]
Definition at line 181 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_amp_idsat [private]
Definition at line 189 of file TechParameter.hh.
Referenced by get_amp_idsat(), and init().
double TechParameter::m_AreaAND [private]
Definition at line 398 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_AreaDFF [private]
Definition at line 399 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_AreaINV [private]
Definition at line 397 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_AreaMUX2 [private]
Definition at line 400 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_AreaMUX3 [private]
Definition at line 401 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_AreaMUX4 [private]
Definition at line 402 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_AreaNOR [private]
Definition at line 396 of file TechParameter.hh.
Referenced by init_tech_32_90().
uint32_t TechParameter::m_bit_out [private]
Definition at line 187 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_BitHeight [private]
Definition at line 243 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_BitlineSpacing [private]
Definition at line 244 of file TechParameter.hh.
Referenced by get_BitlineSpacing(), and init_tech_32_90().
double TechParameter::m_BitWidth [private]
Definition at line 242 of file TechParameter.hh.
Referenced by get_BitWidth(), and init_tech_32_90().
double TechParameter::m_BufferDriveResistance [private]
Definition at line 389 of file TechParameter.hh.
Referenced by get_BufferDriveResistance(), and init_tech_32_90().
double TechParameter::m_BufferInputCapacitance [private]
Definition at line 391 of file TechParameter.hh.
Referenced by get_BufferInputCapacitance(), and init_tech_32_90().
double TechParameter::m_BufferIntrinsicDelay [private]
Definition at line 390 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_BufferNMOSOffCurrent [private]
Definition at line 393 of file TechParameter.hh.
Referenced by get_BufferNMOSOffCurrent(), and init_tech_32_90().
double TechParameter::m_BufferPMOSOffCurrent [private]
Definition at line 392 of file TechParameter.hh.
Referenced by get_BufferPMOSOffCurrent(), and init_tech_32_90().
double TechParameter::m_CamCellHeight [private]
Definition at line 367 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_CamCellWidth [private]
Definition at line 368 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Cbitmetal [private]
Definition at line 253 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_CC2M2metal [private]
Definition at line 264 of file TechParameter.hh.
Referenced by get_CC2M2metal(), and init_tech_32_90().
double TechParameter::m_CC2M3metal [private]
Definition at line 265 of file TechParameter.hh.
Referenced by get_CC2M3metal(), and init_tech_32_90().
double TechParameter::m_CC2metal [private]
Definition at line 263 of file TechParameter.hh.
Referenced by get_CC2metal(), and init_tech_32_90().
double TechParameter::m_CC3M2metal [private]
Definition at line 268 of file TechParameter.hh.
Referenced by get_CC3M2metal(), and init_tech_32_90().
double TechParameter::m_CC3M3metal [private]
Definition at line 269 of file TechParameter.hh.
Referenced by get_CC3M3metal(), and init_tech_32_90().
double TechParameter::m_CC3metal [private]
Definition at line 267 of file TechParameter.hh.
Referenced by get_CC3metal(), and init_tech_32_90().
double TechParameter::m_CCM2metal [private]
Definition at line 260 of file TechParameter.hh.
Referenced by get_CCM2metal(), and init_tech_32_90().
double TechParameter::m_CCM3metal [private]
Definition at line 261 of file TechParameter.hh.
Referenced by get_CCM3metal(), and init_tech_32_90().
double TechParameter::m_CCmetal [private]
Definition at line 259 of file TechParameter.hh.
Referenced by get_CCmetal(), and init_tech_32_90().
double TechParameter::m_Cgate [private]
Definition at line 218 of file TechParameter.hh.
Referenced by calc_gatecap(), init_tech_110_800(), and init_tech_32_90().
double TechParameter::m_Cgatepass [private]
Definition at line 217 of file TechParameter.hh.
Referenced by init_tech_110_800(), and init_tech_32_90().
double TechParameter::m_ClockCap [private]
Definition at line 394 of file TechParameter.hh.
Referenced by get_ClockCap(), and init_tech_32_90().
double TechParameter::m_Clockwire [private]
Definition at line 271 of file TechParameter.hh.
Referenced by get_Clockwire(), and init_tech_32_90().
double TechParameter::m_CM2metal [private]
Definition at line 256 of file TechParameter.hh.
Referenced by get_CM2metal(), and init_tech_32_90().
double TechParameter::m_CM3metal [private]
Definition at line 257 of file TechParameter.hh.
Referenced by get_CM3metal(), and init_tech_32_90().
double TechParameter::m_Cmetal [private]
Definition at line 255 of file TechParameter.hh.
Referenced by get_Cmetal(), and init_tech_32_90().
double TechParameter::m_Cndiffarea [private]
Definition at line 214 of file TechParameter.hh.
Referenced by calc_draincap(), init_tech_110_800(), and init_tech_32_90().
double TechParameter::m_Cndiffovlp [private]
Definition at line 220 of file TechParameter.hh.
Referenced by init_tech_110_800(), and init_tech_32_90().
double TechParameter::m_Cndiffside [private]
Definition at line 215 of file TechParameter.hh.
Referenced by calc_draincap(), init_tech_110_800(), and init_tech_32_90().
double TechParameter::m_Cnoverlap [private]
Definition at line 216 of file TechParameter.hh.
Referenced by calc_draincap(), init_tech_110_800(), and init_tech_32_90().
double TechParameter::m_Cnoxideovlp [private]
Definition at line 222 of file TechParameter.hh.
Referenced by init_tech_110_800(), and init_tech_32_90().
double TechParameter::m_Cout [private]
Definition at line 250 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Cpdiffarea [private]
Definition at line 211 of file TechParameter.hh.
Referenced by calc_draincap(), init_tech_110_800(), and init_tech_32_90().
double TechParameter::m_Cpdiffovlp [private]
Definition at line 219 of file TechParameter.hh.
Referenced by init_tech_110_800(), and init_tech_32_90().
double TechParameter::m_Cpdiffside [private]
Definition at line 212 of file TechParameter.hh.
Referenced by calc_draincap(), init_tech_110_800(), and init_tech_32_90().
double TechParameter::m_Cpolywire [private]
Definition at line 279 of file TechParameter.hh.
Referenced by calc_gatecap(), and init_tech_32_90().
double TechParameter::m_Cpoverlap [private]
Definition at line 213 of file TechParameter.hh.
Referenced by calc_draincap(), init_tech_110_800(), and init_tech_32_90().
double TechParameter::m_Cpoxideovlp [private]
Definition at line 221 of file TechParameter.hh.
Referenced by init_tech_110_800(), and init_tech_32_90().
double TechParameter::m_CrsbarCellHeight [private]
Definition at line 373 of file TechParameter.hh.
Referenced by get_CrsbarCellHeight(), and init_tech_32_90().
double TechParameter::m_CrsbarCellWidth [private]
Definition at line 374 of file TechParameter.hh.
Referenced by get_CrsbarCellWidth(), and init_tech_32_90().
double TechParameter::m_Cwordmetal [private]
Definition at line 252 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_DFF_TAB[1] [private]
Definition at line 408 of file TechParameter.hh.
Referenced by get_DFF_TAB(), and init_tech_32_90().
double TechParameter::m_EnergyFactor [private]
Definition at line 226 of file TechParameter.hh.
Referenced by get_EnergyFactor(), and init_tech_32_90().
double TechParameter::m_freq [private]
Definition at line 177 of file TechParameter.hh.
Referenced by get_freq(), and TechParameter().
double TechParameter::m_fudge_factor [private]
Definition at line 193 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_gen_power_factor [private]
Definition at line 191 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_invCap [private]
Definition at line 273 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_krise [private]
Definition at line 376 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Lamda [private]
Definition at line 277 of file TechParameter.hh.
Referenced by get_Lamda(), and init_tech_32_90().
double TechParameter::m_Leff [private]
Definition at line 276 of file TechParameter.hh.
Referenced by calc_draincap(), calc_gatecap(), and init_tech_32_90().
double TechParameter::m_LSCALE [private]
Definition at line 239 of file TechParameter.hh.
Referenced by calc_driver_psize(), and init_tech_32_90().
double TechParameter::m_MatchlineSpacing [private]
Definition at line 370 of file TechParameter.hh.
Referenced by init_tech_32_90().
uint32_t TechParameter::m_max_n [private]
Definition at line 182 of file TechParameter.hh.
Referenced by init().
uint32_t TechParameter::m_max_spd [private]
Definition at line 184 of file TechParameter.hh.
Referenced by init().
uint32_t TechParameter::m_max_subarrays [private]
Definition at line 183 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_MSCALE [private]
Definition at line 240 of file TechParameter.hh.
Referenced by get_MSCALE(), and init_tech_32_90().
double TechParameter::m_NAND2_TAB[4] [private]
Definition at line 406 of file TechParameter.hh.
Referenced by get_NAND2_TAB(), and init_tech_32_90().
double TechParameter::m_NMOS_TAB[1] [private]
Definition at line 404 of file TechParameter.hh.
Referenced by get_NMOS_TAB(), and init_tech_32_90().
double TechParameter::m_NOR2_TAB[4] [private]
Definition at line 407 of file TechParameter.hh.
Referenced by get_NOR2_TAB(), and init_tech_32_90().
double TechParameter::m_normalize_scale [private]
Definition at line 197 of file TechParameter.hh.
Referenced by init().
const OrionConfig* TechParameter::m_orion_cfg_ptr [private]
Definition at line 173 of file TechParameter.hh.
Referenced by TechParameter().
double TechParameter::m_period [private]
Definition at line 178 of file TechParameter.hh.
Referenced by get_period(), and TechParameter().
double TechParameter::m_PMOS_TAB[1] [private]
Definition at line 405 of file TechParameter.hh.
Referenced by get_PMOS_TAB(), and init_tech_32_90().
double TechParameter::m_Rbitmetal [private]
Definition at line 287 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_RegCellHeight [private]
Definition at line 248 of file TechParameter.hh.
Referenced by get_RegCellHeight(), and init_tech_32_90().
double TechParameter::m_RegCellWidth [private]
Definition at line 247 of file TechParameter.hh.
Referenced by get_RegCellWidth(), and init_tech_32_90().
uint32_t TechParameter::m_res_ialu [private]
Definition at line 207 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_Resout [private]
Definition at line 274 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Reswire [private]
Definition at line 272 of file TechParameter.hh.
Referenced by get_Reswire(), and init_tech_32_90().
double TechParameter::m_Rnchannelon [private]
Definition at line 284 of file TechParameter.hh.
Referenced by calc_restowidth(), and init_tech_32_90().
double TechParameter::m_Rnchannelstatic [private]
Definition at line 281 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Rpchannelon [private]
Definition at line 285 of file TechParameter.hh.
Referenced by calc_restowidth(), and init_tech_32_90().
double TechParameter::m_Rpchannelstatic [private]
Definition at line 282 of file TechParameter.hh.
Referenced by init_tech_32_90().
uint32_t TechParameter::m_ruu_issue_width [private]
Definition at line 188 of file TechParameter.hh.
Referenced by init().
uint32_t TechParameter::m_ruu_size [private]
Definition at line 200 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_Rwordmetal [private]
Definition at line 288 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_SCALE_BW [private]
Definition at line 236 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_SCALE_Crs [private]
Definition at line 237 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_SCALE_H [private]
Definition at line 235 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_SCALE_M [private]
Definition at line 232 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_SCALE_S [private]
Definition at line 233 of file TechParameter.hh.
Referenced by get_SCALE_S(), and init_tech_32_90().
double TechParameter::m_SCALE_T [private]
Definition at line 231 of file TechParameter.hh.
Referenced by calc_draincap(), calc_gatecap(), and init_tech_32_90().
double TechParameter::m_SCALE_W [private]
Definition at line 234 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_SenseEnergyFactor [private]
Definition at line 227 of file TechParameter.hh.
Referenced by get_SenseEnergyFactor(), and init_tech_32_90().
double TechParameter::m_SenseEnergyFactor2 [private]
Definition at line 229 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_SenseEnergyFactor3 [private]
Definition at line 228 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_TaglineSpacing [private]
Definition at line 371 of file TechParameter.hh.
Referenced by init_tech_32_90().
unsigned int TechParameter::m_tech_node [private]
Definition at line 174 of file TechParameter.hh.
Referenced by get_tech_node(), init(), init_tech_32_90(), and TechParameter().
double TechParameter::m_tfalldata [private]
Definition at line 379 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_tfalltag [private]
Definition at line 380 of file TechParameter.hh.
Referenced by init_tech_32_90().
TransistorType TechParameter::m_transistor_type [private]
Definition at line 175 of file TechParameter.hh.
Referenced by init_tech_32_90(), is_trans_type_hvt(), is_trans_type_lvt(), is_trans_type_nvt(), and TechParameter().
double TechParameter::m_tsensedata [private]
Definition at line 377 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_tsensetag [private]
Definition at line 378 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Vbitpre [private]
Definition at line 224 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Vbitsense [private]
Definition at line 225 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_vdd [private]
Definition at line 176 of file TechParameter.hh.
Referenced by get_vdd(), init_tech_32_90(), and TechParameter().
double TechParameter::m_vs_inv [private]
Definition at line 190 of file TechParameter.hh.
Referenced by calc_driver_psize(), and init().
double TechParameter::m_Vt [private]
Definition at line 290 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_vth_comp_inv [private]
Definition at line 186 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_vth_eval_inv [private]
Definition at line 205 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_vth_inv_100x60 [private]
Definition at line 209 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_vth_muxdrv1 [private]
Definition at line 195 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_vth_muxdrv2 [private]
Definition at line 196 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_vth_muxdrv3 [private]
Definition at line 198 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_vth_nand_60x90 [private]
Definition at line 192 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_vth_nor_12x4x1 [private]
Definition at line 201 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_vth_nor_12x4x2 [private]
Definition at line 202 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_vth_nor_12x4x3 [private]
Definition at line 204 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_vth_nor_12x4x4 [private]
Definition at line 206 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_vth_outdr_inv [private]
Definition at line 203 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_vth_outdr_nand [private]
Definition at line 208 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_vth_outdr_nor [private]
Definition at line 185 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_vth_outdrive [private]
Definition at line 194 of file TechParameter.hh.
Referenced by init().
double TechParameter::m_Wbitmuxn [private]
Definition at line 309 of file TechParameter.hh.
Referenced by get_Wbitmuxn(), and init_tech_32_90().
double TechParameter::m_Wbitpreequ [private]
Definition at line 307 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wbusdrvn [private]
Definition at line 339 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wbusdrvp [private]
Definition at line 340 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wcomparen1 [private]
Definition at line 346 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wcomparen2 [private]
Definition at line 345 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wcompcellpd2 [private]
Definition at line 342 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wcompdrivern [private]
Definition at line 343 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wcompdriverp [private]
Definition at line 344 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wcompinvn1 [private]
Definition at line 312 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wcompinvn2 [private]
Definition at line 314 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wcompinvn3 [private]
Definition at line 316 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wcompinvp1 [private]
Definition at line 311 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wcompinvp2 [private]
Definition at line 313 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wcompinvp3 [private]
Definition at line 315 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wcompn [private]
Definition at line 320 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wcompp [private]
Definition at line 321 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wcomppreequ [private]
Definition at line 322 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wdec3to8n [private]
Definition at line 294 of file TechParameter.hh.
Referenced by get_Wdec3to8n(), and init_tech_32_90().
double TechParameter::m_Wdec3to8p [private]
Definition at line 295 of file TechParameter.hh.
Referenced by get_Wdec3to8p(), and init_tech_32_90().
double TechParameter::m_Wdecdriven [private]
Definition at line 293 of file TechParameter.hh.
Referenced by get_Wdecdriven(), and init_tech_32_90().
double TechParameter::m_Wdecdrivep [private]
Definition at line 292 of file TechParameter.hh.
Referenced by get_Wdecdrivep(), and init_tech_32_90().
double TechParameter::m_Wdecinvn [private]
Definition at line 298 of file TechParameter.hh.
Referenced by get_Wdecinvn(), and init_tech_32_90().
double TechParameter::m_Wdecinvp [private]
Definition at line 299 of file TechParameter.hh.
Referenced by get_Wdecinvp(), and init_tech_32_90().
double TechParameter::m_WdecNORn [private]
Definition at line 296 of file TechParameter.hh.
Referenced by get_WdecNORn(), and init_tech_32_90().
double TechParameter::m_WdecNORp [private]
Definition at line 297 of file TechParameter.hh.
Referenced by get_WdecNORp(), and init_tech_32_90().
double TechParameter::m_Wdff [private]
Definition at line 300 of file TechParameter.hh.
Referenced by get_Wdff(), and init_tech_32_90().
double TechParameter::m_Wevalinvn [private]
Definition at line 318 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wevalinvp [private]
Definition at line 317 of file TechParameter.hh.
Referenced by init_tech_32_90().
WireLayerType TechParameter::m_wire_layer_type [private]
Definition at line 179 of file TechParameter.hh.
Referenced by init_tech_32_90(), and TechParameter().
double TechParameter::m_WireBarrierThickness [private]
Definition at line 385 of file TechParameter.hh.
Referenced by get_WireBarrierThickness(), and init_tech_32_90().
double TechParameter::m_WireDielectricConstant [private]
Definition at line 387 of file TechParameter.hh.
Referenced by get_WireDielectricConstant(), and init_tech_32_90().
double TechParameter::m_WireDielectricThickness [private]
Definition at line 386 of file TechParameter.hh.
Referenced by get_WireDielectricThickness(), and init_tech_32_90().
double TechParameter::m_WireMetalThickness [private]
Definition at line 384 of file TechParameter.hh.
Referenced by get_WireMetalThickness(), and init_tech_32_90().
double TechParameter::m_WireMinSpacing [private]
Definition at line 383 of file TechParameter.hh.
Referenced by get_WireMinSpacing(), and init_tech_32_90().
double TechParameter::m_WireMinWidth [private]
Definition at line 382 of file TechParameter.hh.
Referenced by get_WireMinWidth(), and init_tech_32_90().
double TechParameter::m_Wmatchinvn [private]
Definition at line 348 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wmatchinvp [private]
Definition at line 349 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wmatchnandn [private]
Definition at line 350 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wmatchnandp [private]
Definition at line 351 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wmatchnorn [private]
Definition at line 352 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wmatchnorp [private]
Definition at line 353 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wmatchpchg [private]
Definition at line 347 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wmemcella [private]
Definition at line 303 of file TechParameter.hh.
Referenced by get_Wmemcella(), and init_tech_32_90().
double TechParameter::m_Wmemcellbscale [private]
Definition at line 306 of file TechParameter.hh.
Referenced by get_Wmemcellbscale(), and init_tech_32_90().
double TechParameter::m_Wmemcellr [private]
Definition at line 304 of file TechParameter.hh.
Referenced by get_Wmemcellr(), and init_tech_32_90().
double TechParameter::m_Wmemcellw [private]
Definition at line 305 of file TechParameter.hh.
Referenced by get_Wmemcellw(), and init_tech_32_90().
double TechParameter::m_Wmuxdrv12n [private]
Definition at line 323 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wmuxdrv12p [private]
Definition at line 324 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wmuxdrv3n [private]
Definition at line 329 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wmuxdrv3p [private]
Definition at line 330 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_WmuxdrvNANDn [private]
Definition at line 325 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_WmuxdrvNANDp [private]
Definition at line 326 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_WmuxdrvNORn [private]
Definition at line 327 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_WmuxdrvNORp [private]
Definition at line 328 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_WordlineSpacing [private]
Definition at line 245 of file TechParameter.hh.
Referenced by get_WordlineSpacing(), and init_tech_32_90().
double TechParameter::m_Woutdrivern [private]
Definition at line 337 of file TechParameter.hh.
Referenced by get_Woutdrivern(), and init_tech_32_90().
double TechParameter::m_Woutdriverp [private]
Definition at line 338 of file TechParameter.hh.
Referenced by get_Woutdriverp(), and init_tech_32_90().
double TechParameter::m_Woutdrvnandn [private]
Definition at line 333 of file TechParameter.hh.
Referenced by get_Woutdrvnandn(), and init_tech_32_90().
double TechParameter::m_Woutdrvnandp [private]
Definition at line 334 of file TechParameter.hh.
Referenced by get_Woutdrvnandp(), and init_tech_32_90().
double TechParameter::m_Woutdrvnorn [private]
Definition at line 335 of file TechParameter.hh.
Referenced by get_Woutdrvnorn(), and init_tech_32_90().
double TechParameter::m_Woutdrvnorp [private]
Definition at line 336 of file TechParameter.hh.
Referenced by get_Woutdrvnorp(), and init_tech_32_90().
double TechParameter::m_Woutdrvseln [private]
Definition at line 331 of file TechParameter.hh.
Referenced by get_Woutdrvseln(), and init_tech_32_90().
double TechParameter::m_Woutdrvselp [private]
Definition at line 332 of file TechParameter.hh.
Referenced by get_Woutdrvselp(), and init_tech_32_90().
double TechParameter::m_WSelEnn [private]
Definition at line 359 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_WSelEnp [private]
Definition at line 360 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_WSelORn [private]
Definition at line 355 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_WSelORprequ [private]
Definition at line 356 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_WSelPn [private]
Definition at line 357 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_WSelPp [private]
Definition at line 358 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wsenseextdrv1n [private]
Definition at line 363 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wsenseextdrv1p [private]
Definition at line 362 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wsenseextdrv2n [private]
Definition at line 365 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_Wsenseextdrv2p [private]
Definition at line 364 of file TechParameter.hh.
Referenced by init_tech_32_90().
double TechParameter::m_WsenseQ1to4 [private]
Definition at line 310 of file TechParameter.hh.
Referenced by get_WsenseQ1to4(), and init_tech_32_90().
double TechParameter::m_Wworddrivemax [private]
Definition at line 302 of file TechParameter.hh.
Referenced by calc_driver_psize(), and init_tech_32_90().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/TechParameter.hh
mem/ruby/network/orion/TechParameter.cc