gem5: AddrMapper Class Reference
AddrMapper Class Reference
An address mapper changes the packet addresses in going from the slave port side of the mapper to the master port side.
#include <addr_mapper.hh>