gem5: MipsISA::Interrupts Class Reference
MipsISA::Interrupts Class Reference
#include <interrupts.hh>