gem5: CpuLocalTimer Class Reference
CpuLocalTimer Class Reference
#include <timer_cpulocal.hh>