gem5: BaseCache::CacheSlavePort Class Reference
BaseCache::CacheSlavePort Class Reference
A cache slave port is used for the CPU-side port of the cache, and it is basically a simple timing port that uses a transmit list for responses to the CPU (or connected master).
#include <base.hh>