gem5: NetworkMessage Class Reference
NetworkMessage Class Reference
#include <NetworkMessage.hh>