gem5: SparcISA::Sparc32LinuxProcess Class Reference
SparcISA::Sparc32LinuxProcess Class Reference
A process with emulated SPARC/Linux syscalls.
#include <process.hh>