gem5: TsunamiCChip Class Reference
TsunamiCChip Class Reference
Tsunami CChip CSR Emulation.
#include <tsunami_cchip.hh>