gem5: IniFile Class Reference
IniFile Class Reference
This class represents the contents of a ".ini" file.
#include <inifile.hh>
Classes
class Entry
A single key/value pair.
class Section
A section.
Public Member Functions
IniFile ()
Constructor.
~IniFile ()
Destructor.
bool load (std::istream &f)
Load parameter settings from given istream.
bool load (const std::string &file)
Load the specified file.
bool add (const std::string &s)
Take string of the form "<section>:<parameter>=<value>" or "<section>:<parameter>+=<value>" and add to database.
bool find (const std::string &section, const std::string &entry, std::string &value) const
Find value corresponding to given section and entry names.
bool sectionExists (const std::string &section) const
Determine whether the named section exists in the .ini file.
bool printUnreferenced ()
Print unreferenced entries in object.
void dump ()
Dump contents to cout. For debugging.
Protected Types
typedef m5::hash_map
< std::string, Section * > SectionTable
SectionTable type. Map of strings to Section object pointers.
Protected Member Functions
Section * addSection (const std::string &sectionName)
Look up section with the given name, creating a new section if not found.
Section * findSection (const std::string &sectionName) const
Look up section with the given name.
Protected Attributes
SectionTable table
Hash of section names to Section object pointers.
Detailed Description
This class represents the contents of a ".ini" file.
It's basically a two level lookup table: a set of named sections, where each section is a set of key/value pairs. Section names, keys, and values are all uninterpreted strings.
Definition at line 55 of file inifile.hh.
Member Typedef Documentation
typedef m5::hash_map<std::string, Section *> IniFile::SectionTable [protected]
SectionTable type. Map of strings to Section object pointers.
Definition at line 142 of file inifile.hh.
Constructor & Destructor Documentation
IniFile::IniFile ()
Constructor.
Definition at line 43 of file inifile.cc.
IniFile::~IniFile ()
Destructor.
Definition at line 46 of file inifile.cc.
References ArmISA::i, and table.
Member Function Documentation
bool IniFile::add (const std::string & s)
Take string of the form "<section>:<parameter>=<value>" or "<section>:<parameter>+=<value>" and add to database.
Return values:
True if successful, false if parse error.
Referenced by main().
Section* IniFile::addSection (const std::string & sectionName) [protected]
Look up section with the given name, creating a new section if not found.
Return values:
Pointer to section object.
void IniFile::dump ()
Dump contents to cout. For debugging.
Definition at line 322 of file inifile.cc.
References table.
Referenced by main().
bool IniFile::find (const std::string & section, const std::string & entry, std::string & value) const
Find value corresponding to given section and entry names.
Value is returned by reference in 'value' param.
Return values:
True if found, false if not.
Section* IniFile::findSection (const std::string & sectionName) const [protected]
Look up section with the given name.
Return values:
Pointer to section object, or NULL if not found.
bool IniFile::load (const std::string & file)
Load the specified file.
Parameter settings found in the file will be merged with any already defined in this object.
Parameters:
file The path of the file to load.
Return values:
True if successful, false if errors were encountered.
bool IniFile::load (std::istream & f)
Load parameter settings from given istream.
This is a helper function for load(string) and loadCPP(), which open a file and then pass it here.
Return values:
True if successful, false if errors were encountered.
Referenced by main().
bool IniFile::printUnreferenced ()
Print unreferenced entries in object.
Iteratively calls printUnreferend() on all the constituent sections.
Definition at line 284 of file inifile.cc.
References IniFile::Section::findEntry(), IniFile::Section::isReferenced(), IniFile::Section::printUnreferenced(), and table.
bool IniFile::sectionExists (const std::string & section) const
Determine whether the named section exists in the .ini file.
Note that the 'Section' class is (intentionally) not public, so all clients can do is get a bool that says whether there are any values in that section or not.
Returns:
True if the section exists.
Member Data Documentation
SectionTable IniFile::table [protected]
Hash of section names to Section object pointers.
Definition at line 146 of file inifile.hh.
Referenced by dump(), printUnreferenced(), and ~IniFile().
The documentation for this class was generated from the following files:
base/inifile.hh
base/inifile.cc