gem5: OptCPU Class Reference
OptCPU Class Reference
A CPU object to simulate a fully-associative cache with optimal replacement.
#include <opt_cpu.hh>