gem5: BankedArray Class Reference
BankedArray Class Reference
#include <BankedArray.hh>
Classes
class AccessRecord
Public Member Functions
BankedArray (unsigned int banks, Cycles accessLatency, unsigned int startIndexBit)
bool tryAccess (Index idx)
Private Member Functions
unsigned int mapIndexToBank (Index idx)
Private Attributes
unsigned int banks
Cycles accessLatency
unsigned int bankBits
unsigned int startIndexBit
std::vector< AccessRecord > busyBanks
Detailed Description
Definition at line 40 of file BankedArray.hh.
Constructor & Destructor Documentation
BankedArray::BankedArray (unsigned int banks, Cycles accessLatency, unsigned int startIndexBit)
Definition at line 36 of file BankedArray.cc.
References bankBits, busyBanks, and floorLog2().
Member Function Documentation
unsigned int BankedArray::mapIndexToBank (Index idx) [private]
Definition at line 79 of file BankedArray.cc.
References banks.
Referenced by tryAccess().
bool BankedArray::tryAccess (Index idx)
Definition at line 51 of file BankedArray.cc.
References accessLatency, banks, busyBanks, ClockedObject::clockPeriod(), curTick(), g_system_ptr, and mapIndexToBank().
Referenced by CacheMemory::checkResourceAvailable().
Member Data Documentation
Cycles BankedArray::accessLatency [private]
Definition at line 44 of file BankedArray.hh.
Referenced by tryAccess().
unsigned int BankedArray::bankBits [private]
Definition at line 45 of file BankedArray.hh.
Referenced by BankedArray().
unsigned int BankedArray::banks [private]
Definition at line 43 of file BankedArray.hh.
Referenced by mapIndexToBank(), and tryAccess().
std::vector<AccessRecord> BankedArray::busyBanks [private]
Definition at line 59 of file BankedArray.hh.
Referenced by BankedArray(), and tryAccess().
unsigned int BankedArray::startIndexBit [private]
Definition at line 46 of file BankedArray.hh.
The documentation for this class was generated from the following files:
mem/ruby/system/BankedArray.hh
mem/ruby/system/BankedArray.cc