gem5: ObjectMatch Class Reference
ObjectMatch Class Reference
#include <match.hh>
Public Member Functions
ObjectMatch ()
ObjectMatch (const std::string &expression)
void setExpression (const std::string &expression)
void setExpression (const std::vector< std::string > &expression)
bool match (const std::string &name) const
Protected Member Functions
bool domatch (const std::string &name) const
Protected Attributes
std::vector< std::vector
< std::string > > tokens
Detailed Description
Definition at line 41 of file match.hh.
Constructor & Destructor Documentation
ObjectMatch::ObjectMatch ()
Definition at line 36 of file match.cc.
ObjectMatch::ObjectMatch (const std::string & expression)
Member Function Documentation
bool ObjectMatch::domatch (const std::string & name) const [protected]
Referenced by match().
bool ObjectMatch::match (const std::string & name) const [inline]
Definition at line 52 of file match.hh.
References domatch(), and tokens.
Referenced by Trace::dprintf().
void ObjectMatch::setExpression (const std::vector< std::string > & expression)
void ObjectMatch::setExpression (const std::string & expression)
Member Data Documentation
std::vector<std::vector<std::string> > ObjectMatch::tokens [protected]
Definition at line 44 of file match.hh.
Referenced by match().
The documentation for this class was generated from the following files:
base/match.hh
base/match.cc