gem5: AlphaISA::Decoder Class Reference
AlphaISA::Decoder Class Reference
#include <decoder.hh>
Public Member Functions
Decoder ()
void process ()
void reset ()
void moreBytes (const PCState &pc, Addr fetchPC, MachInst inst)
bool needMoreBytes ()
bool instReady ()
void takeOverFrom (Decoder *old)
StaticInstPtr decodeInst (ExtMachInst mach_inst)
StaticInstPtr decode (ExtMachInst mach_inst, Addr addr)
Decode a machine instruction.
StaticInstPtr decode (AlphaISA::PCState &nextPC)
Protected Attributes
ExtMachInst ext_inst
bool instDone
Static Protected Attributes
static GenericISA::BasicDecodeCache defaultCache
A cache of decoded instruction objects.
Detailed Description
Definition at line 42 of file decoder.hh.
Constructor & Destructor Documentation
AlphaISA::Decoder::Decoder () [inline]
Definition at line 50 of file decoder.hh.
Member Function Documentation
StaticInstPtr AlphaISA::Decoder::decode (ExtMachInst mach_inst, Addr addr) [inline]
Decode a machine instruction.
Parameters:
mach_inst The binary instruction to decode.
Return values:
A pointer to the corresponding StaticInst object.
Definition at line 99 of file decoder.hh.
References GenericISA::BasicDecodeCache::decode(), and defaultCache.
Referenced by decode().
StaticInstPtr AlphaISA::Decoder::decode (AlphaISA::PCState & nextPC) [inline]
Definition at line 105 of file decoder.hh.
References decode(), ext_inst, GenericISA::PCStateBase::instAddr(), and instDone.
StaticInstPtr AlphaISA::Decoder::decodeInst (ExtMachInst mach_inst)
bool AlphaISA::Decoder::instReady () [inline]
Definition at line 81 of file decoder.hh.
References instDone.
void AlphaISA::Decoder::moreBytes (const PCState & pc, Addr fetchPC, MachInst inst) [inline]
Definition at line 66 of file decoder.hh.
References ext_inst, FullSystem, instDone, and GenericISA::SimplePCState< MachInst >::pc().
bool AlphaISA::Decoder::needMoreBytes () [inline]
Definition at line 75 of file decoder.hh.
void AlphaISA::Decoder::process () [inline]
Definition at line 54 of file decoder.hh.
void AlphaISA::Decoder::reset () [inline]
Definition at line 58 of file decoder.hh.
References instDone.
void AlphaISA::Decoder::takeOverFrom (Decoder * old) [inline]
Definition at line 86 of file decoder.hh.
Member Data Documentation
GenericISA::BasicDecodeCache AlphaISA::Decoder::defaultCache [static, protected]
A cache of decoded instruction objects.
Definition at line 90 of file decoder.hh.
Referenced by decode().
ExtMachInst AlphaISA::Decoder::ext_inst [protected]
Definition at line 46 of file decoder.hh.
Referenced by decode(), and moreBytes().
bool AlphaISA::Decoder::instDone [protected]
Definition at line 47 of file decoder.hh.
Referenced by decode(), instReady(), moreBytes(), and reset().
The documentation for this class was generated from the following files:
arch/alpha/decoder.hh
arch/alpha/decoder.cc