gem5: X86ISA::X86FaultBase Class Reference
X86ISA::X86FaultBase Class Reference
#include <faults.hh>