gem5: OrionRouter Class Reference
OrionRouter Class Reference
#include <OrionRouter.hh>
Public Member Functions
OrionRouter (const OrionConfig *orion_cfg_ptr_)
OrionRouter (uint32_t num_in_port_, uint32_t num_out_port_, uint32_t num_vclass_, std::vector< uint32_t > vclass_type_, uint32_t num_vc_per_vclass_, uint32_t in_buf_per_data_vc_, uint32_t in_buf_per_ctrl_vc_, uint32_t flit_width_, OrionConfig *orion_cfg_ptr_)
~OrionRouter ()
double calc_dynamic_energy_buf (uint32_t vclass_id_, bool is_read_, bool is_max_=false) const
double calc_dynamic_energy_xbar (bool is_max_=false) const
double calc_dynamic_energy_local_vc_arb (uint32_t vclass_id_, double num_req_, bool is_max_=false) const
double calc_dynamic_energy_global_vc_arb (uint32_t vclass_id_, double num_req_, bool is_max_=false) const
double calc_dynamic_energy_local_sw_arb (double num_req_, bool is_max_=false) const
double calc_dynamic_energy_global_sw_arb (double num_req_, bool is_max_=false) const
double calc_dynamic_energy_clock () const
double get_static_power_buf () const
double get_static_power_xbar () const
double get_static_power_va () const
double get_static_power_sa () const
double get_static_power_clock () const
void print () const
void init ()
Private Attributes
const OrionConfig * m_orion_cfg_ptr
uint32_t m_num_in_port
uint32_t m_num_out_port
uint32_t m_flit_width
uint32_t m_num_vclass
uint32_t num_vc_per_vclass
uint32_t m_total_num_vc
uint32_t * m_num_vc_per_vclass_ary
uint32_t * m_in_buf_num_set_ary
bool m_is_in_shared_buf
bool m_is_out_shared_buf
bool m_is_in_shared_switch
bool m_is_out_shared_switch
Buffer ** m_in_buf_ary_ptr
Crossbar * m_xbar_ptr
VCAllocator ** m_va_ary_ptr
SWAllocator * m_sa_ptr
Clock * m_clk_ptr
Detailed Description
Definition at line 50 of file OrionRouter.hh.
Constructor & Destructor Documentation
OrionRouter::OrionRouter (const OrionConfig * orion_cfg_ptr_)
OrionRouter::OrionRouter (uint32_t num_in_port_, uint32_t num_out_port_, uint32_t num_vclass_, std::vector< uint32_t > vclass_type_, uint32_t num_vc_per_vclass_, uint32_t in_buf_per_data_vc_, uint32_t in_buf_per_ctrl_vc_, uint32_t flit_width_, OrionConfig * orion_cfg_ptr_)
Definition at line 48 of file OrionRouter.cc.
References OrionConfig::get(), ArmISA::i, init(), m_flit_width, m_in_buf_num_set_ary, m_num_in_port, m_num_out_port, m_num_vc_per_vclass_ary, m_num_vclass, m_orion_cfg_ptr, OrionConfig::set_flit_width(), OrionConfig::set_num_in_port(), OrionConfig::set_num_out_port(), and OrionConfig::set_num_vclass().
OrionRouter::~OrionRouter ()
Definition at line 97 of file OrionRouter.cc.
References ArmISA::i, m_clk_ptr, m_in_buf_ary_ptr, m_in_buf_num_set_ary, m_num_vc_per_vclass_ary, m_num_vclass, m_sa_ptr, m_va_ary_ptr, and m_xbar_ptr.
Member Function Documentation
double OrionRouter::calc_dynamic_energy_buf (uint32_t vclass_id_, bool is_read_, bool is_max_ = false) const
Definition at line 125 of file OrionRouter.cc.
References Buffer::get_dynamic_energy(), m_in_buf_ary_ptr, and m_num_vclass.
Referenced by Router_d::calculate_power().
double OrionRouter::calc_dynamic_energy_clock () const
Definition at line 235 of file OrionRouter.cc.
References Clock::get_dynamic_energy(), and m_clk_ptr.
Referenced by Router_d::calculate_power().
double OrionRouter::calc_dynamic_energy_global_sw_arb (double num_req_, bool is_max_ = false) const
Definition at line 223 of file OrionRouter.cc.
References SWAllocator::get_dynamic_energy_global_sw_arb(), and m_sa_ptr.
Referenced by Router_d::calculate_power().
double OrionRouter::calc_dynamic_energy_global_vc_arb (uint32_t vclass_id_, double num_req_, bool is_max_ = false) const
Definition at line 178 of file OrionRouter.cc.
References VCAllocator::get_dynamic_energy_global_vc_arb(), m_num_vclass, and m_va_ary_ptr.
Referenced by Router_d::calculate_power().
double OrionRouter::calc_dynamic_energy_local_sw_arb (double num_req_, bool is_max_ = false) const
Definition at line 211 of file OrionRouter.cc.
References SWAllocator::get_dynamic_energy_local_sw_arb(), and m_sa_ptr.
Referenced by Router_d::calculate_power().
double OrionRouter::calc_dynamic_energy_local_vc_arb (uint32_t vclass_id_, double num_req_, bool is_max_ = false) const
Definition at line 157 of file OrionRouter.cc.
References VCAllocator::get_dynamic_energy_local_vc_arb(), m_num_vclass, and m_va_ary_ptr.
Referenced by Router_d::calculate_power().
double OrionRouter::calc_dynamic_energy_xbar (bool is_max_ = false) const
Definition at line 145 of file OrionRouter.cc.
References Crossbar::get_dynamic_energy(), and m_xbar_ptr.
Referenced by Router_d::calculate_power().
double OrionRouter::get_static_power_buf () const
Definition at line 247 of file OrionRouter.cc.
References Buffer::get_static_power(), ArmISA::i, m_in_buf_ary_ptr, m_is_in_shared_buf, m_num_in_port, m_num_vc_per_vclass_ary, and m_num_vclass.
Referenced by Router_d::calculate_power().
double OrionRouter::get_static_power_clock () const
Definition at line 328 of file OrionRouter.cc.
References Clock::get_static_power(), and m_clk_ptr.
double OrionRouter::get_static_power_sa () const
Definition at line 316 of file OrionRouter.cc.
References SWAllocator::get_static_power(), and m_sa_ptr.
Referenced by Router_d::calculate_power().
double OrionRouter::get_static_power_va () const
Definition at line 286 of file OrionRouter.cc.
References VCAllocator::get_static_power(), ArmISA::i, m_num_vclass, and m_va_ary_ptr.
Referenced by Router_d::calculate_power().
double OrionRouter::get_static_power_xbar () const
Definition at line 274 of file OrionRouter.cc.
References Crossbar::get_static_power(), and m_xbar_ptr.
Referenced by Router_d::calculate_power().
void OrionRouter::init ()
Definition at line 340 of file OrionRouter.cc.
References Crossbar::create_crossbar(), SWAllocator::create_swallocator(), VCAllocator::create_vcallocator(), OrionConfig::get(), ArmISA::i, m_clk_ptr, m_flit_width, m_in_buf_ary_ptr, m_in_buf_num_set_ary, m_is_in_shared_buf, m_is_in_shared_switch, m_is_out_shared_buf, m_is_out_shared_switch, m_num_in_port, m_num_out_port, m_num_vc_per_vclass_ary, m_num_vclass, m_orion_cfg_ptr, m_sa_ptr, m_total_num_vc, m_va_ary_ptr, and m_xbar_ptr.
Referenced by OrionRouter().
void OrionRouter::print (void) const
Definition at line 457 of file OrionRouter.cc.
References ArmISA::i, m_in_buf_ary_ptr, m_num_vclass, m_sa_ptr, m_va_ary_ptr, m_xbar_ptr, SWAllocator::print_all(), VCAllocator::print_all(), Crossbar::print_all(), and Buffer::print_all().
Member Data Documentation
Clock* OrionRouter::m_clk_ptr [private]
Definition at line 115 of file OrionRouter.hh.
Referenced by calc_dynamic_energy_clock(), get_static_power_clock(), init(), and ~OrionRouter().
uint32_t OrionRouter::m_flit_width [private]
Definition at line 99 of file OrionRouter.hh.
Referenced by init(), and OrionRouter().
Buffer** OrionRouter::m_in_buf_ary_ptr [private]
Definition at line 110 of file OrionRouter.hh.
Referenced by calc_dynamic_energy_buf(), get_static_power_buf(), init(), print(), and ~OrionRouter().
uint32_t* OrionRouter::m_in_buf_num_set_ary [private]
Definition at line 104 of file OrionRouter.hh.
Referenced by init(), OrionRouter(), and ~OrionRouter().
bool OrionRouter::m_is_in_shared_buf [private]
Definition at line 105 of file OrionRouter.hh.
Referenced by get_static_power_buf(), and init().
bool OrionRouter::m_is_in_shared_switch [private]
Definition at line 107 of file OrionRouter.hh.
Referenced by init().
bool OrionRouter::m_is_out_shared_buf [private]
Definition at line 106 of file OrionRouter.hh.
Referenced by init().
bool OrionRouter::m_is_out_shared_switch [private]
Definition at line 108 of file OrionRouter.hh.
Referenced by init().
uint32_t OrionRouter::m_num_in_port [private]
Definition at line 97 of file OrionRouter.hh.
Referenced by get_static_power_buf(), init(), and OrionRouter().
uint32_t OrionRouter::m_num_out_port [private]
Definition at line 98 of file OrionRouter.hh.
Referenced by init(), and OrionRouter().
uint32_t* OrionRouter::m_num_vc_per_vclass_ary [private]
Definition at line 103 of file OrionRouter.hh.
Referenced by get_static_power_buf(), init(), OrionRouter(), and ~OrionRouter().
uint32_t OrionRouter::m_num_vclass [private]
Definition at line 100 of file OrionRouter.hh.
Referenced by calc_dynamic_energy_buf(), calc_dynamic_energy_global_vc_arb(), calc_dynamic_energy_local_vc_arb(), get_static_power_buf(), get_static_power_va(), init(), OrionRouter(), print(), and ~OrionRouter().
const OrionConfig* OrionRouter::m_orion_cfg_ptr [private]
Definition at line 95 of file OrionRouter.hh.
Referenced by init(), and OrionRouter().
SWAllocator* OrionRouter::m_sa_ptr [private]
Definition at line 114 of file OrionRouter.hh.
Referenced by calc_dynamic_energy_global_sw_arb(), calc_dynamic_energy_local_sw_arb(), get_static_power_sa(), init(), print(), and ~OrionRouter().
uint32_t OrionRouter::m_total_num_vc [private]
Definition at line 102 of file OrionRouter.hh.
Referenced by init().
VCAllocator** OrionRouter::m_va_ary_ptr [private]
Definition at line 112 of file OrionRouter.hh.
Referenced by calc_dynamic_energy_global_vc_arb(), calc_dynamic_energy_local_vc_arb(), get_static_power_va(), init(), print(), and ~OrionRouter().
Crossbar* OrionRouter::m_xbar_ptr [private]
Definition at line 111 of file OrionRouter.hh.
Referenced by calc_dynamic_energy_xbar(), get_static_power_xbar(), init(), print(), and ~OrionRouter().
uint32_t OrionRouter::num_vc_per_vclass [private]
Definition at line 101 of file OrionRouter.hh.
The documentation for this class was generated from the following files:
mem/ruby/network/orion/OrionRouter.hh
mem/ruby/network/orion/OrionRouter.cc