gem5: OutdrvUnit Class Reference
OutdrvUnit Class Reference
#include <OutdrvUnit.hh>
Public Types
enum OutdrvModel { NO_MODEL = 0, CACHE_OUTDRV, REG_OUTDRV }
Public Member Functions
OutdrvUnit (const string &outdrv_model_str_, const SRAM *sram_ptr_, const TechParameter *tech_param_ptr_)
~OutdrvUnit ()
double get_e_select () const
double get_e_chg_data () const
double get_e_out_0 () const
double get_e_out_1 () const
Private Member Functions
void init ()
double calc_select_cap ()
double calc_chgdata_cap ()
double calc_outdata_cap (bool value_)
double calc_i_static ()
Private Attributes
OutdrvModel m_outdrv_model
const SRAM * m_sram_ptr
const TechParameter * m_tech_param_ptr
double m_e_select
double m_e_out_1
double m_e_out_0
double m_e_chg_data
double m_i_static
Detailed Description
Definition at line 44 of file OutdrvUnit.hh.
Member Enumeration Documentation
enum OutdrvUnit::OutdrvModel
Enumerator:
NO_MODEL
CACHE_OUTDRV
REG_OUTDRV
Definition at line 47 of file OutdrvUnit.hh.
Constructor & Destructor Documentation
OutdrvUnit::OutdrvUnit (const string & outdrv_model_str_, const SRAM * sram_ptr_, const TechParameter * tech_param_ptr_)
Definition at line 41 of file OutdrvUnit.cc.
References init(), m_e_chg_data, m_e_out_0, m_e_out_1, m_e_select, m_outdrv_model, m_sram_ptr, m_tech_param_ptr, and NO_MODEL.
OutdrvUnit::~OutdrvUnit ()
Definition at line 75 of file OutdrvUnit.cc.
Member Function Documentation
double OutdrvUnit::calc_chgdata_cap () [private]
Definition at line 122 of file OutdrvUnit.cc.
References TechParameter::calc_gatecap(), TechParameter::get_Woutdrvnandn(), TechParameter::get_Woutdrvnandp(), TechParameter::get_Woutdrvnorn(), TechParameter::get_Woutdrvnorp(), and m_tech_param_ptr.
Referenced by init().
double OutdrvUnit::calc_i_static () [private]
Definition at line 171 of file OutdrvUnit.cc.
Referenced by init().
double OutdrvUnit::calc_outdata_cap (bool value_) [private]
Definition at line 134 of file OutdrvUnit.cc.
References TechParameter::calc_draincap(), TechParameter::calc_gatecap(), TechParameter::get_Woutdrivern(), TechParameter::get_Woutdriverp(), TechParameter::get_Woutdrvnandn(), TechParameter::get_Woutdrvnandp(), TechParameter::get_Woutdrvnorn(), TechParameter::get_Woutdrvnorp(), m_tech_param_ptr, TechParameter::NCH, and TechParameter::PCH.
Referenced by init().
double OutdrvUnit::calc_select_cap () [private]
Definition at line 102 of file OutdrvUnit.cc.
References TechParameter::calc_draincap(), TechParameter::calc_gatecap(), SRAM::get_line_width(), TechParameter::get_Woutdrvnandn(), TechParameter::get_Woutdrvnandp(), TechParameter::get_Woutdrvnorn(), TechParameter::get_Woutdrvnorp(), TechParameter::get_Woutdrvseln(), TechParameter::get_Woutdrvselp(), m_sram_ptr, m_tech_param_ptr, TechParameter::NCH, and TechParameter::PCH.
Referenced by init().
double OutdrvUnit::get_e_chg_data () const [inline]
Definition at line 64 of file OutdrvUnit.hh.
References m_e_chg_data.
Referenced by SRAM::calc_e_read().
double OutdrvUnit::get_e_out_0 () const [inline]
Definition at line 65 of file OutdrvUnit.hh.
References m_e_out_0.
Referenced by SRAM::calc_e_read().
double OutdrvUnit::get_e_out_1 () const [inline]
Definition at line 66 of file OutdrvUnit.hh.
References m_e_out_1.
Referenced by SRAM::calc_e_read().
double OutdrvUnit::get_e_select () const [inline]
Definition at line 63 of file OutdrvUnit.hh.
References m_e_select.
Referenced by SRAM::calc_e_read().
void OutdrvUnit::init () [private]
Definition at line 78 of file OutdrvUnit.cc.
References CACHE_OUTDRV, calc_chgdata_cap(), calc_i_static(), calc_outdata_cap(), calc_select_cap(), fatal, TechParameter::get_EnergyFactor(), m_e_chg_data, m_e_out_0, m_e_out_1, m_e_select, m_i_static, m_outdrv_model, m_tech_param_ptr, and REG_OUTDRV.
Referenced by OutdrvUnit().
Member Data Documentation
double OutdrvUnit::m_e_chg_data [private]
Definition at line 83 of file OutdrvUnit.hh.
Referenced by get_e_chg_data(), init(), and OutdrvUnit().
double OutdrvUnit::m_e_out_0 [private]
Definition at line 82 of file OutdrvUnit.hh.
Referenced by get_e_out_0(), init(), and OutdrvUnit().
double OutdrvUnit::m_e_out_1 [private]
Definition at line 81 of file OutdrvUnit.hh.
Referenced by get_e_out_1(), init(), and OutdrvUnit().
double OutdrvUnit::m_e_select [private]
Definition at line 80 of file OutdrvUnit.hh.
Referenced by get_e_select(), init(), and OutdrvUnit().
double OutdrvUnit::m_i_static [private]
Definition at line 85 of file OutdrvUnit.hh.
Referenced by init().
OutdrvModel OutdrvUnit::m_outdrv_model [private]
Definition at line 76 of file OutdrvUnit.hh.
Referenced by init(), and OutdrvUnit().
const SRAM* OutdrvUnit::m_sram_ptr [private]
Definition at line 77 of file OutdrvUnit.hh.
Referenced by calc_select_cap(), and OutdrvUnit().
const TechParameter* OutdrvUnit::m_tech_param_ptr [private]
Definition at line 78 of file OutdrvUnit.hh.
Referenced by calc_chgdata_cap(), calc_outdata_cap(), calc_select_cap(), init(), and OutdrvUnit().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/Buffer/OutdrvUnit.hh
mem/ruby/network/orion/Buffer/OutdrvUnit.cc