gem5: TrafficGen::StateGraph::BaseGen Class Reference
TrafficGen::StateGraph::BaseGen Class Reference
Base class for all generator states.