gem5: PciConfigAll Class Reference
PciConfigAll Class Reference
PCI Config Space All of PCI config space needs to return -1 on Tsunami, except the devices that exist.
#include <pciconfigall.hh>