gem5: Address Class Reference
Address Class Reference
#include <Address.hh>
Public Member Functions
Address ()
Address (physical_address_t address)
Address (const Address &obj)
Address & operator= (const Address &obj)
void setAddress (physical_address_t address)
physical_address_t getAddress () const
physical_address_t bitSelect (int small, int big) const
physical_address_t bitRemove (int small, int big) const
physical_address_t maskLowOrderBits (int number) const
physical_address_t maskHighOrderBits (int number) const
physical_address_t shiftLowOrderBits (int number) const
physical_address_t getLineAddress () const
physical_address_t getOffset () const
void makeLineAddress ()
void makePageAddress ()
void makeNextStrideAddress (int stride)
int getBankSetNum () const
int getBankSetDist () const
Index memoryModuleIndex () const
void print (std::ostream &out) const
void output (std::ostream &out) const
void input (std::istream &in)
void setOffset (int offset)
Private Attributes
physical_address_t m_address
Detailed Description
Definition at line 45 of file Address.hh.
Constructor & Destructor Documentation
Address::Address () [inline]
Definition at line 48 of file Address.hh.
Address::Address (physical_address_t address) [inline, explicit]
Definition at line 53 of file Address.hh.
Address::Address (const Address & obj)
Definition at line 123 of file Address.cc.
References m_address.
Member Function Documentation
physical_address_t Address::bitRemove (int small, int big) const [inline]
Definition at line 149 of file Address.hh.
References ADDRESS_WIDTH, m_address, and ArmISA::mask.
Referenced by DirectoryMemory::mapAddressToLocalIdx().
physical_address_t Address::bitSelect (int small, int big) const [inline]
Definition at line 132 of file Address.hh.
References ADDRESS_WIDTH, m_address, and ArmISA::mask.
Referenced by SparseMemory::add(), CheckTable::addCheck(), CacheMemory::addressToCacheSet(), SparseMemory::exist(), MultiGrainBloomFilter::get_block_index(), NonCountingBloomFilter::get_index(), LSB_CountingBloomFilter::get_index(), BulkBloomFilter::get_index(), BlockBloomFilter::get_index(), MultiGrainBloomFilter::get_page_index(), getLineAddress(), getOffset(), BulkBloomFilter::isSet(), SparseMemory::lookup(), DirectoryMemory::mapAddressToDirectoryVersion(), mapAddressToRange(), memoryModuleIndex(), BulkBloomFilter::permute(), SparseMemory::recursivelyRemoveLevels(), and BulkBloomFilter::set().
physical_address_t Address::getAddress () const [inline]
Definition at line 61 of file Address.hh.
References m_address.
Referenced by Prefetcher::accessNonunitFilter(), CheckTable::addCheck(), Check::debugPrint(), RubyRequest::functionalWrite(), MemoryVector::getBlockPtr(), Check::initiateAction(), Check::initiateCheck(), Check::initiateFlush(), Check::initiatePrefetch(), DirectoryMemory::mapAddressToLocalIdx(), operator!=(), hash< Address >::operator()(), operator<(), operator==(), MemoryVector::read(), SparseMemory::recordBlocks(), RubyPort::M5Port::recvFunctional(), RubyPort::ruby_eviction_callback(), testAndRead(), testAndWrite(), and MemoryVector::write().
int Address::getBankSetDist () const
int Address::getBankSetNum () const
physical_address_t Address::getLineAddress () const
Definition at line 35 of file Address.cc.
References ADDRESS_WIDTH, bitSelect(), and RubySystem::getBlockSizeBits().
Referenced by MultiBitSelBloomFilter::get_index(), H3BloomFilter::get_index(), and Check::performCallback().
physical_address_t Address::getOffset () const
Definition at line 41 of file Address.cc.
References bitSelect(), and RubySystem::getBlockSizeBits().
Referenced by addressOffset(), SubBlock::internalMergeFrom(), SubBlock::internalMergeTo(), and MessageBuffer::stallMessage().
void Address::input (std::istream & in)
Definition at line 114 of file Address.cc.
References m_address.
void Address::makeLineAddress ()
Definition at line 47 of file Address.cc.
References RubySystem::getBlockSizeBits(), m_address, and maskLowOrderBits().
Referenced by AddressProfiler::addTraceSample(), PerfectCacheMemory< ENTRY >::changePermission(), line_address(), makeLineAddress(), RubyRequest::RubyRequest(), setOffset(), testAndRead(), and testAndWrite().
void Address::makeNextStrideAddress (int stride)
Definition at line 54 of file Address.cc.
References RubySystem::getBlockSizeBits(), RubySystem::getBlockSizeBytes(), m_address, and maskLowOrderBits().
Referenced by next_stride_address().
void Address::makePageAddress ()
Definition at line 140 of file Address.cc.
References AlphaISA::LogVMPageSize, m_address, and maskLowOrderBits().
Referenced by page_address().
physical_address_t Address::maskHighOrderBits (int number) const [inline]
Definition at line 188 of file Address.hh.
References ADDRESS_WIDTH, m_address, and ArmISA::mask.
physical_address_t Address::maskLowOrderBits (int number) const [inline]
Definition at line 175 of file Address.hh.
References ADDRESS_WIDTH, m_address, and ArmISA::mask.
Referenced by AddressProfiler::addTraceSample(), makeLineAddress(), makeNextStrideAddress(), makePageAddress(), and print().
Index Address::memoryModuleIndex () const
Definition at line 61 of file Address.cc.
References ADDRESS_WIDTH, bitSelect(), RubySystem::getBlockSizeBits(), RubySystem::getMemorySizeBits(), and MipsISA::index.
Referenced by DirectoryMemory::invalidateBlock().
Address & Address::operator= (const Address & obj)
Definition at line 129 of file Address.cc.
References m_address.
void Address::output (std::ostream & out) const
Definition at line 104 of file Address.cc.
References m_address.
void Address::print (std::ostream & out) const
Definition at line 95 of file Address.cc.
References RubySystem::getBlockSizeBits(), m_address, and maskLowOrderBits().
Referenced by operator<<().
void Address::setAddress (physical_address_t address) [inline]
Definition at line 60 of file Address.hh.
References m_address.
Referenced by AbstractCacheEntry::AbstractCacheEntry(), SparseMemory::add(), CheckTable::CheckTable(), SparseMemory::exist(), SparseMemory::lookup(), and SparseMemory::recursivelyRemoveLevels().
void Address::setOffset (int offset) [inline]
Definition at line 85 of file Address.hh.
References m_address, and makeLineAddress().
Referenced by setOffset().
physical_address_t Address::shiftLowOrderBits (int number) const [inline]
Definition at line 201 of file Address.hh.
References m_address.
Member Data Documentation
physical_address_t Address::m_address [private]
Definition at line 93 of file Address.hh.
Referenced by Address(), bitRemove(), bitSelect(), getAddress(), input(), makeLineAddress(), makeNextStrideAddress(), makePageAddress(), maskHighOrderBits(), maskLowOrderBits(), operator=(), output(), print(), setAddress(), setOffset(), and shiftLowOrderBits().
The documentation for this class was generated from the following files:
mem/ruby/common/Address.hh
mem/ruby/common/Address.cc