gem5: X86ISA::SMBios::SMBiosTable Class Reference
X86ISA::SMBios::SMBiosTable Class Reference
#include <smbios.hh>