gem5: AlphaBackdoor Class Reference
AlphaBackdoor Class Reference
Memory mapped interface to the system console.
#include <backdoor.hh>