gem5: DecoderUnit Class Reference
DecoderUnit Class Reference
#include <DecoderUnit.hh>
Public Types
enum DecModel { NO_MODEL = 0, GENERIC_DEC }
Public Member Functions
DecoderUnit (const string &dec_model_str_, uint32_t dec_width_, const TechParameter *tech_param_ptr_)
~DecoderUnit ()
uint32_t get_dec_width () const
uint32_t get_num_in_2nd () const
double get_e_chg_addr () const
double get_e_chg_output () const
double get_e_chg_l1 () const
Private Member Functions
void init ()
double calc_chgl1_cap ()
double calc_select_cap ()
double calc_chgaddr_cap ()
Private Attributes
DecModel m_dec_model
uint32_t m_dec_width
const TechParameter * m_tech_param_ptr
uint32_t m_num_in_1st
uint32_t m_num_in_2nd
uint32_t m_num_out_0th
uint32_t m_num_out_1st
double m_e_chg_l1
double m_e_chg_output
double m_e_chg_addr
Detailed Description
Definition at line 42 of file DecoderUnit.hh.
Member Enumeration Documentation
enum DecoderUnit::DecModel
Enumerator:
NO_MODEL
GENERIC_DEC
Definition at line 45 of file DecoderUnit.hh.
Constructor & Destructor Documentation
DecoderUnit::DecoderUnit (const string & dec_model_str_, uint32_t dec_width_, const TechParameter * tech_param_ptr_)
Definition at line 43 of file DecoderUnit.cc.
References init(), m_dec_model, m_dec_width, m_tech_param_ptr, and NO_MODEL.
DecoderUnit::~DecoderUnit ()
Definition at line 67 of file DecoderUnit.cc.
Member Function Documentation
double DecoderUnit::calc_chgaddr_cap () [private]
Definition at line 148 of file DecoderUnit.cc.
References TechParameter::calc_draincap(), TechParameter::calc_gatecap(), TechParameter::get_Wdec3to8n(), TechParameter::get_Wdec3to8p(), TechParameter::get_Wdecdriven(), TechParameter::get_Wdecdrivep(), TechParameter::get_Wdecinvn(), TechParameter::get_Wdecinvp(), m_num_out_0th, m_tech_param_ptr, TechParameter::NCH, and TechParameter::PCH.
Referenced by init().
double DecoderUnit::calc_chgl1_cap () [private]
Definition at line 112 of file DecoderUnit.cc.
References TechParameter::calc_draincap(), TechParameter::calc_gatecap(), TechParameter::get_Wdec3to8n(), TechParameter::get_Wdec3to8p(), TechParameter::get_WdecNORn(), TechParameter::get_WdecNORp(), m_num_in_1st, m_num_in_2nd, m_num_out_0th, m_tech_param_ptr, TechParameter::NCH, and TechParameter::PCH.
Referenced by init().
double DecoderUnit::calc_select_cap () [private]
Definition at line 130 of file DecoderUnit.cc.
References TechParameter::calc_draincap(), TechParameter::calc_gatecap(), TechParameter::get_Wdecinvn(), TechParameter::get_Wdecinvp(), TechParameter::get_WdecNORn(), TechParameter::get_WdecNORp(), m_num_in_2nd, m_tech_param_ptr, TechParameter::NCH, and TechParameter::PCH.
Referenced by init().
uint32_t DecoderUnit::get_dec_width () const [inline]
Definition at line 60 of file DecoderUnit.hh.
References m_dec_width.
Referenced by SRAM::calc_e_read(), and SRAM::calc_e_write().
double DecoderUnit::get_e_chg_addr () const [inline]
Definition at line 62 of file DecoderUnit.hh.
References m_e_chg_addr.
Referenced by SRAM::calc_e_read(), and SRAM::calc_e_write().
double DecoderUnit::get_e_chg_l1 () const [inline]
Definition at line 64 of file DecoderUnit.hh.
References m_e_chg_l1.
Referenced by SRAM::calc_e_read(), and SRAM::calc_e_write().
double DecoderUnit::get_e_chg_output () const [inline]
Definition at line 63 of file DecoderUnit.hh.
References m_e_chg_output.
Referenced by SRAM::calc_e_read(), and SRAM::calc_e_write().
uint32_t DecoderUnit::get_num_in_2nd () const [inline]
Definition at line 61 of file DecoderUnit.hh.
References m_num_in_2nd.
Referenced by SRAM::calc_e_read(), and SRAM::calc_e_write().
void DecoderUnit::init () [private]
Definition at line 71 of file DecoderUnit.cc.
References calc_chgaddr_cap(), calc_chgl1_cap(), calc_select_cap(), TechParameter::get_vdd(), m_dec_width, m_e_chg_addr, m_e_chg_l1, m_e_chg_output, m_num_in_1st, m_num_in_2nd, m_num_out_0th, m_num_out_1st, and m_tech_param_ptr.
Referenced by DecoderUnit().
Member Data Documentation
DecModel DecoderUnit::m_dec_model [private]
Definition at line 73 of file DecoderUnit.hh.
Referenced by DecoderUnit().
uint32_t DecoderUnit::m_dec_width [private]
Definition at line 74 of file DecoderUnit.hh.
Referenced by DecoderUnit(), get_dec_width(), and init().
double DecoderUnit::m_e_chg_addr [private]
Definition at line 84 of file DecoderUnit.hh.
Referenced by get_e_chg_addr(), and init().
double DecoderUnit::m_e_chg_l1 [private]
Definition at line 82 of file DecoderUnit.hh.
Referenced by get_e_chg_l1(), and init().
double DecoderUnit::m_e_chg_output [private]
Definition at line 83 of file DecoderUnit.hh.
Referenced by get_e_chg_output(), and init().
uint32_t DecoderUnit::m_num_in_1st [private]
Definition at line 77 of file DecoderUnit.hh.
Referenced by calc_chgl1_cap(), and init().
uint32_t DecoderUnit::m_num_in_2nd [private]
Definition at line 78 of file DecoderUnit.hh.
Referenced by calc_chgl1_cap(), calc_select_cap(), get_num_in_2nd(), and init().
uint32_t DecoderUnit::m_num_out_0th [private]
Definition at line 79 of file DecoderUnit.hh.
Referenced by calc_chgaddr_cap(), calc_chgl1_cap(), and init().
uint32_t DecoderUnit::m_num_out_1st [private]
Definition at line 80 of file DecoderUnit.hh.
Referenced by init().
const TechParameter* DecoderUnit::m_tech_param_ptr [private]
Definition at line 75 of file DecoderUnit.hh.
Referenced by calc_chgaddr_cap(), calc_chgl1_cap(), calc_select_cap(), DecoderUnit(), and init().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/Buffer/DecoderUnit.hh
mem/ruby/network/orion/Buffer/DecoderUnit.cc