gem5: X86System Class Reference
X86System Class Reference
#include <system.hh>