gem5: Profiler Class Reference
Profiler Class Reference
#include <Profiler.hh>