gem5: SparcISA::ISA Class Reference
SparcISA::ISA Class Reference
#include <isa.hh>