gem5: X86ISA::Speaker Class Reference
X86ISA::Speaker Class Reference
#include <speaker.hh>