gem5: InOrderThreadState Class Reference
InOrderThreadState Class Reference
Class that has various thread state, such as the status, the current instruction being processed, whether or not the thread has a trap pending or is being externally updated, the ThreadContext pointer, etc.
#include <thread_state.hh>