gem5: Throttle Class Reference
Throttle Class Reference
#include <Throttle.hh>