gem5: ProtoInputStream Class Reference
ProtoInputStream Class Reference
A ProtoInputStream wraps a coded stream, potentially with decompression, based on looking at the file name.
#include <protoio.hh>