gem5: RawDiskImage Class Reference
RawDiskImage Class Reference
Specialization for accessing a raw disk image.
#include <disk_image.hh>