gem5: flitBuffer Class Reference
flitBuffer Class Reference
#include <flitBuffer.hh>
Public Member Functions
flitBuffer ()
flitBuffer (int maximum_size)
bool isReady (Cycles curTime)
bool isReadyForNext (Cycles curTime)
bool isFull ()
bool isEmpty ()
void setMaxSize (int maximum)
flit * getTopFlit ()
flit * peekTopFlit ()
void insert (flit *flt)
void print (std::ostream &out) const
bool functionalRead (Packet *)
uint32_t functionalWrite (Packet *)
Private Attributes
std::vector< flit * > m_buffer
int max_size
Detailed Description
Definition at line 40 of file flitBuffer.hh.
Constructor & Destructor Documentation
flitBuffer::flitBuffer ()
Definition at line 37 of file flitBuffer.cc.
References max_size.
flitBuffer::flitBuffer (int maximum_size)
Definition at line 42 of file flitBuffer.cc.
References max_size.
Member Function Documentation
bool flitBuffer::functionalRead (Packet * pkt)
Definition at line 117 of file flitBuffer.cc.
References ArmISA::i, and m_buffer.
Referenced by NetworkLink::functionalRead(), and NetworkInterface::functionalRead().
uint32_t flitBuffer::functionalWrite (Packet * pkt)
Definition at line 128 of file flitBuffer.cc.
References ArmISA::i, and m_buffer.
Referenced by NetworkLink::functionalWrite(), and NetworkInterface::functionalWrite().
flit * flitBuffer::getTopFlit ()
Definition at line 88 of file flitBuffer.cc.
References ArmISA::f, and m_buffer.
Referenced by NetworkLink::consumeLink(), and NetworkLink::wakeup().
void flitBuffer::insert (flit * flt)
Definition at line 103 of file flitBuffer.cc.
References m_buffer.
Referenced by NetworkInterface::scheduleOutputLink(), and NetworkLink::wakeup().
bool flitBuffer::isEmpty ()
Definition at line 48 of file flitBuffer.cc.
References m_buffer.
bool flitBuffer::isFull ()
Definition at line 76 of file flitBuffer.cc.
References m_buffer, and max_size.
bool flitBuffer::isReady (Cycles curTime)
Definition at line 54 of file flitBuffer.cc.
References flit::get_time(), and m_buffer.
Referenced by NetworkLink::isReady(), and NetworkLink::wakeup().
bool flitBuffer::isReadyForNext (Cycles curTime)
Definition at line 65 of file flitBuffer.cc.
References flit::get_time(), and m_buffer.
flit * flitBuffer::peekTopFlit ()
Definition at line 97 of file flitBuffer.cc.
References m_buffer.
Referenced by NetworkLink::peekLink().
void flitBuffer::print (std::ostream & out) const
Definition at line 110 of file flitBuffer.cc.
References m_buffer.
Referenced by operator<<().
void flitBuffer::setMaxSize (int maximum)
Definition at line 82 of file flitBuffer.cc.
References max_size.
Member Data Documentation
std::vector<flit *> flitBuffer::m_buffer [private]
Definition at line 60 of file flitBuffer.hh.
Referenced by functionalRead(), functionalWrite(), getTopFlit(), insert(), isEmpty(), isFull(), isReady(), isReadyForNext(), peekTopFlit(), and print().
int flitBuffer::max_size [private]
Definition at line 61 of file flitBuffer.hh.
Referenced by flitBuffer(), isFull(), and setMaxSize().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet/flexible-pipeline/flitBuffer.hh
mem/ruby/network/garnet/flexible-pipeline/flitBuffer.cc