gem5: BackEnd< Impl >::InstQueue Class Reference
BackEnd< Impl >::InstQueue Class Reference
#include <back_end.hh>
Classes
struct pqCompare
Public Member Functions
InstQueue (Params *params)
std::string name () const
void regStats ()
void setIssueExecQueue (TimeBuffer< IssueToExec > *i2e_queue)
void setBE (BackEnd *_be)
void insert (DynInstPtr &inst)
void scheduleReadyInsts ()
void scheduleNonSpec (const InstSeqNum &sn)
DynInstPtr getReadyInst ()
void commit (const InstSeqNum &sn)
void squash (const InstSeqNum &sn)
int wakeDependents (DynInstPtr &inst)
void rescheduleMemInst (DynInstPtr &inst)
Tells memory dependence unit that a memory instruction needs to be rescheduled.
void replayMemInst (DynInstPtr &inst)
Re-executes all rescheduled memory instructions.
void completeMemInst (DynInstPtr &inst)
Completes memory instruction.
void violation (DynInstPtr &inst, DynInstPtr &violation)
bool isFull ()
void dumpInsts ()
Public Attributes
int size
int numInsts
int width
Stats::VectorDistribution occ_dist
Stats::Vector inst_count
Stats::Vector peak_inst_count
Stats::Scalar empty_count
Stats::Scalar current_count
Stats::Scalar fullCount
Stats::Formula occ_rate
Stats::Formula avg_residency
Stats::Formula empty_rate
Stats::Formula full_rate
Private Types
enum queue {
NonSpec, IQ, ToBeScheduled, ReadyList,
ReplayList
}
typedef std::list< DynInstPtr > InstList
typedef std::list< DynInstPtr >
::iterator InstListIt
typedef std::priority_queue
< DynInstPtr, std::vector
< DynInstPtr >, pqCompare > ReadyInstQueue
Private Member Functions
bool find (queue q, typename std::list< DynInstPtr >::iterator it)
Private Attributes
BackEnd * be
TimeBuffer< IssueToExec > * i2e
TimeBuffer< IssueToExec >::wire numIssued
InstList iq
InstList toBeScheduled
InstList readyList
InstList nonSpec
InstList replayList
ReadyInstQueue readyQueue
Detailed Description
template<class Impl>
class BackEnd< Impl >::InstQueue
Definition at line 84 of file back_end.hh.
Member Typedef Documentation
template<class Impl> typedef std::list<DynInstPtr> BackEnd< Impl >::InstQueue::InstList [private]
Definition at line 145 of file back_end.hh.
template<class Impl> typedef std::list<DynInstPtr>::iterator BackEnd< Impl >::InstQueue::InstListIt [private]
Definition at line 146 of file back_end.hh.
template<class Impl> typedef std::priority_queue<DynInstPtr, std::vector<DynInstPtr>, pqCompare> BackEnd< Impl >::InstQueue::ReadyInstQueue [private]
Definition at line 147 of file back_end.hh.
Member Enumeration Documentation
template<class Impl> enum BackEnd::InstQueue::queue [private]
Enumerator:
NonSpec
IQ
ToBeScheduled
ReadyList
ReplayList
Definition at line 85 of file back_end.hh.
Constructor & Destructor Documentation
template<class Impl > BackEnd< Impl >::InstQueue::InstQueue (Params * params)
Definition at line 35 of file back_end_impl.hh.
Member Function Documentation
template<class Impl> void BackEnd< Impl >::InstQueue::commit (const InstSeqNum & sn) [inline]
Definition at line 117 of file back_end.hh.
Referenced by BackEnd< Impl >::updateStructures().
template<class Impl > void BackEnd< Impl >::InstQueue::completeMemInst (DynInstPtr & inst)
Completes memory instruction.
Definition at line 337 of file back_end_impl.hh.
References panic.
Referenced by BackEnd< Impl >::completeMemInst().
template<class Impl > void BackEnd< Impl >::InstQueue::dumpInsts ()
Definition at line 381 of file back_end_impl.hh.
References cprintf(), BackEnd< Impl >::InstQueue::iq, BackEnd< Impl >::InstQueue::nonSpec, BackEnd< Impl >::InstQueue::readyList, and BackEnd< Impl >::InstQueue::toBeScheduled.
template<class Impl> bool BackEnd< Impl >::InstQueue::find (queue q, typename std::list< DynInstPtr >::iterator it) [private]
Referenced by BackEnd< Impl >::InstQueue::getReadyInst(), BackEnd< Impl >::InstQueue::replayMemInst(), BackEnd< Impl >::InstQueue::scheduleNonSpec(), and BackEnd< Impl >::InstQueue::wakeDependents().
template<class Impl > Impl::DynInstPtr BackEnd< Impl >::InstQueue::getReadyInst ()
Definition at line 207 of file back_end_impl.hh.
References BackEnd< Impl >::InstQueue::find(), BackEnd< Impl >::InstQueue::numInsts, BackEnd< Impl >::InstQueue::ReadyList, BackEnd< Impl >::InstQueue::readyList, and BackEnd< Impl >::InstQueue::readyQueue.
Referenced by BackEnd< Impl >::executeInsts().
template<class Impl > void BackEnd< Impl >::InstQueue::insert (DynInstPtr & inst)
Definition at line 127 of file back_end_impl.hh.
References DPRINTF, BackEnd< Impl >::InstQueue::inst_count, BackEnd< Impl >::InstQueue::iq, BackEnd< Impl >::InstQueue::nonSpec, BackEnd< Impl >::InstQueue::numInsts, and BackEnd< Impl >::InstQueue::toBeScheduled.
Referenced by BackEnd< Impl >::addToIQ().
template<class Impl> bool BackEnd< Impl >::InstQueue::isFull () [inline]
Definition at line 136 of file back_end.hh.
References BackEnd< Impl >::InstQueue::numInsts, and BackEnd< Impl >::InstQueue::size.
Referenced by BackEnd< Impl >::checkDispatchStatus(), and BackEnd< Impl >::dispatchInsts().
template<class Impl > std::string BackEnd< Impl >::InstQueue::name () const
Definition at line 42 of file back_end_impl.hh.
References BackEnd< Impl >::InstQueue::be, and BackEnd< Impl >::name().
Referenced by BackEnd< Impl >::InstQueue::regStats().
template<class Impl > void BackEnd< Impl >::InstQueue::regStats ()
Definition at line 49 of file back_end_impl.hh.
References BackEnd< Impl >::InstQueue::avg_residency, BackEnd< Impl >::InstQueue::be, Stats::cdf, BackEnd< Impl >::cpu, BackEnd< Impl >::InstQueue::current_count, BackEnd< Impl >::InstQueue::empty_count, BackEnd< Impl >::InstQueue::empty_rate, BackEnd< Impl >::InstQueue::full_rate, BackEnd< Impl >::InstQueue::fullCount, Stats::VectorBase< Derived, Stor >::init(), Stats::VectorDistribution::init(), BackEnd< Impl >::InstQueue::inst_count, Stats::DataWrap< Derived, InfoProxyType >::name(), BackEnd< Impl >::InstQueue::name(), BackEnd< Impl >::InstQueue::occ_dist, BackEnd< Impl >::InstQueue::occ_rate, BackEnd< Impl >::InstQueue::peak_inst_count, BackEnd< Impl >::InstQueue::size, and Stats::total.
Referenced by BackEnd< Impl >::regStats().
template<class Impl > void BackEnd< Impl >::InstQueue::replayMemInst (DynInstPtr & inst)
Re-executes all rescheduled memory instructions.
Definition at line 319 of file back_end_impl.hh.
References DPRINTF, BackEnd< Impl >::InstQueue::find(), BackEnd< Impl >::InstQueue::replayList, BackEnd< Impl >::InstQueue::ReplayList, and BackEnd< Impl >::InstQueue::toBeScheduled.
Referenced by BackEnd< Impl >::replayMemInst().
template<class Impl > void BackEnd< Impl >::InstQueue::rescheduleMemInst (DynInstPtr & inst)
Tells memory dependence unit that a memory instruction needs to be rescheduled.
It will re-execute once replayMemInst() is called.
Definition at line 307 of file back_end_impl.hh.
References DPRINTF, BackEnd< Impl >::InstQueue::numInsts, and BackEnd< Impl >::InstQueue::replayList.
Referenced by BackEnd< Impl >::rescheduleMemInst().
template<class Impl > void BackEnd< Impl >::InstQueue::scheduleNonSpec (const InstSeqNum & sn)
Definition at line 180 of file back_end_impl.hh.
References DPRINTF, BackEnd< Impl >::InstQueue::find(), BackEnd< Impl >::InstQueue::NonSpec, BackEnd< Impl >::InstQueue::nonSpec, BackEnd< Impl >::InstQueue::numIssued, BackEnd< Impl >::InstQueue::readyList, BackEnd< Impl >::InstQueue::readyQueue, and TimeBuffer< T >::size.
Referenced by BackEnd< Impl >::updateStructures().
template<class Impl > void BackEnd< Impl >::InstQueue::scheduleReadyInsts ()
Definition at line 152 of file back_end_impl.hh.
References DPRINTF, BackEnd< Impl >::InstQueue::numIssued, BackEnd< Impl >::InstQueue::readyList, BackEnd< Impl >::InstQueue::readyQueue, TimeBuffer< T >::size, BackEnd< Impl >::InstQueue::toBeScheduled, and BackEnd< Impl >::InstQueue::width.
Referenced by BackEnd< Impl >::scheduleReadyInsts().
template<class Impl> void BackEnd< Impl >::InstQueue::setBE (BackEnd * _be) [inline]
Definition at line 107 of file back_end.hh.
References BackEnd< Impl >::InstQueue::be.
Referenced by BackEnd< Impl >::BackEnd().
template<class Impl > void BackEnd< Impl >::InstQueue::setIssueExecQueue (TimeBuffer< IssueToExec > * i2e_queue)
Definition at line 119 of file back_end_impl.hh.
References TimeBuffer< T >::getWire(), BackEnd< Impl >::InstQueue::i2e, and BackEnd< Impl >::InstQueue::numIssued.
Referenced by BackEnd< Impl >::BackEnd().
template<class Impl > void BackEnd< Impl >::InstQueue::squash (const InstSeqNum & sn)
Definition at line 223 of file back_end_impl.hh.
References DPRINTF, BackEnd< Impl >::InstQueue::iq, BackEnd< Impl >::InstQueue::nonSpec, BackEnd< Impl >::InstQueue::numInsts, and BackEnd< Impl >::InstQueue::replayList.
Referenced by BackEnd< Impl >::squash().
template<class Impl> void BackEnd< Impl >::InstQueue::violation (DynInstPtr & inst, DynInstPtr & violation) [inline]
Definition at line 134 of file back_end.hh.
template<class Impl > int BackEnd< Impl >::InstQueue::wakeDependents (DynInstPtr & inst)
Definition at line 276 of file back_end_impl.hh.
References DPRINTF, BackEnd< Impl >::InstQueue::find(), ArmISA::i, BackEnd< Impl >::InstQueue::iq, BackEnd< Impl >::InstQueue::IQ, BackEnd< Impl >::InstQueue::nonSpec, BackEnd< Impl >::InstQueue::NonSpec, and BackEnd< Impl >::InstQueue::toBeScheduled.
Referenced by BackEnd< Impl >::writebackInsts().
Member Data Documentation
template<class Impl> Stats::Formula BackEnd< Impl >::InstQueue::avg_residency
Definition at line 169 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::regStats().
template<class Impl> BackEnd* BackEnd< Impl >::InstQueue::be [private]
Definition at line 142 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::name(), BackEnd< Impl >::InstQueue::regStats(), and BackEnd< Impl >::InstQueue::setBE().
template<class Impl> Stats::Scalar BackEnd< Impl >::InstQueue::current_count
Definition at line 165 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::regStats().
template<class Impl> Stats::Scalar BackEnd< Impl >::InstQueue::empty_count
Definition at line 164 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::regStats().
template<class Impl> Stats::Formula BackEnd< Impl >::InstQueue::empty_rate
Definition at line 170 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::regStats().
template<class Impl> Stats::Formula BackEnd< Impl >::InstQueue::full_rate
Definition at line 171 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::regStats().
template<class Impl> Stats::Scalar BackEnd< Impl >::InstQueue::fullCount
Definition at line 166 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::regStats().
template<class Impl> TimeBuffer<IssueToExec>* BackEnd< Impl >::InstQueue::i2e [private]
Definition at line 143 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::setIssueExecQueue().
template<class Impl> Stats::Vector BackEnd< Impl >::InstQueue::inst_count
Definition at line 162 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::insert(), and BackEnd< Impl >::InstQueue::regStats().
template<class Impl> InstList BackEnd< Impl >::InstQueue::iq [private]
Definition at line 149 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::dumpInsts(), BackEnd< Impl >::InstQueue::insert(), BackEnd< Impl >::InstQueue::squash(), and BackEnd< Impl >::InstQueue::wakeDependents().
template<class Impl> InstList BackEnd< Impl >::InstQueue::nonSpec [private]
Definition at line 152 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::dumpInsts(), BackEnd< Impl >::InstQueue::insert(), BackEnd< Impl >::InstQueue::scheduleNonSpec(), BackEnd< Impl >::InstQueue::squash(), and BackEnd< Impl >::InstQueue::wakeDependents().
template<class Impl> int BackEnd< Impl >::InstQueue::numInsts
Definition at line 157 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::getReadyInst(), BackEnd< Impl >::InstQueue::insert(), BackEnd< Impl >::InstQueue::isFull(), BackEnd< Impl >::InstQueue::rescheduleMemInst(), BackEnd< Impl >::InstQueue::squash(), and BackEnd< Impl >::tick().
template<class Impl> TimeBuffer<IssueToExec>::wire BackEnd< Impl >::InstQueue::numIssued [private]
Definition at line 144 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::scheduleNonSpec(), BackEnd< Impl >::InstQueue::scheduleReadyInsts(), and BackEnd< Impl >::InstQueue::setIssueExecQueue().
template<class Impl> Stats::VectorDistribution BackEnd< Impl >::InstQueue::occ_dist
Definition at line 160 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::regStats().
template<class Impl> Stats::Formula BackEnd< Impl >::InstQueue::occ_rate
Definition at line 168 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::regStats().
template<class Impl> Stats::Vector BackEnd< Impl >::InstQueue::peak_inst_count
Definition at line 163 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::regStats().
template<class Impl> InstList BackEnd< Impl >::InstQueue::readyList [private]
Definition at line 151 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::dumpInsts(), BackEnd< Impl >::InstQueue::getReadyInst(), BackEnd< Impl >::InstQueue::scheduleNonSpec(), and BackEnd< Impl >::InstQueue::scheduleReadyInsts().
template<class Impl> ReadyInstQueue BackEnd< Impl >::InstQueue::readyQueue [private]
Definition at line 154 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::getReadyInst(), BackEnd< Impl >::InstQueue::scheduleNonSpec(), and BackEnd< Impl >::InstQueue::scheduleReadyInsts().
template<class Impl> InstList BackEnd< Impl >::InstQueue::replayList [private]
Definition at line 153 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::replayMemInst(), BackEnd< Impl >::InstQueue::rescheduleMemInst(), and BackEnd< Impl >::InstQueue::squash().
template<class Impl> int BackEnd< Impl >::InstQueue::size
Definition at line 156 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::isFull(), and BackEnd< Impl >::InstQueue::regStats().
template<class Impl> InstList BackEnd< Impl >::InstQueue::toBeScheduled [private]
Definition at line 150 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::dumpInsts(), BackEnd< Impl >::InstQueue::insert(), BackEnd< Impl >::InstQueue::replayMemInst(), BackEnd< Impl >::InstQueue::scheduleReadyInsts(), and BackEnd< Impl >::InstQueue::wakeDependents().
template<class Impl> int BackEnd< Impl >::InstQueue::width
Definition at line 158 of file back_end.hh.
Referenced by BackEnd< Impl >::InstQueue::scheduleReadyInsts().
The documentation for this class was generated from the following files:
cpu/ozone/back_end.hh
cpu/ozone/back_end_impl.hh