gem5: ArmISA::FpRegRegRegImmOp Class Reference
ArmISA::FpRegRegRegImmOp Class Reference
#include <vfp.hh>