gem5: DumbTOD Class Reference
DumbTOD Class Reference
DumbTOD simply returns some idea of time when read.
#include <dtod.hh>