gem5: CoherentBus::CoherentBusMasterPort Class Reference
CoherentBus::CoherentBusMasterPort Class Reference
Declaration of the coherent bus master port type, one will be instantiated for each of the slave interfaces connecting to the bus.
#include <coherent_bus.hh>