gem5: LRU Class Reference
LRU Class Reference
A LRU cache tag store.
#include <lru.hh>