gem5: X86ISA::PS2Device Class Reference
X86ISA::PS2Device Class Reference
#include <i8042.hh>