gem5: MSHRQueue Class Reference
MSHRQueue Class Reference
A Class for maintaining a list of pending and allocated memory requests.
#include <mshr_queue.hh>