gem5: Request Class Reference
Request Class Reference
#include <request.hh>
Public Types
typedef uint32_t FlagsType
typedef ::Flags< FlagsType > Flags
Public Member Functions
Request ()
Minimal constructor.
Request (Addr paddr, int size, Flags flags, MasterID mid)
Constructor for physical (e.g.
Request (Addr paddr, int size, Flags flags, MasterID mid, Tick time)
Request (Addr paddr, int size, Flags flags, MasterID mid, Tick time, Addr pc)
Request (int asid, Addr vaddr, int size, Flags flags, MasterID mid, Addr pc, int cid, ThreadID tid)
~Request ()
void setThreadContext (int context_id, ThreadID tid)
Set up CPU and thread numbers.
void setPhys (Addr paddr, int size, Flags flags, MasterID mid, Tick time)
Set up a physical (e.g.
void setPhys (Addr paddr, int size, Flags flags, MasterID mid)
void setVirt (int asid, Addr vaddr, int size, Flags flags, MasterID mid, Addr pc)
Set up a virtual (e.g., CPU) request in a previously allocated Request object.
void setPaddr (Addr paddr)
Set just the physical address.
void splitOnVaddr (Addr split_addr, RequestPtr &req1, RequestPtr &req2)
Generate two requests as if this request had been split into two pieces.
bool hasPaddr ()
Accessor for paddr.
Addr getPaddr ()
bool hasSize ()
Accessor for size.
int getSize ()
Tick time () const
Accessor for time.
void time (Tick time)
Flags getFlags ()
Accessor for flags.
void setFlags (Flags flags)
Note that unlike other accessors, this function sets *specific flags* (ORs them in); it does not assign its argument to the _flags field.
Addr getVaddr ()
Accessor function for vaddr.
MasterID masterId ()
Accesssor for the requestor id.
int getAsid ()
Accessor function for asid.
void setAsid (int asid)
Accessor function for asid.
uint8_t getAsi ()
Accessor function for asi.
bool extraDataValid ()
Accessor function to check if sc result is valid.
uint64_t getExtraData () const
Accessor function for store conditional return value.
void setExtraData (uint64_t extraData)
Accessor function for store conditional return value.
bool hasContextId () const
int contextId () const
Accessor function for context ID.
int threadId () const
Accessor function for thread ID.
bool hasPC () const
Addr getPC () const
Accessor function for pc.
bool isUncacheable () const
Accessor functions for flags.
bool isInstFetch () const
bool isPrefetch () const
bool isLLSC () const
bool isLocked () const
bool isSwap () const
bool isCondSwap () const
bool isMmappedIpr () const
bool isClearLL () const
Static Public Attributes
static const FlagsType ASI_BITS = 0x000000FF
ASI information for this request if it exists.
static const FlagsType INST_FETCH = 0x00000100
The request was an instruction fetch.
static const FlagsType PHYSICAL = 0x00000200
The virtual address is also the physical address.
static const FlagsType VPTE = 0x00000400
The request is an ALPHA VPTE pal access (hw_ld).
static const FlagsType ALTMODE = 0x00000800
Use the alternate mode bits in ALPHA.
static const FlagsType UNCACHEABLE = 0x00001000
The request is to an uncacheable address.
static const FlagsType MMAPPED_IPR = 0x00002000
This request is to a memory mapped register.
static const FlagsType CLEAR_LL = 0x00004000
This request is a clear exclusive.
static const FlagsType NO_ACCESS = 0x00080000
The request should not cause a memory access.
static const FlagsType LOCKED = 0x00100000
This request will lock or unlock the accessed memory.
static const FlagsType LLSC = 0x00200000
The request is a Load locked/store conditional.
static const FlagsType MEM_SWAP = 0x00400000
This request is for a memory swap.
static const FlagsType MEM_SWAP_COND = 0x00800000
static const FlagsType PREFETCH = 0x01000000
The request is a prefetch.
static const FlagsType PF_EXCLUSIVE = 0x02000000
The request should be prefetched into the exclusive state.
static const FlagsType EVICT_NEXT = 0x04000000
The request should be marked as LRU.
static const FlagsType STICKY_FLAGS = INST_FETCH
These flags are *not* cleared when a Request object is reused (assigned a new address).
static const uint32_t invldPid = UINT_MAX
Invalid or unknown Pid.
static const MasterID wbMasterId = 0
Request Ids that are statically allocated.
static const MasterID funcMasterId = 1
This request id is used for functional requests that don't come from a particular device.
static const MasterID intMasterId = 2
This request id is used for message signaled interrupts.
static const MasterID invldMasterId = USHRT_MAX
Invalid request id for assertion checking only.
Private Types
typedef uint8_t PrivateFlagsType
typedef ::Flags< PrivateFlagsType > PrivateFlags
Private Attributes
Addr _paddr
The physical address of the request.
int _size
The size of the request.
MasterID _masterId
The requestor ID which is unique in the system for all ports that are capable of issuing a transaction.
Flags _flags
Flag structure for the request.
PrivateFlags privateFlags
Private flags for field validity checking.
Tick _time
The time this request was started.
int _asid
The address space ID.
Addr _vaddr
The virtual address of the request.
uint64_t _extraData
Extra data for the request, such as the return value of store conditional or the compare value for a CAS.
int _contextId
The context ID (for statistics, typically).
int _threadId
The thread ID (id within this CPU).
Addr _pc
program counter of initiating access; for tracing/debugging
Static Private Attributes
static const PrivateFlagsType VALID_SIZE = 0x00000001
Whether or not the size is valid.
static const PrivateFlagsType VALID_PADDR = 0x00000002
Whether or not paddr is valid (has been written yet).
static const PrivateFlagsType VALID_VADDR = 0x00000004
Whether or not the vaddr & asid are valid.
static const PrivateFlagsType VALID_PC = 0x00000010
Whether or not the pc is valid.
static const PrivateFlagsType VALID_CONTEXT_ID = 0x00000020
Whether or not the context ID is valid.
static const PrivateFlagsType VALID_THREAD_ID = 0x00000040
static const PrivateFlagsType VALID_EXTRA_DATA = 0x00000080
Whether or not the sc result is valid.
static const PrivateFlagsType STICKY_PRIVATE_FLAGS
These flags are *not* cleared when a Request object is reused (assigned a new address).
Detailed Description
Definition at line 85 of file request.hh.
Member Typedef Documentation
typedef ::Flags<FlagsType> Request::Flags
Definition at line 89 of file request.hh.
typedef uint32_t Request::FlagsType
Definition at line 88 of file request.hh.
typedef ::Flags<PrivateFlagsType> Request::PrivateFlags [private]
Definition at line 156 of file request.hh.
typedef uint8_t Request::PrivateFlagsType [private]
Definition at line 155 of file request.hh.
Constructor & Destructor Documentation
Request::Request () [inline]
Minimal constructor.
No fields are initialized. (Note that _flags and privateFlags are cleared by Flags default constructor.)
Definition at line 233 of file request.hh.
Request::Request (Addr paddr, int size, Flags flags, MasterID mid) [inline]
Constructor for physical (e.g.
device) requests. Initializes just physical address, size, flags, and timestamp (to curTick()). These fields are adequate to perform a request.
Definition at line 241 of file request.hh.
References setPhys().
Request::Request (Addr paddr, int size, Flags flags, MasterID mid, Tick time) [inline]
Definition at line 246 of file request.hh.
References setPhys().
Request::Request (Addr paddr, int size, Flags flags, MasterID mid, Tick time, Addr pc) [inline]
Definition at line 251 of file request.hh.
References _pc, privateFlags, Flags< T >::set(), setPhys(), and VALID_PC.
Request::Request (int asid, Addr vaddr, int size, Flags flags, MasterID mid, Addr pc, int cid, ThreadID tid) [inline]
Definition at line 258 of file request.hh.
References setThreadContext(), and setVirt().
Request::~Request () [inline]
Definition at line 265 of file request.hh.
Member Function Documentation
int Request::contextId () const [inline]
Accessor function for context ID.
Definition at line 490 of file request.hh.
References _contextId, Flags< T >::isSet(), privateFlags, and VALID_CONTEXT_ID.
Referenced by Cache< TagStore >::access(), AbstractMemory::checkLockedAddrList(), Sequencer::issueRequest(), CacheBlk::Lock::matchesContext(), LockedAddr::matchesContext(), BasePrefetcher::notify(), Sinic::Device::read(), CpuLocalTimer::read(), TsunamiCChip::read(), Pl390::readCpu(), Pl390::readDistributor(), Iob::readJBus(), AbstractMemory::trackLoadLocked(), Sinic::Device::write(), CpuLocalTimer::write(), Pl390::writeCpu(), Pl390::writeDistributor(), and Iob::writeJBus().
bool Request::extraDataValid () [inline]
Accessor function to check if sc result is valid.
Definition at line 461 of file request.hh.
References Flags< T >::isSet(), privateFlags, and VALID_EXTRA_DATA.
Referenced by CheckerCPU::writeMem().
uint8_t Request::getAsi () [inline]
Accessor function for asi.
Definition at line 453 of file request.hh.
References _flags, ASI_BITS, Flags< T >::isSet(), privateFlags, and VALID_VADDR.
int Request::getAsid () [inline]
Accessor function for asid.
Definition at line 438 of file request.hh.
References _asid, Flags< T >::isSet(), privateFlags, and VALID_VADDR.
uint64_t Request::getExtraData () const [inline]
Accessor function for store conditional return value.
Definition at line 468 of file request.hh.
References _extraData, Flags< T >::isSet(), privateFlags, and VALID_EXTRA_DATA.
Referenced by AbstractMemory::access(), Cache< TagStore >::cmpAndSwap(), BaseO3DynInst< Impl >::completeAcc(), RubyPort::M5Port::hitCallback(), AtomicSimpleCPU::writeMem(), and CheckerCPU::writeMem().
Flags Request::getFlags () [inline]
Accessor for flags.
Definition at line 404 of file request.hh.
References _flags, Flags< T >::isSet(), privateFlags, VALID_PADDR, and VALID_VADDR.
Referenced by TimingSimpleCPU::buildSplitPacket(), CheckerCPU::checkFlags(), TimingSimpleCPU::completeDataAccess(), WholeTranslationState::finish(), WholeTranslationState::getFlags(), Sequencer::makeRequest(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), TimingSimpleCPU::sendData(), TimingSimpleCPU::sendSplitData(), X86ISA::TLB::translate(), AlphaISA::TLB::translateData(), ArmISA::TLB::translateFs(), AlphaISA::TLB::translateInst(), ArmISA::TLB::translateSe(), AtomicSimpleCPU::writeMem(), and CheckerCPU::writeMem().
Addr Request::getPaddr () [inline]
Definition at line 365 of file request.hh.
References _paddr, Flags< T >::isSet(), privateFlags, and VALID_PADDR.
Referenced by TimingSimpleCPU::buildSplitPacket(), AlphaISA::TLB::checkCacheability(), CheckerCPU::checkFlags(), AbstractMemory::checkLockedAddrList(), NetworkTest::completeRequest(), MemTest::completeRequest(), CacheUnit::doTLBAccess(), TLBUnit::execute(), WholeTranslationState::finish(), DefaultFetch< Impl >::finishTranslation(), NetworkTest::generatePkt(), WholeTranslationState::getPaddr(), MipsISA::handleLockedRead(), ArmISA::handleLockedRead(), AlphaISA::handleLockedRead(), MipsISA::handleLockedWrite(), ArmISA::handleLockedWrite(), AlphaISA::handleLockedWrite(), CacheBlk::Lock::matchesContext(), CacheBlk::Lock::overlapping(), Packet::Packet(), CacheUnit::processCacheCompletion(), OzoneLWLSQ< Impl >::read(), LSQUnit< Impl >::read(), CheckerCPU::readMem(), Packet::reinitFromRequest(), DmaPort::sendDma(), TimingSimpleCPU::sendFetch(), MemTest::tick(), AbstractMemory::trackLoadLocked(), X86ISA::TLB::translate(), AlphaISA::TLB::translateData(), AlphaISA::TLB::translateInst(), OzoneLWLSQ< Impl >::write(), LSQUnit< Impl >::write(), OzoneLWLSQ< Impl >::writebackStores(), LSQUnit< Impl >::writebackStores(), and CheckerCPU::writeMem().
Addr Request::getPC () const [inline]
Accessor function for pc.
Definition at line 512 of file request.hh.
References _pc, Flags< T >::isSet(), privateFlags, and VALID_PC.
Referenced by StridePrefetcher::calculatePrefetch(), Sequencer::issueRequest(), AlphaISA::TLB::translateData(), and AlphaISA::TLB::translateInst().
int Request::getSize () [inline]
Definition at line 381 of file request.hh.
References _size, Flags< T >::isSet(), privateFlags, and VALID_SIZE.
Referenced by TimingSimpleCPU::buildSplitPacket(), MemTest::completeRequest(), NetworkTest::generatePkt(), DmaPort::handleResp(), Check::initiateCheck(), Check::initiateFlush(), Check::initiatePrefetch(), CacheBlk::Lock::matchesContext(), CacheBlk::Lock::overlapping(), Packet::Packet(), OzoneLWLSQ< Impl >::read(), LSQUnit< Impl >::read(), Packet::reinitFromRequest(), TrafficGen::StateGraph::BaseGen::send(), DmaPort::sendDma(), BaseDynInst< Impl >::splitRequest(), MemTest::tick(), PageTable::translate(), X86ISA::TLB::translate(), AlphaISA::TLB::translateData(), PowerISA::TLB::translateInst(), X86ISA::TLB::translateInt(), LSQUnit< Impl >::write(), OzoneLWLSQ< Impl >::writebackStores(), and LSQUnit< Impl >::writebackStores().
Addr Request::getVaddr () [inline]
Accessor function for vaddr.
Definition at line 423 of file request.hh.
References _vaddr, Flags< T >::isSet(), privateFlags, and VALID_VADDR.
Referenced by PowerISA::TLB::checkCacheability(), MipsISA::TLB::checkCacheability(), CheckerCPU::checkFlags(), CacheUnit::doTLBAccess(), TLBUnit::execute(), TimingSimpleCPU::fetch(), DefaultFetch< Impl >::finishTranslation(), CacheUnit::processCacheCompletion(), OzoneLWLSQ< Impl >::read(), LSQUnit< Impl >::read(), CheckerCPU::readMem(), BaseDynInst< Impl >::readMem(), TimingSimpleCPU::sendFetch(), BaseDynInst< Impl >::splitRequest(), PageTable::translate(), X86ISA::TLB::translate(), AlphaISA::TLB::translateData(), ArmISA::TLB::translateFs(), PowerISA::TLB::translateInst(), AlphaISA::TLB::translateInst(), X86ISA::TLB::translateInt(), ArmISA::TLB::translateSe(), ArmISA::TableWalker::walk(), CheckerCPU::writeMem(), and BaseDynInst< Impl >::writeMem().
bool Request::hasContextId () const [inline]
Definition at line 483 of file request.hh.
References Flags< T >::isSet(), privateFlags, and VALID_CONTEXT_ID.
Referenced by Cache< TagStore >::access(), Sequencer::issueRequest(), Pl390::readCpu(), Pl390::writeCpu(), and Pl390::writeDistributor().
bool Request::hasPaddr () [inline]
Accessor for paddr.
Definition at line 359 of file request.hh.
References Flags< T >::isSet(), privateFlags, and VALID_PADDR.
Referenced by Packet::Packet(), and Packet::reinitFromRequest().
bool Request::hasPC () const [inline]
Definition at line 505 of file request.hh.
References Flags< T >::isSet(), privateFlags, and VALID_PC.
Referenced by StridePrefetcher::calculatePrefetch(), and Sequencer::issueRequest().
bool Request::hasSize () [inline]
Accessor for size.
Definition at line 375 of file request.hh.
References Flags< T >::isSet(), privateFlags, and VALID_SIZE.
Referenced by Packet::Packet().
bool Request::isClearLL () const [inline]
Definition at line 528 of file request.hh.
References _flags, CLEAR_LL, and Flags< T >::isSet().
Referenced by Cache< TagStore >::uncacheableFlush().
bool Request::isCondSwap () const [inline]
Definition at line 526 of file request.hh.
References _flags, Flags< T >::isSet(), and MEM_SWAP_COND.
Referenced by AbstractMemory::access(), Cache< TagStore >::cmpAndSwap(), CacheUnit::doCacheAccess(), CacheUnit::execute(), BaseDynInst< Impl >::finishTranslation(), TimingSimpleCPU::sendData(), and AtomicSimpleCPU::writeMem().
bool Request::isInstFetch () const [inline]
Definition at line 521 of file request.hh.
References _flags, INST_FETCH, and Flags< T >::isSet().
Referenced by Cache< TagStore >::access(), AbstractMemory::access(), Sequencer::makeRequest(), BasePrefetcher::notify(), Cache< TagStore >::satisfyCpuSideRequest(), ArmISA::TLB::translateFs(), and Cache< TagStore >::uncacheableFlush().
bool Request::isLLSC () const [inline]
Definition at line 523 of file request.hh.
References _flags, Flags< T >::isSet(), and LLSC.
Referenced by CacheUnit::buildDataPacket(), TimingSimpleCPU::buildPacket(), TimingSimpleCPU::completeDataAccess(), CacheUnit::doCacheAccess(), CacheUnit::execute(), CacheUnit::processCacheCompletion(), OzoneLWLSQ< Impl >::read(), LSQUnit< Impl >::read(), TimingSimpleCPU::readMem(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), TimingSimpleCPU::sendData(), OzoneLWLSQ< Impl >::writebackStores(), LSQUnit< Impl >::writebackStores(), TimingSimpleCPU::writeMem(), and AtomicSimpleCPU::writeMem().
bool Request::isLocked () const [inline]
Definition at line 524 of file request.hh.
References _flags, Flags< T >::isSet(), and LOCKED.
Referenced by Sequencer::makeRequest(), AtomicSimpleCPU::readMem(), and AtomicSimpleCPU::writeMem().
bool Request::isMmappedIpr () const [inline]
Definition at line 527 of file request.hh.
References _flags, Flags< T >::isSet(), and MMAPPED_IPR.
Referenced by TimingSimpleCPU::buildSplitPacket(), TimingSimpleCPU::handleReadPacket(), TimingSimpleCPU::handleWritePacket(), LSQUnit< Impl >::read(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), LSQUnit< Impl >::writebackStores(), and AtomicSimpleCPU::writeMem().
bool Request::isPrefetch () const [inline]
Definition at line 522 of file request.hh.
References _flags, Flags< T >::isSet(), and PREFETCH.
Referenced by WholeTranslationState::isPrefetch(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), ArmISA::TLB::translateFs(), AtomicSimpleCPU::writeMem(), and CheckerCPU::writeMem().
bool Request::isSwap () const [inline]
Definition at line 525 of file request.hh.
References _flags, Flags< T >::isSet(), MEM_SWAP, and MEM_SWAP_COND.
Referenced by CacheUnit::buildDataPacket(), TimingSimpleCPU::buildPacket(), CacheUnit::execute(), ArmISA::handleLockedWrite(), TimingSimpleCPU::readMem(), OzoneLWLSQ< Impl >::writebackStores(), LSQUnit< Impl >::writebackStores(), TimingSimpleCPU::writeMem(), and AtomicSimpleCPU::writeMem().
bool Request::isUncacheable () const [inline]
Accessor functions for flags.
Note that these are for testing only; setting flags should be done via setFlags().
Definition at line 520 of file request.hh.
References _flags, Flags< T >::isSet(), and UNCACHEABLE.
Referenced by Cache< TagStore >::access(), MSHR::allocate(), BaseCache::allocateMissBuffer(), BaseCache::allocateUncachedReadBuffer(), AlphaISA::TLB::checkCacheability(), FrontEnd< Impl >::fetchCacheLine(), Cache< TagStore >::getBusPacket(), MipsISA::handleLockedWrite(), AlphaISA::handleLockedWrite(), WholeTranslationState::isUncacheable(), BasePrefetcher::notify(), OzoneLWLSQ< Impl >::read(), LSQUnit< Impl >::read(), CheckerCPU::readMem(), CoherentBus::recvAtomic(), Cache< TagStore >::recvAtomic(), Cache< TagStore >::recvAtomicSnoop(), CoherentBus::recvFunctional(), CoherentBus::recvTimingReq(), Cache< TagStore >::recvTimingReq(), Cache< TagStore >::recvTimingResp(), Cache< TagStore >::recvTimingSnoopReq(), and OzoneLWLSQ< Impl >::writebackStores().
MasterID Request::masterId () [inline]
Accesssor for the requestor id.
Definition at line 431 of file request.hh.
References _masterId.
Referenced by Cache< TagStore >::access(), AbstractMemory::access(), StridePrefetcher::calculatePrefetch(), GHBPrefetcher::calculatePrefetch(), Cache< TagStore >::getNextMSHR(), Cache< TagStore >::handleFill(), BaseCache::incHitCount(), BaseCache::incMissCount(), Cache< TagStore >::recvTimingReq(), and Cache< TagStore >::recvTimingResp().
void Request::setAsid (int asid) [inline]
Accessor function for asid.
Definition at line 446 of file request.hh.
References _asid.
Referenced by ArmISA::TLB::translateFs().
void Request::setExtraData (uint64_t extraData) [inline]
Accessor function for store conditional return value.
Definition at line 476 of file request.hh.
References _extraData, privateFlags, Flags< T >::set(), and VALID_EXTRA_DATA.
Referenced by Cache< TagStore >::access(), AbstractMemory::checkLockedAddrList(), CacheBlk::checkWrite(), BaseO3DynInst< Impl >::completeAcc(), CacheUnit::doCacheAccess(), BaseDynInst< Impl >::finishTranslation(), Sequencer::handleLlsc(), MipsISA::handleLockedWrite(), ArmISA::handleLockedWrite(), AlphaISA::handleLockedWrite(), Cache< TagStore >::recvTimingResp(), TimingSimpleCPU::sendData(), OzoneLWLSQ< Impl >::writebackStores(), AtomicSimpleCPU::writeMem(), and AbstractMemory::writeOK().
void Request::setFlags (Flags flags) [inline]
Note that unlike other accessors, this function sets *specific flags* (ORs them in); it does not assign its argument to the _flags field.
Thus this method should rightly be called setFlags() and not just flags().
Definition at line 415 of file request.hh.
References _flags, Flags< T >::isSet(), privateFlags, Flags< T >::set(), VALID_PADDR, and VALID_VADDR.
Referenced by PowerISA::TLB::checkCacheability(), MipsISA::TLB::checkCacheability(), AlphaISA::TLB::checkCacheability(), WholeTranslationState::finish(), X86ISA::TLB::translate(), ArmISA::TLB::translateFs(), AlphaISA::TLB::translateInst(), and X86ISA::TLB::translateInt().
void Request::setPaddr (Addr paddr) [inline]
Set just the physical address.
This should only be used to record the result of a translation, and thus the vaddr must be valid before this method is called. Otherwise, use setPhys() to guarantee that the size and flags are also set.
Definition at line 330 of file request.hh.
References _paddr, Flags< T >::isSet(), privateFlags, Flags< T >::set(), VALID_PADDR, and VALID_VADDR.
Referenced by AlphaISA::TLB::checkCacheability(), WholeTranslationState::finish(), NetworkTest::generatePkt(), PageTable::translate(), X86ISA::TLB::translate(), AlphaISA::TLB::translateData(), ArmISA::TLB::translateFs(), AlphaISA::TLB::translateInst(), X86ISA::TLB::translateInt(), and ArmISA::TLB::translateSe().
void Request::setPhys (Addr paddr, int size, Flags flags, MasterID mid) [inline]
Definition at line 297 of file request.hh.
References curTick(), and setPhys().
void Request::setPhys (Addr paddr, int size, Flags flags, MasterID mid, Tick time) [inline]
Set up a physical (e.g.
device) request in a previously allocated Request object.
Definition at line 283 of file request.hh.
References _flags, _masterId, _paddr, _size, _time, Flags< T >::clear(), privateFlags, Flags< T >::set(), STICKY_FLAGS, STICKY_PRIVATE_FLAGS, VALID_PADDR, and VALID_SIZE.
Referenced by PortProxy::blobHelper(), TimingSimpleCPU::buildSplitPacket(), CacheRecorder::enqueueNextFetchRequest(), NetworkTest::generatePkt(), Request(), setPhys(), and MemTest::tick().
void Request::setThreadContext (int context_id, ThreadID tid) [inline]
Set up CPU and thread numbers.
Definition at line 271 of file request.hh.
References _contextId, _threadId, privateFlags, Flags< T >::set(), VALID_CONTEXT_ID, and VALID_THREAD_ID.
Referenced by TimingSimpleCPU::fetch(), NetworkTest::generatePkt(), AtomicSimpleCPU::init(), Check::initiateCheck(), Check::initiatePrefetch(), BasePrefetcher::notify(), Request(), AtomicSimpleCPU::takeOverFrom(), and MemTest::tick().
void Request::setVirt (int asid, Addr vaddr, int size, Flags flags, MasterID mid, Addr pc) [inline]
Set up a virtual (e.g., CPU) request in a previously allocated Request object.
Definition at line 307 of file request.hh.
References _asid, _flags, _masterId, _pc, _size, _time, _vaddr, Flags< T >::clear(), curTick(), privateFlags, Flags< T >::set(), STICKY_FLAGS, STICKY_PRIVATE_FLAGS, VALID_PC, VALID_SIZE, and VALID_VADDR.
Referenced by NetworkTest::generatePkt(), CacheUnit::processCacheCompletion(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), Request(), BaseSimpleCPU::setupFetchRequest(), Checker< Impl >::verify(), AtomicSimpleCPU::writeMem(), and CheckerCPU::writeMem().
void Request::splitOnVaddr (Addr split_addr, RequestPtr & req1, RequestPtr & req2) [inline]
Generate two requests as if this request had been split into two pieces.
The original request can't have been translated already.
Definition at line 341 of file request.hh.
References _size, _vaddr, Flags< T >::isSet(), Flags< T >::noneSet(), privateFlags, VALID_PADDR, and VALID_VADDR.
Referenced by TimingSimpleCPU::readMem(), BaseDynInst< Impl >::splitRequest(), and TimingSimpleCPU::writeMem().
int Request::threadId () const [inline]
Accessor function for thread ID.
Definition at line 498 of file request.hh.
References _threadId, Flags< T >::isSet(), privateFlags, and VALID_THREAD_ID.
Referenced by DefaultFetch< Impl >::finishTranslation(), MipsISA::handleLockedRead(), MipsISA::handleLockedWrite(), BasePrefetcher::notify(), DefaultFetch< Impl >::processCacheCompletion(), LSQ< Impl >::read(), LSQ< Impl >::recvTimingResp(), and LSQ< Impl >::write().
Tick Request::time () const [inline]
Accessor for time.
Definition at line 389 of file request.hh.
References _time, Flags< T >::isSet(), privateFlags, VALID_PADDR, and VALID_VADDR.
Referenced by InorderBackEnd< Impl >::read(), and InorderBackEnd< Impl >::write().
void Request::time (Tick time) [inline]
Definition at line 396 of file request.hh.
References _time, Flags< T >::isSet(), privateFlags, VALID_PADDR, and VALID_VADDR.
Member Data Documentation
int Request::_asid [private]
The address space ID.
Definition at line 210 of file request.hh.
Referenced by getAsid(), setAsid(), and setVirt().
int Request::_contextId [private]
The context ID (for statistics, typically).
Definition at line 221 of file request.hh.
Referenced by contextId(), and setThreadContext().
uint64_t Request::_extraData [private]
Extra data for the request, such as the return value of store conditional or the compare value for a CAS.
Definition at line 218 of file request.hh.
Referenced by getExtraData(), and setExtraData().
Flags Request::_flags [private]
Flag structure for the request.
Definition at line 197 of file request.hh.
Referenced by getAsi(), getFlags(), isClearLL(), isCondSwap(), isInstFetch(), isLLSC(), isLocked(), isMmappedIpr(), isPrefetch(), isSwap(), isUncacheable(), setFlags(), setPhys(), and setVirt().
MasterID Request::_masterId [private]
The requestor ID which is unique in the system for all ports that are capable of issuing a transaction.
Definition at line 194 of file request.hh.
Referenced by masterId(), setPhys(), and setVirt().
Addr Request::_paddr [private]
The physical address of the request.
Valid only if validPaddr is set.
Definition at line 182 of file request.hh.
Referenced by getPaddr(), setPaddr(), and setPhys().
Addr Request::_pc [private]
program counter of initiating access; for tracing/debugging
Definition at line 226 of file request.hh.
Referenced by getPC(), Request(), and setVirt().
int Request::_size [private]
The size of the request.
This field must be set when vaddr or paddr is written via setVirt() or setPhys(), so it is always valid as long as one of the address fields is valid.
Definition at line 189 of file request.hh.
Referenced by getSize(), setPhys(), setVirt(), and splitOnVaddr().
int Request::_threadId [private]
The thread ID (id within this CPU).
Definition at line 223 of file request.hh.
Referenced by setThreadContext(), and threadId().
Tick Request::_time [private]
The time this request was started.
Used to calculate latencies. This field is set to curTick() any time paddr or vaddr is written.
Definition at line 207 of file request.hh.
Referenced by setPhys(), setVirt(), and time().
Addr Request::_vaddr [private]
The virtual address of the request.
Definition at line 213 of file request.hh.
Referenced by getVaddr(), setVirt(), and splitOnVaddr().
const FlagsType Request::ALTMODE = 0x00000800 [static]
Use the alternate mode bits in ALPHA.
Definition at line 100 of file request.hh.
Referenced by AlphaISA::TLB::translateData().
const FlagsType Request::ASI_BITS = 0x000000FF [static]
ASI information for this request if it exists.
Definition at line 92 of file request.hh.
Referenced by getAsi().
const FlagsType Request::CLEAR_LL = 0x00004000 [static]
This request is a clear exclusive.
Definition at line 106 of file request.hh.
Referenced by isClearLL(), and ArmISA::TLB::translateFs().
const FlagsType Request::EVICT_NEXT = 0x04000000 [static]
The request should be marked as LRU.
Definition at line 128 of file request.hh.
const MasterID Request::funcMasterId = 1 [static]
This request id is used for functional requests that don't come from a particular device.
Definition at line 141 of file request.hh.
Referenced by PortProxy::blobHelper(), CacheRecorder::enqueueNextFetchRequest(), CacheRecorder::enqueueNextFlushRequest(), MasterPort::printAddr(), RubyPort::ruby_eviction_callback(), and Cache< TagStore >::writebackVisitor().
const FlagsType Request::INST_FETCH = 0x00000100 [static]
The request was an instruction fetch.
Definition at line 94 of file request.hh.
Referenced by CacheRecorder::enqueueNextFetchRequest(), FetchUnit::execute(), DefaultFetch< Impl >::fetchCacheLine(), NetworkTest::generatePkt(), Check::initiateCheck(), Check::initiatePrefetch(), isInstFetch(), BaseSimpleCPU::setupFetchRequest(), and Checker< Impl >::verify().
const MasterID Request::intMasterId = 2 [static]
This request id is used for message signaled interrupts.
Definition at line 143 of file request.hh.
Referenced by X86ISA::prepIntRequest().
const MasterID Request::invldMasterId = USHRT_MAX [static]
Invalid request id for assertion checking only.
It is invalid behavior to ever send this id as part of a request.
Todo:
C++1x replace with numeric_limits when constexpr is added
Definition at line 147 of file request.hh.
Referenced by LRU::invalidate().
const uint32_t Request::invldPid = UINT_MAX [static]
Invalid or unknown Pid.
Possible when operating system is not present or has not assigned a pid yet
Definition at line 152 of file request.hh.
Referenced by LinuxArmSystem::startup().
const FlagsType Request::LLSC = 0x00200000 [static]
The request is a Load locked/store conditional.
Definition at line 118 of file request.hh.
Referenced by isLLSC().
const FlagsType Request::LOCKED = 0x00100000 [static]
This request will lock or unlock the accessed memory.
When used with a load, the access locks the particular chunk of memory. When used with a store, it unlocks. The rule is that locked accesses have to be made up of a locked load, some operation on the data, and then a locked store.
Definition at line 116 of file request.hh.
Referenced by isLocked().
const FlagsType Request::MEM_SWAP = 0x00400000 [static]
This request is for a memory swap.
Definition at line 120 of file request.hh.
Referenced by isSwap().
const FlagsType Request::MEM_SWAP_COND = 0x00800000 [static]
Definition at line 121 of file request.hh.
Referenced by isCondSwap(), and isSwap().
const FlagsType Request::MMAPPED_IPR = 0x00002000 [static]
This request is to a memory mapped register.
Definition at line 104 of file request.hh.
Referenced by isMmappedIpr(), and X86ISA::TLB::translateInt().
const FlagsType Request::NO_ACCESS = 0x00080000 [static]
The request should not cause a memory access.
Definition at line 109 of file request.hh.
Referenced by TimingSimpleCPU::buildSplitPacket(), TimingSimpleCPU::completeDataAccess(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), TimingSimpleCPU::sendData(), TimingSimpleCPU::sendSplitData(), and AtomicSimpleCPU::writeMem().
const FlagsType Request::PF_EXCLUSIVE = 0x02000000 [static]
The request should be prefetched into the exclusive state.
Definition at line 126 of file request.hh.
Referenced by Check::initiatePrefetch().
const FlagsType Request::PHYSICAL = 0x00000200 [static]
The virtual address is also the physical address.
Definition at line 96 of file request.hh.
Referenced by AlphaISA::TLB::translateData(), and AlphaISA::TLB::translateInst().
const FlagsType Request::PREFETCH = 0x01000000 [static]
The request is a prefetch.
Definition at line 124 of file request.hh.
Referenced by Check::initiatePrefetch(), AlphaISA::DtbFault::invoke(), and isPrefetch().
PrivateFlags Request::privateFlags [private]
Private flags for field validity checking.
Definition at line 200 of file request.hh.
Referenced by contextId(), extraDataValid(), getAsi(), getAsid(), getExtraData(), getFlags(), getPaddr(), getPC(), getSize(), getVaddr(), hasContextId(), hasPaddr(), hasPC(), hasSize(), Request(), setExtraData(), setFlags(), setPaddr(), setPhys(), setThreadContext(), setVirt(), splitOnVaddr(), threadId(), and time().
const FlagsType Request::STICKY_FLAGS = INST_FETCH [static]
These flags are *not* cleared when a Request object is reused (assigned a new address).
Definition at line 132 of file request.hh.
Referenced by setPhys(), and setVirt().
const PrivateFlagsType Request::STICKY_PRIVATE_FLAGS [static, private]
Initial value:
        VALID_CONTEXT_ID | VALID_THREAD_ID
These flags are *not* cleared when a Request object is reused (assigned a new address).
Definition at line 174 of file request.hh.
Referenced by setPhys(), and setVirt().
const FlagsType Request::UNCACHEABLE = 0x00001000 [static]
The request is to an uncacheable address.
Definition at line 102 of file request.hh.
Referenced by PowerISA::TLB::checkCacheability(), MipsISA::TLB::checkCacheability(), AlphaISA::TLB::checkCacheability(), Pl111::fillFifo(), isUncacheable(), X86ISA::prepIntRequest(), ArmISA::TableWalker::processWalk(), MemTest::tick(), X86ISA::TLB::translate(), ArmISA::TLB::translateFs(), and X86ISA::TLB::translateInt().
const PrivateFlagsType Request::VALID_CONTEXT_ID = 0x00000020 [static, private]
Whether or not the context ID is valid.
Definition at line 167 of file request.hh.
Referenced by contextId(), hasContextId(), and setThreadContext().
const PrivateFlagsType Request::VALID_EXTRA_DATA = 0x00000080 [static, private]
Whether or not the sc result is valid.
Definition at line 170 of file request.hh.
Referenced by extraDataValid(), getExtraData(), and setExtraData().
const PrivateFlagsType Request::VALID_PADDR = 0x00000002 [static, private]
Whether or not paddr is valid (has been written yet).
Definition at line 161 of file request.hh.
Referenced by getFlags(), getPaddr(), hasPaddr(), setFlags(), setPaddr(), setPhys(), splitOnVaddr(), and time().
const PrivateFlagsType Request::VALID_PC = 0x00000010 [static, private]
Whether or not the pc is valid.
Definition at line 165 of file request.hh.
Referenced by getPC(), hasPC(), Request(), and setVirt().
const PrivateFlagsType Request::VALID_SIZE = 0x00000001 [static, private]
Whether or not the size is valid.
Definition at line 159 of file request.hh.
Referenced by getSize(), hasSize(), setPhys(), and setVirt().
const PrivateFlagsType Request::VALID_THREAD_ID = 0x00000040 [static, private]
Definition at line 168 of file request.hh.
Referenced by setThreadContext(), and threadId().
const PrivateFlagsType Request::VALID_VADDR = 0x00000004 [static, private]
Whether or not the vaddr & asid are valid.
Definition at line 163 of file request.hh.
Referenced by getAsi(), getAsid(), getFlags(), getVaddr(), setFlags(), setPaddr(), setVirt(), splitOnVaddr(), and time().
const FlagsType Request::VPTE = 0x00000400 [static]
The request is an ALPHA VPTE pal access (hw_ld).
Definition at line 98 of file request.hh.
Referenced by AlphaISA::DtbFault::invoke(), and AlphaISA::TLB::translateData().
const MasterID Request::wbMasterId = 0 [static]
Request Ids that are statically allocated.
This request id is used for writeback requests by the caches
Definition at line 137 of file request.hh.
Referenced by Cache< TagStore >::writebackBlk().
The documentation for this class was generated from the following file:
mem/request.hh