gem5: Stats::StatStor Class Reference
Stats::StatStor Class Reference
Templatized storage and interface for a simple scalar stat.
#include <statistics.hh>
Classes
struct Params
Public Member Functions
StatStor (Info *info)
Builds this storage element and calls the base constructor of the datatype.
void set (Counter val)
The the stat to the given value.
void inc (Counter val)
Increment the stat by the given value.
void dec (Counter val)
Decrement the stat by the given value.
Counter value () const
Return the value of this stat as its base type.
Result result () const
Return the value of this stat as a result type.
void prepare (Info *info)
Prepare stat data for dumping or serialization.
void reset (Info *info)
Reset stat value to default.
bool zero () const
Private Attributes
Counter data
The statistic value.
Detailed Description
Templatized storage and interface for a simple scalar stat.
Definition at line 455 of file statistics.hh.
Constructor & Destructor Documentation
Stats::StatStor::StatStor (Info * info) [inline]
Builds this storage element and calls the base constructor of the datatype.
Definition at line 469 of file statistics.hh.
Member Function Documentation
void Stats::StatStor::dec (Counter val) [inline]
Decrement the stat by the given value.
Parameters:
val The new value.
Definition at line 487 of file statistics.hh.
References data.
Referenced by Stats::ScalarBase< Scalar, StatStor >::operator--(), and Stats::ScalarBase< Scalar, StatStor >::operator-=().
void Stats::StatStor::inc (Counter val) [inline]
Increment the stat by the given value.
Parameters:
val The new value.
Definition at line 482 of file statistics.hh.
References data.
Referenced by Stats::ScalarBase< Scalar, StatStor >::operator++(), and Stats::ScalarBase< Scalar, StatStor >::operator+=().
void Stats::StatStor::prepare (Info * info) [inline]
Prepare stat data for dumping or serialization.
Definition at line 501 of file statistics.hh.
Referenced by Stats::ScalarBase< Scalar, StatStor >::prepare().
void Stats::StatStor::reset (Info * info) [inline]
Reset stat value to default.
Definition at line 505 of file statistics.hh.
References data.
Referenced by Stats::ScalarBase< Scalar, StatStor >::reset().
Result Stats::StatStor::result () const [inline]
Return the value of this stat as a result type.
Returns:
The value of this stat.
Definition at line 497 of file statistics.hh.
References data.
Referenced by Stats::ScalarBase< Scalar, StatStor >::result().
void Stats::StatStor::set (Counter val) [inline]
The the stat to the given value.
Parameters:
val The new value.
Definition at line 477 of file statistics.hh.
References data, and X86ISA::val.
Referenced by Stats::ScalarBase< Scalar, StatStor >::operator=().
Counter Stats::StatStor::value () const [inline]
Return the value of this stat as its base type.
Returns:
The value of this stat.
Definition at line 492 of file statistics.hh.
References data.
Referenced by Stats::ScalarBase< Scalar, StatStor >::value().
bool Stats::StatStor::zero () const [inline]
Returns:
true if zero value
Definition at line 510 of file statistics.hh.
References data.
Member Data Documentation
Counter Stats::StatStor::data [private]
The statistic value.
Definition at line 459 of file statistics.hh.
Referenced by dec(), inc(), reset(), result(), set(), value(), and zero().
The documentation for this class was generated from the following file:
base/statistics.hh