gem5: SimpleDRAM Class Reference
SimpleDRAM Class Reference
The simple DRAM is a basic single-channel memory controller aiming to mimic a high-level DRAM controller and the most important timing constraints associated with the DRAM.
#include <simple_dram.hh>