gem5: CheckTable Class Reference
CheckTable Class Reference
#include <CheckTable.hh>
Public Member Functions
CheckTable (int _num_writers, int _num_readers, RubyTester *_tester)
~CheckTable ()
Check * getRandomCheck ()
Check * getCheck (const Address &address)
void print (std::ostream &out) const
Private Member Functions
void addCheck (const Address &address)
CheckTable (const CheckTable &obj)
CheckTable & operator= (const CheckTable &obj)
Private Attributes
std::vector< Check * > m_check_vector
m5::hash_map< Address, Check * > m_lookup_map
int m_num_writers
int m_num_readers
RubyTester * m_tester_ptr
Detailed Description
Definition at line 43 of file CheckTable.hh.
Constructor & Destructor Documentation
CheckTable::CheckTable (int _num_writers, int _num_readers, RubyTester * _tester)
Definition at line 35 of file CheckTable.cc.
References addCheck(), CHECK_SIZE, ArmISA::i, and Address::setAddress().
CheckTable::~CheckTable ()
Definition at line 73 of file CheckTable.cc.
References ArmISA::i, and m_check_vector.
CheckTable::CheckTable (const CheckTable & obj) [private]
Member Function Documentation
void CheckTable::addCheck (const Address & address) [private]
Definition at line 81 of file CheckTable.cc.
References Address::bitSelect(), CHECK_SIZE, CHECK_SIZE_BITS, floorLog2(), Address::getAddress(), ArmISA::i, m_check_vector, m_lookup_map, m_num_readers, m_num_writers, m_tester_ptr, and panic.
Referenced by CheckTable().
Check * CheckTable::getCheck (const Address & address)
Definition at line 114 of file CheckTable.cc.
References DPRINTF, ArmISA::i, and m_lookup_map.
Referenced by RubyTester::hitCallback().
Check * CheckTable::getRandomCheck ()
Definition at line 107 of file CheckTable.cc.
References m_check_vector, and random().
Referenced by RubyTester::wakeup().
CheckTable& CheckTable::operator= (const CheckTable & obj) [private]
void CheckTable::print (std::ostream & out) const
Definition at line 129 of file CheckTable.cc.
Referenced by operator<<().
Member Data Documentation
std::vector<Check*> CheckTable::m_check_vector [private]
Definition at line 66 of file CheckTable.hh.
Referenced by addCheck(), getRandomCheck(), and ~CheckTable().
m5::hash_map<Address, Check*> CheckTable::m_lookup_map [private]
Definition at line 67 of file CheckTable.hh.
Referenced by addCheck(), and getCheck().
int CheckTable::m_num_readers [private]
Definition at line 70 of file CheckTable.hh.
Referenced by addCheck().
int CheckTable::m_num_writers [private]
Definition at line 69 of file CheckTable.hh.
Referenced by addCheck().
RubyTester* CheckTable::m_tester_ptr [private]
Definition at line 71 of file CheckTable.hh.
Referenced by addCheck().
The documentation for this class was generated from the following files:
cpu/testers/rubytest/CheckTable.hh
cpu/testers/rubytest/CheckTable.cc