gem5: SyscallDesc Class Reference
SyscallDesc Class Reference
System call descriptor.
#include <syscall_emul.hh>
Public Types
enum Flags { SuppressReturnValue = 1 }
Flag values for controlling syscall behavior.
typedef SyscallReturn(* FuncPtr)(SyscallDesc *, int num, LiveProcess *, ThreadContext *)
Typedef for target syscall handler functions.
Public Member Functions
SyscallDesc (const char *_name, FuncPtr _funcPtr, int _flags=0)
Constructor.
void doSyscall (int callnum, LiveProcess *proc, ThreadContext *tc)
Emulate the syscall. Public interface for calling through funcPtr.
Public Attributes
const char * name
Syscall name (e.g., "open").
FuncPtr funcPtr
Pointer to emulation function.
int flags
Flags (see Flags enum).
Detailed Description
System call descriptor.
Definition at line 75 of file syscall_emul.hh.
Member Typedef Documentation
typedef SyscallReturn(* SyscallDesc::FuncPtr)(SyscallDesc *, int num, LiveProcess *, ThreadContext *)
Typedef for target syscall handler functions.
Definition at line 80 of file syscall_emul.hh.
Member Enumeration Documentation
enum SyscallDesc::Flags
Flag values for controlling syscall behavior.
Enumerator:
SuppressReturnValue
Don't set return regs according to funcPtr return value.
Used for syscalls with non-standard return conventions that explicitly set the ThreadContext regs (e.g., sigreturn).
Definition at line 88 of file syscall_emul.hh.
Constructor & Destructor Documentation
SyscallDesc::SyscallDesc (const char * _name, FuncPtr _funcPtr, int _flags = 0) [inline]
Constructor.
Definition at line 97 of file syscall_emul.hh.
Member Function Documentation
void SyscallDesc::doSyscall (int callnum, LiveProcess * proc, ThreadContext * tc)
Emulate the syscall. Public interface for calling through funcPtr.
Definition at line 56 of file syscall_emul.cc.
References curTick(), DPRINTFR, flags, ThreadContext::getCpuPtr(), LiveProcess::getSyscallArg(), MipsISA::index, name, SimObject::name(), and SuppressReturnValue.
Referenced by Tru64::indirectSyscallFunc(), and LiveProcess::syscall().
Member Data Documentation
int SyscallDesc::flags
Flags (see Flags enum).
Definition at line 85 of file syscall_emul.hh.
Referenced by doSyscall().
FuncPtr SyscallDesc::funcPtr
Pointer to emulation function.
Definition at line 84 of file syscall_emul.hh.
const char* SyscallDesc::name
Syscall name (e.g., "open").
Definition at line 83 of file syscall_emul.hh.
Referenced by doSyscall(), ignoreFunc(), ignoreWarnOnceFunc(), setThreadArea32Func(), and unimplementedFunc().
The documentation for this class was generated from the following files:
sim/syscall_emul.hh
sim/syscall_emul.cc