gem5: SyscallReturn Class Reference
SyscallReturn Class Reference
#include <syscallreturn.hh>
Public Member Functions
template<class T >
SyscallReturn (T v, bool s)
template<class T >
SyscallReturn (T v)
~SyscallReturn ()
SyscallReturn & operator= (const SyscallReturn &s)
bool successful ()
uint64_t value ()
Private Attributes
uint64_t retval
bool success
Detailed Description
Definition at line 36 of file syscallreturn.hh.
Constructor & Destructor Documentation
template<class T > SyscallReturn::SyscallReturn (T v, bool s) [inline]
Definition at line 40 of file syscallreturn.hh.
References retval, and success.
template<class T > SyscallReturn::SyscallReturn (T v) [inline]
Definition at line 47 of file syscallreturn.hh.
References retval, and success.
SyscallReturn::~SyscallReturn () [inline]
Definition at line 53 of file syscallreturn.hh.
Member Function Documentation
SyscallReturn& SyscallReturn::operator= (const SyscallReturn & s) [inline]
Definition at line 55 of file syscallreturn.hh.
References retval, and success.
bool SyscallReturn::successful () [inline]
Definition at line 62 of file syscallreturn.hh.
References success.
Referenced by SparcLiveProcess::setSyscallReturn(), PowerLiveProcess::setSyscallReturn(), MipsLiveProcess::setSyscallReturn(), and AlphaLiveProcess::setSyscallReturn().
uint64_t SyscallReturn::value () [inline]
Definition at line 63 of file syscallreturn.hh.
References retval.
Referenced by X86ISA::X86LiveProcess::setSyscallReturn(), SparcLiveProcess::setSyscallReturn(), PowerLiveProcess::setSyscallReturn(), MipsLiveProcess::setSyscallReturn(), ArmLiveProcess::setSyscallReturn(), and AlphaLiveProcess::setSyscallReturn().
Member Data Documentation
uint64_t SyscallReturn::retval [private]
Definition at line 66 of file syscallreturn.hh.
Referenced by operator=(), SyscallReturn(), and value().
bool SyscallReturn::success [private]
Definition at line 67 of file syscallreturn.hh.
Referenced by operator=(), successful(), and SyscallReturn().
The documentation for this class was generated from the following file:
sim/syscallreturn.hh