gem5: RoutingUnit_d Class Reference
RoutingUnit_d Class Reference
#include <RoutingUnit_d.hh>
Public Member Functions
RoutingUnit_d (Router_d *router)
void addRoute (const NetDest &routing_table_entry)
int routeCompute (flit_d *t_flit)
void addWeight (int link_weight)
void RC_stage (flit_d *t_flit, InputUnit_d *in_unit, int invc)
Private Attributes
Router_d * m_router
std::vector< NetDest > m_routing_table
std::vector< int > m_weight_table
Detailed Description
Definition at line 42 of file RoutingUnit_d.hh.
Constructor & Destructor Documentation
RoutingUnit_d::RoutingUnit_d (Router_d * router)
Definition at line 37 of file RoutingUnit_d.cc.
References m_router, m_routing_table, and m_weight_table.
Member Function Documentation
void RoutingUnit_d::addRoute (const NetDest & routing_table_entry)
Definition at line 45 of file RoutingUnit_d.cc.
References m_routing_table.
Referenced by Router_d::addOutPort().
void RoutingUnit_d::addWeight (int link_weight)
Definition at line 51 of file RoutingUnit_d.cc.
References m_weight_table.
Referenced by Router_d::addOutPort().
void RoutingUnit_d::RC_stage (flit_d * t_flit, InputUnit_d * in_unit, int invc)
Definition at line 57 of file RoutingUnit_d.cc.
References flit_d::advance_stage(), ClockedObject::curCycle(), m_router, routeCompute(), InputUnit_d::updateRoute(), VA_, and Router_d::vcarb_req().
Referenced by Router_d::route_req().
int RoutingUnit_d::routeCompute (flit_d * t_flit)
Definition at line 66 of file RoutingUnit_d.cc.
References X86ISA::exit, fatal, RefCountingPtr< T >::get(), flit_d::get_msg_ptr(), NetworkMessage::getInternalDestination(), m_routing_table, m_weight_table, and safe_cast().
Referenced by RC_stage().
Member Data Documentation
Router_d* RoutingUnit_d::m_router [private]
Definition at line 52 of file RoutingUnit_d.hh.
Referenced by RC_stage(), and RoutingUnit_d().
std::vector<NetDest> RoutingUnit_d::m_routing_table [private]
Definition at line 53 of file RoutingUnit_d.hh.
Referenced by addRoute(), routeCompute(), and RoutingUnit_d().
std::vector<int> RoutingUnit_d::m_weight_table [private]
Definition at line 54 of file RoutingUnit_d.hh.
Referenced by addWeight(), routeCompute(), and RoutingUnit_d().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet/fixed-pipeline/RoutingUnit_d.hh
mem/ruby/network/garnet/fixed-pipeline/RoutingUnit_d.cc