gem5: OrionConfig Class Reference
OrionConfig Class Reference
#include <OrionConfig.hh>
Classes
struct key_not_found
Public Member Functions
OrionConfig (const string &cfg_fn_)
OrionConfig (const OrionConfig &orion_cfg_)
~OrionConfig ()
void set_num_in_port (uint32_t num_in_port_)
void set_num_out_port (uint32_t num_out_port_)
void set_num_vclass (uint32_t num_vclass_)
void set_num_vchannel (uint32_t num_vchannel_)
void set_in_buf_num_set (uint32_t in_buf_num_set_)
void set_flit_width (uint32_t flit_width_)
void read_file (const std::string &filename_)
void print_config (std::ostream &out_)
template<class T >
T get (const std::string &key_) const
const TechParameter * get_tech_param_ptr () const
uint32_t get_num_in_port () const
uint32_t get_num_out_port () const
uint32_t get_num_vclass () const
uint32_t get_num_vchannel () const
uint32_t get_in_buf_num_set () const
uint32_t get_flit_width () const
template<class T >
T get (const string &key_) const
template<class T >
T string_as_T (const string &str_)
Protected Member Functions
template<>
string string_as_T (const string &str_)
template<>
bool string_as_T (const string &str_)
Static Protected Member Functions
template<class T >
static T string_as_T (const std::string &str_)
template<class T >
static std::string T_as_string (const T &t_)
Private Attributes
std::map< std::string,
std::string > m_params_map
TechParameter * m_tech_param_ptr
uint32_t m_num_in_port
uint32_t m_num_out_port
uint32_t m_num_vclass
uint32_t m_num_vchannel
uint32_t m_in_buf_num_set
uint32_t m_flit_width
Static Private Attributes
static std::string ms_param_name []
Detailed Description
Definition at line 42 of file OrionConfig.hh.
Constructor & Destructor Documentation
OrionConfig::OrionConfig (const string & cfg_fn_)
Definition at line 97 of file OrionConfig.cc.
References ArmISA::i, m_params_map, m_tech_param_ptr, ms_param_name, and read_file().
OrionConfig::OrionConfig (const OrionConfig & orion_cfg_)
Definition at line 110 of file OrionConfig.cc.
References m_flit_width, m_in_buf_num_set, m_num_in_port, m_num_out_port, m_num_vchannel, m_num_vclass, m_params_map, and m_tech_param_ptr.
OrionConfig::~OrionConfig ()
Definition at line 123 of file OrionConfig.cc.
References m_tech_param_ptr.
Member Function Documentation
template<class T > T OrionConfig::get (const std::string & key_) const
Referenced by NetworkLink_d::calculate_power(), Router_d::calculate_power(), Crossbar::create_crossbar(), SWAllocator::create_swallocator(), VCAllocator::create_vcallocator(), OrionRouter::init(), OrionLink::init(), Clock::init(), Buffer::init(), OrionRouter::OrionRouter(), and TechParameter::TechParameter().
template<class T > T OrionConfig::get (const string & key_) const
Definition at line 99 of file OrionConfig.hh.
References m_params_map.
uint32_t OrionConfig::get_flit_width () const [inline]
Definition at line 69 of file OrionConfig.hh.
References m_flit_width.
Referenced by Clock::init().
uint32_t OrionConfig::get_in_buf_num_set () const [inline]
Definition at line 68 of file OrionConfig.hh.
References m_in_buf_num_set.
uint32_t OrionConfig::get_num_in_port () const [inline]
Definition at line 64 of file OrionConfig.hh.
References m_num_in_port.
Referenced by Clock::init().
uint32_t OrionConfig::get_num_out_port () const [inline]
Definition at line 65 of file OrionConfig.hh.
References m_num_out_port.
Referenced by Clock::init().
uint32_t OrionConfig::get_num_vchannel () const [inline]
Definition at line 67 of file OrionConfig.hh.
References m_num_vchannel.
Referenced by Clock::init().
uint32_t OrionConfig::get_num_vclass () const [inline]
Definition at line 66 of file OrionConfig.hh.
References m_num_vclass.
Referenced by Clock::init().
const TechParameter* OrionConfig::get_tech_param_ptr () const [inline]
Definition at line 63 of file OrionConfig.hh.
References m_tech_param_ptr.
Referenced by Buffer::Buffer(), Crossbar::create_crossbar(), SWAllocator::create_swallocator(), VCAllocator::create_vcallocator(), OrionLink::init(), and Clock::init().
void OrionConfig::print_config (std::ostream & out_)
void OrionConfig::read_file (const std::string & filename_)
Referenced by OrionConfig().
void OrionConfig::set_flit_width (uint32_t flit_width_)
Definition at line 163 of file OrionConfig.cc.
References m_flit_width, and m_params_map.
Referenced by OrionRouter::OrionRouter().
void OrionConfig::set_in_buf_num_set (uint32_t in_buf_num_set_)
Definition at line 156 of file OrionConfig.cc.
References m_in_buf_num_set, and m_params_map.
void OrionConfig::set_num_in_port (uint32_t num_in_port_)
Definition at line 128 of file OrionConfig.cc.
References m_num_in_port, and m_params_map.
Referenced by OrionRouter::OrionRouter().
void OrionConfig::set_num_out_port (uint32_t num_out_port_)
Definition at line 135 of file OrionConfig.cc.
References m_num_out_port, and m_params_map.
Referenced by OrionRouter::OrionRouter().
void OrionConfig::set_num_vchannel (uint32_t num_vchannel_)
Definition at line 149 of file OrionConfig.cc.
References m_num_vchannel, and m_params_map.
void OrionConfig::set_num_vclass (uint32_t num_vclass_)
Definition at line 142 of file OrionConfig.cc.
References m_num_vclass, and m_params_map.
Referenced by OrionRouter::OrionRouter().
template<> bool OrionConfig::string_as_T (const string & str_) [inline, protected]
template<class T > T OrionConfig::string_as_T (const string & str_)
Definition at line 113 of file OrionConfig.hh.
template<class T > static T OrionConfig::string_as_T (const std::string & str_) [static, protected]
template<> string OrionConfig::string_as_T (const string & str_) [inline, protected]
template<class T > string OrionConfig::T_as_string (const T & t_) [static, protected]
Definition at line 149 of file OrionConfig.hh.
Member Data Documentation
uint32_t OrionConfig::m_flit_width [private]
Definition at line 80 of file OrionConfig.hh.
Referenced by get_flit_width(), OrionConfig(), and set_flit_width().
uint32_t OrionConfig::m_in_buf_num_set [private]
Definition at line 79 of file OrionConfig.hh.
Referenced by get_in_buf_num_set(), OrionConfig(), and set_in_buf_num_set().
uint32_t OrionConfig::m_num_in_port [private]
Definition at line 75 of file OrionConfig.hh.
Referenced by get_num_in_port(), OrionConfig(), and set_num_in_port().
uint32_t OrionConfig::m_num_out_port [private]
Definition at line 76 of file OrionConfig.hh.
Referenced by get_num_out_port(), OrionConfig(), and set_num_out_port().
uint32_t OrionConfig::m_num_vchannel [private]
Definition at line 78 of file OrionConfig.hh.
Referenced by get_num_vchannel(), OrionConfig(), and set_num_vchannel().
uint32_t OrionConfig::m_num_vclass [private]
Definition at line 77 of file OrionConfig.hh.
Referenced by get_num_vclass(), OrionConfig(), and set_num_vclass().
std::map<std::string, std::string> OrionConfig::m_params_map [private]
Definition at line 72 of file OrionConfig.hh.
Referenced by get(), OrionConfig(), set_flit_width(), set_in_buf_num_set(), set_num_in_port(), set_num_out_port(), set_num_vchannel(), and set_num_vclass().
TechParameter* OrionConfig::m_tech_param_ptr [private]
Definition at line 74 of file OrionConfig.hh.
Referenced by get_tech_param_ptr(), OrionConfig(), and ~OrionConfig().
string OrionConfig::ms_param_name [static, private]
Definition at line 95 of file OrionConfig.hh.
Referenced by OrionConfig().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/OrionConfig.hh
mem/ruby/network/orion/OrionConfig.cc