gem5: MemObject Class Reference
MemObject Class Reference
The MemObject class extends the ClockedObject with accessor functions to get its master and slave ports.
#include <mem_object.hh>