gem5: PowerLiveProcess Class Reference
PowerLiveProcess Class Reference
#include <process.hh>