gem5: ResourcePool Class Reference
ResourcePool Class Reference
#include <resource_pool.hh>
Classes
class ResPoolEvent
Public Types
enum ResPoolEventType { InstGraduated = InOrderCPU::NumCPUEvents, SquashAll, UpdateAfterContextSwitch, Default }
enum ResPoolEventPri { ResPool_Pri = InOrderCPU::InOrderCPU_Pri - 5, ResGrad_Pri, ResSquash_Pri }
typedef InOrderDynInst::DynInstPtr DynInstPtr
Public Member Functions
ResourcePool (InOrderCPU *_cpu, ThePipeline::Params *params)
virtual ~ResourcePool ()
std::string name ()
std::string name (int res_idx)
void init ()
void print ()
void regStats ()
Register Statistics in All Resources.
unsigned getResIdx (const ThePipeline::ResourceId &res_id)
Returns a specific resource.
Resource * getResource (int res_idx)
Returns a pointer to a resource.
ResReqPtr request (int res_idx, DynInstPtr inst)
Request usage of this resource.
void squash (DynInstPtr inst, int res_idx, InstSeqNum done_seq_num, ThreadID tid)
Squash The Resource.
void squashAll (DynInstPtr inst, int stage_num, InstSeqNum done_seq_num, ThreadID tid)
Squash All Resources in Pool after Done Seq.
void squashDueToMemStall (DynInstPtr inst, int stage_num, InstSeqNum done_seq_num, ThreadID tid)
Squash Resources in Pool after a memory stall NOTE: Only use during Switch-On-Miss Thread model.
void activateThread (ThreadID tid)
Activate Thread in all resources.
void deactivateThread (ThreadID tid)
De-Activate Thread in all resources.
void suspendThread (ThreadID tid)
Suspend Thread in all resources.
void updateAfterContextSwitch (DynInstPtr inst, ThreadID tid)
Broadcast Context Switch Update to all resources.
void instGraduated (InstSeqNum seq_num, ThreadID tid)
Broadcast graduation to all resources.
void trap (Fault fault, ThreadID tid, DynInstPtr inst)
Broadcast trap to all resources.
int slotsAvail (int res_idx)
The number of instructions available that a resource can can still process.
int slotsInUse (int res_idx)
The number of instructions using a resource.
void scheduleEvent (InOrderCPU::CPUEventType e_type, DynInstPtr inst=NULL, Cycles delay=Cycles(0), int res_idx=0, ThreadID tid=0)
Schedule resource event, regardless of its current state.
void unscheduleEvent (int res_idx, DynInstPtr inst)
UnSchedule resource event, regardless of its current state.
virtual void startup ()
Tasks to perform when simulation starts.
FetchUnit * getInstUnit () const
Get a pointer to the (always present) instruction fetch unit.
CacheUnit * getDataUnit () const
Get a pointer to the (always present) data load/store unit.
Public Attributes
InOrderCPU * cpu
The CPU(s) that this resource interacts with.
DynInstPtr dummyInst [ThePipeline::MaxThreads]
Private Attributes
FetchUnit * instUnit
The instruction fetch unit.
CacheUnit * dataUnit
The data load/store unit.
std::vector< Resource * > resources
std::vector< int > gradObjects
Resources that need to be updated on an inst.
Detailed Description
Definition at line 64 of file resource_pool.hh.
Member Typedef Documentation
typedef InOrderDynInst::DynInstPtr ResourcePool::DynInstPtr
Definition at line 66 of file resource_pool.hh.
Member Enumeration Documentation
enum ResourcePool::ResPoolEventPri
Enumerator:
ResPool_Pri
ResGrad_Pri
ResSquash_Pri
Definition at line 80 of file resource_pool.hh.
enum ResourcePool::ResPoolEventType
Enumerator:
InstGraduated
SquashAll
UpdateAfterContextSwitch
Default
Definition at line 73 of file resource_pool.hh.
Constructor & Destructor Documentation
ResourcePool::ResourcePool (InOrderCPU * _cpu, ThePipeline::Params * params)
Definition at line 54 of file resource_pool.cc.
References ThePipeline::AGEN, ThePipeline::BPred, cpu, dataUnit, ThePipeline::DCache, ThePipeline::Decode, ThePipeline::ExecUnit, ThePipeline::FetchBuff, ThePipeline::FetchBuff2, ThePipeline::FetchSeq, ThePipeline::Grad, gradObjects, ThePipeline::ICache, instUnit, ThePipeline::MaxThreads, ThePipeline::MDU, ThePipeline::RegManager, resources, and InOrderCPU::stageWidth.
ResourcePool::~ResourcePool () [virtual]
Definition at line 121 of file resource_pool.cc.
References DPRINTF, ArmISA::i, name(), and resources.
Member Function Documentation
void ResourcePool::activateThread (ThreadID tid)
Activate Thread in all resources.
Definition at line 341 of file resource_pool.cc.
References InOrderCPU::activeThreadId(), cpu, DPRINTF, InOrderCPU::numActiveThreads(), resources, InOrderCPU::SwitchOnCacheMiss, and InOrderCPU::threadModel.
Referenced by InOrderCPU::activateNextReadyThread(), and InOrderCPU::CPUEvent::process().
void ResourcePool::deactivateThread (ThreadID tid)
De-Activate Thread in all resources.
Definition at line 364 of file resource_pool.cc.
References DPRINTF, and resources.
Referenced by InOrderCPU::CPUEvent::process().
CacheUnit* ResourcePool::getDataUnit () const [inline]
Get a pointer to the (always present) data load/store unit.
Returns:
the data cache unit
Definition at line 234 of file resource_pool.hh.
References dataUnit.
Referenced by InOrderCPU::getDTBPtr(), InOrderCPU::read(), and InOrderCPU::write().
FetchUnit* ResourcePool::getInstUnit () const [inline]
Get a pointer to the (always present) instruction fetch unit.
Returns:
the instruction unit
Definition at line 227 of file resource_pool.hh.
References instUnit.
Referenced by InOrderCPU::getDecoderPtr(), and InOrderCPU::getITBPtr().
unsigned ResourcePool::getResIdx (const ThePipeline::ResourceId & res_id)
Returns a specific resource.
Definition at line 174 of file resource_pool.cc.
References Resource::getId(), panic, and resources.
Referenced by CacheUnit::write().
Resource* ResourcePool::getResource (int res_idx) [inline]
Returns a pointer to a resource.
Definition at line 159 of file resource_pool.hh.
References resources.
void ResourcePool::init ()
Definition at line 115 of file resource_pool.9stage.cc.
References ArmISA::i, and resources.
Referenced by InOrderCPU::init().
void ResourcePool::instGraduated (InstSeqNum seq_num, ThreadID tid)
Broadcast graduation to all resources.
Definition at line 292 of file resource_pool.9stage.cc.
References DPRINTF, and resources.
Referenced by ResourcePool::ResPoolEvent::process().
std::string ResourcePool::name (int res_idx) [inline]
Definition at line 146 of file resource_pool.hh.
References resources.
string ResourcePool::name ()
Definition at line 123 of file resource_pool.9stage.cc.
References cpu, and SimObject::name().
Referenced by print(), PipelineStage::processInstSchedule(), and ~ResourcePool().
void ResourcePool::print ()
Definition at line 151 of file resource_pool.cc.
References DPRINTF, ArmISA::i, name(), and resources.
void ResourcePool::regStats ()
Register Statistics in All Resources.
Definition at line 130 of file resource_pool.9stage.cc.
References DPRINTF, and resources.
Referenced by InOrderCPU::regStats().
ResReqPtr ResourcePool::request (int res_idx, DynInstPtr inst)
Request usage of this resource.
Returns -1 if not granted and a positive request tag if granted.
Definition at line 142 of file resource_pool.9stage.cc.
References resources.
Referenced by PipelineStage::processInstSchedule().
void ResourcePool::scheduleEvent (InOrderCPU::CPUEventType e_type, DynInstPtr inst = NULL, Cycles delay = Cycles(0), int res_idx = 0, ThreadID tid = 0)
Schedule resource event, regardless of its current state.
Definition at line 239 of file resource_pool.cc.
References ClockedObject::clockEdge(), cpu, curTick(), DPRINTF, InOrderCPU::eventNames, InstGraduated, EventManager::schedule(), SquashAll, and UpdateAfterContextSwitch.
Referenced by PipelineStage::activateThread(), InOrderCPU::checkForInterrupts(), InOrderCPU::scheduleCpuEvent(), Resource::setupSquash(), and InOrderCPU::syscallContext().
int ResourcePool::slotsAvail (int res_idx)
The number of instructions available that a resource can can still process.
Definition at line 158 of file resource_pool.9stage.cc.
References resources.
int ResourcePool::slotsInUse (int res_idx)
The number of instructions using a resource.
Definition at line 164 of file resource_pool.9stage.cc.
References resources.
void ResourcePool::squash (DynInstPtr inst, int res_idx, InstSeqNum done_seq_num, ThreadID tid)
Squash The Resource.
Definition at line 151 of file resource_pool.9stage.cc.
References ThePipeline::NumStages, and resources.
void ResourcePool::squashAll (DynInstPtr inst, int stage_num, InstSeqNum done_seq_num, ThreadID tid)
Squash All Resources in Pool after Done Seq.
Num
Definition at line 252 of file resource_pool.9stage.cc.
References DPRINTF, and resources.
Referenced by ResourcePool::ResPoolEvent::process().
void ResourcePool::squashDueToMemStall (DynInstPtr inst, int stage_num, InstSeqNum done_seq_num, ThreadID tid)
Squash Resources in Pool after a memory stall NOTE: Only use during Switch-On-Miss Thread model.
Definition at line 325 of file resource_pool.cc.
References DPRINTF, and resources.
Referenced by InOrderCPU::CPUEvent::process().
virtual void ResourcePool::startup () [inline, virtual]
Tasks to perform when simulation starts.
Definition at line 215 of file resource_pool.hh.
void ResourcePool::suspendThread (ThreadID tid)
Suspend Thread in all resources.
Definition at line 377 of file resource_pool.cc.
References DPRINTF, and resources.
Referenced by InOrderCPU::CPUEvent::process().
void ResourcePool::trap (Fault fault, ThreadID tid, DynInstPtr inst)
Broadcast trap to all resources.
Definition at line 209 of file resource_pool.cc.
References DPRINTF, and resources.
Referenced by InOrderCPU::CPUEvent::process().
void ResourcePool::unscheduleEvent (int res_idx, DynInstPtr inst)
UnSchedule resource event, regardless of its current state.
Definition at line 246 of file resource_pool.9stage.cc.
References resources.
void ResourcePool::updateAfterContextSwitch (DynInstPtr inst, ThreadID tid)
Broadcast Context Switch Update to all resources.
Definition at line 403 of file resource_pool.cc.
References DPRINTF, and resources.
Member Data Documentation
InOrderCPU* ResourcePool::cpu
The CPU(s) that this resource interacts with.
Definition at line 218 of file resource_pool.hh.
Referenced by activateThread(), name(), ResourcePool::ResPoolEvent::process(), ResourcePool(), ResourcePool::ResPoolEvent::scheduleEvent(), and scheduleEvent().
CacheUnit* ResourcePool::dataUnit [private]
The data load/store unit.
Definition at line 242 of file resource_pool.hh.
Referenced by getDataUnit(), and ResourcePool().
DynInstPtr ResourcePool::dummyInst[ThePipeline::MaxThreads]
Definition at line 220 of file resource_pool.hh.
std::vector<int> ResourcePool::gradObjects [private]
Resources that need to be updated on an inst.
graduation
Definition at line 247 of file resource_pool.hh.
Referenced by ResourcePool().
FetchUnit* ResourcePool::instUnit [private]
The instruction fetch unit.
Definition at line 239 of file resource_pool.hh.
Referenced by getInstUnit(), and ResourcePool().
std::vector<Resource *> ResourcePool::resources [private]
Definition at line 244 of file resource_pool.hh.
Referenced by activateThread(), deactivateThread(), getResIdx(), getResource(), init(), instGraduated(), name(), print(), regStats(), request(), ResourcePool(), slotsAvail(), slotsInUse(), squash(), squashAll(), squashDueToMemStall(), suspendThread(), trap(), unscheduleEvent(), updateAfterContextSwitch(), and ~ResourcePool().
The documentation for this class was generated from the following files:
cpu/inorder/resource_pool.hh
cpu/inorder/resource_pool.9stage.cc
cpu/inorder/resource_pool.cc