gem5: FreebsdAlphaSystem Class Reference
FreebsdAlphaSystem Class Reference
#include <system.hh>