gem5: AddrRange Class Reference
AddrRange Class Reference
#include <addr_range.hh>
Public Member Functions
AddrRange ()
AddrRange (Addr _start, Addr _end, uint8_t _intlv_high_bit, uint8_t _intlv_bits, uint8_t _intlv_match)
AddrRange (Addr _start, Addr _end)
AddrRange (const std::vector< AddrRange > &ranges)
Create an address range by merging a collection of interleaved ranges.
bool interleaved () const
Determine if the range is interleaved or not.
uint64_t granularity () const
Determing the interleaving granularity of the range.
uint32_t stripes () const
Determine the number of interleaved address stripes this range is part of.
Addr size () const
Get the size of the address range.
bool valid () const
Determine if the range is valid.
Addr start () const
Get the start address of the range.
std::string to_string () const
Get a string representation of the range.
bool mergesWith (const AddrRange &r) const
Determine if another range merges with the current one, i.e.
bool intersects (const AddrRange &r) const
Determine if another range intersects this one, i.e.
bool isSubset (const AddrRange &r) const
Determine if this range is a subset of another range, i.e.
bool contains (const Addr &a) const
Determine if the range contains an address.
bool operator< (const AddrRange &r) const
Keep the operators away from SWIG.
Private Attributes
Addr _start
Private fields for the start and end of the range.
Addr _end
uint8_t intlvHighBit
The high bit of the slice that is used for interleaving.
uint8_t intlvBits
The number of bits used for interleaving, set to 0 to disable.
uint8_t intlvMatch
The value to compare the slice addr[high:(high - bits + 1)] with.
Detailed Description
Definition at line 55 of file addr_range.hh.
Constructor & Destructor Documentation
AddrRange::AddrRange () [inline]
Definition at line 76 of file addr_range.hh.
AddrRange::AddrRange (Addr _start, Addr _end, uint8_t _intlv_high_bit, uint8_t _intlv_bits, uint8_t _intlv_match) [inline]
Definition at line 80 of file addr_range.hh.
AddrRange::AddrRange (Addr _start, Addr _end) [inline]
Definition at line 86 of file addr_range.hh.
AddrRange::AddrRange (const std::vector< AddrRange > & ranges) [inline]
Create an address range by merging a collection of interleaved ranges.
Parameters:
ranges Interleaved ranges to be merged
Definition at line 97 of file addr_range.hh.
References _end, _start, fatal, intlvBits, intlvHighBit, mergesWith(), MipsISA::r, and ULL.
Member Function Documentation
bool AddrRange::contains (const Addr & a) const [inline]
Determine if the range contains an address.
Parameters:
a Address to compare with
Returns:
true if the address is in the range
Definition at line 259 of file addr_range.hh.
References _end, _start, bits(), interleaved(), intlvBits, intlvHighBit, and intlvMatch.
Referenced by BaseBus::findPort(), intersects(), and PhysicalMemory::isMemAddr().
uint64_t AddrRange::granularity () const [inline]
Determing the interleaving granularity of the range.
Returns:
The size of the regions created by the interleaving bits
Definition at line 143 of file addr_range.hh.
References intlvBits, intlvHighBit, and ULL.
Referenced by SimpleDRAM::init().
bool AddrRange::interleaved () const [inline]
Determine if the range is interleaved or not.
Returns:
true if interleaved
Definition at line 136 of file addr_range.hh.
References intlvBits.
Referenced by contains(), PhysicalMemory::createBackingStore(), SimpleDRAM::init(), intersects(), isSubset(), and to_string().
bool AddrRange::intersects (const AddrRange & r) const [inline]
Determine if another range intersects this one, i.e.
if there is an address that is both in this range and the other range. No check is made to ensure either range is valid.
Parameters:
r Range to intersect with
Returns:
true if the intersection of the two ranges is not empty
Definition at line 214 of file addr_range.hh.
References _end, _start, contains(), interleaved(), intlvMatch, mergesWith(), panic, size(), start(), and to_string().
bool AddrRange::isSubset (const AddrRange & r) const [inline]
Determine if this range is a subset of another range, i.e.
if every address in this range is also in the other range. No check is made to ensure either range is valid.
Parameters:
r Range to compare with
Returns:
true if the this range is a subset of the other one
Definition at line 246 of file addr_range.hh.
References _end, _start, interleaved(), panic, and to_string().
bool AddrRange::mergesWith (const AddrRange & r) const [inline]
Determine if another range merges with the current one, i.e.
if they are part of the same contigous range and have the same interleaving bits.
Parameters:
r Range to evaluate merging with
Returns:
true if the two ranges would merge
Definition at line 199 of file addr_range.hh.
References _end, _start, intlvBits, and intlvHighBit.
Referenced by AddrRange(), and intersects().
bool AddrRange::operator< (const AddrRange & r) const [inline]
Keep the operators away from SWIG.
Less-than operator used to turn an STL map into a binary search tree of non-overlapping address ranges.
Parameters:
r Range to compare with
Returns:
true if the start address is less than that of the other range
Definition at line 282 of file addr_range.hh.
References _start, and intlvMatch.
Addr AddrRange::size () const [inline]
Get the size of the address range.
For a case where interleaving is used we make the simplifying assumption that the size is a divisible by the size of the interleaving slice.
Definition at line 161 of file addr_range.hh.
References _end, _start, and intlvBits.
Referenced by PhysicalMemory::createBackingStore(), intersects(), and AbstractMemory::size().
Addr AddrRange::start () const [inline]
Get the start address of the range.
Definition at line 174 of file addr_range.hh.
References _start.
Referenced by AbstractMemory::access(), AbstractMemory::functionalAccess(), intersects(), and AbstractMemory::start().
uint32_t AddrRange::stripes () const [inline]
Determine the number of interleaved address stripes this range is part of.
Returns:
The number of stripes spanned by the interleaving bits
Definition at line 154 of file addr_range.hh.
References intlvBits, and ULL.
Referenced by SimpleDRAM::init().
std::string AddrRange::to_string () const [inline]
Get a string representation of the range.
This could alternatively be implemented as a operator<<, but at the moment that seems like overkill.
Definition at line 181 of file addr_range.hh.
References _end, _start, csprintf(), interleaved(), intlvBits, intlvHighBit, and intlvMatch.
Referenced by PhysicalMemory::createBackingStore(), intersects(), isSubset(), and BaseBus::recvRangeChange().
bool AddrRange::valid () const [inline]
Determine if the range is valid.
Definition at line 169 of file addr_range.hh.
References _end, and _start.
Member Data Documentation
Addr AddrRange::_end [private]
Definition at line 62 of file addr_range.hh.
Referenced by AddrRange(), contains(), intersects(), isSubset(), mergesWith(), size(), to_string(), and valid().
Addr AddrRange::_start [private]
Private fields for the start and end of the range.
Definition at line 61 of file addr_range.hh.
Referenced by AddrRange(), contains(), intersects(), isSubset(), mergesWith(), operator<(), size(), start(), to_string(), and valid().
uint8_t AddrRange::intlvBits [private]
The number of bits used for interleaving, set to 0 to disable.
Definition at line 68 of file addr_range.hh.
Referenced by AddrRange(), contains(), granularity(), interleaved(), mergesWith(), size(), stripes(), and to_string().
uint8_t AddrRange::intlvHighBit [private]
The high bit of the slice that is used for interleaving.
Definition at line 65 of file addr_range.hh.
Referenced by AddrRange(), contains(), granularity(), mergesWith(), and to_string().
uint8_t AddrRange::intlvMatch [private]
The value to compare the slice addr[high:(high - bits + 1)] with.
Definition at line 72 of file addr_range.hh.
Referenced by contains(), intersects(), operator<(), and to_string().
The documentation for this class was generated from the following file:
base/addr_range.hh