gem5: DecodeCache::AddrMap< Value > Class Template Reference
DecodeCache::AddrMap< Value > Class Template Reference
A sparse map from an Addr to a Value, stored in page chunks.
#include <decode_cache.hh>
Classes
struct CachePage
Public Member Functions
AddrMap ()
Constructor.
Value & lookup (Addr addr)
Protected Types
typedef m5::hash_map< Addr,
CachePage * > PageMap
typedef PageMap::iterator PageIt
Protected Member Functions
void update (PageIt recentest)
Update the mini cache of recent lookups.
CachePage * getPage (Addr addr)
Attempt to find the CacheePage which goes with a particular address.
Protected Attributes
PageIt recent [2]
PageMap pageMap
Detailed Description
template<class Value>
class DecodeCache::AddrMap< Value >
A sparse map from an Addr to a Value, stored in page chunks.
Definition at line 53 of file decode_cache.hh.
Member Typedef Documentation
template<class Value> typedef PageMap::iterator DecodeCache::AddrMap< Value >::PageIt [protected]
Definition at line 62 of file decode_cache.hh.
template<class Value> typedef m5::hash_map<Addr, CachePage *> DecodeCache::AddrMap< Value >::PageMap [protected]
Definition at line 61 of file decode_cache.hh.
Constructor & Destructor Documentation
template<class Value> DecodeCache::AddrMap< Value >::AddrMap () [inline]
Constructor.
Definition at line 114 of file decode_cache.hh.
Member Function Documentation
template<class Value> CachePage* DecodeCache::AddrMap< Value >::getPage (Addr addr) [inline, protected]
Attempt to find the CacheePage which goes with a particular address.
First check the small cache of recent results, then actually look in the hash_map.
Parameters:
addr The address to look up.
Definition at line 81 of file decode_cache.hh.
Referenced by DecodeCache::AddrMap< StaticInstPtr >::lookup().
template<class Value> Value& DecodeCache::AddrMap< Value >::lookup (Addr addr) [inline]
Definition at line 120 of file decode_cache.hh.
Referenced by GenericISA::BasicDecodeCache::decode(), and X86ISA::Decoder::doResetState().
template<class Value> void DecodeCache::AddrMap< Value >::update (PageIt recentest) [inline, protected]
Update the mini cache of recent lookups.
Parameters:
recentest The most recent result;
Definition at line 70 of file decode_cache.hh.
Referenced by DecodeCache::AddrMap< StaticInstPtr >::getPage().
Member Data Documentation
template<class Value> PageMap DecodeCache::AddrMap< Value >::pageMap [protected]
Definition at line 65 of file decode_cache.hh.
Referenced by DecodeCache::AddrMap< StaticInstPtr >::AddrMap(), and DecodeCache::AddrMap< StaticInstPtr >::getPage().
template<class Value> PageIt DecodeCache::AddrMap< Value >::recent[2] [protected]
Definition at line 64 of file decode_cache.hh.
Referenced by DecodeCache::AddrMap< StaticInstPtr >::AddrMap(), DecodeCache::AddrMap< StaticInstPtr >::getPage(), and DecodeCache::AddrMap< StaticInstPtr >::update().
The documentation for this class was generated from the following file:
cpu/decode_cache.hh