gem5: MmDisk Class Reference
MmDisk Class Reference
#include <mm_disk.hh>