gem5: PageTable Class Reference
PageTable Class Reference
Page Table Declaration.
#include <page_table.hh>
Classes
struct cacheElement
Public Member Functions
PageTable (const std::string &__name, uint64_t _pid, Addr _pageSize=TheISA::VMPageSize)
~PageTable ()
const std::string name () const
Addr pageAlign (Addr a)
Addr pageOffset (Addr a)
void map (Addr vaddr, Addr paddr, int64_t size, bool clobber=false)
void remap (Addr vaddr, int64_t size, Addr new_vaddr)
void unmap (Addr vaddr, int64_t size)
bool isUnmapped (Addr vaddr, int64_t size)
Check if any pages in a region are already allocated.
bool lookup (Addr vaddr, TheISA::TlbEntry &entry)
Lookup function.
bool translate (Addr vaddr, Addr &paddr)
Translate function.
bool translate (Addr vaddr)
Simplified translate function (just check for translation).
Fault translate (RequestPtr req)
Perform a translation on the memory request, fills in paddr field of req.
void updateCache (Addr vaddr, TheISA::TlbEntry entry)
Update the page table cache.
void serialize (std::ostream &os)
void unserialize (Checkpoint *cp, const std::string &section)
Protected Types
typedef m5::hash_map< Addr,
TheISA::TlbEntry > PTable
typedef PTable::iterator PTableItr
Protected Attributes
PTable pTable
struct cacheElement pTableCache [3]
const Addr pageSize
const Addr offsetMask
const uint64_t pid
const std::string _name
Detailed Description
Page Table Declaration.
Definition at line 52 of file page_table.hh.
Member Typedef Documentation
typedef m5::hash_map<Addr, TheISA::TlbEntry> PageTable::PTable [protected]
Definition at line 55 of file page_table.hh.
typedef PTable::iterator PageTable::PTableItr [protected]
Definition at line 56 of file page_table.hh.
Constructor & Destructor Documentation
PageTable::PageTable (const std::string & __name, uint64_t _pid, Addr _pageSize = TheISA::VMPageSize)
Definition at line 53 of file page_table.cc.
References isPowerOf2(), pageSize, pTableCache, and PageTable::cacheElement::vaddr.
PageTable::~PageTable ()
Definition at line 63 of file page_table.cc.
Member Function Documentation
bool PageTable::isUnmapped (Addr vaddr, int64_t size)
Check if any pages in a region are already allocated.
Parameters:
vaddr The starting virtual address of the region.
size The length of the region.
Returns:
True if no pages in the region are mapped.
Definition at line 121 of file page_table.cc.
References pageOffset(), pageSize, and pTable.
Referenced by mmapFunc().
bool PageTable::lookup (Addr vaddr, TheISA::TlbEntry & entry)
Lookup function.
Parameters:
vaddr The virtual address.
Returns:
entry The page table entry corresponding to vaddr.
Definition at line 136 of file page_table.cc.
References PageTable::cacheElement::entry, pageAlign(), pTable, pTableCache, and updateCache().
Referenced by SparcISA::RemoteGDB::acc(), MipsISA::RemoteGDB::acc(), ArmISA::RemoteGDB::acc(), SparcISA::FastDataAccessMMUMiss::invoke(), SparcISA::FastInstructionAccessMMUMiss::invoke(), AlphaISA::NDtbMissFault::invoke(), AlphaISA::ItbPageFault::invoke(), translate(), and X86ISA::TLB::translate().
void PageTable::map (Addr vaddr, Addr paddr, int64_t size, bool clobber = false)
Definition at line 68 of file page_table.cc.
References DPRINTF, fatal, pageOffset(), pageSize, pid, pTable, and updateCache().
Referenced by Process::allocateMem(), and Process::map().
const std::string PageTable::name () const [inline]
Definition at line 80 of file page_table.hh.
References _name.
Referenced by serialize(), and unserialize().
Addr PageTable::pageAlign (Addr a) [inline]
Definition at line 82 of file page_table.hh.
References offsetMask.
Referenced by SparcISA::FastDataAccessMMUMiss::invoke(), SparcISA::FastInstructionAccessMMUMiss::invoke(), lookup(), and translate().
Addr PageTable::pageOffset (Addr a) [inline]
Definition at line 83 of file page_table.hh.
References offsetMask.
Referenced by isUnmapped(), map(), remap(), translate(), and unmap().
void PageTable::remap (Addr vaddr, int64_t size, Addr new_vaddr)
Definition at line 87 of file page_table.cc.
References DPRINTF, pageOffset(), pageSize, pTable, and updateCache().
Referenced by mremapFunc().
void PageTable::serialize (std::ostream & os)
Definition at line 195 of file page_table.cc.
References X86ISA::count, csprintf(), name(), paramOut(), and pTable.
Referenced by Process::serialize().
bool PageTable::translate (Addr vaddr, Addr & paddr)
Translate function.
Parameters:
vaddr The virtual address.
paddr Physical address from translation.
Returns:
True if translation exists
Definition at line 165 of file page_table.cc.
References DPRINTF, lookup(), and pageOffset().
Referenced by brkFunc(), translate(), GenericTLB::translateAtomic(), ArmISA::TLB::translateSe(), SETranslatingPortProxy::tryMemsetBlob(), SETranslatingPortProxy::tryReadBlob(), SETranslatingPortProxy::tryReadString(), SETranslatingPortProxy::tryWriteBlob(), and SETranslatingPortProxy::tryWriteString().
Fault PageTable::translate (RequestPtr req)
Perform a translation on the memory request, fills in paddr field of req.
Parameters:
req The memory request.
Definition at line 178 of file page_table.cc.
References Request::getSize(), Request::getVaddr(), NoFault, pageAlign(), pageSize, panic, Request::setPaddr(), and translate().
bool PageTable::translate (Addr vaddr) [inline]
Simplified translate function (just check for translation).
Parameters:
vaddr The virtual address.
Returns:
True if translation exists
Definition at line 117 of file page_table.hh.
References translate().
Referenced by translate().
void PageTable::unmap (Addr vaddr, int64_t size)
Definition at line 106 of file page_table.cc.
References DPRINTF, pageOffset(), pageSize, and pTable.
Referenced by mremapFunc().
void PageTable::unserialize (Checkpoint * cp, const std::string & section)
Definition at line 216 of file page_table.cc.
References X86ISA::count, csprintf(), ArmISA::i, name(), paramIn(), pTable, and MipsISA::vaddr.
Referenced by Process::unserialize().
void PageTable::updateCache (Addr vaddr, TheISA::TlbEntry entry) [inline]
Update the page table cache.
Parameters:
vaddr virtual address (page aligned) to check
pte page table entry to return
Definition at line 131 of file page_table.hh.
References PageTable::cacheElement::entry, pTableCache, and PageTable::cacheElement::vaddr.
Referenced by lookup(), map(), and remap().
Member Data Documentation
const std::string PageTable::_name [protected]
Definition at line 70 of file page_table.hh.
Referenced by name().
const Addr PageTable::offsetMask [protected]
Definition at line 67 of file page_table.hh.
Referenced by pageAlign(), and pageOffset().
const Addr PageTable::pageSize [protected]
Definition at line 66 of file page_table.hh.
Referenced by isUnmapped(), map(), PageTable(), remap(), translate(), and unmap().
const uint64_t PageTable::pid [protected]
Definition at line 69 of file page_table.hh.
Referenced by map().
PTable PageTable::pTable [protected]
Definition at line 57 of file page_table.hh.
Referenced by isUnmapped(), lookup(), map(), remap(), serialize(), unmap(), and unserialize().
struct cacheElement PageTable::pTableCache[3] [protected]
Definition at line 64 of file page_table.hh.
Referenced by lookup(), PageTable(), and updateCache().
The documentation for this class was generated from the following files:
mem/page_table.hh
mem/page_table.cc