gem5: IsaFake Class Reference
IsaFake Class Reference
IsaFake is a device that returns, BadAddr, 1 or 0 on all reads and rites.
#include <isa_fake.hh>