gem5: ListenSocket Class Reference
ListenSocket Class Reference
#include <socket.hh>
Public Member Functions
ListenSocket ()
virtual ~ListenSocket ()
virtual int accept (bool nodelay=false)
virtual bool listen (int port, bool reuse=true)
int getfd () const
bool islistening () const
Static Public Member Functions
static void disableAll ()
static bool allDisabled ()
Protected Attributes
bool listening
int fd
Static Protected Attributes
static bool listeningDisabled = false
static bool anyListening = false
Detailed Description
Definition at line 34 of file socket.hh.
Constructor & Destructor Documentation
ListenSocket::ListenSocket ()
Definition at line 66 of file socket.cc.
ListenSocket::~ListenSocket () [virtual]
Definition at line 70 of file socket.cc.
References fd.
Member Function Documentation
int ListenSocket::accept (bool nodelay = false) [virtual]
Definition at line 119 of file socket.cc.
References fd, and ArmISA::i.
Referenced by Terminal::accept(), TapListener::accept(), VncServer::accept(), GDBListener::accept(), and Trace::NativeTrace::NativeTrace().
bool ListenSocket::allDisabled () [static]
Definition at line 57 of file socket.cc.
References listeningDisabled.
Referenced by EtherTap::EtherTap(), Terminal::listen(), VncServer::listen(), GDBListener::listen(), and Trace::NativeTrace::NativeTrace().
void ListenSocket::disableAll () [static]
Definition at line 49 of file socket.cc.
References anyListening, listeningDisabled, and panic.
int ListenSocket::getfd () const [inline]
Definition at line 55 of file socket.hh.
References fd.
Referenced by Terminal::listen(), TapListener::listen(), VncServer::listen(), and GDBListener::listen().
bool ListenSocket::islistening () const [inline]
Definition at line 56 of file socket.hh.
References listening.
Referenced by Terminal::accept(), TapListener::accept(), VncServer::accept(), and GDBListener::accept().
bool ListenSocket::listen (int port, bool reuse = true) [virtual]
Definition at line 78 of file socket.cc.
References anyListening, fd, ArmISA::i, listening, and panic.
Referenced by Terminal::listen(), TapListener::listen(), VncServer::listen(), GDBListener::listen(), and Trace::NativeTrace::NativeTrace().
Member Data Documentation
bool ListenSocket::anyListening = false [static, protected]
Definition at line 38 of file socket.hh.
Referenced by disableAll(), and listen().
int ListenSocket::fd [protected]
Definition at line 46 of file socket.hh.
Referenced by accept(), getfd(), listen(), and ~ListenSocket().
bool ListenSocket::listening [protected]
Definition at line 45 of file socket.hh.
Referenced by islistening(), and listen().
bool ListenSocket::listeningDisabled = false [static, protected]
Definition at line 37 of file socket.hh.
Referenced by allDisabled(), and disableAll().
The documentation for this class was generated from the following files:
base/socket.hh
base/socket.cc