gem5: Wire Class Reference
Wire Class Reference
#include <Wire.hh>
Public Types
enum WidthSpacingModel { SWIDTH_SSPACE, SWIDTH_DSPACE, DWIDTH_SSPACE, DWIDTH_DSPACE }
enum BufferScheme { MIN_DELAY, STAGGERED }
Public Member Functions
Wire (const string &wire_spacing_model_str_, const string &buf_scheme_str_, bool is_shielding_, const TechParameter *tech_param_ptr_)
~Wire ()
void calc_opt_buffering (int *k_, double *h_, double len_) const
double calc_dynamic_energy (double len_) const
double calc_static_power (double len_) const
Private Member Functions
void init ()
void set_width_spacing_model (const string &wire_spacing_model_str_)
void set_buf_scheme (const string &buf_scheme_str_)
double calc_res_unit_len ()
double calc_gnd_cap_unit_len ()
double calc_couple_cap_unit_len ()
Private Attributes
const TechParameter * m_tech_param_ptr
WidthSpacingModel m_width_spacing_model
BufferScheme m_buf_scheme
bool m_is_shielding
double m_res_unit_len
double m_gnd_cap_unit_len
double m_couple_cap_unit_len
Detailed Description
Definition at line 43 of file Wire.hh.
Member Enumeration Documentation
enum Wire::BufferScheme
Enumerator:
MIN_DELAY
STAGGERED
Definition at line 53 of file Wire.hh.
enum Wire::WidthSpacingModel
Enumerator:
SWIDTH_SSPACE
SWIDTH_DSPACE
DWIDTH_SSPACE
DWIDTH_DSPACE
Definition at line 46 of file Wire.hh.
Constructor & Destructor Documentation
Wire::Wire (const string & wire_spacing_model_str_, const string & buf_scheme_str_, bool is_shielding_, const TechParameter * tech_param_ptr_)
Definition at line 46 of file Wire.cc.
References X86ISA::exit, TechParameter::get_tech_node(), init(), m_is_shielding, m_tech_param_ptr, set_buf_scheme(), and set_width_spacing_model().
Wire::~Wire ()
Definition at line 69 of file Wire.cc.
Member Function Documentation
double Wire::calc_couple_cap_unit_len () [private]
Definition at line 323 of file Wire.cc.
References DWIDTH_DSPACE, DWIDTH_SSPACE, TechParameter::get_WireDielectricConstant(), TechParameter::get_WireDielectricThickness(), TechParameter::get_WireMetalThickness(), TechParameter::get_WireMinSpacing(), TechParameter::get_WireMinWidth(), m_tech_param_ptr, m_width_spacing_model, SWIDTH_DSPACE, SWIDTH_SSPACE, and warn.
Referenced by init().
double Wire::calc_dynamic_energy (double len_) const
Definition at line 133 of file Wire.cc.
References calc_opt_buffering(), TechParameter::get_BufferInputCapacitance(), TechParameter::get_EnergyFactor(), MipsISA::k, m_couple_cap_unit_len, m_gnd_cap_unit_len, and m_tech_param_ptr.
double Wire::calc_gnd_cap_unit_len () [private]
Definition at line 257 of file Wire.cc.
References DWIDTH_DSPACE, DWIDTH_SSPACE, TechParameter::get_WireDielectricConstant(), TechParameter::get_WireDielectricThickness(), TechParameter::get_WireMetalThickness(), TechParameter::get_WireMinSpacing(), TechParameter::get_WireMinWidth(), m_tech_param_ptr, m_width_spacing_model, SWIDTH_DSPACE, SWIDTH_SSPACE, and warn.
Referenced by init().
void Wire::calc_opt_buffering (int * k_, double * h_, double len_) const
Definition at line 74 of file Wire.cc.
References TechParameter::get_BufferDriveResistance(), TechParameter::get_BufferInputCapacitance(), m_buf_scheme, m_couple_cap_unit_len, m_gnd_cap_unit_len, m_is_shielding, m_res_unit_len, m_tech_param_ptr, MIN_DELAY, MipsISA::r, and STAGGERED.
Referenced by calc_dynamic_energy(), and calc_static_power().
double Wire::calc_res_unit_len () [private]
Definition at line 225 of file Wire.cc.
References DWIDTH_DSPACE, DWIDTH_SSPACE, TechParameter::get_WireBarrierThickness(), TechParameter::get_WireMetalThickness(), TechParameter::get_WireMinWidth(), m_tech_param_ptr, m_width_spacing_model, MipsISA::r, SWIDTH_DSPACE, SWIDTH_SSPACE, and warn.
Referenced by init().
double Wire::calc_static_power (double len_) const
Definition at line 152 of file Wire.cc.
References calc_opt_buffering(), TechParameter::get_BufferNMOSOffCurrent(), TechParameter::get_BufferPMOSOffCurrent(), TechParameter::get_vdd(), MipsISA::k, and m_tech_param_ptr.
void Wire::init () [private]
Definition at line 167 of file Wire.cc.
References calc_couple_cap_unit_len(), calc_gnd_cap_unit_len(), calc_res_unit_len(), m_couple_cap_unit_len, m_gnd_cap_unit_len, and m_res_unit_len.
Referenced by Wire().
void Wire::set_buf_scheme (const string & buf_scheme_str_) [private]
Definition at line 203 of file Wire.cc.
References X86ISA::exit, and m_buf_scheme.
Referenced by Wire().
void Wire::set_width_spacing_model (const string & wire_spacing_model_str_) [private]
Definition at line 175 of file Wire.cc.
References X86ISA::exit, and m_width_spacing_model.
Referenced by Wire().
Member Data Documentation
BufferScheme Wire::m_buf_scheme [private]
Definition at line 84 of file Wire.hh.
Referenced by calc_opt_buffering(), and set_buf_scheme().
double Wire::m_couple_cap_unit_len [private]
Definition at line 89 of file Wire.hh.
Referenced by calc_dynamic_energy(), calc_opt_buffering(), and init().
double Wire::m_gnd_cap_unit_len [private]
Definition at line 88 of file Wire.hh.
Referenced by calc_dynamic_energy(), calc_opt_buffering(), and init().
bool Wire::m_is_shielding [private]
Definition at line 85 of file Wire.hh.
Referenced by calc_opt_buffering(), and Wire().
double Wire::m_res_unit_len [private]
Definition at line 87 of file Wire.hh.
Referenced by calc_opt_buffering(), and init().
const TechParameter* Wire::m_tech_param_ptr [private]
Definition at line 82 of file Wire.hh.
Referenced by calc_couple_cap_unit_len(), calc_dynamic_energy(), calc_gnd_cap_unit_len(), calc_opt_buffering(), calc_res_unit_len(), calc_static_power(), and Wire().
WidthSpacingModel Wire::m_width_spacing_model [private]
Definition at line 83 of file Wire.hh.
Referenced by calc_couple_cap_unit_len(), calc_gnd_cap_unit_len(), calc_res_unit_len(), and set_width_spacing_model().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/Wire.hh
mem/ruby/network/orion/Wire.cc