gem5: UseDefUnit Class Reference
UseDefUnit Class Reference
#include <use_def.hh>