gem5: CoherentBus::CoherentBusSlavePort Class Reference
CoherentBus::CoherentBusSlavePort Class Reference
Declaration of the coherent bus slave port type, one will be instantiated for each of the master ports connecting to the bus.
#include <coherent_bus.hh>