gem5: X86ISA::RegOpBase Class Reference
X86ISA::RegOpBase Class Reference
Base classes for RegOps which provides a generateDisassembly method.
#include <microregop.hh>