gem5: GHBPrefetcher Class Reference
GHBPrefetcher Class Reference
#include <ghb.hh>