gem5: LinuxMipsSystem Class Reference
LinuxMipsSystem Class Reference
This class contains linux specific system code (Loading, Events).
#include <system.hh>