gem5: TrafficGen::StateGraph::RandomGen Class Reference
TrafficGen::StateGraph::RandomGen Class Reference
The random generator is similar to the linear one, but does not generate sequential addresses.