gem5: TBETable< ENTRY > Class Template Reference
TBETable< ENTRY > Class Template Reference
#include <TBETable.hh>
Public Member Functions
TBETable (int number_of_TBEs)
bool isPresent (const Address &address) const
void allocate (const Address &address)
void deallocate (const Address &address)
bool areNSlotsAvailable (int n) const
ENTRY * lookup (const Address &address)
void print (std::ostream &out) const
Private Member Functions
TBETable (const TBETable &obj)
TBETable & operator= (const TBETable &obj)
Private Attributes
m5::hash_map< Address, ENTRY > m_map
int m_number_of_TBEs
Detailed Description
template<class ENTRY>
class TBETable< ENTRY >
Definition at line 38 of file TBETable.hh.
Constructor & Destructor Documentation
template<class ENTRY > TBETable< ENTRY >::TBETable (int number_of_TBEs) [inline]
Definition at line 41 of file TBETable.hh.
template<class ENTRY > TBETable< ENTRY >::TBETable (const TBETable< ENTRY > & obj) [private]
Member Function Documentation
template<class ENTRY > void TBETable< ENTRY >::allocate (const Address & address) [inline]
Definition at line 92 of file TBETable.hh.
References TBETable< ENTRY >::isPresent(), TBETable< ENTRY >::m_map, and TBETable< ENTRY >::m_number_of_TBEs.
template<class ENTRY > bool TBETable< ENTRY >::areNSlotsAvailable (int n) const [inline]
Definition at line 50 of file TBETable.hh.
References TBETable< ENTRY >::m_map, and TBETable< ENTRY >::m_number_of_TBEs.
template<class ENTRY > void TBETable< ENTRY >::deallocate (const Address & address) [inline]
Definition at line 101 of file TBETable.hh.
References TBETable< ENTRY >::isPresent(), and TBETable< ENTRY >::m_map.
template<class ENTRY > bool TBETable< ENTRY >::isPresent (const Address & address) const [inline]
Definition at line 83 of file TBETable.hh.
References line_address(), TBETable< ENTRY >::m_map, and TBETable< ENTRY >::m_number_of_TBEs.
Referenced by TBETable< ENTRY >::allocate(), and TBETable< ENTRY >::deallocate().
template<class ENTRY > ENTRY * TBETable< ENTRY >::lookup (const Address & address) [inline]
Definition at line 111 of file TBETable.hh.
References TBETable< ENTRY >::m_map.
template<class ENTRY > TBETable& TBETable< ENTRY >::operator= (const TBETable< ENTRY > & obj) [private]
template<class ENTRY > void TBETable< ENTRY >::print (std::ostream & out) const [inline]
Definition at line 120 of file TBETable.hh.
Member Data Documentation
template<class ENTRY > m5::hash_map<Address, ENTRY> TBETable< ENTRY >::m_map [private]
Definition at line 66 of file TBETable.hh.
Referenced by TBETable< ENTRY >::allocate(), TBETable< ENTRY >::areNSlotsAvailable(), TBETable< ENTRY >::deallocate(), TBETable< ENTRY >::isPresent(), and TBETable< ENTRY >::lookup().
template<class ENTRY > int TBETable< ENTRY >::m_number_of_TBEs [private]
Definition at line 69 of file TBETable.hh.
Referenced by TBETable< ENTRY >::allocate(), TBETable< ENTRY >::areNSlotsAvailable(), and TBETable< ENTRY >::isPresent().
The documentation for this class was generated from the following file:
mem/ruby/system/TBETable.hh