gem5: InstBuffer Class Reference
InstBuffer Class Reference
#include <inst_buffer.hh>