gem5: ResourceSked Class Reference
ResourceSked Class Reference
The ResourceSked maintains the complete schedule for an instruction.
#include <resource_sked.hh>
Public Types
typedef std::list
< ScheduleEntry * >::iterator SkedIt
typedef std::vector< std::list
< ScheduleEntry * > > StageList
Public Member Functions
ResourceSked ()
void init ()
Initializee the current entry pointer to pipeline stage 0 and the 1st schedule entry.
int size ()
Goes through the remaining stages on the schedule and sums all the remaining entries left to be processed.
bool empty ()
Is the schedule empty?
SkedIt begin ()
Beginning Entry of this schedule.
SkedIt end ()
Ending Entry of this schedule.
SkedIt end (int stage_num)
Ending Entry of a specified stage.
SkedIt find (int stage_num, int cmd)
Find a schedule entry based on stage and command.
ScheduleEntry * top ()
What is the next task for this instruction schedule?
void pop ()
Top() Task is completed, remove it from schedule.
void push (ScheduleEntry *sked_entry)
Add To Schedule based on stage num and priority of Schedule Entry.
void pushBefore (ScheduleEntry *sked_entry, int sked_cmd, int sked_cmd_idx)
Add Schedule Entry to be in front of another Entry.
void print ()
Print what's left on the instruction schedule.
StageList * getStages ()
Private Member Functions
SkedIt findIterByPriority (ScheduleEntry *sked_entry, int stage_num)
Find a place to insert the instruction using the schedule entries priority.
SkedIt findIterByCommand (ScheduleEntry *sked_entry, int stage_num, int sked_cmd, int sked_cmd_idx=-1)
Find a place to insert the instruction using a particular command to look for.
Private Attributes
SkedIt curSkedEntry
Current Schedule Entry Pointer.
StageList stages
The Stage-by-Stage Resource Schedule: Resized to Number of Stages in the constructor.
Detailed Description
The ResourceSked maintains the complete schedule for an instruction.
That schedule includes what resources an instruction wants to acquire at each pipeline stage and is represented by a collection of ScheduleEntry objects (described above) that must be executed in-order.
In every pipeline stage, the InOrder model will process all entries on the resource schedule for that stage and then send the instruction to the next stage if and only if the instruction successfully completed each ScheduleEntry.
Definition at line 87 of file resource_sked.hh.
Member Typedef Documentation
typedef std::list<ScheduleEntry*>::iterator ResourceSked::SkedIt
Definition at line 89 of file resource_sked.hh.
typedef std::vector<std::list<ScheduleEntry*> > ResourceSked::StageList
Definition at line 90 of file resource_sked.hh.
Constructor & Destructor Documentation
ResourceSked::ResourceSked ()
Definition at line 43 of file resource_sked.cc.
References ThePipeline::NumStages, and stages.
Member Function Documentation
ResourceSked::SkedIt ResourceSked::begin ()
Beginning Entry of this schedule.
Definition at line 75 of file resource_sked.cc.
References ArmISA::i, size(), and stages.
Referenced by InOrderDynInst::finishSkedEntry(), and InOrderDynInst::setFrontSked().
bool ResourceSked::empty ()
Is the schedule empty?
Definition at line 68 of file resource_sked.cc.
References size().
Referenced by init(), and pop().
ResourceSked::SkedIt ResourceSked::end ()
Ending Entry of this schedule.
Definition at line 87 of file resource_sked.cc.
References stages.
Referenced by InOrderDynInst::setBackSked(), and InOrderDynInst::setFrontSked().
ResourceSked::SkedIt ResourceSked::end (int stage_num)
Ending Entry of a specified stage.
Definition at line 94 of file resource_sked.cc.
References stages.
ResourceSked::SkedIt ResourceSked::find (int stage_num, int cmd)
Find a schedule entry based on stage and command.
Definition at line 100 of file resource_sked.cc.
References stages.
SkedIt ResourceSked::findIterByCommand (ScheduleEntry * sked_entry, int stage_num, int sked_cmd, int sked_cmd_idx = -1) [private]
Find a place to insert the instruction using a particular command to look for.
SkedIt ResourceSked::findIterByPriority (ScheduleEntry * sked_entry, int stage_num) [private]
Find a place to insert the instruction using the schedule entries priority.
StageList* ResourceSked::getStages () [inline]
Definition at line 137 of file resource_sked.hh.
References stages.
Referenced by RSkedIt::init().
void ResourceSked::init ()
Initializee the current entry pointer to pipeline stage 0 and the 1st schedule entry.
Definition at line 49 of file resource_sked.cc.
References curSkedEntry, empty(), and stages.
void ResourceSked::pop ()
Top() Task is completed, remove it from schedule.
Definition at line 123 of file resource_sked.cc.
References curSkedEntry, empty(), ThePipeline::NumStages, and stages.
void ResourceSked::print ()
Print what's left on the instruction schedule.
Definition at line 218 of file resource_sked.cc.
References DPRINTF, ArmISA::i, and stages.
Referenced by InOrderCPU::createBackEndSked(), and InOrderDynInst::printSked().
void ResourceSked::push (ScheduleEntry * sked_entry)
Add To Schedule based on stage num and priority of Schedule Entry.
Referenced by InstBuffer::execute(), InOrderCPU::StageScheduler::needs(), and CacheUnit::write().
void ResourceSked::pushBefore (ScheduleEntry * sked_entry, int sked_cmd, int sked_cmd_idx)
Add Schedule Entry to be in front of another Entry.
int ResourceSked::size ()
Goes through the remaining stages on the schedule and sums all the remaining entries left to be processed.
Definition at line 57 of file resource_sked.cc.
References ArmISA::i, stages, and Stats::total.
Referenced by begin(), empty(), and top().
ScheduleEntry * ResourceSked::top ()
What is the next task for this instruction schedule?
Definition at line 115 of file resource_sked.cc.
References curSkedEntry, and size().
Member Data Documentation
SkedIt ResourceSked::curSkedEntry [private]
Current Schedule Entry Pointer.
Definition at line 144 of file resource_sked.hh.
Referenced by init(), pop(), and top().
StageList ResourceSked::stages [private]
The Stage-by-Stage Resource Schedule: Resized to Number of Stages in the constructor.
Definition at line 149 of file resource_sked.hh.
Referenced by begin(), end(), find(), getStages(), init(), pop(), print(), ResourceSked(), and size().
The documentation for this class was generated from the following files:
cpu/inorder/resource_sked.hh
cpu/inorder/resource_sked.cc