gem5: PacketFifo Class Reference
PacketFifo Class Reference
#include <pktfifo.hh>
Public Types
typedef std::list
< PacketFifoEntry > fifo_list
typedef fifo_list::iterator iterator
Public Member Functions
PacketFifo (int max)
virtual ~PacketFifo ()
unsigned packets () const
unsigned maxsize () const
unsigned size () const
unsigned reserved () const
unsigned avail () const
bool empty () const
bool full () const
unsigned reserve (unsigned len=0)
iterator begin ()
iterator end ()
EthPacketPtr front ()
bool push (EthPacketPtr ptr)
void pop ()
void clear ()
void remove (iterator i)
bool copyout (void *dest, unsigned offset, unsigned len)
int countPacketsBefore (iterator i)
int countPacketsAfter (iterator i)
void check ()
void serialize (const std::string &base, std::ostream &os)
Serialization stuff.
void unserialize (const std::string &base, Checkpoint *cp, const std::string &section)
Protected Attributes
std::list< PacketFifoEntry > fifo
uint64_t _counter
unsigned _maxsize
unsigned _size
unsigned _reserved
Detailed Description
Definition at line 78 of file pktfifo.hh.
Member Typedef Documentation
typedef std::list<PacketFifoEntry> PacketFifo::fifo_list
Definition at line 82 of file pktfifo.hh.
typedef fifo_list::iterator PacketFifo::iterator
Definition at line 83 of file pktfifo.hh.
Constructor & Destructor Documentation
PacketFifo::PacketFifo (int max) [inline, explicit]
Definition at line 93 of file pktfifo.hh.
virtual PacketFifo::~PacketFifo () [inline, virtual]
Definition at line 95 of file pktfifo.hh.
Member Function Documentation
unsigned PacketFifo::avail () const [inline]
Definition at line 101 of file pktfifo.hh.
References _maxsize, _reserved, and _size.
Referenced by full(), Sinic::Device::prepareRead(), push(), Sinic::Device::recvPacket(), NSGigE::recvPacket(), reserve(), Sinic::Device::transmit(), NSGigE::transmit(), Sinic::Device::txKick(), NSGigE::txKick(), IGbE::txStateMachine(), and IGbE::txWire().
iterator PacketFifo::begin () [inline]
Definition at line 113 of file pktfifo.hh.
References fifo.
Referenced by check(), clear(), Sinic::Device::prepareRead(), Sinic::Device::serialize(), and Sinic::Device::unserialize().
void PacketFifo::check () [inline]
Definition at line 190 of file pktfifo.hh.
References _size, begin(), end(), ArmISA::i, panic, and Stats::total.
Referenced by Sinic::Device::rxKick().
void PacketFifo::clear () [inline]
Definition at line 147 of file pktfifo.hh.
References _reserved, _size, begin(), end(), fifo, and ArmISA::i.
Referenced by IGbE::IGbE(), Sinic::Device::reset(), NSGigE::rxReset(), NSGigE::txReset(), and IGbE::write().
bool PacketFifo::copyout (void * dest, unsigned offset, unsigned len)
Definition at line 37 of file pktfifo.cc.
References RefCountingPtr< T >::data, end(), fifo, ArmISA::i, panic, and size().
int PacketFifo::countPacketsAfter (iterator i) [inline]
Definition at line 182 of file pktfifo.hh.
References end(), and fifo.
Referenced by Sinic::Device::prepareRead().
int PacketFifo::countPacketsBefore (iterator i) [inline]
Definition at line 175 of file pktfifo.hh.
References fifo.
Referenced by Sinic::Device::rxKick(), and Sinic::Device::serialize().
bool PacketFifo::empty () const [inline]
Definition at line 102 of file pktfifo.hh.
References size().
Referenced by pop(), Sinic::Device::prepareRead(), Sinic::Device::rxKick(), NSGigE::rxKick(), IGbE::rxStateMachine(), Sinic::Device::transferDone(), NSGigE::transferDone(), Sinic::Device::transmit(), NSGigE::transmit(), and IGbE::txWire().
iterator PacketFifo::end () [inline]
Definition at line 114 of file pktfifo.hh.
References fifo.
Referenced by check(), clear(), copyout(), countPacketsAfter(), Sinic::Device::recvPacket(), Sinic::Device::reset(), Sinic::Device::rxKick(), Sinic::Device::serialize(), Sinic::Device::unserialize(), and Sinic::Device::write().
EthPacketPtr PacketFifo::front () [inline]
Definition at line 116 of file pktfifo.hh.
References fifo.
Referenced by NSGigE::rxKick(), IGbE::rxStateMachine(), Sinic::Device::transmit(), NSGigE::transmit(), and IGbE::txWire().
bool PacketFifo::full () const [inline]
Definition at line 103 of file pktfifo.hh.
References avail().
Referenced by NSGigE::txKick().
unsigned PacketFifo::maxsize () const [inline]
Definition at line 98 of file pktfifo.hh.
References _maxsize.
unsigned PacketFifo::packets () const [inline]
Definition at line 97 of file pktfifo.hh.
References fifo.
Referenced by Sinic::Device::prepareRead().
void PacketFifo::pop () [inline]
Definition at line 135 of file pktfifo.hh.
References _size, empty(), and fifo.
Referenced by NSGigE::rxKick(), IGbE::rxStateMachine(), Sinic::Device::transmit(), NSGigE::transmit(), and IGbE::txWire().
bool PacketFifo::push (EthPacketPtr ptr) [inline]
Definition at line 118 of file pktfifo.hh.
References _counter, _reserved, _size, avail(), fifo, PacketFifoEntry::number, and PacketFifoEntry::packet.
Referenced by IGbE::ethRxPkt(), Sinic::Device::recvPacket(), NSGigE::recvPacket(), Sinic::Device::txKick(), NSGigE::txKick(), and IGbE::txStateMachine().
void PacketFifo::remove (iterator i) [inline]
Definition at line 156 of file pktfifo.hh.
References _size, fifo, and ArmISA::i.
Referenced by Sinic::Device::rxKick().
unsigned PacketFifo::reserve (unsigned len = 0) [inline]
Definition at line 106 of file pktfifo.hh.
References _reserved, avail(), and ArmISA::len.
Referenced by NSGigE::txKick(), and IGbE::txStateMachine().
unsigned PacketFifo::reserved () const [inline]
Definition at line 100 of file pktfifo.hh.
References _reserved.
void PacketFifo::serialize (const std::string & base, std::ostream & os)
Serialization stuff.
Referenced by Sinic::Device::serialize(), and IGbE::serialize().
unsigned PacketFifo::size () const [inline]
Definition at line 99 of file pktfifo.hh.
References _size.
Referenced by copyout(), empty(), Sinic::Device::prepareRead(), Sinic::Device::recvPacket(), Sinic::Device::rxKick(), NSGigE::rxKick(), Sinic::Device::transmit(), NSGigE::transmit(), and Sinic::Device::txKick().
void PacketFifo::unserialize (const std::string & base, Checkpoint * cp, const std::string & section)
Referenced by Sinic::Device::unserialize(), NSGigE::unserialize(), and IGbE::unserialize().
Member Data Documentation
uint64_t PacketFifo::_counter [protected]
Definition at line 87 of file pktfifo.hh.
Referenced by push().
unsigned PacketFifo::_maxsize [protected]
Definition at line 88 of file pktfifo.hh.
Referenced by avail(), and maxsize().
unsigned PacketFifo::_reserved [protected]
Definition at line 90 of file pktfifo.hh.
Referenced by avail(), clear(), push(), reserve(), and reserved().
unsigned PacketFifo::_size [protected]
Definition at line 89 of file pktfifo.hh.
Referenced by avail(), check(), clear(), pop(), push(), remove(), and size().
std::list<PacketFifoEntry> PacketFifo::fifo [protected]
Definition at line 86 of file pktfifo.hh.
Referenced by begin(), clear(), copyout(), countPacketsAfter(), countPacketsBefore(), end(), front(), packets(), pop(), push(), and remove().
The documentation for this class was generated from the following files:
dev/pktfifo.hh
dev/pktfifo.cc