gem5: MsrBase Class Reference
MsrBase Class Reference
#include <misc.hh>