gem5: Tru64 Class Reference
Tru64 Class Reference
This class encapsulates the types, structures, constants, functions, and syscall-number mappings specific to the Alpha Tru64 syscall interface.
#include <tru64.hh>