gem5: Stats::Text Class Reference
Stats::Text Class Reference
#include <text.hh>