gem5: BaseBus::Layer< PortClass > Class Template Reference
BaseBus::Layer< PortClass > Class Template Reference
A bus layer is an internal bus structure with its own flow control and arbitration.
#include <bus.hh>