gem5: X86ISA::SMBios::SMBiosStructure Class Reference
X86ISA::SMBios::SMBiosStructure Class Reference
#include <smbios.hh>