gem5: flit_d Class Reference
flit_d Class Reference
#include <flit_d.hh>
Public Member Functions
flit_d (int id, int vc, int vnet, int size, MsgPtr msg_ptr, Cycles curTime)
flit_d (int vc, bool is_free_signal, Cycles curTime)
void set_outport (int port)
int get_outport ()
void print (std::ostream &out) const
bool is_free_signal ()
int get_size ()
Cycles get_enqueue_time ()
int get_id ()
Cycles get_time ()
void set_time (Cycles time)
int get_vnet ()
int get_vc ()
void set_vc (int vc)
MsgPtr & get_msg_ptr ()
flit_type get_type ()
bool is_stage (flit_stage t_stage, Cycles curTime)
bool is_next_stage (flit_stage t_stage, Cycles curTime)
void advance_stage (flit_stage t_stage, Cycles curTime)
std::pair< flit_stage, Cycles > get_stage ()
void set_delay (Cycles delay)
Cycles get_delay ()
bool functionalWrite (Packet *pkt)
Static Public Member Functions
static bool greater (flit_d *n1, flit_d *n2)
Private Attributes
int m_id
int m_vnet
int m_vc
int m_size
bool m_is_free_signal
Cycles m_enqueue_time
Cycles m_time
flit_type m_type
MsgPtr m_msg_ptr
int m_outport
Cycles src_delay
std::pair< flit_stage, Cycles > m_stage
Detailed Description
Definition at line 41 of file flit_d.hh.
Constructor & Destructor Documentation
flit_d::flit_d (int id, int vc, int vnet, int size, MsgPtr msg_ptr, Cycles curTime)
Definition at line 33 of file flit_d.cc.
References m_enqueue_time, m_id, m_msg_ptr, m_size, m_stage, m_time, m_type, m_vc, and m_vnet.
flit_d::flit_d (int vc, bool is_free_signal, Cycles curTime)
Definition at line 58 of file flit_d.cc.
References m_id, m_is_free_signal, m_time, and m_vc.
Member Function Documentation
void flit_d::advance_stage (flit_stage t_stage, Cycles curTime) [inline]
Definition at line 76 of file flit_d.hh.
References m_stage.
Referenced by SWallocator_d::arbitrate_outports(), VirtualChannel_d::grant_vc(), RoutingUnit_d::RC_stage(), Switch_d::wakeup(), and InputUnit_d::wakeup().
bool flit_d::functionalWrite (Packet * pkt)
Definition at line 79 of file flit_d.cc.
References Message::functionalWrite(), RefCountingPtr< T >::get(), and m_msg_ptr.
Cycles flit_d::get_delay () [inline]
Definition at line 85 of file flit_d.hh.
References src_delay.
Referenced by NetworkInterface_d::wakeup().
Cycles flit_d::get_enqueue_time () [inline]
Definition at line 51 of file flit_d.hh.
References m_enqueue_time.
Referenced by NetworkInterface_d::wakeup().
int flit_d::get_id () [inline]
Definition at line 52 of file flit_d.hh.
References m_id.
Referenced by greater().
MsgPtr& flit_d::get_msg_ptr () [inline]
Definition at line 58 of file flit_d.hh.
References m_msg_ptr.
Referenced by RoutingUnit_d::routeCompute(), and NetworkInterface_d::wakeup().
int flit_d::get_outport () [inline]
Definition at line 47 of file flit_d.hh.
References m_outport.
Referenced by Switch_d::wakeup().
int flit_d::get_size () [inline]
Definition at line 50 of file flit_d.hh.
References m_size.
std::pair<flit_stage, Cycles> flit_d::get_stage () [inline]
Definition at line 82 of file flit_d.hh.
References m_stage.
Cycles flit_d::get_time () [inline]
Definition at line 53 of file flit_d.hh.
References m_time.
Referenced by greater(), flitBuffer_d::isReady(), and flitBuffer_d::isReadyForNext().
flit_type flit_d::get_type () [inline]
Definition at line 59 of file flit_d.hh.
References m_type.
Referenced by SWallocator_d::arbitrate_outports(), NetworkInterface_d::scheduleOutputLink(), NetworkInterface_d::wakeup(), and InputUnit_d::wakeup().
int flit_d::get_vc () [inline]
Definition at line 56 of file flit_d.hh.
References m_vc.
Referenced by OutputUnit_d::wakeup(), NetworkLink_d::wakeup(), NetworkInterface_d::wakeup(), and InputUnit_d::wakeup().
int flit_d::get_vnet () [inline]
Definition at line 55 of file flit_d.hh.
References m_vnet.
Referenced by NetworkInterface_d::wakeup().
static bool flit_d::greater (flit_d * n1, flit_d * n2) [inline, static]
Definition at line 88 of file flit_d.hh.
References get_id(), and get_time().
bool flit_d::is_free_signal () [inline]
Definition at line 49 of file flit_d.hh.
References m_is_free_signal.
Referenced by OutputUnit_d::wakeup(), and NetworkInterface_d::wakeup().
bool flit_d::is_next_stage (flit_stage t_stage, Cycles curTime) [inline]
Definition at line 69 of file flit_d.hh.
References m_stage.
Referenced by VirtualChannel_d::need_stage_nextcycle().
bool flit_d::is_stage (flit_stage t_stage, Cycles curTime) [inline]
Definition at line 62 of file flit_d.hh.
References m_stage.
Referenced by VirtualChannel_d::need_stage(), and Switch_d::wakeup().
void flit_d::print (std::ostream & out) const
Definition at line 67 of file flit_d.cc.
References m_enqueue_time, m_id, m_type, m_vc, and m_vnet.
Referenced by operator<<().
void flit_d::set_delay (Cycles delay) [inline]
Definition at line 84 of file flit_d.hh.
References src_delay.
Referenced by NetworkInterface_d::flitisizeMessage().
void flit_d::set_outport (int port) [inline]
Definition at line 46 of file flit_d.hh.
References m_outport.
Referenced by SWallocator_d::arbitrate_outports().
void flit_d::set_time (Cycles time) [inline]
Definition at line 54 of file flit_d.hh.
References m_time.
Referenced by SWallocator_d::arbitrate_outports(), NetworkInterface_d::scheduleOutputLink(), Switch_d::wakeup(), and NetworkLink_d::wakeup().
void flit_d::set_vc (int vc) [inline]
Definition at line 57 of file flit_d.hh.
References m_vc.
Referenced by SWallocator_d::arbitrate_outports().
Member Data Documentation
Cycles flit_d::m_enqueue_time [private]
Definition at line 106 of file flit_d.hh.
Referenced by flit_d(), get_enqueue_time(), and print().
int flit_d::m_id [private]
Definition at line 101 of file flit_d.hh.
Referenced by flit_d(), get_id(), and print().
bool flit_d::m_is_free_signal [private]
Definition at line 105 of file flit_d.hh.
Referenced by flit_d(), and is_free_signal().
MsgPtr flit_d::m_msg_ptr [private]
Definition at line 108 of file flit_d.hh.
Referenced by flit_d(), functionalWrite(), and get_msg_ptr().
int flit_d::m_outport [private]
Definition at line 109 of file flit_d.hh.
Referenced by get_outport(), and set_outport().
int flit_d::m_size [private]
Definition at line 104 of file flit_d.hh.
Referenced by flit_d(), and get_size().
std::pair<flit_stage, Cycles> flit_d::m_stage [private]
Definition at line 111 of file flit_d.hh.
Referenced by advance_stage(), flit_d(), get_stage(), is_next_stage(), and is_stage().
Cycles flit_d::m_time [private]
Definition at line 106 of file flit_d.hh.
Referenced by flit_d(), get_time(), and set_time().
flit_type flit_d::m_type [private]
Definition at line 107 of file flit_d.hh.
Referenced by flit_d(), get_type(), and print().
int flit_d::m_vc [private]
Definition at line 103 of file flit_d.hh.
Referenced by flit_d(), get_vc(), print(), and set_vc().
int flit_d::m_vnet [private]
Definition at line 102 of file flit_d.hh.
Referenced by flit_d(), get_vnet(), and print().
Cycles flit_d::src_delay [private]
Definition at line 110 of file flit_d.hh.
Referenced by get_delay(), and set_delay().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet/fixed-pipeline/flit_d.hh
mem/ruby/network/garnet/fixed-pipeline/flit_d.cc