gem5: MaltaCChip Class Reference
MaltaCChip Class Reference
Malta CChip CSR Emulation.
#include <malta_cchip.hh>