gem5: Bridge::BridgeMasterPort Class Reference
Bridge::BridgeMasterPort Class Reference
Port on the side that forwards requests and receives responses.
#include <bridge.hh>