gem5: PacketQueue Class Reference
PacketQueue Class Reference
A packet queue is a class that holds deferred packets and later sends them using the associated slave port or master port.
#include <packet_queue.hh>