gem5: PortProxy Class Reference
PortProxy Class Reference
This object is a proxy for a structural port, to be used for debug accesses.
#include <port_proxy.hh>