gem5: X86ISA::IntDev Class Reference
X86ISA::IntDev Class Reference
#include <intdev.hh>