gem5: InOrderCPU::StageScheduler Class Reference
InOrderCPU::StageScheduler Class Reference
#include <cpu.hh>
Public Member Functions
StageScheduler (ThePipeline::RSkedPtr _rsked, int stage_num)
void needs (int unit, int request)
void needs (int unit, int request, int param)
Private Attributes
ThePipeline::RSkedPtr rsked
int stageNum
int nextTaskPriority
Detailed Description
Definition at line 414 of file cpu.hh.
Constructor & Destructor Documentation
InOrderCPU::StageScheduler::StageScheduler (ThePipeline::RSkedPtr _rsked, int stage_num) [inline]
Definition at line 421 of file cpu.hh.
Member Function Documentation
void InOrderCPU::StageScheduler::needs (int unit, int request) [inline]
Definition at line 426 of file cpu.hh.
References nextTaskPriority, ResourceSked::push(), rsked, and stageNum.
Referenced by InOrderCPU::createBackEndSked(), InOrderCPU::createFaultSked(), and InOrderCPU::createFrontEndSked().
void InOrderCPU::StageScheduler::needs (int unit, int request, int param) [inline]
Definition at line 432 of file cpu.hh.
References nextTaskPriority, ResourceSked::push(), rsked, and stageNum.
Member Data Documentation
int InOrderCPU::StageScheduler::nextTaskPriority [private]
Definition at line 418 of file cpu.hh.
Referenced by needs().
ThePipeline::RSkedPtr InOrderCPU::StageScheduler::rsked [private]
Definition at line 416 of file cpu.hh.
Referenced by needs().
int InOrderCPU::StageScheduler::stageNum [private]
Definition at line 417 of file cpu.hh.
Referenced by needs().
The documentation for this class was generated from the following file:
cpu/inorder/cpu.hh