gem5: X86ISA::TLB Class Reference
X86ISA::TLB Class Reference
#include <tlb.hh>