gem5: Scoreboard Class Reference
Scoreboard Class Reference
Implements a simple scoreboard to track which registers are ready.
#include <scoreboard.hh>
Public Member Functions
Scoreboard (unsigned activeThreads, unsigned _numLogicalIntRegs, unsigned _numPhysicalIntRegs, unsigned _numLogicalFloatRegs, unsigned _numPhysicalFloatRegs, unsigned _numMiscRegs, unsigned _zeroRegIdx)
Constructs a scoreboard.
~Scoreboard ()
Destructor.
std::string name () const
Returns the name of the scoreboard.
bool getReg (PhysRegIndex ready_reg)
Checks if the register is ready.
void setReg (PhysRegIndex phys_reg)
Sets the register as ready.
void unsetReg (PhysRegIndex ready_reg)
Sets the register as not ready.
Private Member Functions
void resize (int newSize)
bool indexInBounds (int idx)
Private Attributes
std::vector< bool > regScoreBoard
Scoreboard of physical integer registers, saying whether or not they are ready.
int numLogicalIntRegs
Number of logical integer registers.
int numPhysicalIntRegs
Number of physical integer registers.
int numLogicalFloatRegs
Number of logical floating point registers.
int numPhysicalFloatRegs
Number of physical floating point registers.
int numMiscRegs
Number of miscellaneous registers.
int numLogicalRegs
Number of logical integer + float registers.
int numPhysicalRegs
Number of physical integer + float registers.
int zeroRegIdx
The logical index of the zero register.
int currentSize
Detailed Description
Implements a simple scoreboard to track which registers are ready.
This class assumes that the fp registers start, index wise, right after the integer registers. The misc. registers start, index wise, right after the fp registers.
Todo:
: Fix up handling of the zero register in case the decoder does not automatically make insts that write the zero register into nops.
Definition at line 50 of file scoreboard.hh.
Constructor & Destructor Documentation
Scoreboard::Scoreboard (unsigned activeThreads, unsigned _numLogicalIntRegs, unsigned _numPhysicalIntRegs, unsigned _numLogicalFloatRegs, unsigned _numPhysicalFloatRegs, unsigned _numMiscRegs, unsigned _zeroRegIdx)
Constructs a scoreboard.
Parameters:
activeThreads The number of active threads.
_numLogicalIntRegs Number of logical integer registers.
_numPhysicalIntRegs Number of physical integer registers.
_numLogicalFloatRegs Number of logical fp registers.
_numPhysicalFloatRegs Number of physical fp registers.
_numMiscRegs Number of miscellaneous registers.
_zeroRegIdx Index of the zero register.
Definition at line 36 of file scoreboard.cc.
References ArmISA::i, indexInBounds(), numLogicalFloatRegs, numLogicalIntRegs, numLogicalRegs, numMiscRegs, numPhysicalFloatRegs, numPhysicalIntRegs, numPhysicalRegs, regScoreBoard, and resize().
Scoreboard::~Scoreboard () [inline]
Destructor.
Definition at line 71 of file scoreboard.hh.
Member Function Documentation
bool Scoreboard::getReg (PhysRegIndex ready_reg)
Checks if the register is ready.
Definition at line 85 of file scoreboard.cc.
References indexInBounds(), numPhysicalIntRegs, regScoreBoard, and zeroRegIdx.
Referenced by DefaultRename< Impl >::renameSrcRegs().
bool Scoreboard::indexInBounds (int idx) [inline, private]
Definition at line 125 of file scoreboard.hh.
References currentSize.
Referenced by getReg(), Scoreboard(), setReg(), and unsetReg().
std::string Scoreboard::name () const
Returns the name of the scoreboard.
Definition at line 79 of file scoreboard.cc.
void Scoreboard::resize (int newSize) [inline, private]
Definition at line 118 of file scoreboard.hh.
References currentSize, and regScoreBoard.
Referenced by Scoreboard().
void Scoreboard::setReg (PhysRegIndex phys_reg)
Sets the register as ready.
Definition at line 105 of file scoreboard.cc.
References DPRINTF, indexInBounds(), and regScoreBoard.
Referenced by DefaultRename< Impl >::doSquash(), FullO3CPU< Impl >::insertThread(), and DefaultIEW< Impl >::writebackInsts().
void Scoreboard::unsetReg (PhysRegIndex ready_reg)
Sets the register as not ready.
Definition at line 114 of file scoreboard.cc.
References indexInBounds(), numPhysicalIntRegs, regScoreBoard, and zeroRegIdx.
Referenced by FullO3CPU< Impl >::removeThread(), and DefaultRename< Impl >::renameDestRegs().
Member Data Documentation
int Scoreboard::currentSize [private]
Definition at line 115 of file scoreboard.hh.
Referenced by indexInBounds(), and resize().
int Scoreboard::numLogicalFloatRegs [private]
Number of logical floating point registers.
Definition at line 98 of file scoreboard.hh.
Referenced by Scoreboard().
int Scoreboard::numLogicalIntRegs [private]
Number of logical integer registers.
Definition at line 92 of file scoreboard.hh.
Referenced by Scoreboard().
int Scoreboard::numLogicalRegs [private]
Number of logical integer + float registers.
Definition at line 107 of file scoreboard.hh.
Referenced by Scoreboard().
int Scoreboard::numMiscRegs [private]
Number of miscellaneous registers.
Definition at line 104 of file scoreboard.hh.
Referenced by Scoreboard().
int Scoreboard::numPhysicalFloatRegs [private]
Number of physical floating point registers.
Definition at line 101 of file scoreboard.hh.
Referenced by Scoreboard().
int Scoreboard::numPhysicalIntRegs [private]
Number of physical integer registers.
Definition at line 95 of file scoreboard.hh.
Referenced by getReg(), Scoreboard(), and unsetReg().
int Scoreboard::numPhysicalRegs [private]
Number of physical integer + float registers.
Definition at line 110 of file scoreboard.hh.
Referenced by Scoreboard().
std::vector<bool> Scoreboard::regScoreBoard [private]
Scoreboard of physical integer registers, saying whether or not they are ready.
Definition at line 89 of file scoreboard.hh.
Referenced by getReg(), resize(), Scoreboard(), setReg(), and unsetReg().
int Scoreboard::zeroRegIdx [private]
The logical index of the zero register.
Definition at line 113 of file scoreboard.hh.
Referenced by getReg(), and unsetReg().
The documentation for this class was generated from the following files:
cpu/o3/scoreboard.hh
cpu/o3/scoreboard.cc