gem5: ResourceEvent Class Reference
ResourceEvent Class Reference
#include <resource.hh>