gem5: Bridge::BridgeSlavePort Class Reference
Bridge::BridgeSlavePort Class Reference
The port on the side that receives requests and sends responses.
#include <bridge.hh>