gem5: TraceCPU Class Reference
TraceCPU Class Reference
A cpu object for running memory traces through a memory hierarchy.
#include <trace_cpu.hh>