gem5: SWAllocator Class Reference
SWAllocator Class Reference
#include <SWAllocator.hh>
Public Member Functions
~SWAllocator ()
double get_dynamic_energy_local_sw_arb (double num_req_, bool is_max_) const
double get_dynamic_energy_global_sw_arb (double num_req_, bool is_max_) const
double get_static_power () const
void print_all () const
Static Public Member Functions
static SWAllocator * create_swallocator (uint32_t num_in_port_, uint32_t num_out_port_, uint32_t num_vclass_, uint32_t num_vchannel_, const Crossbar *xbar_ptr_, const OrionConfig *orion_cfg_ptr_)
Protected Member Functions
SWAllocator (uint32_t num_in_port_, uint32_t num_out_port_, uint32_t num_vclass_, uint32_t num_vchannel_, double len_in_wire_, const string &local_arb_model_str_, const string &local_arb_ff_model_str_, const string &global_arb_model_str_, const string &global_arb_ff_model_str_, const TechParameter *tech_param_ptr_)
void init ()
Protected Attributes
uint32_t m_num_in_port
uint32_t m_num_out_port
uint32_t m_num_vclass
uint32_t m_num_vchannel
Arbiter * m_local_arb_ptr
Arbiter * m_global_arb_ptr
Detailed Description
Definition at line 46 of file SWAllocator.hh.
Constructor & Destructor Documentation
SWAllocator::SWAllocator (uint32_t num_in_port_, uint32_t num_out_port_, uint32_t num_vclass_, uint32_t num_vchannel_, double len_in_wire_, const string & local_arb_model_str_, const string & local_arb_ff_model_str_, const string & global_arb_model_str_, const string & global_arb_ff_model_str_, const TechParameter * tech_param_ptr_) [protected]
Definition at line 46 of file SWAllocator.cc.
References Arbiter::create_arbiter(), m_global_arb_ptr, m_local_arb_ptr, m_num_in_port, m_num_out_port, m_num_vchannel, and m_num_vclass.
Referenced by create_swallocator().
SWAllocator::~SWAllocator ()
Definition at line 93 of file SWAllocator.cc.
Member Function Documentation
SWAllocator * SWAllocator::create_swallocator (uint32_t num_in_port_, uint32_t num_out_port_, uint32_t num_vclass_, uint32_t num_vchannel_, const Crossbar * xbar_ptr_, const OrionConfig * orion_cfg_ptr_) [static]
Definition at line 157 of file SWAllocator.cc.
References OrionConfig::get(), Crossbar::get_len_req_wire(), OrionConfig::get_tech_param_ptr(), and SWAllocator().
Referenced by OrionRouter::init().
double SWAllocator::get_dynamic_energy_global_sw_arb (double num_req_, bool is_max_) const
Definition at line 107 of file SWAllocator.cc.
References Arbiter::calc_dynamic_energy(), and m_global_arb_ptr.
Referenced by OrionRouter::calc_dynamic_energy_global_sw_arb(), and print_all().
double SWAllocator::get_dynamic_energy_local_sw_arb (double num_req_, bool is_max_) const
Definition at line 96 of file SWAllocator.cc.
References Arbiter::calc_dynamic_energy(), and m_local_arb_ptr.
Referenced by OrionRouter::calc_dynamic_energy_local_sw_arb(), and print_all().
double SWAllocator::get_static_power () const
Definition at line 118 of file SWAllocator.cc.
References Arbiter::get_static_power(), m_global_arb_ptr, m_local_arb_ptr, m_num_in_port, and m_num_out_port.
Referenced by OrionRouter::get_static_power_sa(), and print_all().
void SWAllocator::init () [protected]
void SWAllocator::print_all () const
Definition at line 134 of file SWAllocator.cc.
References get_dynamic_energy_global_sw_arb(), get_dynamic_energy_local_sw_arb(), get_static_power(), ArmISA::i, m_global_arb_ptr, m_local_arb_ptr, m_num_in_port, m_num_vchannel, and m_num_vclass.
Referenced by OrionRouter::print().
Member Data Documentation
Arbiter* SWAllocator::m_global_arb_ptr [protected]
Definition at line 82 of file SWAllocator.hh.
Referenced by get_dynamic_energy_global_sw_arb(), get_static_power(), print_all(), and SWAllocator().
Arbiter* SWAllocator::m_local_arb_ptr [protected]
Definition at line 81 of file SWAllocator.hh.
Referenced by get_dynamic_energy_local_sw_arb(), get_static_power(), print_all(), and SWAllocator().
uint32_t SWAllocator::m_num_in_port [protected]
Definition at line 76 of file SWAllocator.hh.
Referenced by get_static_power(), print_all(), and SWAllocator().
uint32_t SWAllocator::m_num_out_port [protected]
Definition at line 77 of file SWAllocator.hh.
Referenced by get_static_power(), and SWAllocator().
uint32_t SWAllocator::m_num_vchannel [protected]
Definition at line 79 of file SWAllocator.hh.
Referenced by print_all(), and SWAllocator().
uint32_t SWAllocator::m_num_vclass [protected]
Definition at line 78 of file SWAllocator.hh.
Referenced by print_all(), and SWAllocator().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/Allocator/SWAllocator.hh
mem/ruby/network/orion/Allocator/SWAllocator.cc