gem5: FlexibleConsumer Class Reference
FlexibleConsumer Class Reference
#include <FlexibleConsumer.hh>