gem5: TimeBuffer< T > Class Template Reference
TimeBuffer< T > Class Template Reference
#include <timebuf.hh>
Classes
class wire
Public Member Functions
TimeBuffer (int p, int f)
TimeBuffer ()
~TimeBuffer ()
void id (int id)
int id ()
void advance ()
T * access (int idx)
T & operator[] (int idx)
wire getWire (int idx)
wire zero ()
unsigned getSize ()
Protected Member Functions
void valid (int idx)
Protected Attributes
int past
int future
unsigned size
int _id
char * data
std::vector< char * > index
unsigned base
Friends
class wire
Detailed Description
template<class T>
class TimeBuffer< T >
Definition at line 40 of file timebuf.hh.
Constructor & Destructor Documentation
template<class T> TimeBuffer< T >::TimeBuffer (int p, int f) [inline]
Definition at line 140 of file timebuf.hh.
template<class T> TimeBuffer< T >::TimeBuffer () [inline]
Definition at line 156 of file timebuf.hh.
template<class T> TimeBuffer< T >::~TimeBuffer () [inline]
Definition at line 161 of file timebuf.hh.
Member Function Documentation
template<class T> T* TimeBuffer< T >::access (int idx) [inline]
Definition at line 192 of file timebuf.hh.
Referenced by InorderBackEnd< Impl >::executeInsts(), InstructionQueue< Impl >::processFUCompletion(), and InstructionQueue< Impl >::scheduleReadyInsts().
template<class T> void TimeBuffer< T >::advance () [inline]
Definition at line 179 of file timebuf.hh.
Referenced by ActivityRecorder::advance(), BackEnd< Impl >::dispatchInsts(), LWBackEnd< Impl >::doSwitchOut(), FullO3CPU< Impl >::drain(), InorderBackEnd< Impl >::executeInsts(), ActivityRecorder::reset(), InorderBackEnd< Impl >::squash(), DefaultIEW< Impl >::takeOverFrom(), OzoneCPU< Impl >::takeOverFrom(), LWBackEnd< Impl >::tick(), FrontEnd< Impl >::tick(), BackEnd< Impl >::tick(), DefaultIEW< Impl >::tick(), OzoneCPU< Impl >::tick(), FullO3CPU< Impl >::tick(), and InOrderCPU::tick().
template<class T> unsigned TimeBuffer< T >::getSize () [inline]
Definition at line 234 of file timebuf.hh.
Referenced by LWBackEnd< Impl >::doSwitchOut(), FullO3CPU< Impl >::drain(), and DefaultIEW< Impl >::takeOverFrom().
template<class T> wire TimeBuffer< T >::getWire (int idx) [inline]
Definition at line 222 of file timebuf.hh.
Referenced by BackEnd< Impl >::BackEnd(), DefaultIEW< Impl >::DefaultIEW(), InorderBackEnd< Impl >::InorderBackEnd(), LWBackEnd< Impl >::LWBackEnd(), LWBackEnd< Impl >::setCommBuffer(), FrontEnd< Impl >::setCommBuffer(), BackEnd< Impl >::setCommBuffer(), DefaultRename< Impl >::setDecodeQueue(), DefaultDecode< Impl >::setDecodeQueue(), DefaultFetch< Impl >::setFetchQueue(), DefaultDecode< Impl >::setFetchQueue(), DefaultCommit< Impl >::setFetchQueue(), DefaultIEW< Impl >::setIEWQueue(), DefaultCommit< Impl >::setIEWQueue(), BackEnd< Impl >::InstQueue::setIssueExecQueue(), PipelineStage::setNextStageQueue(), PipelineStage::setPrevStageQueue(), DefaultRename< Impl >::setRenameQueue(), DefaultIEW< Impl >::setRenameQueue(), DefaultCommit< Impl >::setRenameQueue(), DefaultRename< Impl >::setTimeBuffer(), InstructionQueue< Impl >::setTimeBuffer(), DefaultIEW< Impl >::setTimeBuffer(), DefaultFetch< Impl >::setTimeBuffer(), DefaultDecode< Impl >::setTimeBuffer(), DefaultCommit< Impl >::setTimeBuffer(), and PipelineStage::setTimeBuffer().
template<class T> void TimeBuffer< T >::id (int id) [inline]
Definition at line 168 of file timebuf.hh.
Referenced by PipelineStage::sendInstToNextStage(), and PipelineStage::sortInsts().
template<class T> int TimeBuffer< T >::id () [inline]
Definition at line 173 of file timebuf.hh.
template<class T> T& TimeBuffer< T >::operator[] (int idx) [inline]
Definition at line 207 of file timebuf.hh.
template<class T> void TimeBuffer< T >::valid (int idx) [inline, protected]
Definition at line 52 of file timebuf.hh.
Referenced by TimeBuffer< DecodeStruct >::access(), TimeBuffer< DecodeStruct >::getWire(), and TimeBuffer< DecodeStruct >::operator[]().
template<class T> wire TimeBuffer< T >::zero () [inline]
Definition at line 229 of file timebuf.hh.
Friends And Related Function Documentation
template<class T> friend class wire [friend]
Definition at line 58 of file timebuf.hh.
Referenced by TimeBuffer< DecodeStruct >::getWire(), and TimeBuffer< DecodeStruct >::zero().
Member Data Documentation
template<class T> int TimeBuffer< T >::_id [protected]
Definition at line 46 of file timebuf.hh.
Referenced by TimeBuffer< DecodeStruct >::id(), and TimeBuffer< DecodeStruct >::TimeBuffer().
template<class T> unsigned TimeBuffer< T >::base [protected]
Definition at line 50 of file timebuf.hh.
Referenced by TimeBuffer< DecodeStruct >::access(), TimeBuffer< DecodeStruct >::advance(), and TimeBuffer< DecodeStruct >::operator[]().
template<class T> char* TimeBuffer< T >::data [protected]
Definition at line 48 of file timebuf.hh.
Referenced by TimeBuffer< DecodeStruct >::TimeBuffer(), and TimeBuffer< DecodeStruct >::~TimeBuffer().
template<class T> int TimeBuffer< T >::future [protected]
Definition at line 44 of file timebuf.hh.
Referenced by TimeBuffer< DecodeStruct >::advance(), TimeBuffer< DecodeStruct >::TimeBuffer(), and TimeBuffer< DecodeStruct >::valid().
template<class T> std::vector<char *> TimeBuffer< T >::index [protected]
Definition at line 49 of file timebuf.hh.
Referenced by TimeBuffer< DecodeStruct >::access(), TimeBuffer< DecodeStruct >::advance(), TimeBuffer< DecodeStruct >::operator[](), TimeBuffer< DecodeStruct >::TimeBuffer(), and TimeBuffer< DecodeStruct >::~TimeBuffer().
template<class T> int TimeBuffer< T >::past [protected]
Definition at line 43 of file timebuf.hh.
Referenced by TimeBuffer< DecodeStruct >::TimeBuffer(), and TimeBuffer< DecodeStruct >::valid().
template<class T> unsigned TimeBuffer< T >::size [protected]
Definition at line 45 of file timebuf.hh.
Referenced by TimeBuffer< DecodeStruct >::access(), TimeBuffer< DecodeStruct >::advance(), DefaultFetch< Impl >::buildInst(), PipelineStage::canSendInstToStage(), DefaultDecode< Impl >::decodeInsts(), BackEnd< Impl >::dispatchInsts(), BackEnd< Impl >::executeInsts(), DefaultIEW< Impl >::executeInsts(), DefaultDecode< Impl >::fetchInstsValid(), DefaultCommit< Impl >::getInsts(), TimeBuffer< DecodeStruct >::getSize(), OptCPU::initTable(), BackEnd< Impl >::instToCommit(), DefaultCommit< Impl >::markCompletedInsts(), TimeBuffer< DecodeStruct >::operator[](), PipelineStage::prevStageInstsValid(), OptCPU::processSet(), PipelineStage::processStage(), DefaultRename< Impl >::renameInsts(), BackEnd< Impl >::InstQueue::scheduleNonSpec(), BackEnd< Impl >::InstQueue::scheduleReadyInsts(), PipelineStage::sendInstToNextStage(), DefaultCommit< Impl >::skidInsert(), DefaultRename< Impl >::sortInsts(), DefaultIEW< Impl >::sortInsts(), DefaultDecode< Impl >::sortInsts(), PipelineStage::sortInsts(), DefaultRename< Impl >::squash(), DefaultDecode< Impl >::squash(), PipelineStage::squashPrevStageInsts(), TimeBuffer< DecodeStruct >::TimeBuffer(), DefaultRename< Impl >::validInsts(), DefaultIEW< Impl >::validInstsFromRename(), and TimeBuffer< DecodeStruct >::~TimeBuffer().
The documentation for this class was generated from the following file:
cpu/timebuf.hh