gem5: DiskImage Class Reference
DiskImage Class Reference
Basic interface for accessing a disk image.
#include <disk_image.hh>