gem5: Stats::StatEvent Class Reference
Stats::StatEvent Class Reference
Event to dump and/or reset the statistics.