gem5: Register Class Reference
Register Class Reference
#include <Register.hh>
Public Member Functions
Register (uint32_t num_entry_, uint32_t line_width_, const TechParameter *tech_param_ptr_)
~Register ()
double calc_e_read () const
double calc_e_write () const
double calc_i_static () const
Private Member Functions
void init ()
Private Attributes
uint32_t m_num_entry
uint32_t m_line_width
const TechParameter * m_tech_param_ptr
FlipFlop * m_ff_ptr
double m_avg_read
double m_avg_write
Detailed Description
Definition at line 44 of file Register.hh.
Constructor & Destructor Documentation
Register::Register (uint32_t num_entry_, uint32_t line_width_, const TechParameter * tech_param_ptr_)
Definition at line 45 of file Register.cc.
References init(), m_line_width, m_num_entry, and m_tech_param_ptr.
Register::~Register ()
Definition at line 61 of file Register.cc.
References m_ff_ptr.
Member Function Documentation
double Register::calc_e_read () const
Definition at line 66 of file Register.cc.
References m_avg_read, m_avg_write, and m_num_entry.
Referenced by Buffer::get_dynamic_energy().
double Register::calc_e_write () const
Definition at line 87 of file Register.cc.
References m_avg_write.
Referenced by Buffer::get_dynamic_energy().
double Register::calc_i_static () const
Definition at line 96 of file Register.cc.
References FlipFlop::get_i_static(), m_ff_ptr, m_line_width, and m_num_entry.
Referenced by Buffer::get_static_power().
void Register::init () [private]
Definition at line 103 of file Register.cc.
References FlipFlop::get_e_clock(), FlipFlop::get_e_switch(), m_avg_read, m_avg_write, m_ff_ptr, m_line_width, and m_tech_param_ptr.
Referenced by Register().
Member Data Documentation
double Register::m_avg_read [private]
Definition at line 69 of file Register.hh.
Referenced by calc_e_read(), and init().
double Register::m_avg_write [private]
Definition at line 70 of file Register.hh.
Referenced by calc_e_read(), calc_e_write(), and init().
FlipFlop* Register::m_ff_ptr [private]
Definition at line 67 of file Register.hh.
Referenced by calc_i_static(), init(), and ~Register().
uint32_t Register::m_line_width [private]
Definition at line 64 of file Register.hh.
Referenced by calc_i_static(), init(), and Register().
uint32_t Register::m_num_entry [private]
Definition at line 63 of file Register.hh.
Referenced by calc_e_read(), calc_i_static(), and Register().
const TechParameter* Register::m_tech_param_ptr [private]
Definition at line 65 of file Register.hh.
Referenced by init(), and Register().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/Buffer/Register.hh
mem/ruby/network/orion/Buffer/Register.cc