gem5: NoncoherentBus Class Reference
NoncoherentBus Class Reference
A non-coherent bus connects a number of non-snooping masters and slaves, and routes the request and response packets based on the address.
#include <noncoherent_bus.hh>