gem5: Net::IpPtr Class Reference
Net::IpPtr Class Reference
#include <inet.hh>
Public Member Functions
IpPtr ()
IpPtr (const EthPacketPtr &ptr)
IpPtr (const EthPtr &ptr)
IpPtr (const IpPtr &ptr)
IpHdr * get ()
IpHdr * operator-> ()
IpHdr & operator* ()
const IpHdr * get () const
const IpHdr * operator-> () const
const IpHdr & operator* () const
const IpPtr & operator= (const EthPacketPtr &ptr)
const IpPtr & operator= (const EthPtr &ptr)
const IpPtr & operator= (const IpPtr &ptr)
const EthPacketPtr packet () const
EthPacketPtr packet ()
bool operator! () const
operator bool () const
int off () const
int pstart () const
Protected Member Functions
void set (const EthPacketPtr &ptr)
Protected Attributes
EthPacketPtr p
Friends
class TcpPtr
class UdpPtr
Detailed Description
Definition at line 239 of file inet.hh.
Constructor & Destructor Documentation
Net::IpPtr::IpPtr () [inline]
Definition at line 258 of file inet.hh.
Net::IpPtr::IpPtr (const EthPacketPtr & ptr) [inline]
Definition at line 259 of file inet.hh.
Net::IpPtr::IpPtr (const EthPtr & ptr) [inline]
Definition at line 260 of file inet.hh.
References Net::EthPtr::p.
Net::IpPtr::IpPtr (const IpPtr & ptr) [inline]
Definition at line 261 of file inet.hh.
Member Function Documentation
IpHdr* Net::IpPtr::get () [inline]
Definition at line 263 of file inet.hh.
References RefCountingPtr< T >::data, and p.
const IpHdr* Net::IpPtr::get () const [inline]
Definition at line 267 of file inet.hh.
References RefCountingPtr< T >::data, and p.
int Net::IpPtr::off () const [inline]
Definition at line 280 of file inet.hh.
Referenced by pstart().
Net::IpPtr::operator bool () const [inline]
Definition at line 279 of file inet.hh.
References p.
bool Net::IpPtr::operator! () const [inline]
Definition at line 278 of file inet.hh.
References p.
IpHdr& Net::IpPtr::operator* () [inline]
Definition at line 265 of file inet.hh.
const IpHdr& Net::IpPtr::operator* () const [inline]
Definition at line 270 of file inet.hh.
const IpHdr* Net::IpPtr::operator-> () const [inline]
Definition at line 269 of file inet.hh.
IpHdr* Net::IpPtr::operator-> () [inline]
Definition at line 264 of file inet.hh.
const IpPtr& Net::IpPtr::operator= (const EthPacketPtr & ptr) [inline]
Definition at line 272 of file inet.hh.
const IpPtr& Net::IpPtr::operator= (const EthPtr & ptr) [inline]
Definition at line 273 of file inet.hh.
References Net::EthPtr::p.
const IpPtr& Net::IpPtr::operator= (const IpPtr & ptr) [inline]
Definition at line 274 of file inet.hh.
References p.
const EthPacketPtr Net::IpPtr::packet () const [inline]
Definition at line 276 of file inet.hh.
References p.
EthPacketPtr Net::IpPtr::packet () [inline]
Definition at line 277 of file inet.hh.
References p.
int Net::IpPtr::pstart () const [inline]
Definition at line 281 of file inet.hh.
References off().
void Net::IpPtr::set (const EthPacketPtr & ptr) [inline, protected]
Definition at line 246 of file inet.hh.
References RefCountingPtr< T >::data, p, and Net::EthHdr::type().
Friends And Related Function Documentation
friend class TcpPtr [friend]
Definition at line 242 of file inet.hh.
friend class UdpPtr [friend]
Definition at line 243 of file inet.hh.
Member Data Documentation
EthPacketPtr Net::IpPtr::p [protected]
Definition at line 244 of file inet.hh.
Referenced by get(), operator bool(), operator!(), operator=(), packet(), and set().
The documentation for this class was generated from the following file:
base/inet.hh