gem5: MemUnit Class Reference
MemUnit Class Reference
#include <MemUnit.hh>
Public Types
enum MemModel { NO_MODEL = 0, NORMAL_MEM }
Public Member Functions
MemUnit (const string &mem_model_str_, const SRAM *sram_ptr_, const TechParameter *tech_param_ptr_)
~MemUnit ()
double get_e_switch () const
double get_i_static () const
Private Member Functions
void init ()
double calc_mem_cap ()
double calc_i_static ()
Private Attributes
MemModel m_mem_model
const SRAM * m_sram_ptr
const TechParameter * m_tech_param_ptr
double m_e_switch
double m_i_static
Detailed Description
Definition at line 44 of file MemUnit.hh.
Member Enumeration Documentation
enum MemUnit::MemModel
Enumerator:
NO_MODEL
NORMAL_MEM
Definition at line 47 of file MemUnit.hh.
Constructor & Destructor Documentation
MemUnit::MemUnit (const string & mem_model_str_, const SRAM * sram_ptr_, const TechParameter * tech_param_ptr_)
Definition at line 44 of file MemUnit.cc.
References init(), m_mem_model, m_sram_ptr, m_tech_param_ptr, and NO_MODEL.
MemUnit::~MemUnit ()
Definition at line 68 of file MemUnit.cc.
Member Function Documentation
double MemUnit::calc_i_static () [private]
Definition at line 109 of file MemUnit.cc.
References TechParameter::get_NMOS_TAB(), SRAM::get_num_data_end(), SRAM::get_num_read_port(), SRAM::get_num_write_port(), TechParameter::get_PMOS_TAB(), TechParameter::get_Wmemcella(), TechParameter::get_Wmemcellbscale(), TechParameter::get_Wmemcellr(), TechParameter::get_Wmemcellw(), m_sram_ptr, and m_tech_param_ptr.
Referenced by init().
double MemUnit::calc_mem_cap () [private]
Definition at line 80 of file MemUnit.cc.
References TechParameter::calc_draincap(), TechParameter::calc_gatecap(), SRAM::get_num_data_end(), SRAM::get_num_read_port(), SRAM::get_num_write_port(), TechParameter::get_Wmemcella(), TechParameter::get_Wmemcellbscale(), TechParameter::get_Wmemcellr(), TechParameter::get_Wmemcellw(), m_sram_ptr, m_tech_param_ptr, TechParameter::NCH, and TechParameter::PCH.
Referenced by init().
double MemUnit::get_e_switch () const [inline]
Definition at line 62 of file MemUnit.hh.
References m_e_switch.
Referenced by SRAM::calc_e_write().
double MemUnit::get_i_static () const [inline]
Definition at line 63 of file MemUnit.hh.
References m_i_static.
Referenced by SRAM::calc_i_static().
void MemUnit::init () [private]
Definition at line 71 of file MemUnit.cc.
References calc_i_static(), calc_mem_cap(), TechParameter::get_EnergyFactor(), m_e_switch, m_i_static, and m_tech_param_ptr.
Referenced by MemUnit().
Member Data Documentation
double MemUnit::m_e_switch [private]
Definition at line 75 of file MemUnit.hh.
Referenced by get_e_switch(), and init().
double MemUnit::m_i_static [private]
Definition at line 76 of file MemUnit.hh.
Referenced by get_i_static(), and init().
MemModel MemUnit::m_mem_model [private]
Definition at line 71 of file MemUnit.hh.
Referenced by MemUnit().
const SRAM* MemUnit::m_sram_ptr [private]
Definition at line 72 of file MemUnit.hh.
Referenced by calc_i_static(), calc_mem_cap(), and MemUnit().
const TechParameter* MemUnit::m_tech_param_ptr [private]
Definition at line 73 of file MemUnit.hh.
Referenced by calc_i_static(), calc_mem_cap(), init(), and MemUnit().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/Buffer/MemUnit.hh
mem/ruby/network/orion/Buffer/MemUnit.cc