gem5: PrechargeUnit Class Reference
PrechargeUnit Class Reference
#include <PrechargeUnit.hh>
Public Types
enum PrechargeModel { NO_MODEL = 0, SINGLE_BITLINE, EQU_BITLINE, SINGLE_OTHER }
Public Member Functions
PrechargeUnit (const string &pre_model_str_, double pre_load_, const SRAM *sram_ptr_, const TechParameter *tech_param_ptr_)
~PrechargeUnit ()
double get_e_charge_gate () const
double get_e_charge_drain () const
double get_i_static () const
Private Member Functions
void init ()
uint32_t calc_num_pre_gate ()
uint32_t calc_num_pre_drain ()
double calc_pre_cap (double width_, double length_)
Private Attributes
PrechargeModel m_pre_model
double m_pre_load
const SRAM * m_sram_ptr
const TechParameter * m_tech_param_ptr
double m_pre_size
double m_e_charge_gate
double m_e_charge_drain
double m_i_static
Detailed Description
Definition at line 44 of file PrechargeUnit.hh.
Member Enumeration Documentation
enum PrechargeUnit::PrechargeModel
Enumerator:
NO_MODEL
SINGLE_BITLINE
EQU_BITLINE
SINGLE_OTHER
Definition at line 47 of file PrechargeUnit.hh.
Constructor & Destructor Documentation
PrechargeUnit::PrechargeUnit (const string & pre_model_str_, double pre_load_, const SRAM * sram_ptr_, const TechParameter * tech_param_ptr_)
Definition at line 41 of file PrechargeUnit.cc.
References init(), m_pre_load, m_pre_model, m_sram_ptr, m_tech_param_ptr, and NO_MODEL.
PrechargeUnit::~PrechargeUnit ()
Definition at line 75 of file PrechargeUnit.cc.
Member Function Documentation
uint32_t PrechargeUnit::calc_num_pre_drain () [private]
Definition at line 122 of file PrechargeUnit.cc.
References EQU_BITLINE, fatal, m_pre_model, SINGLE_BITLINE, and SINGLE_OTHER.
Referenced by init().
uint32_t PrechargeUnit::calc_num_pre_gate () [private]
Definition at line 111 of file PrechargeUnit.cc.
References EQU_BITLINE, fatal, m_pre_model, SINGLE_BITLINE, and SINGLE_OTHER.
Referenced by init().
double PrechargeUnit::calc_pre_cap (double width_, double length_) [private]
Definition at line 133 of file PrechargeUnit.cc.
References TechParameter::calc_gatecap(), and m_tech_param_ptr.
Referenced by init().
double PrechargeUnit::get_e_charge_drain () const [inline]
Definition at line 66 of file PrechargeUnit.hh.
References m_e_charge_drain.
Referenced by SRAM::calc_e_read().
double PrechargeUnit::get_e_charge_gate () const [inline]
Definition at line 65 of file PrechargeUnit.hh.
References m_e_charge_gate.
Referenced by SRAM::calc_e_read().
double PrechargeUnit::get_i_static () const [inline]
Definition at line 67 of file PrechargeUnit.hh.
References m_i_static.
Referenced by SRAM::calc_i_static().
void PrechargeUnit::init () [private]
Definition at line 79 of file PrechargeUnit.cc.
References TechParameter::calc_draincap(), TechParameter::calc_driver_psize(), calc_num_pre_drain(), calc_num_pre_gate(), calc_pre_cap(), TechParameter::get_EnergyFactor(), SRAM::get_num_data_end(), TechParameter::get_period(), TechParameter::get_PMOS_TAB(), TechParameter::get_SenseEnergyFactor(), TechParameter::get_Wdecinvn(), TechParameter::get_Wdecinvp(), m_e_charge_drain, m_e_charge_gate, m_i_static, m_pre_load, m_pre_size, m_sram_ptr, m_tech_param_ptr, and TechParameter::PCH.
Referenced by PrechargeUnit().
Member Data Documentation
double PrechargeUnit::m_e_charge_drain [private]
Definition at line 84 of file PrechargeUnit.hh.
Referenced by get_e_charge_drain(), and init().
double PrechargeUnit::m_e_charge_gate [private]
Definition at line 83 of file PrechargeUnit.hh.
Referenced by get_e_charge_gate(), and init().
double PrechargeUnit::m_i_static [private]
Definition at line 86 of file PrechargeUnit.hh.
Referenced by get_i_static(), and init().
double PrechargeUnit::m_pre_load [private]
Definition at line 77 of file PrechargeUnit.hh.
Referenced by init(), and PrechargeUnit().
PrechargeModel PrechargeUnit::m_pre_model [private]
Definition at line 76 of file PrechargeUnit.hh.
Referenced by calc_num_pre_drain(), calc_num_pre_gate(), and PrechargeUnit().
double PrechargeUnit::m_pre_size [private]
Definition at line 81 of file PrechargeUnit.hh.
Referenced by init().
const SRAM* PrechargeUnit::m_sram_ptr [private]
Definition at line 78 of file PrechargeUnit.hh.
Referenced by init(), and PrechargeUnit().
const TechParameter* PrechargeUnit::m_tech_param_ptr [private]
Definition at line 79 of file PrechargeUnit.hh.
Referenced by calc_pre_cap(), init(), and PrechargeUnit().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/Buffer/PrechargeUnit.hh
mem/ruby/network/orion/Buffer/PrechargeUnit.cc