gem5: TrafficGen::StateGraph::TraceGen Class Reference
TrafficGen::StateGraph::TraceGen Class Reference
The trace replay generator reads a trace file and plays back the transactions.