gem5: TapListener Class Reference
TapListener Class Reference
Classes
class Event
Public Member Functions
TapListener (EtherTap *t, int p)
~TapListener ()
void accept ()
void listen ()
Protected Attributes
Event * event
ListenSocket listener
EtherTap * tap
int port
Friends
class Event
Detailed Description
Definition at line 59 of file ethertap.cc.
Constructor & Destructor Documentation
TapListener::TapListener (EtherTap * t, int p) [inline]
Definition at line 85 of file ethertap.cc.
TapListener::~TapListener () [inline]
Definition at line 87 of file ethertap.cc.
References MipsISA::event.
Member Function Documentation
void TapListener::accept ()
Definition at line 107 of file ethertap.cc.
References ListenSocket::accept(), EtherTap::attach(), ListenSocket::islistening(), listener, panic, and tap.
void TapListener::listen ()
Definition at line 94 of file ethertap.cc.
References ccprintf(), DPRINTF, event, Event, ListenSocket::getfd(), ListenSocket::listen(), listener, pollQueue, port, and PollQueue::schedule().
Referenced by EtherTap::EtherTap().
Friends And Related Function Documentation
friend class Event [friend]
Definition at line 76 of file ethertap.cc.
Referenced by listen().
Member Data Documentation
Event* TapListener::event [protected]
Definition at line 77 of file ethertap.cc.
Referenced by listen().
ListenSocket TapListener::listener [protected]
Definition at line 80 of file ethertap.cc.
Referenced by accept(), and listen().
int TapListener::port [protected]
Definition at line 82 of file ethertap.cc.
Referenced by listen().
EtherTap* TapListener::tap [protected]
Definition at line 81 of file ethertap.cc.
Referenced by accept().
The documentation for this class was generated from the following file:
dev/ethertap.cc