gem5: PciDev Class Reference
PciDev Class Reference
PCI device, base implementation is only config space.
#include <pcidev.hh>