gem5: Stats::FormulaNode Class Reference
Stats::FormulaNode Class Reference
["Statistic Types"]
#include <statistics.hh>