gem5: MipsISA::Decoder Class Reference
MipsISA::Decoder Class Reference
#include <decoder.hh>
Public Member Functions
Decoder ()
void process ()
void reset ()
void moreBytes (const PCState &pc, Addr fetchPC, MachInst inst)
bool needMoreBytes ()
bool instReady ()
void takeOverFrom (Decoder *old)
StaticInstPtr decodeInst (ExtMachInst mach_inst)
StaticInstPtr decode (ExtMachInst mach_inst, Addr addr)
Decode a machine instruction.
StaticInstPtr decode (MipsISA::PCState &nextPC)
Protected Attributes
ExtMachInst emi
bool instDone
Static Protected Attributes
static GenericISA::BasicDecodeCache defaultCache
A cache of decoded instruction objects.
Detailed Description
Definition at line 43 of file decoder.hh.
Constructor & Destructor Documentation
MipsISA::Decoder::Decoder () [inline]
Definition at line 51 of file decoder.hh.
Member Function Documentation
StaticInstPtr MipsISA::Decoder::decode (ExtMachInst mach_inst, Addr addr) [inline]
Decode a machine instruction.
Parameters:
mach_inst The binary instruction to decode.
Return values:
A pointer to the corresponding StaticInst object.
Definition at line 99 of file decoder.hh.
References GenericISA::BasicDecodeCache::decode(), and defaultCache.
Referenced by decode().
StaticInstPtr MipsISA::Decoder::decode (MipsISA::PCState & nextPC) [inline]
Definition at line 105 of file decoder.hh.
References decode(), emi, GenericISA::PCStateBase::instAddr(), and instDone.
StaticInstPtr MipsISA::Decoder::decodeInst (ExtMachInst mach_inst)
bool MipsISA::Decoder::instReady () [inline]
Definition at line 81 of file decoder.hh.
References instDone.
void MipsISA::Decoder::moreBytes (const PCState & pc, Addr fetchPC, MachInst inst) [inline]
Definition at line 68 of file decoder.hh.
References emi, and instDone.
bool MipsISA::Decoder::needMoreBytes () [inline]
Definition at line 75 of file decoder.hh.
void MipsISA::Decoder::process () [inline]
Definition at line 55 of file decoder.hh.
void MipsISA::Decoder::reset () [inline]
Definition at line 60 of file decoder.hh.
References instDone.
void MipsISA::Decoder::takeOverFrom (Decoder * old) [inline]
Definition at line 86 of file decoder.hh.
Member Data Documentation
GenericISA::BasicDecodeCache MipsISA::Decoder::defaultCache [static, protected]
A cache of decoded instruction objects.
Definition at line 90 of file decoder.hh.
Referenced by decode().
ExtMachInst MipsISA::Decoder::emi [protected]
Definition at line 47 of file decoder.hh.
Referenced by decode(), and moreBytes().
bool MipsISA::Decoder::instDone [protected]
Definition at line 48 of file decoder.hh.
Referenced by decode(), instReady(), moreBytes(), and reset().
The documentation for this class was generated from the following files:
arch/mips/decoder.hh
arch/mips/decoder.cc