gem5: ArmISA::MicroIntImmOp Class Reference
ArmISA::MicroIntImmOp Class Reference
Microops of the form IntRegA = IntRegB op Imm.
#include <macromem.hh>