gem5: BitlineUnit Class Reference
BitlineUnit Class Reference
#include <BitlineUnit.hh>
Public Types
enum BitlineModel { NO_MODEL = 0, RW_BITLINE, WO_BITLINE }
Public Member Functions
BitlineUnit (const string bl_model_str_, const SRAM *sram_ptr_, const TechParameter *tech_param_ptr_)
~BitlineUnit ()
double get_pre_unit_load () const
double get_e_col_read () const
double get_e_col_wrtie () const
double get_i_static () const
Private Member Functions
void init ()
double calc_col_select_cap ()
double calc_col_read_cap ()
double calc_col_write_cap ()
double calc_i_static ()
Private Attributes
BitlineModel m_bl_model
const SRAM * m_sram_ptr
const TechParameter * m_tech_param_ptr
double m_bl_len
double m_bl_wire_cap
double m_pre_unit_load
double m_e_col_sel
double m_e_col_read
double m_e_col_write
double m_i_static
Detailed Description
Definition at line 44 of file BitlineUnit.hh.
Member Enumeration Documentation
enum BitlineUnit::BitlineModel
Enumerator:
NO_MODEL
RW_BITLINE
WO_BITLINE
Definition at line 47 of file BitlineUnit.hh.
Constructor & Destructor Documentation
BitlineUnit::BitlineUnit (const string bl_model_str_, const SRAM * sram_ptr_, const TechParameter * tech_param_ptr_)
Definition at line 41 of file BitlineUnit.cc.
References init(), m_bl_model, m_sram_ptr, m_tech_param_ptr, and NO_MODEL.
BitlineUnit::~BitlineUnit ()
Definition at line 69 of file BitlineUnit.cc.
Member Function Documentation
double BitlineUnit::calc_col_read_cap () [private]
Definition at line 127 of file BitlineUnit.cc.
References TechParameter::calc_draincap(), TechParameter::calc_gatecap(), SRAM::get_is_outdrv(), TechParameter::get_MSCALE(), SRAM::get_num_data_end(), SRAM::get_num_row(), TechParameter::get_Wmemcellr(), TechParameter::get_Woutdrvnandn(), TechParameter::get_Woutdrvnandp(), TechParameter::get_Woutdrvnorn(), TechParameter::get_Woutdrvnorp(), TechParameter::get_WsenseQ1to4(), m_bl_wire_cap, m_pre_unit_load, m_sram_ptr, m_tech_param_ptr, and TechParameter::NCH.
Referenced by init().
double BitlineUnit::calc_col_select_cap () [private]
Definition at line 121 of file BitlineUnit.cc.
References TechParameter::calc_gatecap(), TechParameter::get_Wbitmuxn(), and m_tech_param_ptr.
Referenced by init().
double BitlineUnit::calc_col_write_cap () [private]
Definition at line 172 of file BitlineUnit.cc.
References TechParameter::calc_draincap(), TechParameter::calc_driver_psize(), TechParameter::calc_gatecap(), SRAM::get_num_row(), TechParameter::get_period(), TechParameter::get_Wdecinvn(), TechParameter::get_Wdecinvp(), TechParameter::get_Wmemcellw(), m_bl_wire_cap, m_sram_ptr, m_tech_param_ptr, TechParameter::NCH, and TechParameter::PCH.
Referenced by init().
double BitlineUnit::calc_i_static () [private]
Definition at line 192 of file BitlineUnit.cc.
References TechParameter::get_NMOS_TAB(), TechParameter::get_PMOS_TAB(), TechParameter::get_Wdecinvn(), TechParameter::get_Wdecinvp(), and m_tech_param_ptr.
Referenced by init().
double BitlineUnit::get_e_col_read () const [inline]
Definition at line 65 of file BitlineUnit.hh.
References m_e_col_read.
Referenced by SRAM::calc_e_read().
double BitlineUnit::get_e_col_wrtie () const [inline]
Definition at line 66 of file BitlineUnit.hh.
References m_e_col_write.
Referenced by SRAM::calc_e_write().
double BitlineUnit::get_i_static () const [inline]
Definition at line 67 of file BitlineUnit.hh.
References m_i_static.
Referenced by SRAM::calc_i_static().
double BitlineUnit::get_pre_unit_load () const [inline]
Definition at line 63 of file BitlineUnit.hh.
References m_pre_unit_load.
Referenced by SRAM::init().
void BitlineUnit::init () [private]
Definition at line 72 of file BitlineUnit.cc.
References calc_col_read_cap(), calc_col_select_cap(), calc_col_write_cap(), calc_i_static(), fatal, TechParameter::get_CC3M2metal(), TechParameter::get_CM2metal(), TechParameter::get_EnergyFactor(), SRAM::get_num_data_end(), SRAM::get_num_port(), SRAM::get_num_row(), TechParameter::get_RegCellHeight(), TechParameter::get_SenseEnergyFactor(), TechParameter::get_WordlineSpacing(), m_bl_len, m_bl_model, m_bl_wire_cap, m_e_col_read, m_e_col_sel, m_e_col_write, m_i_static, m_sram_ptr, m_tech_param_ptr, RW_BITLINE, and WO_BITLINE.
Referenced by BitlineUnit().
Member Data Documentation
double BitlineUnit::m_bl_len [private]
Definition at line 81 of file BitlineUnit.hh.
Referenced by init().
BitlineModel BitlineUnit::m_bl_model [private]
Definition at line 77 of file BitlineUnit.hh.
Referenced by BitlineUnit(), and init().
double BitlineUnit::m_bl_wire_cap [private]
Definition at line 82 of file BitlineUnit.hh.
Referenced by calc_col_read_cap(), calc_col_write_cap(), and init().
double BitlineUnit::m_e_col_read [private]
Definition at line 86 of file BitlineUnit.hh.
Referenced by get_e_col_read(), and init().
double BitlineUnit::m_e_col_sel [private]
Definition at line 85 of file BitlineUnit.hh.
Referenced by init().
double BitlineUnit::m_e_col_write [private]
Definition at line 87 of file BitlineUnit.hh.
Referenced by get_e_col_wrtie(), and init().
double BitlineUnit::m_i_static [private]
Definition at line 89 of file BitlineUnit.hh.
Referenced by get_i_static(), and init().
double BitlineUnit::m_pre_unit_load [private]
Definition at line 83 of file BitlineUnit.hh.
Referenced by calc_col_read_cap(), and get_pre_unit_load().
const SRAM* BitlineUnit::m_sram_ptr [private]
Definition at line 78 of file BitlineUnit.hh.
Referenced by BitlineUnit(), calc_col_read_cap(), calc_col_write_cap(), and init().
const TechParameter* BitlineUnit::m_tech_param_ptr [private]
Definition at line 79 of file BitlineUnit.hh.
Referenced by BitlineUnit(), calc_col_read_cap(), calc_col_select_cap(), calc_col_write_cap(), calc_i_static(), and init().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/Buffer/BitlineUnit.hh
mem/ruby/network/orion/Buffer/BitlineUnit.cc