gem5: EtherInt Class Reference
EtherInt Class Reference
#include <etherint.hh>