gem5: ElfObject Class Reference
ElfObject Class Reference
#include <elf_object.hh>