gem5: Cache< TagStore > Class Template Reference
Cache< TagStore > Class Template Reference
A template-policy based cache.
#include <cache.hh>