gem5: BasePrefetcher Class Reference
BasePrefetcher Class Reference
#include <base.hh>