gem5: CacheProfiler Class Reference
CacheProfiler Class Reference
#include <CacheProfiler.hh>
Public Member Functions
CacheProfiler (const std::string &description)
~CacheProfiler ()
void printStats (std::ostream &out) const
void clearStats ()
void addCacheStatSample (RubyRequestType requestType, RubyAccessMode type, PrefetchBit pfBit)
void addGenericStatSample (GenericRequestType requestType, RubyAccessMode type, PrefetchBit pfBit)
void print (std::ostream &out) const
Private Member Functions
CacheProfiler (const CacheProfiler &obj)
CacheProfiler & operator= (const CacheProfiler &obj)
void addStatSample (RubyAccessMode type, PrefetchBit pfBit)
Private Attributes
std::string m_description
int64 m_misses
int64 m_demand_misses
int64 m_prefetches
int64 m_sw_prefetches
int64 m_hw_prefetches
int64 m_accessModeTypeHistogram [RubyAccessMode_NUM]
std::vector< int > m_cacheRequestType
std::vector< int > m_genericRequestType
Detailed Description
Definition at line 43 of file CacheProfiler.hh.
Constructor & Destructor Documentation
CacheProfiler::CacheProfiler (const std::string & description)
CacheProfiler::~CacheProfiler ()
Definition at line 43 of file CacheProfiler.cc.
CacheProfiler::CacheProfiler (const CacheProfiler & obj) [private]
Member Function Documentation
void CacheProfiler::addCacheStatSample (RubyRequestType requestType, RubyAccessMode type, PrefetchBit pfBit)
Definition at line 131 of file CacheProfiler.cc.
References addStatSample(), and m_cacheRequestType.
Referenced by CacheMemory::profileMiss().
void CacheProfiler::addGenericStatSample (GenericRequestType requestType, RubyAccessMode type, PrefetchBit pfBit)
Definition at line 140 of file CacheProfiler.cc.
References addStatSample(), and m_genericRequestType.
Referenced by CacheMemory::profileGenericRequest().
void CacheProfiler::addStatSample (RubyAccessMode type, PrefetchBit pfBit) [private]
Definition at line 149 of file CacheProfiler.cc.
References m_accessModeTypeHistogram, m_demand_misses, m_hw_prefetches, m_misses, m_prefetches, and m_sw_prefetches.
Referenced by addCacheStatSample(), and addGenericStatSample().
void CacheProfiler::clearStats ()
Definition at line 112 of file CacheProfiler.cc.
References ArmISA::i, m_accessModeTypeHistogram, m_cacheRequestType, m_demand_misses, m_genericRequestType, m_hw_prefetches, m_misses, m_prefetches, and m_sw_prefetches.
Referenced by CacheMemory::clearStats().
CacheProfiler& CacheProfiler::operator= (const CacheProfiler & obj) [private]
void CacheProfiler::print (std::ostream & out) const
Referenced by operator<<().
void CacheProfiler::printStats (std::ostream & out) const
Member Data Documentation
int64 CacheProfiler::m_accessModeTypeHistogram[RubyAccessMode_NUM] [private]
Definition at line 74 of file CacheProfiler.hh.
Referenced by addStatSample(), and clearStats().
std::vector<int> CacheProfiler::m_cacheRequestType [private]
Definition at line 76 of file CacheProfiler.hh.
Referenced by addCacheStatSample(), and clearStats().
int64 CacheProfiler::m_demand_misses [private]
Definition at line 70 of file CacheProfiler.hh.
Referenced by addStatSample(), and clearStats().
std::string CacheProfiler::m_description [private]
Definition at line 68 of file CacheProfiler.hh.
std::vector<int> CacheProfiler::m_genericRequestType [private]
Definition at line 77 of file CacheProfiler.hh.
Referenced by addGenericStatSample(), and clearStats().
int64 CacheProfiler::m_hw_prefetches [private]
Definition at line 73 of file CacheProfiler.hh.
Referenced by addStatSample(), and clearStats().
int64 CacheProfiler::m_misses [private]
Definition at line 69 of file CacheProfiler.hh.
Referenced by addStatSample(), and clearStats().
int64 CacheProfiler::m_prefetches [private]
Definition at line 71 of file CacheProfiler.hh.
Referenced by addStatSample(), and clearStats().
int64 CacheProfiler::m_sw_prefetches [private]
Definition at line 72 of file CacheProfiler.hh.
Referenced by addStatSample(), and clearStats().
The documentation for this class was generated from the following files:
mem/ruby/profiler/CacheProfiler.hh
mem/ruby/profiler/CacheProfiler.cc