gem5: Clock Class Reference
Clock Class Reference
#include <Clock.hh>
Public Member Functions
Clock (bool is_in_buf_, bool is_in_shared_switch_, bool is_out_buf_, bool is_out_shared_switch_, const OrionConfig *orion_cfg_ptr_)
~Clock ()
double get_dynamic_energy () const
double get_static_power () const
Private Member Functions
void init ()
double calc_cap_pipe_reg ()
Private Attributes
bool m_is_in_buf
bool m_is_in_shared_switch
bool m_is_out_buf
bool m_is_out_shared_switch
const OrionConfig * m_orion_cfg_ptr
const TechParameter * m_tech_param_ptr
double m_e_pipe_reg
double m_e_htree
double m_i_static
Detailed Description
Definition at line 44 of file Clock.hh.
Constructor & Destructor Documentation
Clock::Clock (bool is_in_buf_, bool is_in_shared_switch_, bool is_out_buf_, bool is_out_shared_switch_, const OrionConfig * orion_cfg_ptr_)
Definition at line 41 of file Clock.cc.
References init(), m_is_in_buf, m_is_in_shared_switch, m_is_out_buf, m_is_out_shared_switch, and m_orion_cfg_ptr.
Clock::~Clock ()
Definition at line 58 of file Clock.cc.
Member Function Documentation
double Clock::calc_cap_pipe_reg () [private]
double Clock::get_dynamic_energy () const
Definition at line 61 of file Clock.cc.
References m_e_htree, and m_e_pipe_reg.
Referenced by OrionRouter::calc_dynamic_energy_clock().
double Clock::get_static_power () const
Definition at line 66 of file Clock.cc.
References TechParameter::get_vdd(), m_i_static, and m_tech_param_ptr.
Referenced by OrionRouter::get_static_power_clock().
void Clock::init () [private]
Definition at line 72 of file Clock.cc.
References ArmISA::e, OrionConfig::get(), TechParameter::get_BufferNMOSOffCurrent(), TechParameter::get_BufferPMOSOffCurrent(), TechParameter::get_ClockCap(), TechParameter::get_DFF_TAB(), TechParameter::get_EnergyFactor(), OrionConfig::get_flit_width(), OrionConfig::get_num_in_port(), OrionConfig::get_num_out_port(), OrionConfig::get_num_vchannel(), OrionConfig::get_num_vclass(), TechParameter::get_SCALE_S(), OrionConfig::get_tech_param_ptr(), TechParameter::get_Wdff(), TechParameter::is_trans_type_hvt(), TechParameter::is_trans_type_nvt(), MipsISA::k, m_e_htree, m_e_pipe_reg, m_i_static, m_is_in_buf, m_is_in_shared_switch, m_is_out_buf, m_is_out_shared_switch, m_orion_cfg_ptr, and m_tech_param_ptr.
Referenced by Clock().
Member Data Documentation
double Clock::m_e_htree [private]
Definition at line 73 of file Clock.hh.
Referenced by get_dynamic_energy(), and init().
double Clock::m_e_pipe_reg [private]
Definition at line 72 of file Clock.hh.
Referenced by get_dynamic_energy(), and init().
double Clock::m_i_static [private]
Definition at line 74 of file Clock.hh.
Referenced by get_static_power(), and init().
bool Clock::m_is_in_buf [private]
Definition at line 65 of file Clock.hh.
Referenced by Clock(), and init().
bool Clock::m_is_in_shared_switch [private]
Definition at line 66 of file Clock.hh.
Referenced by Clock(), and init().
bool Clock::m_is_out_buf [private]
Definition at line 67 of file Clock.hh.
Referenced by Clock(), and init().
bool Clock::m_is_out_shared_switch [private]
Definition at line 68 of file Clock.hh.
Referenced by Clock(), and init().
const OrionConfig* Clock::m_orion_cfg_ptr [private]
Definition at line 69 of file Clock.hh.
Referenced by Clock(), and init().
const TechParameter* Clock::m_tech_param_ptr [private]
Definition at line 70 of file Clock.hh.
Referenced by get_static_power(), and init().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/Clock.hh
mem/ruby/network/orion/Clock.cc