gem5: Stats::Distribution Class Reference
Stats::Distribution Class Reference
["Statistic Types"]
A simple distribution stat.
#include <statistics.hh>