gem5: EndQuiesceEvent Class Reference
EndQuiesceEvent Class Reference
Event for timing out quiesce instruction.
#include <quiesce_event.hh>