gem5: BasicExtLink Class Reference
BasicExtLink Class Reference
#include <BasicLink.hh>