gem5: IGbE Class Reference
IGbE Class Reference
#include <i8254xGBe.hh>