gem5: Resource Class Reference
Resource Class Reference
#include <resource.hh>