gem5: MemCmd Class Reference
MemCmd Class Reference
#include <packet.hh>
Classes
struct CommandInfo
Structure that defines attributes and other data associated with a Command.
Public Types
enum Command {
InvalidCmd, ReadReq, ReadResp, ReadRespWithInvalidate,
WriteReq, WriteResp, Writeback, SoftPFReq,
HardPFReq, SoftPFResp, HardPFResp, WriteInvalidateReq,
WriteInvalidateResp, UpgradeReq, SCUpgradeReq, UpgradeResp,
SCUpgradeFailReq, UpgradeFailResp, ReadExReq, ReadExResp,
LoadLockedReq, StoreCondReq, StoreCondFailReq, StoreCondResp,
SwapReq, SwapResp, MessageReq, MessageResp,
InvalidDestError, BadAddressError, FunctionalReadError, FunctionalWriteError,
PrintReq, FlushReq, InvalidationReq, NUM_MEM_CMDS
}
List of all commands associated with a packet.
Public Member Functions
bool isRead () const
bool isWrite () const
bool isUpgrade () const
bool isRequest () const
bool isResponse () const
bool needsExclusive () const
bool needsResponse () const
bool isInvalidate () const
bool hasData () const
bool isReadWrite () const
bool isLLSC () const
bool isError () const
bool isPrint () const
bool isFlush () const
const Command responseCommand () const
const std::string & toString () const
Return the string to a cmd given by idx.
int toInt () const
MemCmd (Command _cmd)
MemCmd (int _cmd)
MemCmd ()
bool operator== (MemCmd c2) const
bool operator!= (MemCmd c2) const
Private Types
enum Attribute {
IsRead, IsWrite, IsUpgrade, IsInvalidate,
NeedsExclusive, IsRequest, IsResponse, NeedsResponse,
IsSWPrefetch, IsHWPrefetch, IsLlsc, HasData,
IsError, IsPrint, IsFlush, NUM_COMMAND_ATTRIBUTES
}
List of command attributes.
Private Member Functions
bool testCmdAttrib (MemCmd::Attribute attrib) const
Private Attributes
Command cmd
Static Private Attributes
static const CommandInfo commandInfo []
Array to map Command enum to associated info.
Friends
class Packet
Detailed Description
Definition at line 73 of file packet.hh.
Member Enumeration Documentation
enum MemCmd::Attribute [private]
List of command attributes.
Enumerator:
IsRead
Data flows from responder to requester.
IsWrite
Data flows from requester to responder.
IsUpgrade
IsInvalidate
NeedsExclusive
Requires exclusive copy to complete in-cache.
IsRequest
Issued by requester.
IsResponse
Issue by responder.
NeedsResponse
Requester needs response from target.
IsSWPrefetch
IsHWPrefetch
IsLlsc
Alpha/MIPS LL or SC access.
HasData
There is an associated payload.
IsError
Error response.
IsPrint
Print state matching address (for debugging).
IsFlush
Flush the address from caches.
NUM_COMMAND_ATTRIBUTES
Definition at line 138 of file packet.hh.
enum MemCmd::Command
List of all commands associated with a packet.
Enumerator:
InvalidCmd
ReadReq
ReadResp
ReadRespWithInvalidate
WriteReq
WriteResp
Writeback
SoftPFReq
HardPFReq
SoftPFResp
HardPFResp
WriteInvalidateReq
WriteInvalidateResp
UpgradeReq
SCUpgradeReq
UpgradeResp
SCUpgradeFailReq
UpgradeFailResp
ReadExReq
ReadExResp
LoadLockedReq
StoreCondReq
StoreCondFailReq
StoreCondResp
SwapReq
SwapResp
MessageReq
MessageResp
InvalidDestError
BadAddressError
FunctionalReadError
FunctionalWriteError
PrintReq
FlushReq
InvalidationReq
NUM_MEM_CMDS
Definition at line 81 of file packet.hh.
Constructor & Destructor Documentation
MemCmd::MemCmd (Command _cmd) [inline]
Definition at line 213 of file packet.hh.
MemCmd::MemCmd (int _cmd) [inline]
Definition at line 214 of file packet.hh.
MemCmd::MemCmd () [inline]
Definition at line 215 of file packet.hh.
Member Function Documentation
bool MemCmd::hasData () const [inline]
Definition at line 196 of file packet.hh.
References HasData, and testCmdAttrib().
Referenced by Packet::hasData().
bool MemCmd::isError () const [inline]
Definition at line 199 of file packet.hh.
References IsError, and testCmdAttrib().
Referenced by Packet::isError().
bool MemCmd::isFlush () const [inline]
Definition at line 201 of file packet.hh.
References IsFlush, and testCmdAttrib().
Referenced by Packet::isFlush().
bool MemCmd::isInvalidate () const [inline]
Definition at line 195 of file packet.hh.
References IsInvalidate, and testCmdAttrib().
Referenced by Packet::isInvalidate().
bool MemCmd::isLLSC () const [inline]
Definition at line 198 of file packet.hh.
References IsLlsc, and testCmdAttrib().
Referenced by Packet::isLLSC().
bool MemCmd::isPrint () const [inline]
Definition at line 200 of file packet.hh.
References IsPrint, and testCmdAttrib().
Referenced by Packet::isPrint().
bool MemCmd::isRead () const [inline]
Definition at line 188 of file packet.hh.
References IsRead, and testCmdAttrib().
Referenced by TrafficGen::StateGraph::TraceGen::execute(), Packet::isRead(), isReadWrite(), and TrafficGen::StateGraph::TraceGen::nextExecuteTick().
bool MemCmd::isReadWrite () const [inline]
Definition at line 197 of file packet.hh.
References isRead(), and isWrite().
Referenced by Packet::isReadWrite().
bool MemCmd::isRequest () const [inline]
Definition at line 191 of file packet.hh.
References IsRequest, and testCmdAttrib().
Referenced by Packet::isRequest().
bool MemCmd::isResponse () const [inline]
Definition at line 192 of file packet.hh.
References IsResponse, and testCmdAttrib().
Referenced by Packet::isResponse().
bool MemCmd::isUpgrade () const [inline]
Definition at line 190 of file packet.hh.
References IsUpgrade, and testCmdAttrib().
Referenced by Packet::isUpgrade().
bool MemCmd::isWrite () const [inline]
Definition at line 189 of file packet.hh.
References IsWrite, and testCmdAttrib().
Referenced by isReadWrite(), Packet::isWrite(), and TrafficGen::StateGraph::BaseGen::send().
bool MemCmd::needsExclusive () const [inline]
Definition at line 193 of file packet.hh.
References NeedsExclusive, and testCmdAttrib().
Referenced by Packet::needsExclusive().
bool MemCmd::needsResponse () const [inline]
Definition at line 194 of file packet.hh.
References NeedsResponse, and testCmdAttrib().
Referenced by Packet::needsResponse().
bool MemCmd::operator!= (MemCmd c2) const [inline]
Definition at line 218 of file packet.hh.
References cmd.
bool MemCmd::operator== (MemCmd c2) const [inline]
Definition at line 217 of file packet.hh.
References cmd.
const Command MemCmd::responseCommand () const [inline]
Definition at line 204 of file packet.hh.
References cmd, commandInfo, and MemCmd::CommandInfo::response.
Referenced by TimingSimpleCPU::buildSplitPacket(), and Packet::makeResponse().
bool MemCmd::testCmdAttrib (MemCmd::Attribute attrib) const [inline, private]
Definition at line 181 of file packet.hh.
References MemCmd::CommandInfo::attributes, cmd, and commandInfo.
Referenced by hasData(), isError(), isFlush(), isInvalidate(), isLLSC(), isPrint(), isRead(), isRequest(), isResponse(), isUpgrade(), isWrite(), needsExclusive(), and needsResponse().
int MemCmd::toInt () const [inline]
Definition at line 211 of file packet.hh.
References cmd.
Referenced by Packet::cmdToIndex().
const std::string& MemCmd::toString () const [inline]
Return the string to a cmd given by idx.
Definition at line 210 of file packet.hh.
References cmd, commandInfo, and MemCmd::CommandInfo::str.
Referenced by Packet::cmdString(), MessageSlavePort::recvAtomic(), and BaseCache::regStats().
Friends And Related Function Documentation
friend class Packet [friend]
Definition at line 75 of file packet.hh.
Member Data Documentation
Command MemCmd::cmd [private]
Definition at line 178 of file packet.hh.
Referenced by operator!=(), operator==(), TrafficGen::StateGraph::TraceGen::InputStream::read(), responseCommand(), testCmdAttrib(), toInt(), and toString().
const MemCmd::CommandInfo MemCmd::commandInfo [static, private]
Array to map Command enum to associated info.
Definition at line 174 of file packet.hh.
Referenced by responseCommand(), testCmdAttrib(), and toString().
The documentation for this class was generated from the following files:
mem/packet.hh
mem/packet.cc