gem5: Set Class Reference
Set Class Reference
#include <Set.hh>
Public Member Functions
Set ()
Set (int size)
Set (const Set &obj)
~Set ()
Set & operator= (const Set &obj)
void add (NodeID index)
void addSet (const Set &set)
void addRandom ()
void remove (NodeID index)
void removeSet (const Set &set)
void clear ()
void broadcast ()
int count () const
bool isEqual (const Set &set) const
Set OR (const Set &orSet) const
Set AND (const Set &andSet) const
bool intersectionIsEmpty (const Set &other_set) const
bool isSuperset (const Set &test) const
bool isSubset (const Set &test) const
bool isElement (NodeID element) const
bool isBroadcast () const
bool isEmpty () const
NodeID smallestElement () const
void setSize (int size)
NodeID elementAt (int index) const
int getSize () const
void print (std::ostream &out) const
Private Member Functions
void clearExcess ()
Private Attributes
int m_nSize
int m_nArrayLen
long * m_p_nArray
long m_p_nArray_Static [NUMBER_WORDS_PER_SET]
Static Private Attributes
static const int LONG_BITS = std::numeric_limits<long>::digits + 1
static const int INDEX_SHIFT = LONG_BITS == 64 ? 6 : 5
static const int INDEX_MASK = (1 << INDEX_SHIFT) - 1
Detailed Description
Definition at line 53 of file Set.hh.
Constructor & Destructor Documentation
Set::Set ()
Definition at line 38 of file Set.cc.
References m_nArrayLen, m_nSize, and m_p_nArray.
Set::Set (int size)
Definition at line 55 of file Set.cc.
References m_nArrayLen, m_nSize, m_p_nArray, and setSize().
Set::Set (const Set & obj)
Definition at line 45 of file Set.cc.
References ArmISA::i, m_nArrayLen, m_nSize, m_p_nArray, and setSize().
Set::~Set ()
Definition at line 64 of file Set.cc.
References m_p_nArray, and m_p_nArray_Static.
Member Function Documentation
void Set::add (NodeID index) [inline]
Definition at line 83 of file Set.hh.
References INDEX_MASK, INDEX_SHIFT, and m_p_nArray.
Referenced by AccessTraceForAddress::update().
void Set::addRandom ()
Definition at line 110 of file Set.cc.
References clearExcess(), ArmISA::i, m_nArrayLen, m_p_nArray, and random().
void Set::addSet (const Set & set)
Definition at line 98 of file Set.cc.
References getSize(), ArmISA::i, m_nArrayLen, and m_p_nArray.
Referenced by AddressProfiler::profileGetS(), AddressProfiler::profileGetX(), and Profiler::profileSharing().
Set Set::AND (const Set & andSet) const
Definition at line 271 of file Set.cc.
References ArmISA::i, m_nArrayLen, m_nSize, and m_p_nArray.
void Set::broadcast ()
Definition at line 136 of file Set.cc.
References clearExcess(), ArmISA::i, m_nArrayLen, and m_p_nArray.
void Set::clear () [inline]
Definition at line 102 of file Set.hh.
References ArmISA::i, m_nArrayLen, and m_p_nArray.
Referenced by setSize().
void Set::clearExcess () [private]
Definition at line 72 of file Set.cc.
References INDEX_MASK, ArmISA::j, LONG_BITS, m_nArrayLen, m_nSize, m_p_nArray, and ArmISA::mask.
Referenced by addRandom(), and broadcast().
int Set::count () const
Definition at line 148 of file Set.cc.
References ArmISA::i, ArmISA::j, LONG_BITS, m_nArrayLen, m_p_nArray, and ArmISA::mask.
Referenced by AccessTraceForAddress::getTouchedBy(), AccessTraceForAddress::print(), AddressProfiler::profileGetS(), AddressProfiler::profileGetX(), Profiler::profileSharing(), and smallestElement().
NodeID Set::elementAt (int index) const [inline]
Definition at line 146 of file Set.hh.
References isElement().
int Set::getSize () const [inline]
Definition at line 154 of file Set.hh.
References m_nSize.
Referenced by addSet(), and operator=().
bool Set::intersectionIsEmpty (const Set & other_set) const [inline]
Definition at line 120 of file Set.hh.
References ArmISA::i, m_nArrayLen, and m_p_nArray.
bool Set::isBroadcast () const
Definition at line 216 of file Set.cc.
References ArmISA::i, ArmISA::j, LONG_BITS, m_nArrayLen, m_nSize, m_p_nArray, and ArmISA::mask.
bool Set::isElement (NodeID element) const [inline]
Definition at line 132 of file Set.hh.
References INDEX_MASK, INDEX_SHIFT, and m_p_nArray.
Referenced by elementAt().
bool Set::isEmpty () const
Definition at line 246 of file Set.cc.
References ArmISA::i, m_nArrayLen, and m_p_nArray.
bool Set::isEqual (const Set & set) const
Definition at line 173 of file Set.cc.
References ArmISA::i, m_nArrayLen, m_nSize, and m_p_nArray.
bool Set::isSubset (const Set & test) const [inline]
Definition at line 129 of file Set.hh.
References isSuperset().
bool Set::isSuperset (const Set & test) const
Definition at line 288 of file Set.cc.
References ArmISA::i, m_nArrayLen, m_nSize, and m_p_nArray.
Referenced by isSubset().
Set & Set::operator= (const Set & obj)
Definition at line 332 of file Set.cc.
References getSize(), ArmISA::i, m_nArrayLen, m_p_nArray, and setSize().
Set Set::OR (const Set & orSet) const
Definition at line 259 of file Set.cc.
References ArmISA::i, m_nArrayLen, m_nSize, and m_p_nArray.
void Set::print (std::ostream & out) const
Definition at line 347 of file Set.cc.
References csprintf(), ArmISA::i, m_nArrayLen, m_nSize, and m_p_nArray.
Referenced by operator<<().
void Set::remove (NodeID index) [inline]
Definition at line 93 of file Set.hh.
References MipsISA::index, INDEX_MASK, INDEX_SHIFT, and m_p_nArray.
Referenced by AddressProfiler::profileGetS(), AddressProfiler::profileGetX(), and Profiler::profileSharing().
void Set::removeSet (const Set & set)
Definition at line 125 of file Set.cc.
References ArmISA::i, m_nArrayLen, m_nSize, and m_p_nArray.
void Set::setSize (int size)
Definition at line 300 of file Set.cc.
References clear(), LONG_BITS, m_nArrayLen, m_nSize, m_p_nArray, m_p_nArray_Static, and NUMBER_WORDS_PER_SET.
Referenced by operator=(), and Set().
NodeID Set::smallestElement () const
Definition at line 188 of file Set.cc.
References count(), ArmISA::i, ArmISA::j, LONG_BITS, m_nArrayLen, m_p_nArray, panic, and X86ISA::x.
Member Data Documentation
const int Set::INDEX_MASK = (1 << INDEX_SHIFT) - 1 [static, private]
Definition at line 70 of file Set.hh.
Referenced by add(), clearExcess(), isElement(), and remove().
const int Set::INDEX_SHIFT = LONG_BITS == 64 ? 6 : 5 [static, private]
Definition at line 69 of file Set.hh.
Referenced by add(), isElement(), and remove().
const int Set::LONG_BITS = std::numeric_limits<long>::digits + 1 [static, private]
Definition at line 68 of file Set.hh.
Referenced by clearExcess(), count(), isBroadcast(), setSize(), and smallestElement().
int Set::m_nArrayLen [private]
Definition at line 57 of file Set.hh.
Referenced by addRandom(), addSet(), AND(), broadcast(), clear(), clearExcess(), count(), intersectionIsEmpty(), isBroadcast(), isEmpty(), isEqual(), isSuperset(), operator=(), OR(), print(), removeSet(), Set(), setSize(), and smallestElement().
int Set::m_nSize [private]
Definition at line 56 of file Set.hh.
Referenced by AND(), clearExcess(), getSize(), isBroadcast(), isEqual(), isSuperset(), OR(), print(), removeSet(), Set(), and setSize().
long* Set::m_p_nArray [private]
Definition at line 65 of file Set.hh.
Referenced by add(), addRandom(), addSet(), AND(), broadcast(), clear(), clearExcess(), count(), intersectionIsEmpty(), isBroadcast(), isElement(), isEmpty(), isEqual(), isSuperset(), operator=(), OR(), print(), remove(), removeSet(), Set(), setSize(), smallestElement(), and ~Set().
long Set::m_p_nArray_Static[NUMBER_WORDS_PER_SET] [private]
Definition at line 66 of file Set.hh.
Referenced by setSize(), and ~Set().
The documentation for this class was generated from the following files:
mem/ruby/common/Set.hh
mem/ruby/common/Set.cc