gem5: RubyRequest Class Reference
RubyRequest Class Reference
#include <RubyRequest.hh>