gem5: PersistentTable Class Reference
PersistentTable Class Reference
#include <PersistentTable.hh>
Public Member Functions
PersistentTable ()
~PersistentTable ()
void persistentRequestLock (const Address &address, MachineID locker, AccessType type)
void persistentRequestUnlock (const Address &address, MachineID unlocker)
bool okToIssueStarving (const Address &address, MachineID machID) const
MachineID findSmallest (const Address &address) const
AccessType typeOfSmallest (const Address &address) const
void markEntries (const Address &address)
bool isLocked (const Address &addr) const
int countStarvingForAddress (const Address &addr) const
int countReadStarvingForAddress (const Address &addr) const
void print (std::ostream &out) const
Private Types
typedef m5::hash_map< Address,
PersistentTableEntry > AddressMap
Private Member Functions
PersistentTable (const PersistentTable &obj)
PersistentTable & operator= (const PersistentTable &obj)
Private Attributes
AddressMap m_map
Detailed Description
Definition at line 51 of file PersistentTable.hh.
Member Typedef Documentation
typedef m5::hash_map<Address, PersistentTableEntry> PersistentTable::AddressMap [private]
Definition at line 80 of file PersistentTable.hh.
Constructor & Destructor Documentation
PersistentTable::PersistentTable ()
Definition at line 41 of file PersistentTable.cc.
PersistentTable::~PersistentTable ()
Definition at line 45 of file PersistentTable.cc.
PersistentTable::PersistentTable (const PersistentTable & obj) [private]
Member Function Documentation
int PersistentTable::countReadStarvingForAddress (const Address & addr) const
Definition at line 204 of file PersistentTable.cc.
References NetDest::count(), ArmISA::i, line_address(), m_map, PersistentTableEntry::m_request_to_write, and PersistentTableEntry::m_starving.
int PersistentTable::countStarvingForAddress (const Address & addr) const
Definition at line 192 of file PersistentTable.cc.
References NetDest::count(), ArmISA::i, line_address(), m_map, and PersistentTableEntry::m_starving.
MachineID PersistentTable::findSmallest (const Address & address) const
Definition at line 141 of file PersistentTable.cc.
References ArmISA::i, line_address(), and m_map.
bool PersistentTable::isLocked (const Address & addr) const
Definition at line 183 of file PersistentTable.cc.
References line_address(), and m_map.
void PersistentTable::markEntries (const Address & address)
Definition at line 166 of file PersistentTable.cc.
References ArmISA::i, NetDest::isEmpty(), line_address(), m_map, PersistentTableEntry::m_marked, and PersistentTableEntry::m_starving.
bool PersistentTable::okToIssueStarving (const Address & address, MachineID machID) const
Definition at line 118 of file PersistentTable.cc.
References ArmISA::i, NetDest::isElement(), NetDest::isEmpty(), line_address(), m_map, PersistentTableEntry::m_marked, and PersistentTableEntry::m_starving.
PersistentTable& PersistentTable::operator= (const PersistentTable & obj) [private]
void PersistentTable::persistentRequestLock (const Address & address, MachineID locker, AccessType type)
Definition at line 50 of file PersistentTable.cc.
References NetDest::add(), ArmISA::i, NetDest::isElement(), NetDest::isSubset(), line_address(), m_map, PersistentTableEntry::m_marked, PersistentTableEntry::m_request_to_write, PersistentTableEntry::m_starving, X86ISA::present, and MipsISA::r.
void PersistentTable::persistentRequestUnlock (const Address & address, MachineID unlocker)
Definition at line 85 of file PersistentTable.cc.
References line_address(), and m_map.
void PersistentTable::print (std::ostream & out) const
Referenced by operator<<().
AccessType PersistentTable::typeOfSmallest (const Address & address) const
Definition at line 151 of file PersistentTable.cc.
References ArmISA::i, line_address(), and m_map.
Member Data Documentation
AddressMap PersistentTable::m_map [private]
Definition at line 81 of file PersistentTable.hh.
Referenced by countReadStarvingForAddress(), countStarvingForAddress(), findSmallest(), isLocked(), markEntries(), okToIssueStarving(), persistentRequestLock(), persistentRequestUnlock(), and typeOfSmallest().
The documentation for this class was generated from the following files:
mem/ruby/system/PersistentTable.hh
mem/ruby/system/PersistentTable.cc