gem5: LinuxAlphaSystem Class Reference
LinuxAlphaSystem Class Reference
This class contains linux specific system code (Loading, Events).
#include <system.hh>