gem5: Stats::Formula Class Reference
Stats::Formula Class Reference
["Statistic Types"]
A formula for statistics that is calculated when printed.
#include <statistics.hh>