gem5: TrafficGen::StateGraph::TraceGen::InputStream Class Reference
TrafficGen::StateGraph::TraceGen::InputStream Class Reference
The InputStream encapsulates a trace file and the internal buffers and populates TraceElements based on the input.
Public Member Functions
InputStream (const std::string &filename)
Create a trace input stream for a given file name.
void reset ()
Reset the stream such that it can be played once again.
bool read (TraceElement &element)
Attempt to read a trace element from the stream, and also notify the caller if the end of the file was reached.
Private Attributes
ProtoInputStream trace
Input file stream for the protobuf trace.
Detailed Description
The InputStream encapsulates a trace file and the internal buffers and populates TraceElements based on the input.
Definition at line 456 of file traffic_gen.hh.
Constructor & Destructor Documentation
TrafficGen::StateGraph::TraceGen::InputStream::InputStream (const std::string & filename)
Create a trace input stream for a given file name.
Parameters:
filename Path to the file to read from
Member Function Documentation
bool TrafficGen::StateGraph::TraceGen::InputStream::read (TraceElement & element)
Attempt to read a trace element from the stream, and also notify the caller if the end of the file was reached.
Parameters:
element Trace element to populate
Returns:
True if an element could be read successfully
Definition at line 515 of file traffic_gen.cc.
References TrafficGen::StateGraph::TraceGen::TraceElement::addr, TrafficGen::StateGraph::TraceGen::TraceElement::blocksize, MemCmd::cmd, TrafficGen::StateGraph::TraceGen::TraceElement::cmd, ProtoInputStream::read(), TrafficGen::StateGraph::TraceGen::TraceElement::tick, and trace.
Referenced by TrafficGen::StateGraph::TraceGen::nextExecuteTick().
void TrafficGen::StateGraph::TraceGen::InputStream::reset ()
Reset the stream such that it can be played once again.
Definition at line 509 of file traffic_gen.cc.
References ProtoInputStream::reset(), and trace.
Referenced by TrafficGen::StateGraph::TraceGen::exit().
Member Data Documentation
ProtoInputStream TrafficGen::StateGraph::TraceGen::InputStream::trace [private]
Input file stream for the protobuf trace.
Definition at line 462 of file traffic_gen.hh.
Referenced by read(), and reset().
The documentation for this class was generated from the following files:
cpu/testers/traffic_gen/traffic_gen.hh
cpu/testers/traffic_gen/traffic_gen.cc