gem5: RefCountingPtr< T > Class Template Reference
RefCountingPtr< T > Class Template Reference
If you want a reference counting pointer to a mutable object, create it like this:
#include <refcnt.hh>
Public Member Functions
RefCountingPtr ()
Create an empty reference counting pointer.
RefCountingPtr (T *data)
Create a new reference counting pointer to some object (probably something newly created).
RefCountingPtr (const RefCountingPtr &r)
Create a new reference counting pointer by copying another one.
~RefCountingPtr ()
Destroy the pointer and any reference it may hold.
T * operator-> () const
Access a member variable.
T & operator* () const
Dereference the pointer.
T * get () const
Directly access the pointer itself without taking a reference.
const RefCountingPtr & operator= (T *p)
Assign a new value to the pointer.
const RefCountingPtr & operator= (const RefCountingPtr &r)
Copy the pointer from another RefCountingPtr.
bool operator! () const
Check if the pointer is empty.
operator bool () const
Check if the pointer is non-empty.
Protected Member Functions
void copy (T *d)
Copy a new pointer value and increment the reference count if it is a valid pointer.
void del ()
Delete the reference to any existing object if it is non NULL.
void set (T *d)
Drop the old reference and change it to something new.
Protected Attributes
T * data
The stored pointer.
Detailed Description
template<class T>
class RefCountingPtr< T >
If you want a reference counting pointer to a mutable object, create it like this:
 typedef RefCountingPtr<Foo> FooPtr;
Attention:
Do not use "const FooPtr" To create a reference counting pointer to a const object, use this:
 typedef RefCountingPtr<const Foo> ConstFooPtr;
These two usages are analogous to iterator and const_iterator in the stl.
Definition at line 106 of file refcnt.hh.
Constructor & Destructor Documentation
template<class T> RefCountingPtr< T >::RefCountingPtr () [inline]
Create an empty reference counting pointer.
Definition at line 156 of file refcnt.hh.
template<class T> RefCountingPtr< T >::RefCountingPtr (T * data) [inline]
Create a new reference counting pointer to some object (probably something newly created).
Adds a reference.
Definition at line 160 of file refcnt.hh.
template<class T> RefCountingPtr< T >::RefCountingPtr (const RefCountingPtr< T > & r) [inline]
Create a new reference counting pointer by copying another one.
Adds a reference.
Definition at line 164 of file refcnt.hh.
template<class T> RefCountingPtr< T >::~RefCountingPtr () [inline]
Destroy the pointer and any reference it may hold.
Definition at line 167 of file refcnt.hh.
Member Function Documentation
template<class T> void RefCountingPtr< T >::copy (T * d) [inline, protected]
Copy a new pointer value and increment the reference count if it is a valid pointer.
Note, this does not delete the reference any existing object.
Parameters:
d Pointer to store.
Definition at line 120 of file refcnt.hh.
Referenced by RefCountingPtr< InOrderDynInst >::RefCountingPtr(), and RefCountingPtr< InOrderDynInst >::set().
template<class T> void RefCountingPtr< T >::del () [inline, protected]
Delete the reference to any existing object if it is non NULL.
Attention:
this doesn't clear the pointer value, so a double decref could happen if not careful.
Definition at line 133 of file refcnt.hh.
Referenced by RefCountingPtr< InOrderDynInst >::set(), and RefCountingPtr< InOrderDynInst >::~RefCountingPtr().
template<class T> T* RefCountingPtr< T >::get () const [inline]
Directly access the pointer itself without taking a reference.
Definition at line 180 of file refcnt.hh.
Referenced by MessageBuffer::dequeue(), CacheUnit::doCacheAccess(), RubyMemoryControl::enqueue(), MessageBuffer::enqueue(), NetworkInterface::flitisizeMessage(), NetworkInterface_d::flitisizeMessage(), BaseO3DynInst< Impl >::forwardOldRegs(), flit::functionalRead(), flit::functionalWrite(), flit_d::functionalWrite(), operator!=(), operator==(), WireBuffer::peek(), RubyMemoryControl::peek(), CacheUnit::processCacheCompletion(), Router::routeCompute(), RoutingUnit_d::routeCompute(), ArmISA::VldMultOp::VldMultOp(), ArmISA::VldSingleOp::VldSingleOp(), ArmISA::VstMultOp::VstMultOp(), ArmISA::VstSingleOp::VstSingleOp(), Throttle::wakeup(), and PerfectSwitch::wakeup().
template<class T> RefCountingPtr< T >::operator bool () const [inline]
Check if the pointer is non-empty.
Definition at line 193 of file refcnt.hh.
template<class T> bool RefCountingPtr< T >::operator! () const [inline]
Check if the pointer is empty.
Definition at line 190 of file refcnt.hh.
template<class T> T& RefCountingPtr< T >::operator* () const [inline]
Dereference the pointer.
Definition at line 177 of file refcnt.hh.
template<class T> T* RefCountingPtr< T >::operator-> () const [inline]
Access a member variable.
Definition at line 174 of file refcnt.hh.
template<class T> const RefCountingPtr& RefCountingPtr< T >::operator= (const RefCountingPtr< T > & r) [inline]
Copy the pointer from another RefCountingPtr.
Definition at line 186 of file refcnt.hh.
Referenced by RefCountingPtr< InOrderDynInst >::operator=().
template<class T> const RefCountingPtr& RefCountingPtr< T >::operator= (T * p) [inline]
Assign a new value to the pointer.
Definition at line 183 of file refcnt.hh.
template<class T> void RefCountingPtr< T >::set (T * d) [inline, protected]
Drop the old reference and change it to something new.
Definition at line 143 of file refcnt.hh.
Member Data Documentation
template<class T> T* RefCountingPtr< T >::data [protected]
The stored pointer.
Arguably this should be private.
Definition at line 111 of file refcnt.hh.
Referenced by RefCountingPtr< InOrderDynInst >::copy(), PacketFifo::copyout(), RefCountingPtr< InOrderDynInst >::del(), EtherDump::dumpPacket(), RefCountingPtr< InOrderDynInst >::get(), Net::UdpPtr::get(), Net::TcpPtr::get(), Net::IpPtr::get(), IGbE::TxDescCache::getPacketData(), RefCountingPtr< InOrderDynInst >::operator bool(), Net::EthPtr::operator const EthHdr *(), Net::EthPtr::operator EthHdr *(), RefCountingPtr< InOrderDynInst >::operator!(), RefCountingPtr< InOrderDynInst >::operator*(), Net::EthPtr::operator*(), RefCountingPtr< InOrderDynInst >::operator->(), Net::EthPtr::operator->(), RefCountingPtr< InOrderDynInst >::operator=(), EtherTap::process(), Net::EthPtr::pstart(), EtherTap::recvPacket(), RefCountingPtr< InOrderDynInst >::RefCountingPtr(), Sinic::Device::rxFilter(), NSGigE::rxFilter(), NSGigE::rxKick(), EtherBus::send(), RefCountingPtr< InOrderDynInst >::set(), Net::IpPtr::set(), Sinic::Device::transmit(), NSGigE::transmit(), EtherLink::Link::transmit(), EtherLink::Link::txComplete(), EtherBus::txDone(), Sinic::Device::txKick(), NSGigE::txKick(), NSGigE::unserialize(), and IGbE::RxDescCache::writePacket().
The documentation for this class was generated from the following file:
base/refcnt.hh