gem5: VirtualChannel_d Class Reference
VirtualChannel_d Class Reference
#include <VirtualChannel_d.hh>
Public Member Functions
VirtualChannel_d (int id, Cycles curTime)
~VirtualChannel_d ()
bool need_stage (VC_state_type state, flit_stage stage, Cycles curTime)
bool need_stage_nextcycle (VC_state_type state, flit_stage stage, Cycles curTime)
void set_outport (int outport)
void grant_vc (int out_vc, Cycles curTime)
Cycles get_enqueue_time ()
void set_enqueue_time (Cycles time)
VC_state_type get_state ()
int get_outvc ()
bool has_credits ()
int get_route ()
void update_credit (int credit)
void increment_credit ()
bool isReady (Cycles curTime)
void insertFlit (flit_d *t_flit)
void set_state (VC_state_type m_state, Cycles curTime)
flit_d * peekTopFlit ()
flit_d * getTopFlit ()
uint32_t functionalWrite (Packet *pkt)
Private Attributes
int m_id
flitBuffer_d * m_input_buffer
std::pair< VC_state_type, Cycles > m_vc_state
int route
Cycles m_enqueue_time
int m_output_vc
int m_credit_count
Detailed Description
Definition at line 39 of file VirtualChannel_d.hh.
Constructor & Destructor Documentation
VirtualChannel_d::VirtualChannel_d (int id, Cycles curTime)
Definition at line 33 of file VirtualChannel_d.cc.
References m_id, m_input_buffer, and m_vc_state.
VirtualChannel_d::~VirtualChannel_d ()
Definition at line 42 of file VirtualChannel_d.cc.
References m_input_buffer.
Member Function Documentation
uint32_t VirtualChannel_d::functionalWrite (Packet * pkt)
Definition at line 90 of file VirtualChannel_d.cc.
References flitBuffer_d::functionalWrite(), and m_input_buffer.
Cycles VirtualChannel_d::get_enqueue_time () [inline]
Definition at line 51 of file VirtualChannel_d.hh.
References m_enqueue_time.
int VirtualChannel_d::get_outvc () [inline]
Definition at line 54 of file VirtualChannel_d.hh.
References m_output_vc.
int VirtualChannel_d::get_route () [inline]
Definition at line 56 of file VirtualChannel_d.hh.
References route.
VC_state_type VirtualChannel_d::get_state () [inline]
Definition at line 53 of file VirtualChannel_d.hh.
References m_vc_state.
flit_d* VirtualChannel_d::getTopFlit () [inline]
Definition at line 85 of file VirtualChannel_d.hh.
References flitBuffer_d::getTopFlit(), and m_input_buffer.
void VirtualChannel_d::grant_vc (int out_vc, Cycles curTime)
Definition at line 54 of file VirtualChannel_d.cc.
References flit_d::advance_stage(), m_input_buffer, m_output_vc, m_vc_state, flitBuffer_d::peekTopFlit(), and SA_.
bool VirtualChannel_d::has_credits () [inline]
Definition at line 55 of file VirtualChannel_d.hh.
References m_credit_count.
void VirtualChannel_d::increment_credit () [inline]
Definition at line 58 of file VirtualChannel_d.hh.
References m_credit_count.
void VirtualChannel_d::insertFlit (flit_d * t_flit) [inline]
Definition at line 66 of file VirtualChannel_d.hh.
References flitBuffer_d::insert(), and m_input_buffer.
bool VirtualChannel_d::isReady (Cycles curTime) [inline]
Definition at line 60 of file VirtualChannel_d.hh.
References flitBuffer_d::isReady(), and m_input_buffer.
bool VirtualChannel_d::need_stage (VC_state_type state, flit_stage stage, Cycles curTime)
Definition at line 64 of file VirtualChannel_d.cc.
References flit_d::is_stage(), flitBuffer_d::isReady(), m_input_buffer, m_vc_state, and flitBuffer_d::peekTopFlit().
bool VirtualChannel_d::need_stage_nextcycle (VC_state_type state, flit_stage stage, Cycles curTime)
Definition at line 77 of file VirtualChannel_d.cc.
References flit_d::is_next_stage(), flitBuffer_d::isReadyForNext(), m_input_buffer, m_vc_state, and flitBuffer_d::peekTopFlit().
flit_d* VirtualChannel_d::peekTopFlit () [inline]
Definition at line 79 of file VirtualChannel_d.hh.
References m_input_buffer, and flitBuffer_d::peekTopFlit().
void VirtualChannel_d::set_enqueue_time (Cycles time) [inline]
Definition at line 52 of file VirtualChannel_d.hh.
References m_enqueue_time.
void VirtualChannel_d::set_outport (int outport)
Definition at line 48 of file VirtualChannel_d.cc.
References route.
void VirtualChannel_d::set_state (VC_state_type m_state, Cycles curTime) [inline]
Definition at line 72 of file VirtualChannel_d.hh.
References m_vc_state.
void VirtualChannel_d::update_credit (int credit) [inline]
Definition at line 57 of file VirtualChannel_d.hh.
References m_credit_count.
Member Data Documentation
int VirtualChannel_d::m_credit_count [private]
Definition at line 99 of file VirtualChannel_d.hh.
Referenced by has_credits(), increment_credit(), and update_credit().
Cycles VirtualChannel_d::m_enqueue_time [private]
Definition at line 97 of file VirtualChannel_d.hh.
Referenced by get_enqueue_time(), and set_enqueue_time().
int VirtualChannel_d::m_id [private]
Definition at line 93 of file VirtualChannel_d.hh.
Referenced by VirtualChannel_d().
flitBuffer_d* VirtualChannel_d::m_input_buffer [private]
Definition at line 94 of file VirtualChannel_d.hh.
Referenced by functionalWrite(), getTopFlit(), grant_vc(), insertFlit(), isReady(), need_stage(), need_stage_nextcycle(), peekTopFlit(), VirtualChannel_d(), and ~VirtualChannel_d().
int VirtualChannel_d::m_output_vc [private]
Definition at line 98 of file VirtualChannel_d.hh.
Referenced by get_outvc(), and grant_vc().
std::pair<VC_state_type, Cycles> VirtualChannel_d::m_vc_state [private]
Definition at line 95 of file VirtualChannel_d.hh.
Referenced by get_state(), grant_vc(), need_stage(), need_stage_nextcycle(), set_state(), and VirtualChannel_d().
int VirtualChannel_d::route [private]
Definition at line 96 of file VirtualChannel_d.hh.
Referenced by get_route(), and set_outport().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet/fixed-pipeline/VirtualChannel_d.hh
mem/ruby/network/garnet/fixed-pipeline/VirtualChannel_d.cc