gem5: QueuedSlavePort Class Reference
QueuedSlavePort Class Reference
A queued port is a port that has an infinite queue for outgoing packets and thus decouples the module that wants to send request/responses from the flow control (retry mechanism) of the port.
#include <qport.hh>