gem5: TsunamiPChip Class Reference
TsunamiPChip Class Reference
A very simple implementation of the Tsunami PCI interface chips.
#include <tsunami_pchip.hh>