gem5: PhysicalMemory Class Reference
PhysicalMemory Class Reference
The physical memory encapsulates all memories in the system and provides basic functionality for accessing those memories without going through the memory system and interconnect.
#include <physical.hh>