gem5: X86ISA::PS2Mouse Class Reference
X86ISA::PS2Mouse Class Reference
#include <i8042.hh>