gem5: ObjectFile Class Reference
ObjectFile Class Reference
#include <object_file.hh>