gem5: SimpleDisk Class Reference
SimpleDisk Class Reference
#include <simple_disk.hh>