gem5: Buffer Class Reference
Buffer Class Reference
#include <Buffer.hh>
Public Types
enum BufferModel { NO_MODEL = 0, BUF_SRAM, BUF_REG }
Public Member Functions
Buffer (const string &buffer_model_str_, bool is_fifo_, bool is_outdrv_, uint32_t num_entry_, uint32_t line_width_, uint32_t num_read_port_, uint32_t num_write_port_, const OrionConfig *orion_cfg_ptr_)
~Buffer ()
double get_dynamic_energy (bool is_read_, bool is_max_) const
double get_static_power () const
void print_all () const
Private Member Functions
void init ()
Private Attributes
BufferModel m_buffer_model
uint32_t m_num_entry
uint32_t m_line_width
bool m_is_fifo
bool m_is_outdrv
uint32_t m_num_read_port
uint32_t m_num_write_port
const OrionConfig * m_orion_cfg_ptr
const TechParameter * m_tech_param_ptr
SRAM * m_sram_ptr
Register * m_reg_ptr
Detailed Description
Definition at line 47 of file Buffer.hh.
Member Enumeration Documentation
enum Buffer::BufferModel
Enumerator:
NO_MODEL
BUF_SRAM
BUF_REG
Definition at line 50 of file Buffer.hh.
Constructor & Destructor Documentation
Buffer::Buffer (const string & buffer_model_str_, bool is_fifo_, bool is_outdrv_, uint32_t num_entry_, uint32_t line_width_, uint32_t num_read_port_, uint32_t num_write_port_, const OrionConfig * orion_cfg_ptr_)
Definition at line 47 of file Buffer.cc.
References OrionConfig::get_tech_param_ptr(), init(), m_buffer_model, m_is_fifo, m_is_outdrv, m_line_width, m_num_entry, m_num_read_port, m_num_write_port, m_orion_cfg_ptr, m_tech_param_ptr, and NO_MODEL.
Buffer::~Buffer ()
Definition at line 92 of file Buffer.cc.
References m_sram_ptr.
Member Function Documentation
double Buffer::get_dynamic_energy (bool is_read_, bool is_max_) const
Definition at line 97 of file Buffer.cc.
References BUF_REG, BUF_SRAM, Register::calc_e_read(), SRAM::calc_e_read(), Register::calc_e_write(), SRAM::calc_e_write(), m_buffer_model, m_reg_ptr, and m_sram_ptr.
Referenced by OrionRouter::calc_dynamic_energy_buf(), VCAllocator::get_dynamic_energy_vc_select(), and print_all().
double Buffer::get_static_power () const
Definition at line 130 of file Buffer.cc.
References BUF_REG, BUF_SRAM, Register::calc_i_static(), SRAM::calc_i_static(), TechParameter::get_SCALE_S(), TechParameter::get_vdd(), m_buffer_model, m_reg_ptr, m_sram_ptr, and m_tech_param_ptr.
Referenced by VCAllocator::get_static_power(), OrionRouter::get_static_power_buf(), and print_all().
void Buffer::init () [private]
Definition at line 157 of file Buffer.cc.
References BUF_REG, BUF_SRAM, OrionConfig::get(), m_buffer_model, m_is_fifo, m_is_outdrv, m_line_width, m_num_entry, m_num_read_port, m_num_write_port, m_orion_cfg_ptr, m_reg_ptr, m_sram_ptr, and m_tech_param_ptr.
Referenced by Buffer().
void Buffer::print_all () const
Definition at line 148 of file Buffer.cc.
References get_dynamic_energy(), and get_static_power().
Referenced by OrionRouter::print().
Member Data Documentation
BufferModel Buffer::m_buffer_model [private]
Definition at line 80 of file Buffer.hh.
Referenced by Buffer(), get_dynamic_energy(), get_static_power(), and init().
bool Buffer::m_is_fifo [private]
Definition at line 84 of file Buffer.hh.
Referenced by Buffer(), and init().
bool Buffer::m_is_outdrv [private]
Definition at line 85 of file Buffer.hh.
Referenced by Buffer(), and init().
uint32_t Buffer::m_line_width [private]
Definition at line 82 of file Buffer.hh.
Referenced by Buffer(), and init().
uint32_t Buffer::m_num_entry [private]
Definition at line 81 of file Buffer.hh.
Referenced by Buffer(), and init().
uint32_t Buffer::m_num_read_port [private]
Definition at line 86 of file Buffer.hh.
Referenced by Buffer(), and init().
uint32_t Buffer::m_num_write_port [private]
Definition at line 87 of file Buffer.hh.
Referenced by Buffer(), and init().
const OrionConfig* Buffer::m_orion_cfg_ptr [private]
Definition at line 88 of file Buffer.hh.
Referenced by Buffer(), and init().
Register* Buffer::m_reg_ptr [private]
Definition at line 92 of file Buffer.hh.
Referenced by get_dynamic_energy(), get_static_power(), and init().
SRAM* Buffer::m_sram_ptr [private]
Definition at line 91 of file Buffer.hh.
Referenced by get_dynamic_energy(), get_static_power(), init(), and ~Buffer().
const TechParameter* Buffer::m_tech_param_ptr [private]
Definition at line 89 of file Buffer.hh.
Referenced by Buffer(), get_static_power(), and init().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/Buffer/Buffer.hh
mem/ruby/network/orion/Buffer/Buffer.cc