gem5: RegDepMap Class Reference
RegDepMap Class Reference
#include <reg_dep_map.hh>
Public Types
typedef ThePipeline::DynInstPtr DynInstPtr
typedef TheISA::RegIndex RegIndex
typedef uint8_t RegType
Public Member Functions
RegDepMap (int size=TheISA::TotalNumRegs)
~RegDepMap ()
std::string name ()
void setCPU (InOrderCPU *_cpu)
void clear ()
Clear the Entire Map.
void insert (DynInstPtr inst)
Insert all of a instruction's destination registers into map.
void remove (DynInstPtr inst)
Remove all of a instruction's destination registers into map.
void removeFront (uint8_t reg_type, RegIndex idx, DynInstPtr inst)
Remove Front instruction from a destination register.
bool canRead (uint8_t reg_type, RegIndex idx, DynInstPtr inst)
Is the current instruction able to read from this destination register?
DynInstPtr canForward (uint8_t reg_type, unsigned reg_idx, DynInstPtr inst)
Is the current instruction able to get a forwarded value from another instruction for this destination register?
DynInstPtr findBypassInst (RegIndex idx)
find an instruction to forward/bypass a value from
bool canWrite (uint8_t reg_type, RegIndex idx, DynInstPtr inst)
Is the current instruction able to write to this destination register?
int depSize (RegIndex idx)
Size of Dependency of Map.
void dump ()
Static Public Attributes
static std::string mapNames []
Private Types
typedef std::vector< std::list
< DynInstPtr > > DepMap
Private Member Functions
void insert (uint8_t reg_type, RegIndex idx, DynInstPtr inst)
Insert an instruction into a specific destination register index onto map.
void remove (uint8_t reg_type, RegIndex idx, DynInstPtr inst)
Remove a specific instruction and dest.
Private Attributes
std::vector< DepMap > regMap
InOrderCPU * cpu
Detailed Description
Definition at line 43 of file reg_dep_map.hh.
Member Typedef Documentation
typedef std::vector<std::list<DynInstPtr> > RegDepMap::DepMap [private]
Definition at line 104 of file reg_dep_map.hh.
typedef ThePipeline::DynInstPtr RegDepMap::DynInstPtr
Definition at line 46 of file reg_dep_map.hh.
typedef TheISA::RegIndex RegDepMap::RegIndex
Definition at line 47 of file reg_dep_map.hh.
typedef uint8_t RegDepMap::RegType
Definition at line 48 of file reg_dep_map.hh.
Constructor & Destructor Documentation
RegDepMap::RegDepMap (int size = TheISA::TotalNumRegs)
Definition at line 44 of file reg_dep_map.cc.
References AlphaISA::NumFloatRegs, AlphaISA::NumIntRegs, AlphaISA::NumMiscRegs, InOrderCPU::NumRegTypes, and regMap.
RegDepMap::~RegDepMap ()
Definition at line 52 of file reg_dep_map.cc.
References clear().
Member Function Documentation
ThePipeline::DynInstPtr RegDepMap::canForward (uint8_t reg_type, unsigned reg_idx, DynInstPtr inst)
Is the current instruction able to get a forwarded value from another instruction for this destination register?
Definition at line 219 of file reg_dep_map.cc.
References curTick(), DPRINTF, and regMap.
Referenced by UseDefUnit::execute().
bool RegDepMap::canRead (uint8_t reg_type, RegIndex idx, DynInstPtr inst)
Is the current instruction able to read from this destination register?
Definition at line 201 of file reg_dep_map.cc.
References DPRINTF, and regMap.
bool RegDepMap::canWrite (uint8_t reg_type, RegIndex idx, DynInstPtr inst)
Is the current instruction able to write to this destination register?
Definition at line 267 of file reg_dep_map.cc.
References DPRINTF, and regMap.
void RegDepMap::clear ()
Clear the Entire Map.
Definition at line 74 of file reg_dep_map.cc.
References ArmISA::i, ArmISA::j, and regMap.
Referenced by ~RegDepMap().
int RegDepMap::depSize (RegIndex idx)
Size of Dependency of Map.
void RegDepMap::dump ()
Definition at line 286 of file reg_dep_map.cc.
References cprintf(), and regMap.
DynInstPtr RegDepMap::findBypassInst (RegIndex idx)
find an instruction to forward/bypass a value from
void RegDepMap::insert (DynInstPtr inst)
Insert all of a instruction's destination registers into map.
Definition at line 85 of file reg_dep_map.cc.
References cpu, DPRINTF, InOrderCPU::flattenRegIdx(), ArmISA::i, InOrderCPU::IntType, and AlphaISA::ZeroReg.
Referenced by UseDefUnit::execute().
void RegDepMap::insert (uint8_t reg_type, RegIndex idx, DynInstPtr inst) [private]
Insert an instruction into a specific destination register index onto map.
Definition at line 120 of file reg_dep_map.cc.
References DPRINTF, mapNames, and regMap.
string RegDepMap::name ()
Definition at line 58 of file reg_dep_map.cc.
References cpu, and SimObject::name().
void RegDepMap::remove (DynInstPtr inst)
Remove all of a instruction's destination registers into map.
Definition at line 132 of file reg_dep_map.cc.
References cpu, DPRINTF, InOrderCPU::getRegType(), ArmISA::i, InOrderCPU::IntType, and AlphaISA::ZeroReg.
Referenced by InOrderCPU::squashInstIt().
void RegDepMap::remove (uint8_t reg_type, RegIndex idx, DynInstPtr inst) [private]
Remove a specific instruction and dest.
register index from map
Definition at line 166 of file reg_dep_map.cc.
References DPRINTF, mapNames, panic, and regMap.
void RegDepMap::removeFront (uint8_t reg_type, RegIndex idx, DynInstPtr inst)
Remove Front instruction from a destination register.
Definition at line 186 of file reg_dep_map.cc.
References DPRINTF, and regMap.
Referenced by UseDefUnit::execute().
void RegDepMap::setCPU (InOrderCPU * _cpu)
Definition at line 67 of file reg_dep_map.cc.
References cpu.
Member Data Documentation
InOrderCPU* RegDepMap::cpu [private]
Definition at line 107 of file reg_dep_map.hh.
Referenced by insert(), name(), remove(), and setCPU().
std::string RegDepMap::mapNames [static]
Initial value:
{"IntReg", "FloatReg", "MiscReg"}
Definition at line 53 of file reg_dep_map.hh.
Referenced by insert(), and remove().
std::vector<DepMap> RegDepMap::regMap [private]
Definition at line 105 of file reg_dep_map.hh.
Referenced by canForward(), canRead(), canWrite(), clear(), dump(), insert(), RegDepMap(), remove(), and removeFront().
The documentation for this class was generated from the following files:
cpu/inorder/reg_dep_map.hh
cpu/inorder/reg_dep_map.cc