gem5: Random Class Reference
Random Class Reference
#include <random.hh>
Public Member Functions
Random ()
Random (uint32_t s)
Random (uint32_t init_key[], int key_length)
~Random ()
void init (uint32_t s)
void init (uint32_t init_key[], int key_length)
template<typename T >
T random ()
template<typename T >
T random (T min, T max)
double gen_real1 ()
double gen_real2 ()
double gen_real3 ()
void serialize (const std::string &base, std::ostream &os)
void unserialize (const std::string &base, Checkpoint *cp, const std::string &section)
Protected Member Functions
uint32_t genrand ()
uint32_t genrand (uint32_t max)
uint64_t genrand (uint64_t max)
void _random (int8_t &value)
void _random (int16_t &value)
void _random (int32_t &value)
void _random (int64_t &value)
void _random (uint8_t &value)
void _random (uint16_t &value)
void _random (uint32_t &value)
void _random (uint64_t &value)
void _random (float &value)
void _random (double &value)
int8_t _random (int8_t min, int8_t max)
int16_t _random (int16_t min, int16_t max)
int32_t _random (int32_t min, int32_t max)
int64_t _random (int64_t min, int64_t max)
uint8_t _random (uint8_t min, uint8_t max)
uint16_t _random (uint16_t min, uint16_t max)
uint32_t _random (uint32_t min, uint32_t max)
uint64_t _random (uint64_t min, uint64_t max)
Protected Attributes
uint32_t mt [N]
int mti
Static Protected Attributes
static const int N = 624
static const int M = 397
static const uint32_t MATRIX_A = (uint32_t)0x9908b0df
static const uint32_t UPPER_MASK = (uint32_t)0x80000000
static const uint32_t LOWER_MASK = (uint32_t)0x7fffffff
Detailed Description
Definition at line 49 of file random.hh.
Constructor & Destructor Documentation
Random::Random ()
Definition at line 41 of file random.cc.
References init().
Random::Random (uint32_t s)
Definition at line 47 of file random.cc.
References init().
Random::Random (uint32_t init_key[], int key_length)
Definition at line 52 of file random.cc.
References init().
Random::~Random ()
Definition at line 57 of file random.cc.
Member Function Documentation
void Random::_random (int8_t & value) [inline, protected]
Definition at line 66 of file random.hh.
References genrand().
Referenced by random().
void Random::_random (int16_t & value) [inline, protected]
Definition at line 72 of file random.hh.
References genrand().
void Random::_random (uint8_t & value) [inline, protected]
Definition at line 90 of file random.hh.
References genrand().
int32_t Random::_random (int32_t min, int32_t max) [inline, protected]
Definition at line 146 of file random.hh.
References genrand().
int64_t Random::_random (int64_t min, int64_t max) [inline, protected]
Definition at line 153 of file random.hh.
References genrand().
void Random::_random (uint16_t & value) [inline, protected]
Definition at line 96 of file random.hh.
References genrand().
uint8_t Random::_random (uint8_t min, uint8_t max) [inline, protected]
Definition at line 160 of file random.hh.
References genrand().
uint16_t Random::_random (uint16_t min, uint16_t max) [inline, protected]
Definition at line 167 of file random.hh.
References genrand().
void Random::_random (uint32_t & value) [inline, protected]
Definition at line 102 of file random.hh.
References genrand().
uint32_t Random::_random (uint32_t min, uint32_t max) [inline, protected]
Definition at line 174 of file random.hh.
References genrand().
uint64_t Random::_random (uint64_t min, uint64_t max) [inline, protected]
Definition at line 181 of file random.hh.
References genrand().
void Random::_random (uint64_t & value) [inline, protected]
Definition at line 108 of file random.hh.
References genrand().
void Random::_random (int32_t & value) [inline, protected]
Definition at line 78 of file random.hh.
References genrand().
void Random::_random (float & value) [inline, protected]
Definition at line 115 of file random.hh.
References genrand().
void Random::_random (double & value) [inline, protected]
Definition at line 123 of file random.hh.
References genrand().
void Random::_random (int64_t & value) [inline, protected]
Definition at line 84 of file random.hh.
References genrand().
int8_t Random::_random (int8_t min, int8_t max) [inline, protected]
Definition at line 132 of file random.hh.
References genrand().
int16_t Random::_random (int16_t min, int16_t max) [inline, protected]
Definition at line 139 of file random.hh.
References genrand().
double Random::gen_real1 () [inline]
Definition at line 214 of file random.hh.
References genrand().
Referenced by TrafficGen::StateGraph::transition().
double Random::gen_real2 () [inline]
Definition at line 221 of file random.hh.
References genrand().
double Random::gen_real3 () [inline]
Definition at line 228 of file random.hh.
References genrand().
uint32_t Random::genrand (uint32_t max) [protected]
Definition at line 67 of file random.cc.
References ceilLog2(), genrand(), and ArmISA::shift.
uint32_t Random::genrand () [protected]
Definition at line 117 of file random_mt.cc.
References LOWER_MASK, M, MATRIX_A, mt, mti, N, and UPPER_MASK.
Referenced by _random(), gen_real1(), gen_real2(), gen_real3(), and genrand().
uint64_t Random::genrand (uint64_t max) [protected]
Definition at line 86 of file random.cc.
References ceilLog2(), genrand(), and ArmISA::shift.
void Random::init (uint32_t s)
Definition at line 50 of file random_mt.cc.
References mt, mti, and N.
Referenced by init(), and Random().
void Random::init (uint32_t init_key[], int key_length)
Definition at line 71 of file random_mt.cc.
References ArmISA::i, init(), ArmISA::j, MipsISA::k, mt, and N.
template<typename T > T Random::random (T min, T max) [inline]
Definition at line 207 of file random.hh.
References _random().
template<typename T > T Random::random () [inline]
Definition at line 198 of file random.hh.
References _random().
Referenced by SimpleMemory::calculateLatency(), TrafficGen::StateGraph::RandomGen::execute(), TrafficGen::StateGraph::LinearGen::execute(), TrafficGen::StateGraph::RandomGen::nextExecuteTick(), TrafficGen::StateGraph::LinearGen::nextExecuteTick(), and EtherLink::Link::transmit().
void Random::serialize (const std::string & base, std::ostream & os)
void Random::unserialize (const std::string & base, Checkpoint * cp, const std::string & section)
Member Data Documentation
const uint32_t Random::LOWER_MASK = (uint32_t)0x7fffffff [static, protected]
Definition at line 56 of file random.hh.
Referenced by genrand().
const int Random::M = 397 [static, protected]
Definition at line 53 of file random.hh.
Referenced by genrand().
const uint32_t Random::MATRIX_A = (uint32_t)0x9908b0df [static, protected]
Definition at line 54 of file random.hh.
Referenced by genrand().
uint32_t Random::mt[N] [protected]
Definition at line 58 of file random.hh.
Referenced by genrand(), and init().
int Random::mti [protected]
Definition at line 59 of file random.hh.
Referenced by genrand(), and init().
const int Random::N = 624 [static, protected]
Definition at line 52 of file random.hh.
Referenced by genrand(), and init().
const uint32_t Random::UPPER_MASK = (uint32_t)0x80000000 [static, protected]
Definition at line 55 of file random.hh.
Referenced by genrand().
The documentation for this class was generated from the following files:
base/random.hh
base/random.cc
base/random_mt.cc