gem5: SparcISA::Decoder Class Reference
SparcISA::Decoder Class Reference
#include <decoder.hh>
Public Member Functions
Decoder ()
void process ()
void reset ()
void moreBytes (const PCState &pc, Addr fetchPC, MachInst inst)
bool needMoreBytes ()
bool instReady ()
void setContext (MiscReg _asi)
void takeOverFrom (Decoder *old)
StaticInstPtr decodeInst (ExtMachInst mach_inst)
StaticInstPtr decode (ExtMachInst mach_inst, Addr addr)
Decode a machine instruction.
StaticInstPtr decode (SparcISA::PCState &nextPC)
Protected Attributes
ExtMachInst emi
bool instDone
MiscReg asi
Static Protected Attributes
static GenericISA::BasicDecodeCache defaultCache
A cache of decoded instruction objects.
Detailed Description
Definition at line 42 of file decoder.hh.
Constructor & Destructor Documentation
SparcISA::Decoder::Decoder () [inline]
Definition at line 51 of file decoder.hh.
Member Function Documentation
StaticInstPtr SparcISA::Decoder::decode (ExtMachInst mach_inst, Addr addr) [inline]
Decode a machine instruction.
Parameters:
mach_inst The binary instruction to decode.
Return values:
A pointer to the corresponding StaticInst object.
Definition at line 113 of file decoder.hh.
References GenericISA::BasicDecodeCache::decode(), and defaultCache.
Referenced by decode().
StaticInstPtr SparcISA::Decoder::decode (SparcISA::PCState & nextPC) [inline]
Definition at line 119 of file decoder.hh.
References decode(), emi, GenericISA::PCStateBase::instAddr(), and instDone.
StaticInstPtr SparcISA::Decoder::decodeInst (ExtMachInst mach_inst)
bool SparcISA::Decoder::instReady () [inline]
Definition at line 89 of file decoder.hh.
References instDone.
void SparcISA::Decoder::moreBytes (const PCState & pc, Addr fetchPC, MachInst inst) [inline]
Definition at line 65 of file decoder.hh.
References asi, bits(), emi, and instDone.
bool SparcISA::Decoder::needMoreBytes () [inline]
Definition at line 83 of file decoder.hh.
void SparcISA::Decoder::process () [inline]
Definition at line 54 of file decoder.hh.
void SparcISA::Decoder::reset () [inline]
Definition at line 57 of file decoder.hh.
References instDone.
void SparcISA::Decoder::setContext (MiscReg _asi) [inline]
Definition at line 95 of file decoder.hh.
References asi.
void SparcISA::Decoder::takeOverFrom (Decoder * old) [inline]
Definition at line 100 of file decoder.hh.
Member Data Documentation
MiscReg SparcISA::Decoder::asi [protected]
Definition at line 48 of file decoder.hh.
Referenced by moreBytes(), and setContext().
GenericISA::BasicDecodeCache SparcISA::Decoder::defaultCache [static, protected]
A cache of decoded instruction objects.
Definition at line 104 of file decoder.hh.
Referenced by decode().
ExtMachInst SparcISA::Decoder::emi [protected]
Definition at line 46 of file decoder.hh.
Referenced by decode(), and moreBytes().
bool SparcISA::Decoder::instDone [protected]
Definition at line 47 of file decoder.hh.
Referenced by decode(), instReady(), moreBytes(), and reset().
The documentation for this class was generated from the following files:
arch/sparc/decoder.hh
arch/sparc/decoder.cc