gem5: EcoffObject Class Reference
EcoffObject Class Reference
#include <ecoff_object.hh>