gem5: OrionLink Class Reference
OrionLink Class Reference
#include <OrionLink.hh>
Public Member Functions
OrionLink (double len_, uint32_t line_width_, const OrionConfig *orion_cfg_ptr_)
~OrionLink ()
double calc_dynamic_energy (uint32_t num_bit_flip_) const
double get_static_power () const
void print () const
Private Member Functions
void init ()
Private Attributes
double m_len
uint32_t m_line_width
const OrionConfig * m_orion_cfg_ptr
double m_dynamic_energy_per_bit
double m_static_power_per_bit
Detailed Description
Definition at line 44 of file OrionLink.hh.
Constructor & Destructor Documentation
OrionLink::OrionLink (double len_, uint32_t line_width_, const OrionConfig * orion_cfg_ptr_)
Definition at line 45 of file OrionLink.cc.
References init(), m_len, m_line_width, and m_orion_cfg_ptr.
OrionLink::~OrionLink ()
Definition at line 61 of file OrionLink.cc.
Member Function Documentation
double OrionLink::calc_dynamic_energy (uint32_t num_bit_flip_) const
Definition at line 64 of file OrionLink.cc.
References m_dynamic_energy_per_bit, and m_line_width.
Referenced by NetworkLink_d::calculate_power(), and print().
double OrionLink::get_static_power () const
Definition at line 70 of file OrionLink.cc.
References m_line_width, and m_static_power_per_bit.
Referenced by NetworkLink_d::calculate_power(), and print().
void OrionLink::init () [private]
Definition at line 75 of file OrionLink.cc.
References OrionConfig::get(), OrionConfig::get_tech_param_ptr(), m_dynamic_energy_per_bit, m_len, m_orion_cfg_ptr, and m_static_power_per_bit.
Referenced by OrionLink().
void OrionLink::print (void) const
Definition at line 89 of file OrionLink.cc.
References calc_dynamic_energy(), and get_static_power().
Member Data Documentation
double OrionLink::m_dynamic_energy_per_bit [private]
Definition at line 68 of file OrionLink.hh.
Referenced by calc_dynamic_energy(), and init().
double OrionLink::m_len [private]
Definition at line 64 of file OrionLink.hh.
Referenced by init(), and OrionLink().
uint32_t OrionLink::m_line_width [private]
Definition at line 65 of file OrionLink.hh.
Referenced by calc_dynamic_energy(), get_static_power(), and OrionLink().
const OrionConfig* OrionLink::m_orion_cfg_ptr [private]
Definition at line 66 of file OrionLink.hh.
Referenced by init(), and OrionLink().
double OrionLink::m_static_power_per_bit [private]
Definition at line 69 of file OrionLink.hh.
Referenced by get_static_power(), and init().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/OrionLink.hh
mem/ruby/network/orion/OrionLink.cc