gem5: PerfectCacheMemory< ENTRY > Class Template Reference
PerfectCacheMemory< ENTRY > Class Template Reference
#include <PerfectCacheMemory.hh>
Public Member Functions
PerfectCacheMemory ()
bool isTagPresent (const Address &address) const
bool cacheAvail (const Address &address) const
void allocate (const Address &address)
void deallocate (const Address &address)
Address cacheProbe (const Address &newAddress) const
ENTRY & lookup (const Address &address)
const ENTRY & lookup (const Address &address) const
AccessPermission getPermission (const Address &address) const
void changePermission (const Address &address, AccessPermission new_perm)
void print (std::ostream &out) const
Private Member Functions
PerfectCacheMemory (const PerfectCacheMemory &obj)
PerfectCacheMemory & operator= (const PerfectCacheMemory &obj)
Private Attributes
m5::hash_map< Address,
PerfectCacheLineState< ENTRY > > m_map
Detailed Description
template<class ENTRY>
class PerfectCacheMemory< ENTRY >
Definition at line 52 of file PerfectCacheMemory.hh.
Constructor & Destructor Documentation
template<class ENTRY > PerfectCacheMemory< ENTRY >::PerfectCacheMemory () [inline]
Definition at line 104 of file PerfectCacheMemory.hh.
template<class ENTRY > PerfectCacheMemory< ENTRY >::PerfectCacheMemory (const PerfectCacheMemory< ENTRY > & obj) [private]
Member Function Documentation
template<class ENTRY > void PerfectCacheMemory< ENTRY >::allocate (const Address & address) [inline]
Definition at line 127 of file PerfectCacheMemory.hh.
References line_address(), PerfectCacheLineState< ENTRY >::m_entry, PerfectCacheMemory< ENTRY >::m_map, and PerfectCacheLineState< ENTRY >::m_permission.
template<class ENTRY > bool PerfectCacheMemory< ENTRY >::cacheAvail (const Address & address) const [inline]
Definition at line 118 of file PerfectCacheMemory.hh.
template<class ENTRY > Address PerfectCacheMemory< ENTRY >::cacheProbe (const Address & newAddress) const [inline]
Definition at line 146 of file PerfectCacheMemory.hh.
References panic.
template<class ENTRY > void PerfectCacheMemory< ENTRY >::changePermission (const Address & address, AccessPermission new_perm) [inline]
Definition at line 177 of file PerfectCacheMemory.hh.
References line_address(), PerfectCacheMemory< ENTRY >::m_map, PerfectCacheLineState< ENTRY >::m_permission, and Address::makeLineAddress().
template<class ENTRY > void PerfectCacheMemory< ENTRY >::deallocate (const Address & address) [inline]
Definition at line 138 of file PerfectCacheMemory.hh.
References line_address(), and PerfectCacheMemory< ENTRY >::m_map.
template<class ENTRY > AccessPermission PerfectCacheMemory< ENTRY >::getPermission (const Address & address) const [inline]
Definition at line 170 of file PerfectCacheMemory.hh.
References line_address(), and PerfectCacheMemory< ENTRY >::m_map.
template<class ENTRY > bool PerfectCacheMemory< ENTRY >::isTagPresent (const Address & address) const [inline]
Definition at line 111 of file PerfectCacheMemory.hh.
References line_address(), and PerfectCacheMemory< ENTRY >::m_map.
template<class ENTRY > const ENTRY & PerfectCacheMemory< ENTRY >::lookup (const Address & address) const [inline]
Definition at line 163 of file PerfectCacheMemory.hh.
References line_address(), and PerfectCacheMemory< ENTRY >::m_map.
template<class ENTRY > ENTRY & PerfectCacheMemory< ENTRY >::lookup (const Address & address) [inline]
Definition at line 155 of file PerfectCacheMemory.hh.
References line_address(), and PerfectCacheMemory< ENTRY >::m_map.
template<class ENTRY > PerfectCacheMemory& PerfectCacheMemory< ENTRY >::operator= (const PerfectCacheMemory< ENTRY > & obj) [private]
template<class ENTRY > void PerfectCacheMemory< ENTRY >::print (std::ostream & out) const [inline]
Definition at line 188 of file PerfectCacheMemory.hh.
Member Data Documentation
template<class ENTRY > m5::hash_map<Address, PerfectCacheLineState<ENTRY> > PerfectCacheMemory< ENTRY >::m_map [private]
Definition at line 90 of file PerfectCacheMemory.hh.
Referenced by PerfectCacheMemory< ENTRY >::allocate(), PerfectCacheMemory< ENTRY >::changePermission(), PerfectCacheMemory< ENTRY >::deallocate(), PerfectCacheMemory< ENTRY >::getPermission(), PerfectCacheMemory< ENTRY >::isTagPresent(), and PerfectCacheMemory< ENTRY >::lookup().
The documentation for this class was generated from the following file:
mem/ruby/system/PerfectCacheMemory.hh