gem5: CacheSet Class Reference
CacheSet Class Reference
An associative set of cache blocks.
#include <cacheset.hh>
Public Member Functions
CacheBlk * findBlk (Addr tag) const
Find a block matching the tag in this set.
void moveToHead (CacheBlk *blk)
Move the given block to the head of the list.
void moveToTail (CacheBlk *blk)
Move the given block to the tail of the list.
Public Attributes
int assoc
The associativity of this set.
CacheBlk ** blks
Cache blocks in this set, maintained in LRU order 0 = MRU.
Detailed Description
An associative set of cache blocks.
Definition at line 46 of file cacheset.hh.
Member Function Documentation
CacheBlk * CacheSet::findBlk (Addr tag) const
Find a block matching the tag in this set.
Parameters:
asid The address space ID.
tag The Tag to find.
Returns:
Pointer to the block if found.
Definition at line 35 of file cacheset.cc.
References assoc, blks, and ArmISA::i.
Referenced by LRU::accessBlock(), and LRU::findBlock().
void CacheSet::moveToHead (CacheBlk * blk)
Move the given block to the head of the list.
Parameters:
blk The block to move.
Definition at line 46 of file cacheset.cc.
References assoc, blks, and ArmISA::i.
Referenced by LRU::accessBlock(), and LRU::insertBlock().
void CacheSet::moveToTail (CacheBlk * blk)
Move the given block to the tail of the list.
Parameters:
blk The block to move
Definition at line 70 of file cacheset.cc.
References assoc, blks, and ArmISA::i.
Referenced by LRU::invalidate().
Member Data Documentation
int CacheSet::assoc
The associativity of this set.
Definition at line 50 of file cacheset.hh.
Referenced by findBlk(), LRU::LRU(), moveToHead(), and moveToTail().
CacheBlk** CacheSet::blks
Cache blocks in this set, maintained in LRU order 0 = MRU.
Definition at line 53 of file cacheset.hh.
Referenced by findBlk(), LRU::findVictim(), LRU::LRU(), moveToHead(), and moveToTail().
The documentation for this class was generated from the following files:
mem/cache/tags/cacheset.hh
mem/cache/tags/cacheset.cc