gem5: SymbolTable Class Reference
SymbolTable Class Reference
#include <symtab.hh>
Public Types
typedef std::map< Addr,
std::string > ATable
typedef std::map< std::string,
Addr > STable
Public Member Functions
SymbolTable ()
SymbolTable (const std::string &file)
~SymbolTable ()
void clear ()
bool insert (Addr address, std::string symbol)
bool load (const std::string &file)
const ATable & getAddrTable () const
const STable & getSymbolTable () const
void serialize (const std::string &base, std::ostream &os)
void unserialize (const std::string &base, Checkpoint *cp, const std::string &section)
bool findSymbol (Addr address, std::string &symbol) const
bool findAddress (const std::string &symbol, Addr &address) const
bool findNearestSymbol (Addr addr, std::string &symbol, Addr &symaddr, Addr &nextaddr) const
Find the nearest symbol equal to or less than the supplied address (e.g., the label for the enclosing function).
bool findNearestSymbol (Addr addr, std::string &symbol, Addr &symaddr) const
Overload for findNearestSymbol() for callers who don't care about nextaddr.
bool findNearestAddr (Addr addr, Addr &symaddr, Addr &nextaddr) const
bool findNearestAddr (Addr addr, Addr &symaddr) const
Private Member Functions
bool upperBound (Addr addr, ATable::const_iterator &iter) const
Private Attributes
ATable addrTable
STable symbolTable
Detailed Description
Definition at line 42 of file symtab.hh.
Member Typedef Documentation
typedef std::map<Addr, std::string> SymbolTable::ATable
Definition at line 45 of file symtab.hh.
typedef std::map<std::string, Addr> SymbolTable::STable
Definition at line 46 of file symtab.hh.
Constructor & Destructor Documentation
SymbolTable::SymbolTable () [inline]
Definition at line 67 of file symtab.hh.
SymbolTable::SymbolTable (const std::string & file) [inline]
Definition at line 68 of file symtab.hh.
References load().
SymbolTable::~SymbolTable () [inline]
Definition at line 69 of file symtab.hh.
Member Function Documentation
void SymbolTable::clear ()
Definition at line 47 of file symtab.cc.
References addrTable, and symbolTable.
bool SymbolTable::findAddress (const std::string & symbol, Addr & address) const [inline]
Definition at line 96 of file symtab.hh.
References ArmISA::i, and symbolTable.
Referenced by System::addFuncEvent(), Linux::ThreadInfo::get_data(), LinuxArmSystem::initState(), AlphaSystem::initState(), LinuxAlphaSystem::initState(), LinuxArmSystem::LinuxArmSystem(), main(), X86ISA::ProcessInfo::ProcessInfo(), ArmISA::ProcessInfo::ProcessInfo(), AlphaISA::ProcessInfo::ProcessInfo(), AlphaSystem::setAlphaAccess(), LinuxAlphaSystem::setDelayLoop(), and LinuxAlphaSystem::setupFuncEvents().
bool SymbolTable::findNearestAddr (Addr addr, Addr & symaddr, Addr & nextaddr) const [inline]
Definition at line 146 of file symtab.hh.
References ArmISA::i, and upperBound().
Referenced by FunctionProfile::sample(), and AlphaISA::StackTrace::trace().
bool SymbolTable::findNearestAddr (Addr addr, Addr & symaddr) const [inline]
Definition at line 159 of file symtab.hh.
References ArmISA::i, and upperBound().
bool SymbolTable::findNearestSymbol (Addr addr, std::string & symbol, Addr & symaddr, Addr & nextaddr) const [inline]
Find the nearest symbol equal to or less than the supplied address (e.g., the label for the enclosing function).
Parameters:
addr The address to look up.
symbol Return reference for symbol string.
symaddr Return reference for symbol address.
nextaddr Address of following symbol (for determining valid range of symbol).
Return values:
True if a symbol was found.
Definition at line 115 of file symtab.hh.
References ArmISA::i, and upperBound().
Referenced by BaseCPU::traceFunctionsInternal(), and Trace::ExeTracerRecord::traceInst().
bool SymbolTable::findNearestSymbol (Addr addr, std::string & symbol, Addr & symaddr) const [inline]
Overload for findNearestSymbol() for callers who don't care about nextaddr.
Definition at line 132 of file symtab.hh.
References ArmISA::i, and upperBound().
bool SymbolTable::findSymbol (Addr address, std::string & symbol) const [inline]
Definition at line 85 of file symtab.hh.
References addrTable, and ArmISA::i.
Referenced by PowerISA::BranchNonPCRelCond::generateDisassembly(), PowerISA::BranchPCRelCond::generateDisassembly(), PowerISA::BranchNonPCRel::generateDisassembly(), PowerISA::BranchPCRel::generateDisassembly(), and main().
const ATable& SymbolTable::getAddrTable () const [inline]
Definition at line 75 of file symtab.hh.
References addrTable.
Referenced by main().
const STable& SymbolTable::getSymbolTable () const [inline]
Definition at line 76 of file symtab.hh.
References symbolTable.
bool SymbolTable::insert (Addr address, std::string symbol)
Referenced by EcoffObject::loadGlobalSymbols(), EcoffObject::loadLocalSymbols(), and ElfObject::loadSomeSymbols().
bool SymbolTable::load (const std::string & file)
Referenced by main(), and SymbolTable().
void SymbolTable::serialize (const std::string & base, std::ostream & os)
Referenced by SparcSystem::serializeSymtab(), and AlphaSystem::serializeSymtab().
void SymbolTable::unserialize (const std::string & base, Checkpoint * cp, const std::string & section)
Referenced by SparcSystem::unserializeSymtab(), and AlphaSystem::unserializeSymtab().
bool SymbolTable::upperBound (Addr addr, ATable::const_iterator & iter) const [inline, private]
Definition at line 54 of file symtab.hh.
References addrTable.
Referenced by findNearestAddr(), and findNearestSymbol().
Member Data Documentation
ATable SymbolTable::addrTable [private]
Definition at line 49 of file symtab.hh.
Referenced by clear(), findSymbol(), getAddrTable(), and upperBound().
STable SymbolTable::symbolTable [private]
Definition at line 50 of file symtab.hh.
Referenced by clear(), findAddress(), and getSymbolTable().
The documentation for this class was generated from the following files:
base/loader/symtab.hh
base/loader/symtab.cc