gem5: NoncoherentBus::NoncoherentBusSlavePort Class Reference
NoncoherentBus::NoncoherentBusSlavePort Class Reference
Declaration of the non-coherent bus slave port type, one will be instantiated for each of the master ports connecting to the bus.
#include <noncoherent_bus.hh>