gem5: InOrderCPU::CPUEvent Class Reference
InOrderCPU::CPUEvent Class Reference
Define CPU Event.
#include <cpu.hh>