gem5: ResourceRequest Class Reference
ResourceRequest Class Reference
#include <resource.hh>