gem5: OzoneCPU< Impl > Class Template Reference
OzoneCPU< Impl > Class Template Reference
Light weight out of order CPU model that approximates an out of order CPU.
#include <cpu.hh>