gem5: X86ISA::X86StaticInst Class Reference
X86ISA::X86StaticInst Class Reference
Base class for all X86 static instructions.
#include <static_inst.hh>