gem5: WordlineUnit Class Reference
WordlineUnit Class Reference
#include <WordlineUnit.hh>
Public Types
enum WordlineModel { NO_MODEL = 0, RW_WORDLINE, WO_WORDLINE }
Public Member Functions
WordlineUnit (const string &wl_model_str_, const SRAM *sram_ptr_, const TechParameter *tech_param_ptr_)
~WordlineUnit ()
double get_e_read () const
double get_e_write () const
double get_i_static () const
Private Member Functions
void init ()
double calc_wordline_cap (uint32_t num_mos_, double mos_width_) const
double calc_i_static ()
Private Attributes
WordlineModel m_wl_model
const SRAM * m_sram_ptr
const TechParameter * m_tech_param_ptr
double m_wl_len
double m_wl_wire_cap
double m_e_read
double m_e_write
double m_i_static
Detailed Description
Definition at line 44 of file WordlineUnit.hh.
Member Enumeration Documentation
enum WordlineUnit::WordlineModel
Enumerator:
NO_MODEL
RW_WORDLINE
WO_WORDLINE
Definition at line 47 of file WordlineUnit.hh.
Constructor & Destructor Documentation
WordlineUnit::WordlineUnit (const string & wl_model_str_, const SRAM * sram_ptr_, const TechParameter * tech_param_ptr_)
Definition at line 41 of file WordlineUnit.cc.
References init(), m_sram_ptr, m_tech_param_ptr, m_wl_model, and NO_MODEL.
WordlineUnit::~WordlineUnit ()
Definition at line 69 of file WordlineUnit.cc.
Member Function Documentation
double WordlineUnit::calc_i_static () [private]
double WordlineUnit::calc_wordline_cap (uint32_t num_mos_, double mos_width_) const [private]
Definition at line 127 of file WordlineUnit.cc.
References TechParameter::calc_draincap(), TechParameter::calc_driver_psize(), TechParameter::calc_gatecap(), TechParameter::calc_gatecappass(), TechParameter::get_BitWidth(), TechParameter::get_period(), TechParameter::get_Wdecinvn(), TechParameter::get_Wdecinvp(), m_tech_param_ptr, m_wl_wire_cap, TechParameter::NCH, and TechParameter::PCH.
Referenced by init().
double WordlineUnit::get_e_read () const [inline]
Definition at line 63 of file WordlineUnit.hh.
References m_e_read.
Referenced by SRAM::calc_e_read().
double WordlineUnit::get_e_write () const [inline]
Definition at line 64 of file WordlineUnit.hh.
References m_e_write.
Referenced by SRAM::calc_e_write().
double WordlineUnit::get_i_static () const [inline]
Definition at line 65 of file WordlineUnit.hh.
References m_i_static.
Referenced by SRAM::calc_i_static().
void WordlineUnit::init () [private]
Definition at line 72 of file WordlineUnit.cc.
References calc_wordline_cap(), fatal, TechParameter::get_BitlineSpacing(), TechParameter::get_CC3M3metal(), TechParameter::get_CM3metal(), TechParameter::get_EnergyFactor(), TechParameter::get_NMOS_TAB(), SRAM::get_num_col(), SRAM::get_num_data_end(), SRAM::get_num_port(), SRAM::get_num_read_port(), TechParameter::get_PMOS_TAB(), TechParameter::get_RegCellWidth(), TechParameter::get_Wmemcellr(), TechParameter::get_Wmemcellw(), TechParameter::get_Woutdrivern(), TechParameter::get_Woutdriverp(), m_e_read, m_e_write, m_i_static, m_sram_ptr, m_tech_param_ptr, m_wl_len, m_wl_model, m_wl_wire_cap, RW_WORDLINE, and WO_WORDLINE.
Referenced by WordlineUnit().
Member Data Documentation
double WordlineUnit::m_e_read [private]
Definition at line 80 of file WordlineUnit.hh.
Referenced by get_e_read(), and init().
double WordlineUnit::m_e_write [private]
Definition at line 81 of file WordlineUnit.hh.
Referenced by get_e_write(), and init().
double WordlineUnit::m_i_static [private]
Definition at line 83 of file WordlineUnit.hh.
Referenced by get_i_static(), and init().
const SRAM* WordlineUnit::m_sram_ptr [private]
Definition at line 74 of file WordlineUnit.hh.
Referenced by init(), and WordlineUnit().
const TechParameter* WordlineUnit::m_tech_param_ptr [private]
Definition at line 75 of file WordlineUnit.hh.
Referenced by calc_wordline_cap(), init(), and WordlineUnit().
double WordlineUnit::m_wl_len [private]
Definition at line 77 of file WordlineUnit.hh.
Referenced by init().
WordlineModel WordlineUnit::m_wl_model [private]
Definition at line 73 of file WordlineUnit.hh.
Referenced by init(), and WordlineUnit().
double WordlineUnit::m_wl_wire_cap [private]
Definition at line 78 of file WordlineUnit.hh.
Referenced by calc_wordline_cap(), and init().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/Buffer/WordlineUnit.hh
mem/ruby/network/orion/Buffer/WordlineUnit.cc