gem5: ModNum< T, MV > Class Template Reference
ModNum< T, MV > Class Template Reference
#include <mod_num.hh>
Public Member Functions
ModNum ()
ModNum (T n)
ModNum (const ModNum< T, MV > &n)
ModNum operator= (T n)
const ModNum operator= (ModNum n)
operator T () const
const ModNum< T, MV > operator+= (ModNum< T, MV > r)
const ModNum< T, MV > operator+= (T r)
const ModNum< T, MV > operator-= (ModNum< T, MV > r)
const ModNum< T, MV > operator-= (T r)
const ModNum< T, MV > operator++ ()
const ModNum< T, MV > operator++ (int)
const ModNum< T, MV > operator-- ()
const ModNum< T, MV > operator-- (int)
Private Member Functions
void setValue (T n)
Private Attributes
T value
Detailed Description
template<class T, T MV>
class ModNum< T, MV >
Definition at line 32 of file mod_num.hh.
Constructor & Destructor Documentation
template<class T, T MV> ModNum< T, MV >::ModNum () [inline]
Definition at line 40 of file mod_num.hh.
template<class T, T MV> ModNum< T, MV >::ModNum (T n) [inline]
Definition at line 41 of file mod_num.hh.
References ModNum< T, MV >::setValue().
template<class T, T MV> ModNum< T, MV >::ModNum (const ModNum< T, MV > & n) [inline]
Definition at line 42 of file mod_num.hh.
Member Function Documentation
template<class T, T MV> ModNum< T, MV >::operator T () const [inline]
Definition at line 55 of file mod_num.hh.
References ModNum< T, MV >::value.
template<class T, T MV> const ModNum<T, MV> ModNum< T, MV >::operator++ () [inline]
Definition at line 87 of file mod_num.hh.
template<class T, T MV> const ModNum<T, MV> ModNum< T, MV >::operator++ (int) [inline]
Definition at line 93 of file mod_num.hh.
template<class T, T MV> const ModNum<T, MV> ModNum< T, MV >::operator+= (ModNum< T, MV > r) [inline]
Definition at line 60 of file mod_num.hh.
References ModNum< T, MV >::setValue(), and ModNum< T, MV >::value.
template<class T, T MV> const ModNum<T, MV> ModNum< T, MV >::operator+= (T r) [inline]
Definition at line 65 of file mod_num.hh.
References ModNum< T, MV >::setValue(), and ModNum< T, MV >::value.
template<class T, T MV> const ModNum<T, MV> ModNum< T, MV >::operator-- () [inline]
Definition at line 105 of file mod_num.hh.
template<class T, T MV> const ModNum<T, MV> ModNum< T, MV >::operator-- (int) [inline]
Definition at line 111 of file mod_num.hh.
template<class T, T MV> const ModNum<T, MV> ModNum< T, MV >::operator-= (T r) [inline]
Definition at line 78 of file mod_num.hh.
References ModNum< T, MV >::setValue(), and ModNum< T, MV >::value.
template<class T, T MV> const ModNum<T, MV> ModNum< T, MV >::operator-= (ModNum< T, MV > r) [inline]
Definition at line 73 of file mod_num.hh.
References ModNum< T, MV >::setValue(), and ModNum< T, MV >::value.
template<class T, T MV> const ModNum ModNum< T, MV >::operator= (ModNum< T, MV > n) [inline]
Definition at line 49 of file mod_num.hh.
References ModNum< T, MV >::value.
template<class T, T MV> ModNum ModNum< T, MV >::operator= (T n) [inline]
Definition at line 44 of file mod_num.hh.
References ModNum< T, MV >::setValue().
template<class T, T MV> void ModNum< T, MV >::setValue (T n) [inline, private]
Definition at line 37 of file mod_num.hh.
References ModNum< T, MV >::value.
Referenced by ModNum< T, MV >::ModNum(), ModNum< T, MV >::operator+=(), ModNum< T, MV >::operator-=(), and ModNum< T, MV >::operator=().
Member Data Documentation
template<class T, T MV> T ModNum< T, MV >::value [private]
Definition at line 34 of file mod_num.hh.
Referenced by ModNum< T, MV >::operator T(), ModNum< T, MV >::operator+=(), ModNum< T, MV >::operator-=(), ModNum< T, MV >::operator=(), operator==(), operator>(), operator>=(), and ModNum< T, MV >::setValue().
The documentation for this class was generated from the following file:
base/mod_num.hh