gem5: RubyTester Class Reference
RubyTester Class Reference
#include <RubyTester.hh>