gem5: flitBuffer_d Class Reference
flitBuffer_d Class Reference
#include <flitBuffer_d.hh>
Public Member Functions
flitBuffer_d ()
flitBuffer_d (int maximum_size)
bool isReady (Cycles curTime)
bool isReadyForNext (Cycles curTime)
bool isEmpty ()
void print (std::ostream &out) const
bool isFull ()
void setMaxSize (int maximum)
flit_d * getTopFlit ()
flit_d * peekTopFlit ()
void insert (flit_d *flt)
uint32_t functionalWrite (Packet *pkt)
Private Attributes
std::vector< flit_d * > m_buffer
int max_size
Detailed Description
Definition at line 41 of file flitBuffer_d.hh.
Constructor & Destructor Documentation
flitBuffer_d::flitBuffer_d ()
Definition at line 33 of file flitBuffer_d.cc.
References max_size.
flitBuffer_d::flitBuffer_d (int maximum_size)
Definition at line 38 of file flitBuffer_d.cc.
References max_size.
Member Function Documentation
uint32_t flitBuffer_d::functionalWrite (Packet * pkt)
Definition at line 90 of file flitBuffer_d.cc.
References ArmISA::i, and m_buffer.
Referenced by VirtualChannel_d::functionalWrite(), OutputUnit_d::functionalWrite(), NetworkLink_d::functionalWrite(), and NetworkInterface_d::functionalWrite().
flit_d* flitBuffer_d::getTopFlit () [inline]
Definition at line 55 of file flitBuffer_d.hh.
References ArmISA::f, and m_buffer.
Referenced by NetworkLink_d::consumeLink(), VirtualChannel_d::getTopFlit(), and NetworkLink_d::wakeup().
void flitBuffer_d::insert (flit_d * flt) [inline]
Definition at line 70 of file flitBuffer_d.hh.
References m_buffer.
Referenced by InputUnit_d::increment_credit(), OutputUnit_d::insert_flit(), VirtualChannel_d::insertFlit(), NetworkInterface_d::scheduleOutputLink(), NetworkLink_d::wakeup(), and NetworkInterface_d::wakeup().
bool flitBuffer_d::isEmpty ()
Definition at line 44 of file flitBuffer_d.cc.
References m_buffer.
bool flitBuffer_d::isFull ()
Definition at line 78 of file flitBuffer_d.cc.
References m_buffer, and max_size.
bool flitBuffer_d::isReady (Cycles curTime)
Definition at line 50 of file flitBuffer_d.cc.
References flit_d::get_time(), m_buffer, and peekTopFlit().
Referenced by VirtualChannel_d::isReady(), NetworkLink_d::isReady(), VirtualChannel_d::need_stage(), and NetworkLink_d::wakeup().
bool flitBuffer_d::isReadyForNext (Cycles curTime)
Definition at line 61 of file flitBuffer_d.cc.
References flit_d::get_time(), m_buffer, and peekTopFlit().
Referenced by VirtualChannel_d::need_stage_nextcycle().
flit_d* flitBuffer_d::peekTopFlit () [inline]
Definition at line 64 of file flitBuffer_d.hh.
References m_buffer.
Referenced by VirtualChannel_d::grant_vc(), isReady(), isReadyForNext(), VirtualChannel_d::need_stage(), VirtualChannel_d::need_stage_nextcycle(), NetworkLink_d::peekLink(), and VirtualChannel_d::peekTopFlit().
void flitBuffer_d::print (std::ostream & out) const
Definition at line 72 of file flitBuffer_d.cc.
References m_buffer.
Referenced by operator<<().
void flitBuffer_d::setMaxSize (int maximum)
Definition at line 84 of file flitBuffer_d.cc.
References max_size.
Member Data Documentation
std::vector<flit_d *> flitBuffer_d::m_buffer [private]
Definition at line 79 of file flitBuffer_d.hh.
Referenced by functionalWrite(), getTopFlit(), insert(), isEmpty(), isFull(), isReady(), isReadyForNext(), peekTopFlit(), and print().
int flitBuffer_d::max_size [private]
Definition at line 80 of file flitBuffer_d.hh.
Referenced by flitBuffer_d(), isFull(), and setMaxSize().
The documentation for this class was generated from the following files:
mem/ruby/network/garnet/fixed-pipeline/flitBuffer_d.hh
mem/ruby/network/garnet/fixed-pipeline/flitBuffer_d.cc