gem5: AmbaFake Class Reference
AmbaFake Class Reference
#include <amba_fake.hh>