gem5: EtherLink::Link Class Reference
EtherLink::Link Class Reference
#include <etherlink.hh>
Public Member Functions
Link (const std::string &name, EtherLink *p, int num, double rate, Tick delay, Tick delay_var, EtherDump *dump)
~Link ()
const std::string name () const
bool busy () const
bool transmit (EthPacketPtr packet)
void setTxInt (Interface *i)
void setRxInt (Interface *i)
void serialize (const std::string &base, std::ostream &os)
void unserialize (const std::string &base, Checkpoint *cp, const std::string &section)
Protected Types
typedef EventWrapper< Link,&Link::txDone > DoneEvent
Protected Member Functions
void txDone ()
void txComplete (EthPacketPtr packet)
Protected Attributes
std::string objName
EtherLink * parent
int number
Interface * txint
Interface * rxint
double ticksPerByte
Tick linkDelay
Tick delayVar
EtherDump * dump
EthPacketPtr packet
DoneEvent doneEvent
Friends
class LinkDelayEvent
void DoneEvent::process ()
Detailed Description
Definition at line 60 of file etherlink.hh.
Member Typedef Documentation
typedef EventWrapper<Link, &Link::txDone> EtherLink::Link::DoneEvent [protected]
Definition at line 82 of file etherlink.hh.
Constructor & Destructor Documentation
EtherLink::Link::Link (const std::string & name, EtherLink * p, int num, double rate, Tick delay, Tick delay_var, EtherDump * dump)
EtherLink::Link::~Link () [inline]
Definition at line 92 of file etherlink.hh.
Member Function Documentation
bool EtherLink::Link::busy () const [inline]
Definition at line 96 of file etherlink.hh.
References packet.
Referenced by EtherLink::Interface::isBusy(), transmit(), and txDone().
const std::string EtherLink::Link::name () const [inline]
Definition at line 94 of file etherlink.hh.
References objName.
void EtherLink::Link::serialize (const std::string & base, std::ostream & os)
void EtherLink::Link::setRxInt (Interface * i) [inline]
Definition at line 100 of file etherlink.hh.
References rxint.
void EtherLink::Link::setTxInt (Interface * i) [inline]
Definition at line 99 of file etherlink.hh.
References txint.
bool EtherLink::Link::transmit (EthPacketPtr packet)
Definition at line 171 of file etherlink.cc.
References busy(), curTick(), RefCountingPtr< T >::data, DDUMP, delayVar, doneEvent, DPRINTF, packet, parent, Random::random(), random_mt, EventManager::schedule(), and ticksPerByte.
Referenced by EtherLink::Interface::recvPacket().
void EtherLink::Link::txComplete (EthPacketPtr packet) [protected]
Definition at line 124 of file etherlink.cc.
References RefCountingPtr< T >::data, DDUMP, DPRINTF, rxint, and EtherInt::sendPacket().
Referenced by LinkDelayEvent::process(), and txDone().
void EtherLink::Link::txDone () [protected]
Definition at line 151 of file etherlink.cc.
References busy(), curTick(), DPRINTF, EtherDump::dump(), dump, MipsISA::event, linkDelay, LinkDelayEvent, packet, parent, EventManager::schedule(), EtherLink::Interface::sendDone(), txComplete(), and txint.
void EtherLink::Link::unserialize (const std::string & base, Checkpoint * cp, const std::string & section)
Friends And Related Function Documentation
void DoneEvent::process () [friend]
friend class LinkDelayEvent [friend]
Definition at line 86 of file etherlink.hh.
Referenced by txDone().
Member Data Documentation
Tick EtherLink::Link::delayVar [protected]
Definition at line 73 of file etherlink.hh.
Referenced by transmit().
DoneEvent EtherLink::Link::doneEvent [protected]
Definition at line 84 of file etherlink.hh.
Referenced by transmit().
EtherDump* EtherLink::Link::dump [protected]
Definition at line 74 of file etherlink.hh.
Referenced by txDone().
Tick EtherLink::Link::linkDelay [protected]
Definition at line 72 of file etherlink.hh.
Referenced by txDone().
int EtherLink::Link::number [protected]
Definition at line 66 of file etherlink.hh.
Referenced by LinkDelayEvent::serialize().
std::string EtherLink::Link::objName [protected]
Definition at line 63 of file etherlink.hh.
Referenced by name().
EthPacketPtr EtherLink::Link::packet [protected]
Definition at line 80 of file etherlink.hh.
Referenced by busy(), transmit(), and txDone().
EtherLink* EtherLink::Link::parent [protected]
Definition at line 65 of file etherlink.hh.
Referenced by LinkDelayEvent::serialize(), transmit(), and txDone().
Interface* EtherLink::Link::rxint [protected]
Definition at line 69 of file etherlink.hh.
Referenced by setRxInt(), and txComplete().
double EtherLink::Link::ticksPerByte [protected]
Definition at line 71 of file etherlink.hh.
Referenced by transmit().
Interface* EtherLink::Link::txint [protected]
Definition at line 68 of file etherlink.hh.
Referenced by setTxInt(), and txDone().
The documentation for this class was generated from the following files:
dev/etherlink.hh
dev/etherlink.cc