gem5: PollQueue Class Reference
PollQueue Class Reference
#include <pollevent.hh>
Public Member Functions
PollQueue ()
~PollQueue ()
void copy ()
void remove (PollEvent *event)
void schedule (PollEvent *event)
void service ()
Static Public Member Functions
static void setupAsyncIO (int fd, bool set)
static void handleIO (int)
static void handleALRM (int)
static void removeHandler ()
static void setupHandler ()
Static Protected Attributes
static bool handler = false
static struct sigaction oldio
static struct sigaction oldalrm
Private Types
typedef std::vector< PollEvent * > eventvec_t
Private Attributes
eventvec_t events
pollfd * poll_fds
int max_size
int num_fds
Detailed Description
Definition at line 67 of file pollevent.hh.
Member Typedef Documentation
typedef std::vector<PollEvent *> PollQueue::eventvec_t [private]
Definition at line 70 of file pollevent.hh.
Constructor & Destructor Documentation
PollQueue::PollQueue ()
Definition at line 106 of file pollevent.cc.
PollQueue::~PollQueue ()
Definition at line 110 of file pollevent.cc.
References ArmISA::fd, ArmISA::i, num_fds, poll_fds, removeHandler(), and setupAsyncIO().
Member Function Documentation
void PollQueue::copy ()
Definition at line 120 of file pollevent.cc.
References events, ArmISA::i, num_fds, and poll_fds.
Referenced by PollEvent::disable(), PollEvent::enable(), remove(), and schedule().
void PollQueue::handleALRM (int sig) [static]
Definition at line 270 of file pollevent.cc.
References async_alarm, async_event, and panic.
void PollQueue::handleIO (int sig) [static]
Definition at line 260 of file pollevent.cc.
References async_event, async_io, and panic.
void PollQueue::remove (PollEvent * event)
Definition at line 135 of file pollevent.cc.
References copy(), events, ArmISA::i, and panic.
Referenced by Terminal::detach(), VncServer::detach(), BaseRemoteGDB::detach(), and PollEvent::~PollEvent().
void PollQueue::removeHandler () [static]
Definition at line 250 of file pollevent.cc.
References oldalrm, oldio, and panic.
Referenced by ~PollQueue().
void PollQueue::schedule (PollEvent * event)
Definition at line 155 of file pollevent.cc.
References copy(), events, max_size, num_fds, panic, PollEvent::pfd, poll_fds, PollEvent::queue, setupAsyncIO(), and setupHandler().
Referenced by Terminal::accept(), VncServer::accept(), EtherTap::attach(), BaseRemoteGDB::attach(), Terminal::listen(), TapListener::listen(), VncServer::listen(), GDBListener::listen(), and EtherTap::unserialize().
void PollQueue::service ()
Definition at line 183 of file pollevent.cc.
References events, ArmISA::i, num_fds, and poll_fds.
Referenced by simulate().
void PollQueue::setupAsyncIO (int fd, bool set) [static]
Definition at line 205 of file pollevent.cc.
References ArmISA::fd, and panic.
Referenced by schedule(), and ~PollQueue().
void PollQueue::setupHandler () [static]
Definition at line 226 of file pollevent.cc.
References handler, oldalrm, oldio, and panic.
Referenced by schedule().
Member Data Documentation
eventvec_t PollQueue::events [private]
Definition at line 71 of file pollevent.hh.
Referenced by copy(), remove(), schedule(), and service().
bool PollQueue::handler = false [static, read, protected]
Definition at line 87 of file pollevent.hh.
Referenced by setupHandler().
int PollQueue::max_size [private]
Definition at line 74 of file pollevent.hh.
Referenced by schedule().
int PollQueue::num_fds [private]
Definition at line 75 of file pollevent.hh.
Referenced by copy(), schedule(), service(), and ~PollQueue().
struct sigaction PollQueue::oldalrm [static, protected]
Definition at line 89 of file pollevent.hh.
Referenced by removeHandler(), and setupHandler().
struct sigaction PollQueue::oldio [static, protected]
Definition at line 88 of file pollevent.hh.
Referenced by removeHandler(), and setupHandler().
pollfd* PollQueue::poll_fds [private]
Definition at line 73 of file pollevent.hh.
Referenced by copy(), schedule(), service(), and ~PollQueue().
The documentation for this class was generated from the following files:
base/pollevent.hh
base/pollevent.cc