gem5: AmpUnit Class Reference
AmpUnit Class Reference
#include <AmpUnit.hh>
Public Types
enum AmpModel { NO_MODEL = 0, GENERIC_AMP }
Public Member Functions
AmpUnit (const string &amp_model_str_, const TechParameter *tech_param_ptr_)
~AmpUnit ()
double get_e_access () const
Private Member Functions
void init ()
Private Attributes
AmpModel m_amp_model
const TechParameter * m_tech_param_ptr
double m_e_access
Detailed Description
Definition at line 43 of file AmpUnit.hh.
Member Enumeration Documentation
enum AmpUnit::AmpModel
Enumerator:
NO_MODEL
GENERIC_AMP
Definition at line 46 of file AmpUnit.hh.
Constructor & Destructor Documentation
AmpUnit::AmpUnit (const string & amp_model_str_, const TechParameter * tech_param_ptr_)
Definition at line 39 of file AmpUnit.cc.
References init(), m_amp_model, m_tech_param_ptr, and NO_MODEL.
AmpUnit::~AmpUnit ()
Definition at line 61 of file AmpUnit.cc.
Member Function Documentation
double AmpUnit::get_e_access () const [inline]
Definition at line 60 of file AmpUnit.hh.
References m_e_access.
Referenced by SRAM::calc_e_read().
void AmpUnit::init () [private]
Definition at line 64 of file AmpUnit.cc.
References TechParameter::get_amp_idsat(), TechParameter::get_period(), TechParameter::get_vdd(), m_e_access, and m_tech_param_ptr.
Referenced by AmpUnit().
Member Data Documentation
AmpModel AmpUnit::m_amp_model [private]
Definition at line 66 of file AmpUnit.hh.
Referenced by AmpUnit().
double AmpUnit::m_e_access [private]
Definition at line 69 of file AmpUnit.hh.
Referenced by get_e_access(), and init().
const TechParameter* AmpUnit::m_tech_param_ptr [private]
Definition at line 67 of file AmpUnit.hh.
Referenced by AmpUnit(), and init().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/Buffer/AmpUnit.hh
mem/ruby/network/orion/Buffer/AmpUnit.cc