gem5: FlipFlop Class Reference
FlipFlop Class Reference
#include <FlipFlop.hh>
Public Types
enum FFModel { NO_MODEL = 0, NEG_DFF }
Public Member Functions
FlipFlop (const string &ff_model_str_, double load_, const TechParameter *tech_param_ptr_)
~FlipFlop ()
double get_e_switch () const
double get_e_keep_1 () const
double get_e_keep_0 () const
double get_e_clock () const
double get_i_static () const
Private Member Functions
void init ()
double calc_node_cap (uint32_t num_fanin_, uint32_t num_fanout_)
double calc_clock_cap ()
double calc_i_static ()
Private Attributes
FFModel m_ff_model
const TechParameter * m_tech_param_ptr
double m_load
double m_e_switch
double m_e_keep_1
double m_e_keep_0
double m_e_clock
double m_i_static
Detailed Description
Definition at line 43 of file FlipFlop.hh.
Member Enumeration Documentation
enum FlipFlop::FFModel
Enumerator:
NO_MODEL
NEG_DFF
Definition at line 46 of file FlipFlop.hh.
Constructor & Destructor Documentation
FlipFlop::FlipFlop (const string & ff_model_str_, double load_, const TechParameter * tech_param_ptr_)
Definition at line 44 of file FlipFlop.cc.
References init(), m_ff_model, m_load, m_tech_param_ptr, and NO_MODEL.
FlipFlop::~FlipFlop ()
Definition at line 70 of file FlipFlop.cc.
Member Function Documentation
double FlipFlop::calc_clock_cap () [private]
Definition at line 121 of file FlipFlop.cc.
References TechParameter::calc_gatecap(), TechParameter::get_WdecNORn(), TechParameter::get_WdecNORp(), and m_tech_param_ptr.
Referenced by init().
double FlipFlop::calc_i_static () [private]
Definition at line 128 of file FlipFlop.cc.
References TechParameter::get_NOR2_TAB(), TechParameter::get_WdecNORn(), TechParameter::get_WdecNORp(), and m_tech_param_ptr.
Referenced by init().
double FlipFlop::calc_node_cap (uint32_t num_fanin_, uint32_t num_fanout_) [private]
Definition at line 106 of file FlipFlop.cc.
References TechParameter::calc_draincap(), TechParameter::calc_gatecap(), TechParameter::get_WdecNORn(), TechParameter::get_WdecNORp(), m_tech_param_ptr, TechParameter::NCH, and TechParameter::PCH.
Referenced by init().
double FlipFlop::get_e_clock () const [inline]
Definition at line 64 of file FlipFlop.hh.
References m_e_clock.
Referenced by RRArbiter::calc_dynamic_energy(), MatrixArbiter::calc_dynamic_energy(), and Register::init().
double FlipFlop::get_e_keep_0 () const [inline]
Definition at line 63 of file FlipFlop.hh.
References m_e_keep_0.
Referenced by RRArbiter::calc_dynamic_energy(), and MatrixArbiter::calc_dynamic_energy().
double FlipFlop::get_e_keep_1 () const [inline]
Definition at line 62 of file FlipFlop.hh.
References m_e_keep_1.
Referenced by MatrixArbiter::calc_dynamic_energy().
double FlipFlop::get_e_switch () const [inline]
Definition at line 61 of file FlipFlop.hh.
References m_e_switch.
Referenced by RRArbiter::calc_dynamic_energy(), MatrixArbiter::calc_dynamic_energy(), and Register::init().
double FlipFlop::get_i_static () const [inline]
Definition at line 65 of file FlipFlop.hh.
References m_i_static.
Referenced by Register::calc_i_static().
void FlipFlop::init () [private]
Definition at line 73 of file FlipFlop.cc.
References MipsISA::c2, calc_clock_cap(), calc_i_static(), calc_node_cap(), TechParameter::get_EnergyFactor(), m_e_clock, m_e_keep_0, m_e_keep_1, m_e_switch, m_ff_model, m_i_static, m_load, m_tech_param_ptr, and NEG_DFF.
Referenced by FlipFlop().
Member Data Documentation
double FlipFlop::m_e_clock [private]
Definition at line 82 of file FlipFlop.hh.
Referenced by get_e_clock(), and init().
double FlipFlop::m_e_keep_0 [private]
Definition at line 81 of file FlipFlop.hh.
Referenced by get_e_keep_0(), and init().
double FlipFlop::m_e_keep_1 [private]
Definition at line 80 of file FlipFlop.hh.
Referenced by get_e_keep_1(), and init().
double FlipFlop::m_e_switch [private]
Definition at line 79 of file FlipFlop.hh.
Referenced by get_e_switch(), and init().
FFModel FlipFlop::m_ff_model [private]
Definition at line 74 of file FlipFlop.hh.
Referenced by FlipFlop(), and init().
double FlipFlop::m_i_static [private]
Definition at line 84 of file FlipFlop.hh.
Referenced by get_i_static(), and init().
double FlipFlop::m_load [private]
Definition at line 77 of file FlipFlop.hh.
Referenced by FlipFlop(), and init().
const TechParameter* FlipFlop::m_tech_param_ptr [private]
Definition at line 75 of file FlipFlop.hh.
Referenced by calc_clock_cap(), calc_i_static(), calc_node_cap(), FlipFlop(), and init().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/FlipFlop.hh
mem/ruby/network/orion/FlipFlop.cc