gem5: VideoConvert Class Reference
VideoConvert Class Reference
#include <convert.hh>
Public Types
enum Mode {
UnknownMode, bgr565, rgb565, bgr8888,
rgb8888, rgb888, bgr888, bgr444,
bgr4444, rgb444, rgb4444
}
Public Member Functions
BitUnion32 (Rgb8888) Bitfield<7
EndBitUnion (Rgb8888) BitUnion32(Bgr8888) Bitfield<7
EndBitUnion (Bgr8888) BitUnion16(Bgr565) Bitfield<4
EndBitUnion (Bgr565) BitUnion16(Rgb565) Bitfield<4
EndBitUnion (Rgb565) VideoConvert(Mode input_mode
Setup the converter with the given parameters.
~VideoConvert ()
Destructor.
uint8_t * convert (const uint8_t *fb) const
Convert the provided frame buffer data into the format specified in the constructor.
int area () const
Return the number of pixels that this buffer specifies.
uint64_t getHash (const uint8_t *fb) const
Returns a hash on the raw data.
Public Attributes
blue
Bitfield< 15, 8 > green
Bitfield< 23, 16 > red
Bitfield< 31, 24 > alpha
red
Bitfield< 23, 16 > blue
Bitfield< 10, 5 > green
Bitfield< 15, 11 > blue
Mode output_mode
Mode int _width
Mode int int _height
Private Member Functions
uint8_t * bgr8888rgb8888 (const uint8_t *fb) const
Convert a bgr8888 input to rgb8888.
uint8_t * m565rgb8888 (const uint8_t *fb, bool bgr) const
Convert a bgr565 or rgb565 input to rgb8888.
Private Attributes
Mode inputMode
Mode outputMode
int width
int height
Detailed Description
Definition at line 50 of file convert.hh.
Member Enumeration Documentation
enum VideoConvert::Mode
Enumerator:
UnknownMode
bgr565
rgb565
bgr8888
rgb8888
rgb888
bgr888
bgr444
bgr4444
rgb444
rgb4444
Definition at line 53 of file convert.hh.
Constructor & Destructor Documentation
VideoConvert::~VideoConvert ()
Destructor.
Definition at line 65 of file convert.cc.
Member Function Documentation
int VideoConvert::area () const [inline]
Return the number of pixels that this buffer specifies.
Returns:
number of pixels
Definition at line 116 of file convert.hh.
References height, and width.
Referenced by bgr8888rgb8888(), and m565rgb8888().
uint8_t * VideoConvert::bgr8888rgb8888 (const uint8_t * fb) const [private]
Convert a bgr8888 input to rgb8888.
Parameters:
fb the data to convert
Returns:
converted data
Definition at line 116 of file convert.cc.
References area(), and X86ISA::x.
Referenced by convert().
VideoConvert::BitUnion32 (Rgb8888)
uint8_t * VideoConvert::convert (const uint8_t * fb) const
Convert the provided frame buffer data into the format specified in the constructor.
Parameters:
fb the frame buffer to convert
Returns:
the converted data (user must free)
Definition at line 70 of file convert.cc.
References bgr565, bgr8888, bgr8888rgb8888(), inputMode, m565rgb8888(), panic, and rgb565.
Referenced by VncServer::sendFrameBufferUpdate(), and Bitmap::write().
VideoConvert::EndBitUnion (Rgb8888)
VideoConvert::EndBitUnion (Bgr565)
VideoConvert::EndBitUnion (Rgb565)
Setup the converter with the given parameters.
Parameters:
input_mode type of data that will be provided
output_mode type of data that should be output
_width width of the frame buffer
_height height of the frame buffer
VideoConvert::EndBitUnion (Bgr8888)
uint64_t VideoConvert::getHash (const uint8_t * fb) const [inline]
Returns a hash on the raw data.
Returns:
hash of the buffer
Definition at line 123 of file convert.hh.
References height, and width.
Referenced by Bitmap::getHash().
uint8_t * VideoConvert::m565rgb8888 (const uint8_t * fb, bool bgr) const [private]
Convert a bgr565 or rgb565 input to rgb8888.
Parameters:
fb the data to convert
bgr true if the input data is bgr565
Returns:
converted data
Definition at line 85 of file convert.cc.
References area(), and X86ISA::x.
Referenced by convert().
Member Data Documentation
Mode int int VideoConvert::_height
Definition at line 100 of file convert.hh.
Mode int VideoConvert::_width
Definition at line 100 of file convert.hh.
Bitfield< 31, 24 > VideoConvert::alpha
Definition at line 72 of file convert.hh.
Bitfield<15,11> VideoConvert::blue
Definition at line 85 of file convert.hh.
Bitfield< 15, 11 > VideoConvert::blue
Definition at line 69 of file convert.hh.
Bitfield<23,16> VideoConvert::blue
Definition at line 78 of file convert.hh.
Bitfield< 10, 5 > VideoConvert::green
Definition at line 70 of file convert.hh.
Bitfield<10,5> VideoConvert::green
Definition at line 84 of file convert.hh.
int VideoConvert::height [private]
Definition at line 147 of file convert.hh.
Referenced by area(), and getHash().
Mode VideoConvert::inputMode [private]
Definition at line 144 of file convert.hh.
Referenced by convert().
Mode VideoConvert::output_mode
Definition at line 100 of file convert.hh.
Mode VideoConvert::outputMode [private]
Definition at line 145 of file convert.hh.
Bitfield<23,16> VideoConvert::red
Definition at line 71 of file convert.hh.
VideoConvert::red
Definition at line 76 of file convert.hh.
int VideoConvert::width [private]
Definition at line 146 of file convert.hh.
Referenced by area(), and getHash().
The documentation for this class was generated from the following files:
base/vnc/convert.hh
base/vnc/convert.cc