gem5: Stats::DataWrapVec< Derived, InfoProxyType > Class Template Reference
Stats::DataWrapVec< Derived, InfoProxyType > Class Template Reference
#include <statistics.hh>