gem5: FALRU Class Reference
FALRU Class Reference
A fully associative LRU cache.
#include <fa_lru.hh>