gem5: IGbE::DescCache< T > Class Template Reference
IGbE::DescCache< T > Class Template Reference
Public Member Functions
DescCache (IGbE *i, const std::string n, int s)
virtual ~DescCache ()
std::string name ()
void areaChanged ()
If the address/len/head change when we've got descriptors that are dirty that is very bad.
void writeback (Addr aMask)
void writeback1 ()
void fetchDescriptors ()
Fetch a chunk of descriptors into the descriptor cache.
void fetchDescriptors1 ()
void fetchComplete ()
Called by event when dma to read descriptors is completed.
void wbComplete ()
Called by event when dma to writeback descriptors is completed.
unsigned descLeft () const
unsigned descUsed () const
unsigned descUnused () const
void reset ()
virtual void serialize (std::ostream &os)
virtual void unserialize (Checkpoint *cp, const std::string &section)
virtual bool hasOutstandingEvents ()
Public Attributes
std::string annSmFetch
Annotate sm.
std::string annSmWb
std::string annUnusedDescQ
std::string annUsedCacheQ
std::string annUsedDescQ
std::string annUnusedCacheQ
std::string annDescQ
EventWrapper< DescCache,&DescCache::writeback1 > wbDelayEvent
EventWrapper< DescCache,&DescCache::fetchDescriptors1 > fetchDelayEvent
EventWrapper< DescCache,&DescCache::fetchComplete > fetchEvent
EventWrapper< DescCache,&DescCache::wbComplete > wbEvent
Protected Types
typedef std::deque< T * > CacheType
Protected Member Functions
virtual Addr descBase () const =0
virtual long descHead () const =0
virtual long descTail () const =0
virtual long descLen () const =0
virtual void updateHead (long h)=0
virtual void enableSm ()=0
virtual void actionAfterWb ()
virtual void fetchAfterWb ()=0
Addr pciToDma (Addr a)
Shortcut for DMA address translation.
Protected Attributes
CacheType usedCache
CacheType unusedCache
T * fetchBuf
T * wbBuf
IGbE * igbe
std::string _name
int cachePnt
int size
int curFetching
int wbOut
bool moreToWb
Addr wbAlignment
EthPacketPtr pktPtr
The packet that is currently being dmad to memory if any.
Detailed Description
template<class T>
class IGbE::DescCache< T >
Definition at line 214 of file i8254xGBe.hh.
Member Typedef Documentation
template<class T> typedef std::deque<T *> IGbE::DescCache< T >::CacheType [protected]
Definition at line 226 of file i8254xGBe.hh.
Constructor & Destructor Documentation
template<class T > IGbE::DescCache< T >::DescCache (IGbE * i, const std::string n, int s)
Definition at line 822 of file i8254xGBe.cc.
References IGbE::DescCache< T >::fetchBuf, IGbE::DescCache< T >::size, and IGbE::DescCache< T >::wbBuf.
template<class T > IGbE::DescCache< T >::~DescCache () [virtual]
Definition at line 832 of file i8254xGBe.cc.
References IGbE::DescCache< T >::fetchBuf, IGbE::DescCache< T >::reset(), and IGbE::DescCache< T >::wbBuf.
Member Function Documentation
template<class T> virtual void IGbE::DescCache< T >::actionAfterWb () [inline, protected, virtual]
Reimplemented in IGbE::TxDescCache.
Definition at line 223 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::wbComplete().
template<class T > void IGbE::DescCache< T >::areaChanged ()
If the address/len/head change when we've got descriptors that are dirty that is very bad.
This function checks that we don't and if we do panics.
Definition at line 841 of file i8254xGBe.cc.
References IGbE::DescCache< T >::curFetching, panic, IGbE::DescCache< T >::reset(), IGbE::DescCache< T >::usedCache, and IGbE::DescCache< T >::wbOut.
Referenced by IGbE::write().
template<class T> virtual Addr IGbE::DescCache< T >::descBase () const [protected, pure virtual]
Implemented in IGbE::RxDescCache, and IGbE::TxDescCache.
Referenced by IGbE::DescCache< T >::fetchDescriptors1(), and IGbE::DescCache< T >::writeback1().
template<class T> virtual long IGbE::DescCache< T >::descHead () const [protected, pure virtual]
Implemented in IGbE::RxDescCache, and IGbE::TxDescCache.
Referenced by IGbE::DescCache< T >::fetchDescriptors(), IGbE::DescCache< T >::wbComplete(), IGbE::DescCache< T >::writeback(), and IGbE::DescCache< T >::writeback1().
template<class T> unsigned IGbE::DescCache< T >::descLeft () const [inline]
Definition at line 305 of file i8254xGBe.hh.
Referenced by IGbE::ethTxDone(), IGbE::DescCache< T >::fetchDescriptors(), IGbE::rxStateMachine(), IGbE::txStateMachine(), and IGbE::DescCache< T >::writeback().
template<class T> virtual long IGbE::DescCache< T >::descLen () const [protected, pure virtual]
Implemented in IGbE::RxDescCache, and IGbE::TxDescCache.
Referenced by IGbE::DescCache< iGbReg::RxDesc >::descLeft(), IGbE::DescCache< T >::fetchComplete(), IGbE::DescCache< T >::fetchDescriptors(), IGbE::DescCache< T >::wbComplete(), and IGbE::DescCache< T >::writeback().
template<class T> virtual long IGbE::DescCache< T >::descTail () const [protected, pure virtual]
Implemented in IGbE::RxDescCache, and IGbE::TxDescCache.
Referenced by IGbE::DescCache< iGbReg::RxDesc >::descLeft(), IGbE::DescCache< T >::fetchComplete(), IGbE::DescCache< T >::fetchDescriptors(), and IGbE::DescCache< T >::writeback().
template<class T> unsigned IGbE::DescCache< T >::descUnused () const [inline]
Definition at line 321 of file i8254xGBe.hh.
Referenced by IGbE::rxStateMachine(), and IGbE::txStateMachine().
template<class T> unsigned IGbE::DescCache< T >::descUsed () const [inline]
Definition at line 318 of file i8254xGBe.hh.
Referenced by IGbE::rxStateMachine().
template<class T> virtual void IGbE::DescCache< T >::enableSm () [protected, pure virtual]
Implemented in IGbE::RxDescCache, and IGbE::TxDescCache.
Referenced by IGbE::DescCache< T >::fetchComplete().
template<class T> virtual void IGbE::DescCache< T >::fetchAfterWb () [protected, pure virtual]
Implemented in IGbE::RxDescCache, and IGbE::TxDescCache.
Referenced by IGbE::DescCache< T >::wbComplete().
template<class T > void IGbE::DescCache< T >::fetchComplete ()
Called by event when dma to read descriptors is completed.
Definition at line 1008 of file i8254xGBe.cc.
References IGbE::anBegin(), IGbE::anDq(), IGbE::DescCache< T >::annDescQ, IGbE::DescCache< T >::annSmFetch, IGbE::DescCache< T >::annUnusedCacheQ, IGbE::DescCache< T >::annUnusedDescQ, IGbE::anQ(), IGbE::anWe(), IGbE::anWf(), IGbE::DescCache< T >::cachePnt, IGbE::checkDrain(), IGbE::DescCache< T >::curFetching, IGbE::DescCache< T >::descLen(), IGbE::DescCache< T >::descTail(), DPRINTF, IGbE::DescCache< T >::enableSm(), IGbE::DescCache< T >::fetchBuf, CPA::FL_WAIT, IGbE::DescCache< T >::igbe, IGbE::DescCache< T >::size, IGbE::DescCache< T >::unusedCache, IGbE::DescCache< T >::usedCache, and X86ISA::x.
template<class T > void IGbE::DescCache< T >::fetchDescriptors ()
Fetch a chunk of descriptors into the descriptor cache.
Calls fetchComplete when the memory system returns the data
Definition at line 934 of file i8254xGBe.cc.
References IGbE::anBegin(), IGbE::DescCache< T >::annDescQ, IGbE::DescCache< T >::annSmFetch, IGbE::DescCache< T >::annUnusedDescQ, IGbE::anPq(), IGbE::anRq(), IGbE::anWe(), IGbE::anWf(), IGbE::DescCache< T >::cachePnt, IGbE::DescCache< T >::curFetching, curTick(), IGbE::DescCache< T >::descHead(), IGbE::DescCache< T >::descLeft(), IGbE::DescCache< T >::descLen(), IGbE::DescCache< T >::descTail(), DPRINTF, IGbE::fetchDelay, IGbE::DescCache< T >::fetchDelayEvent, IGbE::DescCache< T >::igbe, EventManager::schedule(), Event::scheduled(), IGbE::DescCache< T >::size, IGbE::DescCache< T >::unusedCache, and IGbE::DescCache< T >::usedCache.
Referenced by IGbE::rxStateMachine(), IGbE::txStateMachine(), and IGbE::write().
template<class T > void IGbE::DescCache< T >::fetchDescriptors1 ()
Definition at line 986 of file i8254xGBe.cc.
References IGbE::anBegin(), IGbE::DescCache< T >::annSmFetch, IGbE::DescCache< T >::cachePnt, IGbE::DescCache< T >::curFetching, curTick(), IGbE::DescCache< T >::descBase(), DmaDevice::dmaRead(), DPRINTF, IGbE::DescCache< T >::fetchBuf, IGbE::fetchCompDelay, IGbE::fetchDelay, IGbE::DescCache< T >::fetchDelayEvent, IGbE::DescCache< T >::fetchEvent, Drainable::getDrainState(), IGbE::DescCache< T >::igbe, IGbE::DescCache< T >::pciToDma(), and EventManager::schedule().
template<class T> virtual bool IGbE::DescCache< T >::hasOutstandingEvents () [inline, virtual]
Reimplemented in IGbE::RxDescCache, and IGbE::TxDescCache.
Definition at line 330 of file i8254xGBe.hh.
template<class T> std::string IGbE::DescCache< T >::name () [inline]
Definition at line 272 of file i8254xGBe.hh.
template<class T> Addr IGbE::DescCache< T >::pciToDma (Addr a) [inline, protected]
Shortcut for DMA address translation.
Definition at line 262 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::fetchDescriptors1(), and IGbE::DescCache< T >::writeback1().
template<class T > void IGbE::DescCache< T >::reset ()
Definition at line 1103 of file i8254xGBe.cc.
References IGbE::DescCache< T >::cachePnt, DPRINTF, IGbE::DescCache< T >::unusedCache, IGbE::DescCache< T >::usedCache, and X86ISA::x.
Referenced by IGbE::DescCache< T >::areaChanged(), IGbE::write(), and IGbE::DescCache< T >::~DescCache().
template<class T > void IGbE::DescCache< T >::serialize (std::ostream & os) [virtual]
Reimplemented in IGbE::RxDescCache, and IGbE::TxDescCache.
Definition at line 1120 of file i8254xGBe.cc.
References arrayParamOut(), IGbE::DescCache< T >::cachePnt, csprintf(), IGbE::DescCache< T >::curFetching, IGbE::DescCache< T >::fetchDelayEvent, IGbE::DescCache< T >::moreToWb, Event::scheduled(), SERIALIZE_SCALAR, IGbE::DescCache< T >::unusedCache, IGbE::DescCache< T >::usedCache, IGbE::DescCache< T >::wbAlignment, IGbE::DescCache< T >::wbDelayEvent, IGbE::DescCache< T >::wbOut, Event::when(), and X86ISA::x.
template<class T > void IGbE::DescCache< T >::unserialize (Checkpoint * cp, const std::string & section) [virtual]
Reimplemented in IGbE::RxDescCache, and IGbE::TxDescCache.
Definition at line 1155 of file i8254xGBe.cc.
References arrayParamIn(), IGbE::DescCache< T >::cachePnt, csprintf(), IGbE::DescCache< T >::curFetching, IGbE::DescCache< T >::fetchDelayEvent, IGbE::DescCache< T >::igbe, IGbE::DescCache< T >::moreToWb, EventManager::schedule(), UNSERIALIZE_SCALAR, IGbE::DescCache< T >::unusedCache, IGbE::DescCache< T >::usedCache, IGbE::DescCache< T >::wbAlignment, IGbE::DescCache< T >::wbDelayEvent, IGbE::DescCache< T >::wbOut, and X86ISA::x.
template<class T> virtual void IGbE::DescCache< T >::updateHead (long h) [protected, pure virtual]
Implemented in IGbE::RxDescCache, and IGbE::TxDescCache.
Referenced by IGbE::DescCache< T >::wbComplete().
template<class T > void IGbE::DescCache< T >::wbComplete ()
Called by event when dma to writeback descriptors is completed.
Definition at line 1052 of file i8254xGBe.cc.
References IGbE::DescCache< T >::actionAfterWb(), IGbE::anBegin(), IGbE::anDq(), IGbE::DescCache< T >::annDescQ, IGbE::DescCache< T >::annSmWb, IGbE::DescCache< T >::annUsedCacheQ, IGbE::anWe(), IGbE::checkDrain(), IGbE::DescCache< T >::descHead(), IGbE::DescCache< T >::descLen(), DPRINTF, IGbE::DescCache< T >::fetchAfterWb(), CPA::FL_WAIT, IGbE::DescCache< T >::igbe, IGbE::DescCache< T >::moreToWb, IGbE::DescCache< T >::updateHead(), IGbE::DescCache< T >::usedCache, IGbE::DescCache< T >::wbAlignment, IGbE::DescCache< T >::wbOut, IGbE::DescCache< T >::writeback(), and X86ISA::x.
template<class T > void IGbE::DescCache< T >::writeback (Addr aMask)
Definition at line 851 of file i8254xGBe.cc.
References IGbE::anBegin(), IGbE::DescCache< T >::annSmWb, IGbE::DescCache< T >::annUsedCacheQ, IGbE::anWe(), IGbE::DescCache< T >::cachePnt, curTick(), IGbE::DescCache< T >::descHead(), IGbE::DescCache< T >::descLeft(), IGbE::DescCache< T >::descLen(), IGbE::DescCache< T >::descTail(), DPRINTF, CPA::FL_WAIT, IGbE::DescCache< T >::igbe, IGbE::DescCache< T >::moreToWb, EventManager::schedule(), Event::scheduled(), IGbE::DescCache< T >::usedCache, IGbE::DescCache< T >::wbAlignment, IGbE::wbDelay, IGbE::DescCache< T >::wbDelayEvent, and IGbE::DescCache< T >::wbOut.
Referenced by IGbE::radvProcess(), IGbE::rdtrProcess(), IGbE::read(), IGbE::rxStateMachine(), IGbE::tadvProcess(), IGbE::tidvProcess(), IGbE::txStateMachine(), and IGbE::DescCache< T >::wbComplete().
template<class T > void IGbE::DescCache< T >::writeback1 ()
Definition at line 905 of file i8254xGBe.cc.
References IGbE::anBegin(), IGbE::DescCache< T >::annDescQ, IGbE::DescCache< T >::annSmWb, IGbE::DescCache< T >::annUsedCacheQ, IGbE::DescCache< T >::annUsedDescQ, IGbE::anPq(), IGbE::anQ(), curTick(), IGbE::DescCache< T >::descBase(), IGbE::DescCache< T >::descHead(), DmaDevice::dmaWrite(), DPRINTF, Drainable::getDrainState(), IGbE::DescCache< T >::igbe, IGbE::DescCache< T >::pciToDma(), EventManager::schedule(), IGbE::DescCache< T >::usedCache, IGbE::DescCache< T >::wbBuf, IGbE::wbCompDelay, IGbE::wbDelay, IGbE::DescCache< T >::wbDelayEvent, IGbE::DescCache< T >::wbEvent, IGbE::DescCache< T >::wbOut, and X86ISA::x.
Member Data Documentation
template<class T> std::string IGbE::DescCache< T >::_name [protected]
Definition at line 237 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< iGbReg::RxDesc >::name().
template<class T> std::string IGbE::DescCache< T >::annDescQ
Definition at line 266 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::fetchComplete(), IGbE::DescCache< T >::fetchDescriptors(), IGbE::DescCache< T >::wbComplete(), and IGbE::DescCache< T >::writeback1().
template<class T> std::string IGbE::DescCache< T >::annSmFetch
Annotate sm.
Definition at line 266 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::fetchComplete(), IGbE::DescCache< T >::fetchDescriptors(), and IGbE::DescCache< T >::fetchDescriptors1().
template<class T> std::string IGbE::DescCache< T >::annSmWb
Definition at line 266 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::wbComplete(), IGbE::DescCache< T >::writeback(), and IGbE::DescCache< T >::writeback1().
template<class T> std::string IGbE::DescCache< T >::annUnusedCacheQ
Definition at line 266 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::fetchComplete(), IGbE::rxStateMachine(), and IGbE::txStateMachine().
template<class T> std::string IGbE::DescCache< T >::annUnusedDescQ
Definition at line 266 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::fetchComplete(), and IGbE::DescCache< T >::fetchDescriptors().
template<class T> std::string IGbE::DescCache< T >::annUsedCacheQ
Definition at line 266 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::wbComplete(), IGbE::DescCache< T >::writeback(), and IGbE::DescCache< T >::writeback1().
template<class T> std::string IGbE::DescCache< T >::annUsedDescQ
Definition at line 266 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::writeback1().
template<class T> int IGbE::DescCache< T >::cachePnt [protected]
Definition at line 240 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< iGbReg::RxDesc >::descLeft(), IGbE::DescCache< T >::fetchComplete(), IGbE::DescCache< T >::fetchDescriptors(), IGbE::DescCache< T >::fetchDescriptors1(), IGbE::DescCache< T >::reset(), IGbE::DescCache< T >::serialize(), IGbE::DescCache< T >::unserialize(), and IGbE::DescCache< T >::writeback().
template<class T> int IGbE::DescCache< T >::curFetching [protected]
Definition at line 246 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::areaChanged(), IGbE::DescCache< T >::fetchComplete(), IGbE::DescCache< T >::fetchDescriptors(), IGbE::DescCache< T >::fetchDescriptors1(), IGbE::DescCache< T >::serialize(), and IGbE::DescCache< T >::unserialize().
template<class T> T* IGbE::DescCache< T >::fetchBuf [protected]
Definition at line 230 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::DescCache(), IGbE::DescCache< T >::fetchComplete(), IGbE::DescCache< T >::fetchDescriptors1(), and IGbE::DescCache< T >::~DescCache().
template<class T> EventWrapper<DescCache, &DescCache::fetchDescriptors1> IGbE::DescCache< T >::fetchDelayEvent
Definition at line 289 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::fetchDescriptors(), IGbE::DescCache< T >::fetchDescriptors1(), IGbE::DescCache< T >::serialize(), and IGbE::DescCache< T >::unserialize().
template<class T> EventWrapper<DescCache, &DescCache::fetchComplete> IGbE::DescCache< T >::fetchEvent
Definition at line 294 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::fetchDescriptors1(), and IGbE::DescCache< iGbReg::RxDesc >::hasOutstandingEvents().
template<class T> IGbE* IGbE::DescCache< T >::igbe [protected]
Definition at line 234 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::fetchComplete(), IGbE::DescCache< T >::fetchDescriptors(), IGbE::DescCache< T >::fetchDescriptors1(), IGbE::DescCache< iGbReg::RxDesc >::pciToDma(), IGbE::DescCache< T >::unserialize(), IGbE::DescCache< T >::wbComplete(), IGbE::DescCache< T >::writeback(), and IGbE::DescCache< T >::writeback1().
template<class T> bool IGbE::DescCache< T >::moreToWb [protected]
Definition at line 253 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::serialize(), IGbE::DescCache< T >::unserialize(), IGbE::DescCache< T >::wbComplete(), and IGbE::DescCache< T >::writeback().
template<class T> EthPacketPtr IGbE::DescCache< T >::pktPtr [protected]
The packet that is currently being dmad to memory if any.
Definition at line 259 of file i8254xGBe.hh.
template<class T> int IGbE::DescCache< T >::size [protected]
Definition at line 243 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::DescCache(), IGbE::DescCache< T >::fetchComplete(), and IGbE::DescCache< T >::fetchDescriptors().
template<class T> CacheType IGbE::DescCache< T >::unusedCache [protected]
Definition at line 228 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< iGbReg::RxDesc >::descLeft(), IGbE::DescCache< iGbReg::RxDesc >::descUnused(), IGbE::DescCache< T >::fetchComplete(), IGbE::DescCache< T >::fetchDescriptors(), IGbE::DescCache< T >::reset(), IGbE::DescCache< T >::serialize(), and IGbE::DescCache< T >::unserialize().
template<class T> CacheType IGbE::DescCache< T >::usedCache [protected]
Definition at line 227 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::areaChanged(), IGbE::DescCache< iGbReg::RxDesc >::descUsed(), IGbE::DescCache< T >::fetchComplete(), IGbE::DescCache< T >::fetchDescriptors(), IGbE::DescCache< T >::reset(), IGbE::DescCache< T >::serialize(), IGbE::DescCache< T >::unserialize(), IGbE::DescCache< T >::wbComplete(), IGbE::DescCache< T >::writeback(), and IGbE::DescCache< T >::writeback1().
template<class T> Addr IGbE::DescCache< T >::wbAlignment [protected]
Definition at line 256 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::serialize(), IGbE::DescCache< T >::unserialize(), IGbE::DescCache< T >::wbComplete(), and IGbE::DescCache< T >::writeback().
template<class T> T* IGbE::DescCache< T >::wbBuf [protected]
Definition at line 231 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::DescCache(), IGbE::DescCache< T >::writeback1(), and IGbE::DescCache< T >::~DescCache().
template<class T> EventWrapper<DescCache, &DescCache::writeback1> IGbE::DescCache< T >::wbDelayEvent
Definition at line 282 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::serialize(), IGbE::DescCache< T >::unserialize(), IGbE::DescCache< T >::writeback(), and IGbE::DescCache< T >::writeback1().
template<class T> EventWrapper<DescCache, &DescCache::wbComplete> IGbE::DescCache< T >::wbEvent
Definition at line 299 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< iGbReg::RxDesc >::hasOutstandingEvents(), and IGbE::DescCache< T >::writeback1().
template<class T> int IGbE::DescCache< T >::wbOut [protected]
Definition at line 249 of file i8254xGBe.hh.
Referenced by IGbE::DescCache< T >::areaChanged(), IGbE::DescCache< T >::serialize(), IGbE::DescCache< T >::unserialize(), IGbE::DescCache< T >::wbComplete(), IGbE::DescCache< T >::writeback(), and IGbE::DescCache< T >::writeback1().
The documentation for this class was generated from the following files:
dev/i8254xGBe.hh
dev/i8254xGBe.cc