gem5: AlphaISA::ISA Class Reference
AlphaISA::ISA Class Reference
#include <isa.hh>