gem5: Stats::HistStor Class Reference
Stats::HistStor Class Reference
Templatized storage and interface for a histogram stat.
#include <statistics.hh>
Classes
struct Params
The parameters for a distribution stat.
Public Member Functions
HistStor (Info *info)
void grow_up ()
void grow_out ()
void grow_convert ()
void sample (Counter val, int number)
Add a value to the distribution for the given number of times.
size_type size () const
Return the number of buckets in this distribution.
bool zero () const
Returns true if any calls to sample have been made.
void prepare (Info *info, DistData &data)
void reset (Info *info)
Reset stat value to default.
Private Attributes
Counter min_bucket
The minimum value to track.
Counter max_bucket
The maximum value to track.
Counter bucket_size
The number of entries in each bucket.
Counter sum
The current sum.
Counter logs
The sum of logarithm of each sample, used to compute geometric mean.
Counter squares
The sum of squares.
Counter samples
The number of samples.
VCounter cvec
Counter for each bucket.
Detailed Description
Templatized storage and interface for a histogram stat.
Definition at line 1455 of file statistics.hh.
Constructor & Destructor Documentation
Stats::HistStor::HistStor (Info * info) [inline]
Definition at line 1487 of file statistics.hh.
References reset().
Member Function Documentation
void Stats::HistStor::grow_convert ()
Definition at line 312 of file statistics.cc.
References bucket_size, cvec, ArmISA::i, max_bucket, min_bucket, and size().
Referenced by sample().
void Stats::HistStor::grow_out ()
Definition at line 273 of file statistics.cc.
References bucket_size, cvec, ArmISA::i, max_bucket, min_bucket, size(), and zero().
Referenced by sample().
void Stats::HistStor::grow_up ()
Definition at line 334 of file statistics.cc.
References bucket_size, cvec, ArmISA::i, max_bucket, and size().
Referenced by sample().
void Stats::HistStor::prepare (Info * info, DistData & data) [inline]
Definition at line 1551 of file statistics.hh.
References Stats::DistData::bucket_size, bucket_size, Stats::HistStor::Params::buckets, cvec, Stats::DistData::cvec, Stats::Hist, ArmISA::i, logs, Stats::DistData::logs, Stats::DistData::max, max_bucket, Stats::DistData::max_val, Stats::DistData::min, min_bucket, Stats::DistData::min_val, safe_cast(), samples, Stats::DistData::samples, squares, Stats::DistData::squares, Stats::Info::storageParams, sum, Stats::DistData::sum, Stats::DistData::type, and Stats::DistParams::type.
void Stats::HistStor::reset (Info * info) [inline]
Reset stat value to default.
Definition at line 1579 of file statistics.hh.
References bucket_size, Stats::HistStor::Params::buckets, cvec, ArmISA::i, logs, max_bucket, min_bucket, safe_cast(), samples, size(), squares, Stats::Info::storageParams, and sum.
Referenced by HistStor().
void Stats::HistStor::sample (Counter val, int number) [inline]
Add a value to the distribution for the given number of times.
Parameters:
val The value to add.
number The number of times to add the value.
Definition at line 1503 of file statistics.hh.
References bucket_size, cvec, grow_convert(), grow_out(), grow_up(), MipsISA::index, logs, max_bucket, min_bucket, samples, size(), squares, and sum.
size_type Stats::HistStor::size () const [inline]
Return the number of buckets in this distribution.
Returns:
the number of buckets.
Definition at line 1538 of file statistics.hh.
References cvec.
Referenced by grow_convert(), grow_out(), grow_up(), reset(), and sample().
bool Stats::HistStor::zero () const [inline]
Returns true if any calls to sample have been made.
Returns:
True if any values have been sampled.
Definition at line 1545 of file statistics.hh.
References samples.
Referenced by grow_out().
Member Data Documentation
Counter Stats::HistStor::bucket_size [private]
The number of entries in each bucket.
Definition at line 1473 of file statistics.hh.
Referenced by grow_convert(), grow_out(), grow_up(), prepare(), reset(), and sample().
VCounter Stats::HistStor::cvec [private]
Counter for each bucket.
Definition at line 1484 of file statistics.hh.
Referenced by grow_convert(), grow_out(), grow_up(), prepare(), reset(), sample(), and size().
Counter Stats::HistStor::logs [private]
The sum of logarithm of each sample, used to compute geometric mean.
Definition at line 1478 of file statistics.hh.
Referenced by prepare(), reset(), and sample().
Counter Stats::HistStor::max_bucket [private]
The maximum value to track.
Definition at line 1471 of file statistics.hh.
Referenced by grow_convert(), grow_out(), grow_up(), prepare(), reset(), and sample().
Counter Stats::HistStor::min_bucket [private]
The minimum value to track.
Definition at line 1469 of file statistics.hh.
Referenced by grow_convert(), grow_out(), prepare(), reset(), and sample().
Counter Stats::HistStor::samples [private]
The number of samples.
Definition at line 1482 of file statistics.hh.
Referenced by prepare(), reset(), sample(), and zero().
Counter Stats::HistStor::squares [private]
The sum of squares.
Definition at line 1480 of file statistics.hh.
Referenced by prepare(), reset(), and sample().
Counter Stats::HistStor::sum [private]
The current sum.
Definition at line 1476 of file statistics.hh.
Referenced by prepare(), reset(), and sample().
The documentation for this class was generated from the following files:
base/statistics.hh
base/statistics.cc