gem5: SparseMemory Class Reference
SparseMemory Class Reference
#include <SparseMemory.hh>
Public Member Functions
SparseMemory (int number_of_levels)
~SparseMemory ()
bool exist (const Address &address) const
void add (const Address &address, AbstractEntry *)
void remove (const Address &address)
void recordBlocks (int cntrl_id, CacheRecorder *) const
Function for recording the contents of memory.
AbstractEntry * lookup (const Address &address)
void print (std::ostream &out) const
void printStats (std::ostream &out) const
Private Member Functions
SparseMemory (const SparseMemory &obj)
SparseMemory & operator= (const SparseMemory &obj)
void recursivelyRemoveTables (SparseMapType *currentTable, int level)
int recursivelyRemoveLevels (const Address &address, CurNextInfo &curInfo)
Private Attributes
SparseMapType * m_map_head
int m_total_number_of_bits
int m_number_of_levels
int * m_number_of_bits_per_level
uint64_t m_total_adds
uint64_t m_total_removes
uint64_t * m_adds_per_level
uint64_t * m_removes_per_level
Detailed Description
Definition at line 51 of file SparseMemory.hh.
Constructor & Destructor Documentation
SparseMemory::SparseMemory (int number_of_levels)
Definition at line 38 of file SparseMemory.cc.
References RubySystem::getBlockSizeBits(), RubySystem::getMemorySizeBits(), X86ISA::level, m_adds_per_level, m_map_head, m_number_of_bits_per_level, m_number_of_levels, m_removes_per_level, m_total_adds, m_total_number_of_bits, and m_total_removes.
SparseMemory::~SparseMemory ()
Definition at line 71 of file SparseMemory.cc.
References m_adds_per_level, m_map_head, m_number_of_bits_per_level, m_removes_per_level, and recursivelyRemoveTables().
SparseMemory::SparseMemory (const SparseMemory & obj) [private]
Member Function Documentation
void SparseMemory::add (const Address & address, AbstractEntry * entry)
Definition at line 153 of file SparseMemory.cc.
References Address::bitSelect(), DataBlock::clear(), exist(), RubySystem::getBlockSizeBits(), AbstractEntry::getDataBlk(), X86ISA::level, line_address(), m_adds_per_level, m_map_head, m_number_of_bits_per_level, m_number_of_levels, m_total_adds, m_total_number_of_bits, and Address::setAddress().
Referenced by DirectoryMemory::allocate().
bool SparseMemory::exist (const Address & address) const
Definition at line 109 of file SparseMemory.cc.
References Address::bitSelect(), DPRINTF, RubySystem::getBlockSizeBits(), X86ISA::level, line_address(), m_map_head, m_number_of_bits_per_level, m_number_of_levels, m_total_number_of_bits, and Address::setAddress().
Referenced by add(), DirectoryMemory::invalidateBlock(), and remove().
AbstractEntry * SparseMemory::lookup (const Address & address)
Definition at line 302 of file SparseMemory.cc.
References Address::bitSelect(), DPRINTF, RubySystem::getBlockSizeBits(), X86ISA::level, line_address(), m_map_head, m_number_of_bits_per_level, m_number_of_levels, m_total_number_of_bits, and Address::setAddress().
Referenced by DirectoryMemory::lookup().
SparseMemory& SparseMemory::operator= (const SparseMemory & obj) [private]
void SparseMemory::print (std::ostream & out) const
void SparseMemory::printStats (std::ostream & out) const
void SparseMemory::recordBlocks (int cntrl_id, CacheRecorder * tr) const
Function for recording the contents of memory.
This function walks through all the levels of the sparse memory in a breadth first fashion. This might need more memory than a depth first approach. But breadth first seems easier to me than a depth first approach.
Definition at line 348 of file SparseMemory.cc.
References CacheRecorder::addRecord(), Address::getAddress(), RubySystem::getBlockSizeBits(), m_map_head, m_number_of_bits_per_level, m_number_of_levels, and m_total_number_of_bits.
int SparseMemory::recursivelyRemoveLevels (const Address & address, CurNextInfo & curInfo) [private]
Definition at line 213 of file SparseMemory.cc.
References Address::bitSelect(), CurNextInfo::curTable, DPRINTF, CurNextInfo::highBit, CurNextInfo::level, CurNextInfo::lowBit, m_number_of_bits_per_level, m_number_of_levels, m_removes_per_level, and Address::setAddress().
Referenced by remove().
void SparseMemory::recursivelyRemoveTables (SparseMapType * currentTable, int level) [private]
Definition at line 83 of file SparseMemory.cc.
References m_number_of_levels.
Referenced by ~SparseMemory().
void SparseMemory::remove (const Address & address)
Definition at line 272 of file SparseMemory.cc.
References CurNextInfo::curTable, exist(), RubySystem::getBlockSizeBits(), CurNextInfo::highBit, CurNextInfo::level, line_address(), CurNextInfo::lowBit, m_map_head, m_number_of_bits_per_level, m_total_number_of_bits, m_total_removes, and recursivelyRemoveLevels().
Referenced by DirectoryMemory::invalidateBlock().
Member Data Documentation
uint64_t* SparseMemory::m_adds_per_level [private]
Definition at line 97 of file SparseMemory.hh.
Referenced by add(), SparseMemory(), and ~SparseMemory().
SparseMapType* SparseMemory::m_map_head [private]
Definition at line 89 of file SparseMemory.hh.
Referenced by add(), exist(), lookup(), recordBlocks(), remove(), SparseMemory(), and ~SparseMemory().
int* SparseMemory::m_number_of_bits_per_level [private]
Definition at line 93 of file SparseMemory.hh.
Referenced by add(), exist(), lookup(), recordBlocks(), recursivelyRemoveLevels(), remove(), SparseMemory(), and ~SparseMemory().
int SparseMemory::m_number_of_levels [private]
Definition at line 92 of file SparseMemory.hh.
Referenced by add(), exist(), lookup(), recordBlocks(), recursivelyRemoveLevels(), recursivelyRemoveTables(), and SparseMemory().
uint64_t* SparseMemory::m_removes_per_level [private]
Definition at line 98 of file SparseMemory.hh.
Referenced by recursivelyRemoveLevels(), SparseMemory(), and ~SparseMemory().
uint64_t SparseMemory::m_total_adds [private]
Definition at line 95 of file SparseMemory.hh.
Referenced by add(), and SparseMemory().
int SparseMemory::m_total_number_of_bits [private]
Definition at line 91 of file SparseMemory.hh.
Referenced by add(), exist(), lookup(), recordBlocks(), remove(), and SparseMemory().
uint64_t SparseMemory::m_total_removes [private]
Definition at line 96 of file SparseMemory.hh.
Referenced by remove(), and SparseMemory().
The documentation for this class was generated from the following files:
mem/ruby/system/SparseMemory.hh
mem/ruby/system/SparseMemory.cc