gem5: BaseCPU Class Reference
BaseCPU Class Reference
#include <cpu_dummy.hh>