gem5: VCAllocator Class Reference
VCAllocator Class Reference
#include <VCAllocator.hh>
Public Types
enum VAModel { NO_MODEL = 0, ONE_STAGE_ARB, TWO_STAGE_ARB, VC_SELECT }
Public Member Functions
~VCAllocator ()
double get_dynamic_energy_local_vc_arb (double num_req_, bool is_max_) const
double get_dynamic_energy_global_vc_arb (double num_req_, bool is_max_) const
double get_dynamic_energy_vc_select (bool is_read_, bool is_max_) const
double get_static_power () const
void print_all () const
Static Public Member Functions
static VCAllocator * create_vcallocator (const string &vcalloc_model_str_, uint32_t num_in_port_, uint32_t num_out_port_, uint32_t num_vclass_, uint32_t num_vchannel_, const OrionConfig *orion_cfg_ptr_)
Protected Member Functions
VCAllocator (uint32_t num_in_port_, uint32_t num_out_port_, uint32_t num_vclass_, uint32_t num_vchannel_, const string &arb_model_str_, const string &arb_ff_model_str_, const TechParameter *tech_param_ptr_)
VCAllocator (uint32_t num_in_port_, uint32_t num_out_port_, uint32_t num_vclass_, uint32_t num_vchannel_, const string &local_arb_model_str_, const string &local_arb_ff_model_str_, const string &global_arb_model_str_, const string &global_arb_ff_model_str_, const TechParameter *tech_param_ptr_)
VCAllocator (uint32_t num_in_port_, uint32_t num_out_port_, uint32_t num_vclass_, uint32_t num_vchannel_, const string &vc_select_buf_model_str_, const OrionConfig *orion_cfg_ptr_)
Protected Attributes
VAModel m_va_model
uint32_t m_num_in_port
uint32_t m_num_out_port
uint32_t m_num_vclass
uint32_t m_num_vchannel
Arbiter * m_local_arb_ptr
Arbiter * m_global_arb_ptr
Buffer * m_vc_select_ptr
Detailed Description
Definition at line 46 of file VCAllocator.hh.
Member Enumeration Documentation
enum VCAllocator::VAModel
Enumerator:
NO_MODEL
ONE_STAGE_ARB
TWO_STAGE_ARB
VC_SELECT
Definition at line 49 of file VCAllocator.hh.
Constructor & Destructor Documentation
VCAllocator::~VCAllocator ()
Definition at line 143 of file VCAllocator.cc.
References m_global_arb_ptr, m_local_arb_ptr, and m_vc_select_ptr.
VCAllocator::VCAllocator (uint32_t num_in_port_, uint32_t num_out_port_, uint32_t num_vclass_, uint32_t num_vchannel_, const string & arb_model_str_, const string & arb_ff_model_str_, const TechParameter * tech_param_ptr_) [protected]
Definition at line 48 of file VCAllocator.cc.
References Arbiter::create_arbiter(), m_global_arb_ptr, m_local_arb_ptr, m_num_in_port, m_num_out_port, m_num_vchannel, m_num_vclass, m_va_model, and m_vc_select_ptr.
Referenced by create_vcallocator().
VCAllocator::VCAllocator (uint32_t num_in_port_, uint32_t num_out_port_, uint32_t num_vclass_, uint32_t num_vchannel_, const string & local_arb_model_str_, const string & local_arb_ff_model_str_, const string & global_arb_model_str_, const string & global_arb_ff_model_str_, const TechParameter * tech_param_ptr_) [protected]
Definition at line 78 of file VCAllocator.cc.
References Arbiter::create_arbiter(), m_global_arb_ptr, m_local_arb_ptr, m_num_in_port, m_num_out_port, m_num_vchannel, m_num_vclass, m_va_model, and m_vc_select_ptr.
VCAllocator::VCAllocator (uint32_t num_in_port_, uint32_t num_out_port_, uint32_t num_vclass_, uint32_t num_vchannel_, const string & vc_select_buf_model_str_, const OrionConfig * orion_cfg_ptr_) [protected]
Definition at line 114 of file VCAllocator.cc.
References m_global_arb_ptr, m_local_arb_ptr, m_num_in_port, m_num_out_port, m_num_vchannel, m_num_vclass, m_va_model, and m_vc_select_ptr.
Member Function Documentation
VCAllocator * VCAllocator::create_vcallocator (const string & vcalloc_model_str_, uint32_t num_in_port_, uint32_t num_out_port_, uint32_t num_vclass_, uint32_t num_vchannel_, const OrionConfig * orion_cfg_ptr_) [static]
Definition at line 254 of file VCAllocator.cc.
References OrionConfig::get(), OrionConfig::get_tech_param_ptr(), and VCAllocator().
Referenced by OrionRouter::init().
double VCAllocator::get_dynamic_energy_global_vc_arb (double num_req_, bool is_max_) const
Definition at line 166 of file VCAllocator.cc.
References Arbiter::calc_dynamic_energy(), m_global_arb_ptr, m_va_model, ONE_STAGE_ARB, TWO_STAGE_ARB, and VC_SELECT.
Referenced by OrionRouter::calc_dynamic_energy_global_vc_arb(), and print_all().
double VCAllocator::get_dynamic_energy_local_vc_arb (double num_req_, bool is_max_) const
Definition at line 150 of file VCAllocator.cc.
References Arbiter::calc_dynamic_energy(), m_local_arb_ptr, m_va_model, ONE_STAGE_ARB, TWO_STAGE_ARB, and VC_SELECT.
Referenced by OrionRouter::calc_dynamic_energy_local_vc_arb(), and print_all().
double VCAllocator::get_dynamic_energy_vc_select (bool is_read_, bool is_max_) const
Definition at line 182 of file VCAllocator.cc.
References Buffer::get_dynamic_energy(), m_va_model, m_vc_select_ptr, ONE_STAGE_ARB, TWO_STAGE_ARB, and VC_SELECT.
Referenced by print_all().
double VCAllocator::get_static_power () const
Definition at line 198 of file VCAllocator.cc.
References X86ISA::exit, Buffer::get_static_power(), Arbiter::get_static_power(), m_global_arb_ptr, m_local_arb_ptr, m_num_in_port, m_num_out_port, m_num_vchannel, m_num_vclass, m_va_model, m_vc_select_ptr, ONE_STAGE_ARB, TWO_STAGE_ARB, and VC_SELECT.
Referenced by OrionRouter::get_static_power_va(), and print_all().
void VCAllocator::print_all () const
Definition at line 220 of file VCAllocator.cc.
References get_dynamic_energy_global_vc_arb(), get_dynamic_energy_local_vc_arb(), get_dynamic_energy_vc_select(), get_static_power(), ArmISA::i, m_num_in_port, m_num_vchannel, m_va_model, ONE_STAGE_ARB, TWO_STAGE_ARB, and VC_SELECT.
Referenced by OrionRouter::print().
Member Data Documentation
Arbiter* VCAllocator::m_global_arb_ptr [protected]
Definition at line 109 of file VCAllocator.hh.
Referenced by get_dynamic_energy_global_vc_arb(), get_static_power(), VCAllocator(), and ~VCAllocator().
Arbiter* VCAllocator::m_local_arb_ptr [protected]
Definition at line 108 of file VCAllocator.hh.
Referenced by get_dynamic_energy_local_vc_arb(), get_static_power(), VCAllocator(), and ~VCAllocator().
uint32_t VCAllocator::m_num_in_port [protected]
Definition at line 103 of file VCAllocator.hh.
Referenced by get_static_power(), print_all(), and VCAllocator().
uint32_t VCAllocator::m_num_out_port [protected]
Definition at line 104 of file VCAllocator.hh.
Referenced by get_static_power(), and VCAllocator().
uint32_t VCAllocator::m_num_vchannel [protected]
Definition at line 106 of file VCAllocator.hh.
Referenced by get_static_power(), print_all(), and VCAllocator().
uint32_t VCAllocator::m_num_vclass [protected]
Definition at line 105 of file VCAllocator.hh.
Referenced by get_static_power(), and VCAllocator().
VAModel VCAllocator::m_va_model [protected]
Definition at line 102 of file VCAllocator.hh.
Referenced by get_dynamic_energy_global_vc_arb(), get_dynamic_energy_local_vc_arb(), get_dynamic_energy_vc_select(), get_static_power(), print_all(), and VCAllocator().
Buffer* VCAllocator::m_vc_select_ptr [protected]
Definition at line 110 of file VCAllocator.hh.
Referenced by get_dynamic_energy_vc_select(), get_static_power(), VCAllocator(), and ~VCAllocator().
The documentation for this class was generated from the following files:
mem/ruby/network/orion/Allocator/VCAllocator.hh
mem/ruby/network/orion/Allocator/VCAllocator.cc