gem5: Histogram Class Reference
Histogram Class Reference
#include <Histogram.hh>
Public Member Functions
Histogram (int binsize=1, uint32_t bins=50)
~Histogram ()
void add (int64 value)
void add (Histogram &hist)
void doubleBinSize ()
void clear ()
void clear (uint32_t bins)
void clear (int binsize, uint32_t bins)
uint64_t size () const
uint32_t getBins () const
int getBinSize () const
int64 getTotal () const
uint64_t getSquaredTotal () const
uint64_t getData (int index) const
int64 getMax () const
void printWithMultiplier (std::ostream &out, double multiplier) const
void printPercent (std::ostream &out) const
void print (std::ostream &out) const
Private Member Functions
double getStandardDeviation () const
Private Attributes
std::vector< uint64_t > m_data
int64 m_max
uint64_t m_count
int m_binsize
uint32_t m_largest_bin
int64 m_sumSamples
uint64_t m_sumSquaredSamples
Detailed Description
Definition at line 37 of file Histogram.hh.
Constructor & Destructor Documentation
Histogram::Histogram (int binsize = 1, uint32_t bins = 50)
Definition at line 37 of file Histogram.cc.
References clear(), and m_binsize.
Histogram::~Histogram ()
Definition at line 43 of file Histogram.cc.
Member Function Documentation
void Histogram::add (int64 value)
Definition at line 87 of file Histogram.cc.
References doubleBinSize(), floorLog2(), MipsISA::index, m_binsize, m_count, m_data, m_largest_bin, m_max, m_sumSamples, and m_sumSquaredSamples.
Referenced by add(), AccessTraceForAddress::addSample(), StoreTrace::downgrade(), Profiler::missLatency(), Profiler::missLatencyDir(), Profiler::missLatencyWcc(), printSorted(), Profiler::profileAverageLatencyEstimate(), AddressProfiler::profileGetS(), AddressProfiler::profileGetX(), AbstractController::profileMsgDelay(), Profiler::profileOutstandingPersistentRequest(), Profiler::profileOutstandingRequest(), Profiler::profilePFWait(), AddressProfiler::profileRetry(), Profiler::profileSharing(), Profiler::sequencerRequests(), and Profiler::swPrefetchLatency().
void Histogram::add (Histogram & hist)
Definition at line 122 of file Histogram.cc.
References add(), doubleBinSize(), fatal, getBins(), getBinSize(), getData(), getMax(), getSquaredTotal(), getTotal(), ArmISA::i, ArmISA::j, m_binsize, m_count, m_data, m_largest_bin, m_max, m_sumSamples, m_sumSquaredSamples, and size().
void Histogram::clear () [inline]
Definition at line 47 of file Histogram.hh.
References clear(), and m_data.
Referenced by clear(), AbstractController::clearStats(), Profiler::clearStats(), AddressProfiler::clearStats(), StoreTrace::clearSummary(), and Histogram().
void Histogram::clear (uint32_t bins)
Definition at line 55 of file Histogram.cc.
References ArmISA::i, m_count, m_data, m_largest_bin, m_max, m_sumSamples, and m_sumSquaredSamples.
void Histogram::clear (int binsize, uint32_t bins)
Definition at line 48 of file Histogram.cc.
References clear(), and m_binsize.
void Histogram::doubleBinSize ()
Definition at line 71 of file Histogram.cc.
References ArmISA::i, m_binsize, and m_data.
Referenced by add().
uint32_t Histogram::getBins () const [inline]
Definition at line 52 of file Histogram.hh.
References m_data.
Referenced by add().
int Histogram::getBinSize () const [inline]
Definition at line 53 of file Histogram.hh.
References m_binsize.
Referenced by add().
uint64_t Histogram::getData (int index) const [inline]
Definition at line 56 of file Histogram.hh.
References m_data.
Referenced by add().
int64 Histogram::getMax () const [inline]
Definition at line 57 of file Histogram.hh.
References m_max.
Referenced by add().
uint64_t Histogram::getSquaredTotal () const [inline]
Definition at line 55 of file Histogram.hh.
References m_sumSquaredSamples.
Referenced by add().
double Histogram::getStandardDeviation () const [private]
Definition at line 170 of file Histogram.cc.
References m_count, m_sumSamples, and m_sumSquaredSamples.
int64 Histogram::getTotal () const [inline]
Definition at line 54 of file Histogram.hh.
References m_sumSamples.
Referenced by add(), and AccessTraceForAddress::getTotal().
void Histogram::print (std::ostream & out) const
Referenced by operator<<().
void Histogram::printPercent (std::ostream & out) const
void Histogram::printWithMultiplier (std::ostream & out, double multiplier) const
uint64_t Histogram::size () const [inline]
Definition at line 51 of file Histogram.hh.
References m_count.
Referenced by add(), and node_less_then_eq().
Member Data Documentation
int Histogram::m_binsize [private]
Definition at line 67 of file Histogram.hh.
Referenced by add(), clear(), doubleBinSize(), getBinSize(), and Histogram().
uint64_t Histogram::m_count [private]
Definition at line 66 of file Histogram.hh.
Referenced by add(), clear(), getStandardDeviation(), and size().
std::vector<uint64_t> Histogram::m_data [private]
Definition at line 64 of file Histogram.hh.
Referenced by add(), clear(), doubleBinSize(), getBins(), and getData().
uint32_t Histogram::m_largest_bin [private]
Definition at line 68 of file Histogram.hh.
Referenced by add(), and clear().
int64 Histogram::m_max [private]
Definition at line 65 of file Histogram.hh.
Referenced by add(), clear(), and getMax().
int64 Histogram::m_sumSamples [private]
Definition at line 70 of file Histogram.hh.
Referenced by add(), clear(), getStandardDeviation(), and getTotal().
uint64_t Histogram::m_sumSquaredSamples [private]
Definition at line 71 of file Histogram.hh.
Referenced by add(), clear(), getSquaredTotal(), and getStandardDeviation().
The documentation for this class was generated from the following files:
mem/ruby/common/Histogram.hh
mem/ruby/common/Histogram.cc