gem5: FullO3CPU< Impl > Class Template Reference
FullO3CPU< Impl > Class Template Reference
FullO3CPU class, has each of the stages (fetch through commit) within it, as well as all of the time buffers between stages.
#include <cpu.hh>