gem5: Trace::LegionTraceRecord Class Reference
Trace::LegionTraceRecord Class Reference
#include <legiontrace.hh>