gem5: Bridge Class Reference
Bridge Class Reference
A bridge is used to interface two different busses (or in general a memory-mapped master and slave), with buffering for requests and responses.
#include <bridge.hh>