gem5: base/cprintf.hh File Reference
base/cprintf.hh File Reference
#include <ios>
#include <iostream>
#include <list>
#include <string>
#include "base/cprintf_formats.hh"
#include "base/varargs.hh"
Classes
struct cp::Print
Namespaces
namespace cp
Defines
#define CPRINTF_DECLARATION VARARGS_DECLARATION(cp::Print)
#define CPRINTF_DEFINITION VARARGS_DEFINITION(cp::Print)
Typedefs
typedef VarArgs::List< cp::Print > CPrintfArgsList
Functions
void ccprintf (std::ostream &stream, const char *format, const CPrintfArgsList &args)
void ccprintf (std::ostream &stream, const char *format, CPRINTF_DECLARATION)
void cprintf (const char *format, CPRINTF_DECLARATION)
std::string csprintf (const char *format, CPRINTF_DECLARATION)
void ccprintf (std::ostream &stream, const std::string &format, const CPrintfArgsList &args)
void ccprintf (std::ostream &stream, const std::string &format, CPRINTF_DECLARATION)
void cprintf (const std::string &format, CPRINTF_DECLARATION)
std::string csprintf (const std::string &format, CPRINTF_DECLARATION)
Define Documentation
#define CPRINTF_DECLARATION VARARGS_DECLARATION(cp::Print)
Definition at line 45 of file cprintf.hh.
#define CPRINTF_DEFINITION VARARGS_DEFINITION(cp::Print)
Definition at line 46 of file cprintf.hh.
Typedef Documentation
typedef VarArgs::List<cp::Print> CPrintfArgsList
Definition at line 131 of file cprintf.hh.
Function Documentation
void ccprintf (std::ostream & stream, const char * format, const CPrintfArgsList & args) [inline]
Definition at line 134 of file cprintf.hh.
References VarArgs::List< RECV >::add_args().
Referenced by __base_message(), __exit_message(), abortHandler(), Terminal::accept(), Stats::Text::begin(), ccprintf(), MemTest::completeRequest(), cprintf(), csprintf(), Trace::dprintf(), Trace::IntelTraceRecord::dump(), Trace::InOrderTraceRecord::dumpTicks(), Stats::Text::end(), AbstractMemory::functionalAccess(), X86ISA::X86MicroopBase::generateDisassembly(), PowerISA::IntRotateOp::generateDisassembly(), PowerISA::IntShiftOp::generateDisassembly(), PowerISA::IntImmOp::generateDisassembly(), PowerISA::IntOp::generateDisassembly(), PowerISA::FloatOp::generateDisassembly(), PowerISA::CondMoveOp::generateDisassembly(), PowerISA::CondLogicOp::generateDisassembly(), PowerISA::BranchRegCond::generateDisassembly(), PowerISA::BranchNonPCRelCond::generateDisassembly(), PowerISA::BranchPCRelCond::generateDisassembly(), PowerISA::BranchNonPCRel::generateDisassembly(), PowerISA::BranchPCRel::generateDisassembly(), ArmISA::FpRegRegRegImmOp::generateDisassembly(), ArmISA::FpRegRegImmOp::generateDisassembly(), ArmISA::FpRegImmOp::generateDisassembly(), PowerISA::PowerStaticInst::generateDisassembly(), ArmISA::PredMacroOp::generateDisassembly(), PowerISA::MiscOp::generateDisassembly(), RegImmRegShiftOp::generateDisassembly(), RegImmRegOp::generateDisassembly(), RegRegImmImmOp::generateDisassembly(), RegRegImmOp::generateDisassembly(), RegRegRegImmOp::generateDisassembly(), RegImmOp::generateDisassembly(), ImmOp::generateDisassembly(), MsrImmOp::generateDisassembly(), PowerISA::MemDispOp::generateDisassembly(), ArmISA::MicroMemOp::generateDisassembly(), ArmISA::MicroIntImmOp::generateDisassembly(), X86ISA::InitInterrupt::invoke(), X86ISA::X86Trap::invoke(), Terminal::listen(), TapListener::listen(), VncServer::listen(), GDBListener::listen(), main(), Trace::NativeTrace::NativeTrace(), Stats::ScalarPrint::operator()(), Net::operator<<(), X86ISA::operator<<(), GenericISA::operator<<(), MSHR::print(), MSHR::TargetList::print(), CacheBlkPrintWrapper::print(), Trace::printColumnLabels(), Packet::PrintReqState::printLabels(), Trace::printLevelHeader(), X86ISA::X86StaticInst::printMem(), X86ISA::X86StaticInst::printMnemonic(), ArmISA::MemoryImm::printOffset(), ArmISA::MemoryReg::printOffset(), X86ISA::X86StaticInst::printReg(), PowerISA::PowerStaticInst::printReg(), ArmISA::ArmStaticInst::printReg(), Trace::printRegPair(), Trace::printSectionHeader(), X86ISA::X86StaticInst::printSegment(), Switch::printStats(), DumpStatsPCEvent::process(), BaseCPU::regStats(), System::regStats(), ArmISA::ArmStaticInst::shift_carry_imm(), ArmISA::ArmStaticInst::shift_carry_rs(), ArmISA::ArmStaticInst::shift_rm_imm(), ArmISA::ArmStaticInst::shift_rm_rs(), BaseCPU::traceFunctionsInternal(), and Trace::ExeTracerRecord::traceInst().
void ccprintf (std::ostream & stream, const char * format, CPRINTF_DECLARATION) [inline]
Definition at line 141 of file cprintf.hh.
References VARARGS_ADDARGS.
void ccprintf (std::ostream & stream, const std::string & format, const CPrintfArgsList & args) [inline]
Definition at line 167 of file cprintf.hh.
References ccprintf().
void ccprintf (std::ostream & stream, const std::string & format, CPRINTF_DECLARATION) [inline]
Definition at line 174 of file cprintf.hh.
References ccprintf().
void cprintf (const std::string & format, CPRINTF_DECLARATION) [inline]
Definition at line 180 of file cprintf.hh.
References ccprintf().
void cprintf (const char * format, CPRINTF_DECLARATION) [inline]
Definition at line 148 of file cprintf.hh.
References ccprintf(), and VARARGS_ALLARGS.
Referenced by Stats::Info::baseCheck(), EventQueue::debugVerify(), Event::dump(), EventQueue::dump(), BPredUnit::dump(), PCEventQueue::dump(), StoreSet::dump(), DependencyGraph< DynInstPtr >::dump(), RegDepMap::dump(), InOrderDynInst::dump(), BaseDynInst< Impl >::dump(), ActivityRecorder::dump(), Trie< Addr, X86ISA::TlbEntry >::dump(), Trie< Key, Value >::Node::dump(), CircleBuf::dump(), Checker< Impl >::dumpAndExit(), dumpDebugFlags(), DefaultRename< Impl >::dumpHistory(), OzoneLWLSQ< Impl >::dumpInsts(), LWBackEnd< Impl >::dumpInsts(), InorderBackEnd< Impl >::dumpInsts(), FrontEnd< Impl >::dumpInsts(), BackEnd< Impl >::dumpInsts(), BackEnd< Impl >::InstQueue::dumpInsts(), OzoneLSQ< Impl >::dumpInsts(), LSQUnit< Impl >::dumpInsts(), InstructionQueue< Impl >::dumpInsts(), PipelineStage::dumpInsts(), Checker< Impl >::dumpInsts(), FullO3CPU< Impl >::dumpInsts(), InOrderCPU::dumpInsts(), MemDepUnit< MemDepPred, Impl >::dumpLists(), InstQueue< Impl >::dumpLists(), InstructionQueue< Impl >::dumpLists(), StatTest::init(), main(), CPUProgressEvent::process(), and InstructionQueue< Impl >::~InstructionQueue().
std::string csprintf (const char * format, CPRINTF_DECLARATION) [inline]
Definition at line 154 of file cprintf.hh.
References ccprintf(), and VARARGS_ALLARGS.
Referenced by PerfectSwitch::addInPort(), BaseCPU::BaseCPU(), CoherentBus::CoherentBus(), Pl111::dmaDone(), SimpleThread::dumpFuncProfile(), OzoneThreadState< SimpleImpl >::dumpFuncProfile(), O3ThreadState< Impl >::dumpFuncProfile(), InOrderThreadState::dumpFuncProfile(), UnknownOp::generateDisassembly(), PowerISA::MemOp::generateDisassembly(), MemDepUnit< MemDepPred, Impl >::init(), MachineIDToString(), Event::name(), Throttle::name(), PerfectSwitch::name(), CopyEngine::CopyEngineChannel::name(), SimpleThread::name(), ResourceRequest::name(), NoncoherentBus::NoncoherentBus(), Set::print(), Linux::procMeminfo(), RubyDirectedTester::RubyDirectedTester(), RubyPort::RubyPort(), RubyTester::RubyTester(), PageTable::serialize(), Iob::serialize(), Sinic::Device::serialize(), IGbE::serialize(), IGbE::DescCache< T >::serialize(), CopyEngine::serialize(), Sp804::serialize(), CpuLocalTimer::serialize(), OzoneCPU< Impl >::serialize(), BaseCPU::serialize(), Process::serialize(), SimpleNetwork::SimpleNetwork(), Stats::SumNode< Op >::str(), Stats::BinaryNode< Op >::str(), Stats::ConstVectorNode< T >::str(), Stats::ScalarProxy< Stat >::str(), AddrRange::to_string(), BaseCPU::traceFunctionsInternal(), Trace::ExeTracerRecord::traceInst(), EventQueue::unserialize(), PageTable::unserialize(), Iob::unserialize(), Sinic::Device::unserialize(), IGbE::unserialize(), IGbE::DescCache< T >::unserialize(), CopyEngine::unserialize(), Sp804::unserialize(), CpuLocalTimer::unserialize(), OzoneCPU< Impl >::unserialize(), BaseCPU::unserialize(), and Process::unserialize().
std::string csprintf (const std::string & format, CPRINTF_DECLARATION) [inline]
Definition at line 186 of file cprintf.hh.
References ccprintf().