gem5: dev/disk_image.cc File Reference
dev/disk_image.cc File Reference
Disk Image Definitions.
#include <sys/types.h>
#include <sys/uio.h>
#include <unistd.h>
#include <cerrno>
#include <cstring>
#include <fstream>
#include <string>
#include "base/callback.hh"
#include "base/misc.hh"
#include "base/trace.hh"
#include "debug/DiskImageRead.hh"
#include "debug/DiskImageWrite.hh"
#include "dev/disk_image.hh"
#include "sim/byteswap.hh"
#include "sim/sim_exit.hh"
Classes
class CowDiskCallback
Functions
void SafeRead (ifstream &stream, void *data, int count)
template<class T >
void SafeRead (ifstream &stream, T &data)
template<class T >
void SafeReadSwap (ifstream &stream, T &data)
void SafeWrite (ofstream &stream, const void *data, int count)
template<class T >
void SafeWrite (ofstream &stream, const T &data)
template<class T >
void SafeWriteSwap (ofstream &stream, const T &data)
Detailed Description
Disk Image Definitions.
Definition in file disk_image.cc.
Function Documentation
void SafeRead (ifstream & stream, void * data, int count)
Definition at line 198 of file disk_image.cc.
References panic.
Referenced by SafeRead(), and SafeReadSwap().
template<class T > void SafeRead (ifstream & stream, T & data)
Definition at line 213 of file disk_image.cc.
References SafeRead().
template<class T > void SafeReadSwap (ifstream & stream, T & data)
Definition at line 220 of file disk_image.cc.
References letoh(), and SafeRead().
void SafeWrite (ofstream & stream, const void * data, int count)
Definition at line 281 of file disk_image.cc.
References panic.
Referenced by SafeWrite(), and SafeWriteSwap().
template<class T > void SafeWrite (ofstream & stream, const T & data)
Definition at line 296 of file disk_image.cc.
References SafeWrite().
template<class T > void SafeWriteSwap (ofstream & stream, const T & data)
Definition at line 303 of file disk_image.cc.
References letoh(), and SafeWrite().