gem5: sim/eventq.hh File Reference
sim/eventq.hh File Reference
#include <algorithm>
#include <cassert>
#include <climits>
#include <iosfwd>
#include <string>
#include "base/flags.hh"
#include "base/misc.hh"
#include "base/types.hh"
#include "debug/Event.hh"
#include "sim/serialize.hh"
Classes
class Event
class EventQueue
class EventManager
class EventWrapper< T, F >
Functions
bool operator< (const Event &l, const Event &r)
bool operator> (const Event &l, const Event &r)
bool operator<= (const Event &l, const Event &r)
bool operator>= (const Event &l, const Event &r)
bool operator== (const Event &l, const Event &r)
bool operator!= (const Event &l, const Event &r)
void dumpMainQueue ()
template<class T , void(T::*)() F>
void DelayFunction (EventQueue *eventq, Tick when, T *object)
Variables
EventQueue mainEventQueue
Function Documentation
template<class T , void(T::*)() F> void DelayFunction (EventQueue * eventq, Tick when, T * object)
Definition at line 482 of file eventq.hh.
References Event::description(), Event::Event(), Event::process(), and EventQueue::schedule().
void dumpMainQueue ()
Definition at line 389 of file eventq.cc.
References EventQueue::dump(), and mainEventQueue.
bool operator!= (const Event & l, const Event & r) [inline]
Definition at line 339 of file eventq.hh.
References Event::priority(), and Event::when().
bool operator< (const Event & l, const Event & r) [inline]
Definition at line 306 of file eventq.hh.
References Event::priority(), and Event::when().
bool operator<= (const Event & l, const Event & r) [inline]
Definition at line 320 of file eventq.hh.
References Event::priority(), and Event::when().
bool operator== (const Event & l, const Event & r) [inline]
Definition at line 333 of file eventq.hh.
References Event::priority(), and Event::when().
bool operator> (const Event & l, const Event & r) [inline]
Definition at line 313 of file eventq.hh.
References Event::priority(), and Event::when().
bool operator>= (const Event & l, const Event & r) [inline]
Definition at line 326 of file eventq.hh.
References Event::priority(), and Event::when().
Variable Documentation
EventQueue mainEventQueue
Referenced by curTick(), dumpMainQueue(), eventqDump(), exitSimLoop(), SimLoopExitEvent::process(), EventQueue::reschedule(), schedBreakCycle(), EventQueue::schedule(), Globals::serialize(), simulate(), TraceCPU::tick(), and Globals::unserialize().