gem5: sim/eventq.cc File Reference
sim/eventq.cc File Reference
#include <cassert>
#include <iostream>
#include <string>
#include <vector>
#include "base/hashmap.hh"
#include "base/misc.hh"
#include "base/trace.hh"
#include "cpu/smt.hh"
#include "debug/Config.hh"
#include "sim/core.hh"
#include "sim/eventq_impl.hh"
Functions
void dumpMainQueue ()
Variables
EventQueue mainEventQueue ("Main Event Queue")
Function Documentation
void dumpMainQueue ()
Definition at line 389 of file eventq.cc.
References EventQueue::dump(), and mainEventQueue.
Variable Documentation
EventQueue mainEventQueue("Main Event Queue")
Referenced by curTick(), dumpMainQueue(), eventqDump(), exitSimLoop(), SimLoopExitEvent::process(), EventQueue::reschedule(), schedBreakCycle(), EventQueue::schedule(), Globals::serialize(), simulate(), TraceCPU::tick(), and Globals::unserialize().