gem5: mem/fs_translating_port_proxy.cc File Reference
mem/fs_translating_port_proxy.cc File Reference
Port object definitions.
#include "base/chunk_generator.hh"
#include "cpu/base.hh"
#include "cpu/thread_context.hh"
#include "mem/fs_translating_port_proxy.hh"
Functions
void CopyOut (ThreadContext *tc, void *dest, Addr src, size_t cplen)
void CopyIn (ThreadContext *tc, Addr dest, void *source, size_t cplen)
void CopyStringOut (ThreadContext *tc, char *dst, Addr vaddr, size_t maxlen)
void CopyStringIn (ThreadContext *tc, char *src, Addr vaddr)
Detailed Description
Port object definitions.
Definition in file fs_translating_port_proxy.cc.
Function Documentation
void CopyIn (ThreadContext * tc, Addr dest, void * source, size_t cplen)
Definition at line 128 of file fs_translating_port_proxy.cc.
References ThreadContext::getVirtProxy(), and FSTranslatingPortProxy::writeBlob().
void CopyOut (ThreadContext * tc, void * dest, Addr src, size_t cplen)
Definition at line 121 of file fs_translating_port_proxy.cc.
References ThreadContext::getVirtProxy(), and FSTranslatingPortProxy::readBlob().
Referenced by Linux::ThreadInfo::curTaskInfo(), Linux::ThreadInfo::curTaskMm(), Linux::ThreadInfo::curTaskPID(), Linux::ThreadInfo::curTaskStart(), Linux::ThreadInfo::curTaskTGID(), X86ISA::StackTrace::decodePrologue(), MipsISA::StackTrace::decodePrologue(), AlphaISA::StackTrace::decodePrologue(), Linux::ThreadInfo::get_data(), and Arguments::operator T *().
void CopyStringIn (ThreadContext * tc, char * src, Addr vaddr)
Definition at line 153 of file fs_translating_port_proxy.cc.
References ThreadContext::getVirtProxy(), AlphaISA::PageBytes, and FSTranslatingPortProxy::writeBlob().
void CopyStringOut (ThreadContext * tc, char * dst, Addr vaddr, size_t maxlen)
Definition at line 135 of file fs_translating_port_proxy.cc.
References ThreadContext::getVirtProxy(), and FSTranslatingPortProxy::readBlob().
Referenced by Linux::ThreadInfo::curTaskName(), X86ISA::ProcessInfo::name(), MipsISA::ProcessInfo::name(), ArmISA::ProcessInfo::name(), AlphaISA::ProcessInfo::name(), and Arguments::operator char *().