gem5: sim/init.hh File Reference
sim/init.hh File Reference
#include <Python.h>
#include <list>
#include <inttypes.h>
Classes
struct EmbeddedPython
struct EmbeddedSwig
Typedefs
typedef _object PyObject
Functions
void dumpStatsHandler (int sigtype)
Stats signal handler.
void dumprstStatsHandler (int sigtype)
void exitNowHandler (int sigtype)
Exit signal handler.
void abortHandler (int sigtype)
Abort signal handler.
void initSignals ()
int initM5Python ()
int m5Main (int argc, char **argv)
PyMODINIT_FUNC initm5 (void)
Typedef Documentation
typedef _object PyObject
Definition at line 44 of file init.hh.
Function Documentation
void abortHandler (int sigtype)
Abort signal handler.
Definition at line 94 of file init.cc.
References ccprintf(), and curTick().
Referenced by initSignals().
void dumprstStatsHandler (int sigtype)
Definition at line 77 of file init.cc.
References async_event, async_statdump, and async_statreset.
Referenced by initSignals().
void dumpStatsHandler (int sigtype)
Stats signal handler.
Definition at line 70 of file init.cc.
References async_event, and async_statdump.
Referenced by initSignals().
void exitNowHandler (int sigtype)
Exit signal handler.
Definition at line 86 of file init.cc.
References async_event, and async_exit.
Referenced by initSignals().
PyMODINIT_FUNC initm5 (void)
Definition at line 298 of file init.cc.
References initM5Python(), and PyCC.
int initM5Python ()
Definition at line 235 of file init.cc.
References EmbeddedPython::initAll(), and EmbeddedSwig::initAll().
Referenced by initm5(), and main().
void initSignals ()
Definition at line 104 of file init.cc.
References abortHandler(), dumprstStatsHandler(), dumpStatsHandler(), and exitNowHandler().
Referenced by main().
int m5Main (int argc, char ** argv)
Definition at line 256 of file init.cc.
References m5MainCommands, panic, and PyCC.
Referenced by main().