gem5: sim/init.cc File Reference
sim/init.cc File Reference
#include <Python.h>
#include <marshal.h>
#include <zlib.h>
#include <csignal>
#include <iostream>
#include <list>
#include <string>
#include "base/cprintf.hh"
#include "base/misc.hh"
#include "base/types.hh"
#include "config/have_protobuf.hh"
#include "sim/async.hh"
#include "sim/core.hh"
#include "sim/init.hh"
Defines
#define PyCC(x) (const_cast<char *>(x))
Functions
void dumpStatsHandler (int sigtype)
Stats signal handler.
void dumprstStatsHandler (int sigtype)
void exitNowHandler (int sigtype)
Exit signal handler.
void abortHandler (int sigtype)
Abort signal handler.
void initSignals ()
int initM5Python ()
const char * __attribute__ ((weak)) m5MainCommands[]
int m5Main (int argc, char **argv)
PyMODINIT_FUNC initm5 (void)
Define Documentation
#define PyCC (x) (const_cast<char *>(x))
Definition at line 128 of file init.cc.
Referenced by EmbeddedPython::addModule(), EmbeddedPython::initAll(), initm5(), and m5Main().
Function Documentation
const char* __attribute__ ((weak))
void abortHandler (int sigtype)
Abort signal handler.
Definition at line 94 of file init.cc.
References ccprintf(), and curTick().
Referenced by initSignals().
void dumprstStatsHandler (int sigtype)
Definition at line 77 of file init.cc.
References async_event, async_statdump, and async_statreset.
Referenced by initSignals().
void dumpStatsHandler (int sigtype)
Stats signal handler.
Definition at line 70 of file init.cc.
References async_event, and async_statdump.
Referenced by initSignals().
void exitNowHandler (int sigtype)
Exit signal handler.
Definition at line 86 of file init.cc.
References async_event, and async_exit.
Referenced by initSignals().
PyMODINIT_FUNC initm5 (void)
Definition at line 298 of file init.cc.
References initM5Python(), and PyCC.
int initM5Python ()
Definition at line 235 of file init.cc.
References EmbeddedPython::initAll(), and EmbeddedSwig::initAll().
Referenced by initm5(), and main().
void initSignals ()
Definition at line 104 of file init.cc.
References abortHandler(), dumprstStatsHandler(), dumpStatsHandler(), and exitNowHandler().
Referenced by main().
int m5Main (int argc, char ** argv)
Definition at line 256 of file init.cc.
References m5MainCommands, panic, and PyCC.
Referenced by main().