gem5: unittest/initest.cc File Reference
unittest/initest.cc File Reference
#include <fstream>
#include <iostream>
#include <string>
#include <vector>
#include "base/cprintf.hh"
#include "base/inifile.hh"
Defines
#define FIND(C, E)
Functions
void usage ()
int main (int argc, char *argv[])
Variables
char * progname
Define Documentation
#define FIND (C, E)
Value:
if (simConfigDB.find(C, E, value)) \
    cout << ">" << value << "<\n"; \
  else \
    cout << "Not Found!\n"
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Definition at line 65 of file initest.cc.
References IniFile::add(), ccprintf(), cprintf(), IniFile::dump(), X86ISA::exit, FIND, ArmISA::i, IniFile::load(), progname, and usage().
void usage ()
Definition at line 45 of file initest.cc.
References X86ISA::exit, and progname.
Referenced by main().
Variable Documentation
char* progname
Definition at line 42 of file initest.cc.
Referenced by main(), and usage().