gem5: arch/x86/bios/intelmp.cc File Reference
arch/x86/bios/intelmp.cc File Reference
#include "arch/x86/bios/intelmp.hh"
#include "arch/x86/isa_traits.hh"
#include "base/misc.hh"
#include "base/types.hh"
#include "mem/port_proxy.hh"
#include "sim/byteswap.hh"
#include "params/X86IntelMPBaseConfigEntry.hh"
#include "params/X86IntelMPExtConfigEntry.hh"
#include "params/X86IntelMPConfigTable.hh"
#include "params/X86IntelMPFloatingPointer.hh"
#include "params/X86IntelMPBus.hh"
#include "params/X86IntelMPIOAPIC.hh"
#include "params/X86IntelMPIOIntAssignment.hh"
#include "params/X86IntelMPLocalIntAssignment.hh"
#include "params/X86IntelMPProcessor.hh"
#include "params/X86IntelMPAddrSpaceMapping.hh"
#include "params/X86IntelMPBusHierarchy.hh"
#include "params/X86IntelMPCompatAddrSpaceMod.hh"
Functions
template<class T >
uint8_t writeOutField (PortProxy &proxy, Addr addr, T val)
uint8_t writeOutString (PortProxy &proxy, Addr addr, string str, int length)
Function Documentation
template<class T > uint8_t writeOutField (PortProxy & proxy, Addr addr, T val)
Definition at line 73 of file intelmp.cc.
References BigEndianGuest::htog(), and PortProxy::writeBlob().
Referenced by X86ISA::IntelMP::CompatAddrSpaceMod::writeOut(), X86ISA::IntelMP::BusHierarchy::writeOut(), X86ISA::IntelMP::AddrSpaceMapping::writeOut(), X86ISA::IntelMP::IntAssignment::writeOut(), X86ISA::IntelMP::IOAPIC::writeOut(), X86ISA::IntelMP::Bus::writeOut(), X86ISA::IntelMP::Processor::writeOut(), X86ISA::IntelMP::ConfigTable::writeOut(), and X86ISA::IntelMP::FloatingPointer::writeOut().
uint8_t writeOutString (PortProxy & proxy, Addr addr, string str, int length)
Definition at line 87 of file intelmp.cc.
References ArmISA::i, warn, and PortProxy::writeBlob().
Referenced by X86ISA::IntelMP::Bus::writeOut(), and X86ISA::IntelMP::ConfigTable::writeOut().