gem5: base/intmath.hh File Reference
base/intmath.hh File Reference
#include <cassert>
#include "base/misc.hh"
#include "base/types.hh"
Functions
int prevPrime (int n)
template<class T >
bool isPrime (T n)
template<class T >
T leastSigBit (T n)
template<class T >
bool isPowerOf2 (T n)
uint64_t power (uint32_t n, uint32_t e)
int floorLog2 (unsigned x)
int floorLog2 (unsigned long x)
int floorLog2 (unsigned long long x)
int floorLog2 (int x)
int floorLog2 (long x)
int floorLog2 (long long x)
template<class T >
int ceilLog2 (T n)
template<class T >
T floorPow2 (T n)
template<class T >
T ceilPow2 (T n)
template<class T , class U >
T divCeil (const T &a, const U &b)
template<class T >
T roundUp (T val, int align)
template<class T >
T roundDown (T val, int align)
bool isHex (char c)
bool isOct (char c)
bool isDec (char c)
int hex2Int (char c)
Function Documentation
template<class T > int ceilLog2 (T n) [inline]
Definition at line 174 of file intmath.hh.
References floorLog2().
Referenced by ceilPow2(), Random::genrand(), SimpleDRAM::init(), Pl390::Pl390(), SimpleDRAM::recvTimingReq(), SimpleDRAM::regStats(), and RubySystem::RubySystem().
template<class T > T ceilPow2 (T n) [inline]
Definition at line 191 of file intmath.hh.
References ceilLog2().
template<class T , class U > T divCeil (const T & a, const U & b) [inline]
Definition at line 198 of file intmath.hh.
Referenced by Process::allocateMem(), BaseBus::calcPacketTiming(), ClockedObject::resetClock(), AtomicSimpleCPU::tick(), and ClockedObject::update().
int floorLog2 (unsigned long long x) [inline]
Definition at line 135 of file intmath.hh.
References ULL.
int floorLog2 (int x) [inline]
Definition at line 152 of file intmath.hh.
References floorLog2().
int floorLog2 (long x) [inline]
Definition at line 159 of file intmath.hh.
References floorLog2().
int floorLog2 (long long x) [inline]
Definition at line 166 of file intmath.hh.
References floorLog2().
int floorLog2 (unsigned long x) [inline]
Definition at line 116 of file intmath.hh.
References ULL.
int floorLog2 (unsigned x) [inline]
Definition at line 100 of file intmath.hh.
Referenced by Histogram::add(), CheckTable::addCheck(), BankedArray::BankedArray(), ceilLog2(), DefaultBTB::DefaultBTB(), DirectoryMemory::DirectoryMemory(), FALRU::FALRU(), floorLog2(), floorPow2(), DirectoryMemory::init(), CacheMemory::init(), LRU::LRU(), and RubySystem::RubySystem().
template<class T > T floorPow2 (T n) [inline]
Definition at line 184 of file intmath.hh.
References floorLog2().
int hex2Int (char c) [inline]
Definition at line 240 of file intmath.hh.
Referenced by __to_number().
bool isDec (char c) [inline]
Definition at line 234 of file intmath.hh.
Referenced by __to_number().
bool isHex (char c) [inline]
Definition at line 220 of file intmath.hh.
Referenced by __to_number().
bool isOct (char c) [inline]
Definition at line 228 of file intmath.hh.
Referenced by __to_number().
template<class T > bool isPowerOf2 (T n) [inline]
Definition at line 73 of file intmath.hh.
References leastSigBit().
Referenced by ChunkGenerator::ChunkGenerator(), DefaultBTB::DefaultBTB(), FALRU::FALRU(), FrontEnd< Impl >::FrontEnd(), LocalBP::LocalBP(), LRU::LRU(), PageTable::PageTable(), PciDev::PciDev(), RubySystem::RubySystem(), StoreSet::StoreSet(), and TournamentBP::TournamentBP().
template<class T > bool isPrime (T n) [inline]
Definition at line 45 of file intmath.hh.
References ArmISA::i.
Referenced by prevPrime().
template<class T > T leastSigBit (T n) [inline]
Definition at line 66 of file intmath.hh.
Referenced by isPowerOf2().
uint64_t power (uint32_t n, uint32_t e) [inline]
Definition at line 79 of file intmath.hh.
References warn, and X86ISA::x.
Referenced by Sp804::Timer::read(), CpuLocalTimer::Timer::read(), A9SCU::read(), Sp804::Timer::restartCounter(), CpuLocalTimer::Timer::restartTimerCounter(), and CpuLocalTimer::Timer::restartWatchdogCounter().
int prevPrime (int n)
Definition at line 35 of file intmath.cc.
References isPrime().
template<class T > T roundDown (T val, int align) [inline]
Definition at line 213 of file intmath.hh.
References ArmISA::mask.
Referenced by X86ISA::X86LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), brkFunc(), Process::fixupStackFault(), Tru64::nxm_task_initFunc(), CacheUnit::read(), TimingSimpleCPU::readMem(), AtomicSimpleCPU::readMem(), CheckerCPU::readMem(), BasePrefetcher::samePage(), BaseDynInst< Impl >::splitRequest(), Tru64::stack_createFunc(), SETranslatingPortProxy::tryMemsetBlob(), SETranslatingPortProxy::tryWriteBlob(), CacheUnit::write(), TimingSimpleCPU::writeMem(), AtomicSimpleCPU::writeMem(), and CheckerCPU::writeMem().
template<class T > T roundUp (T val, int align) [inline]
Definition at line 205 of file intmath.hh.
References ArmISA::mask.
Referenced by AlphaLiveProcess::AlphaLiveProcess(), X86ISA::X86LiveProcess::argsInit(), SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), ArmLiveProcess::ArmLiveProcess(), brkFunc(), ChunkGenerator::ChunkGenerator(), Tru64::getdirentriesFunc(), X86System::initState(), MipsLiveProcess::MipsLiveProcess(), Tru64::nxm_task_initFunc(), PowerLiveProcess::PowerLiveProcess(), SparcLiveProcess::SparcLiveProcess(), Tru64::stack_createFunc(), and X86ISA::X86LiveProcess::X86LiveProcess().