gem5: Trace Namespace Reference
Trace Namespace Reference
Classes
class ArmNativeTrace
class SparcNativeTrace
class X86NativeTrace
class ExeTracerRecord
class ExeTracer
class InOrderTraceRecord
class InOrderTrace
class IntelTraceRecord
class IntelTrace
class LegionTraceRecord
class LegionTrace
class NativeTraceRecord
class NativeTrace
class InstRecord
class InstTracer
Functions
const string DefaultName ("global")
ostream & output ()
void setOutput (const string &filename)
void dprintf (Tick when, const std::string &name, const char *format, CPRINTF_DEFINITION)
void dump (Tick when, const std::string &name, const void *d, int len)
void setOutput (const std::string &filename)
bool changeFlag (const char *str, bool value)
void dumpStatus ()
void dprintf (Tick when, const std::string &name, const char *format, CPRINTF_DECLARATION)
void setupSharedData ()
char * genCenteredLabel (int length, char *buffer, const char *label)
void printRegPair (ostream &os, char const *title, uint64_t a, uint64_t b)
void printColumnLabels (ostream &os)
void printSectionHeader (ostream &os, const char *name)
void printLevelHeader (ostream &os, int level)
Variables
static const char * intRegNames [SparcISA::NumIntArchRegs]
bool enabled = false
ostream * dprintf_stream = &cerr
ObjectMatch ignore
const std::string DefaultName
SharedData * shared_data = NULL
Function Documentation
bool Trace::changeFlag (const char * str, bool value)
Referenced by clearDebugFlag(), and setDebugFlag().
const string Trace::DefaultName ("global")
void Trace::dprintf (Tick when, const std::string & name, const char * format, CPRINTF_DEFINITION)
Definition at line 74 of file trace.cc.
References ccprintf(), dprintf_stream, ignore, ObjectMatch::match(), X86ISA::os, VarArgs::List< RECV >::push_front(), and VARARGS_ALLARGS.
void Trace::dprintf (Tick when, const std::string & name, const char * format, CPRINTF_DECLARATION)
void Trace::dump (Tick when, const std::string & name, const void * d, int len)
void Trace::dumpStatus ()
char* Trace::genCenteredLabel (int length, char * buffer, const char * label) [inline]
Definition at line 96 of file legiontrace.cc.
References ArmISA::format.
Referenced by printColumnLabels(), printLevelHeader(), and printSectionHeader().
std::ostream & Trace::output ()
Referenced by Trace::LegionTraceRecord::dump(), Trace::IntelTraceRecord::dump(), and Trace::ExeTracerRecord::traceInst().
void Trace::printColumnLabels (ostream & os) [inline]
Definition at line 114 of file legiontrace.cc.
References ccprintf(), and genCenteredLabel().
Referenced by Trace::LegionTraceRecord::dump().
void Trace::printLevelHeader (ostream & os, int level) [inline]
Definition at line 132 of file legiontrace.cc.
References ccprintf(), and genCenteredLabel().
Referenced by Trace::LegionTraceRecord::dump().
void Trace::printRegPair (ostream & os, char const * title, uint64_t a, uint64_t b) [inline]
Definition at line 108 of file legiontrace.cc.
References ccprintf().
Referenced by Trace::LegionTraceRecord::dump().
void Trace::printSectionHeader (ostream & os, const char * name) [inline]
Definition at line 123 of file legiontrace.cc.
References ccprintf(), and genCenteredLabel().
Referenced by Trace::LegionTraceRecord::dump().
void Trace::setOutput (const std::string & filename)
void Trace::setOutput (const string & filename)
Definition at line 64 of file trace.cc.
References OutputDirectory::create(), dprintf_stream, OutputDirectory::find(), and simout.
void Trace::setupSharedData ()
Referenced by Trace::LegionTraceRecord::dump().
Variable Documentation
const std::string Trace::DefaultName
Referenced by name().
ostream* Trace::dprintf_stream = &cerr
Definition at line 56 of file trace.cc.
Referenced by dprintf(), and setOutput().
bool Trace::enabled = false
Definition at line 48 of file trace.cc.
Referenced by Trace::IntelTrace::getInstRecord(), Trace::InOrderTrace::getInstRecord(), and Trace::ExeTracer::getInstRecord().
ObjectMatch Trace::ignore
Definition at line 71 of file trace.cc.
Referenced by dprintf().
const char* Trace::intRegNames[SparcISA::NumIntArchRegs] [static]
Initial value:
 {
    "g0", "g1", "g2", "g3", "g4", "g5", "g6", "g7",
    "o0", "o1", "o2", "o3", "o4", "o5", "o6", "o7",
    "l0", "l1", "l2", "l3", "l4", "l5", "l6", "l7",
    "i0", "i1", "i2", "i3", "i4", "i5", "i6", "i7",
}
Definition at line 35 of file nativetrace.cc.
SharedData* Trace::shared_data = NULL
Definition at line 67 of file legiontrace.cc.
Referenced by Trace::LegionTraceRecord::dump().