gem5: PowerISA Namespace Reference
PowerISA Namespace Reference
Namespaces
namespace Kernel
Classes
class Decoder
class PowerFault
class UnimplementedOpcodeFault
class MachineCheckFault
class AlignmentFault
class PCDependentDisassembly
Base class for instructions whose disassembly is not purely a function of the machine instruction (i.e., it depends on the PC).
class BranchPCRel
Base class for unconditional, PC-relative branches.
class BranchNonPCRel
Base class for unconditional, non PC-relative branches.
class BranchCond
Base class for conditional branches.
class BranchPCRelCond
Base class for conditional, PC-relative branches.
class BranchNonPCRelCond
Base class for conditional, non PC-relative branches.
class BranchRegCond
Base class for conditional, register-based branches.
class CondLogicOp
Class for condition register logical operations.
class CondMoveOp
Class for condition register move operations.
class FloatOp
Base class for floating point operations.
class IntOp
We provide a base class for integer operations and then inherit for several other classes.
class IntImmOp
Class for integer immediate (signed and unsigned) operations.
class IntShiftOp
Class for integer operations with a shift.
class IntRotateOp
Class for integer rotate operations.
class MemOp
Base class for memory operations.
class MemDispOp
Class for memory operations with displacement.
class MiscOp
Class for misc operations.
class PowerStaticInst
class Interrupts
class ISA
struct VAddr
struct PTE
union AnyReg
class RemoteGDB
class ProcessInfo
class StackTrace
struct TlbEntry
class TLB
Typedefs
typedef uint8_t RegIndex
typedef uint64_t IntReg
typedef uint64_t FloatRegBits
typedef double FloatReg
typedef uint64_t MiscReg
typedef uint32_t MachInst
Enumerations
enum MiscRegIndex { NUM_MISCREGS = 0 }
enum MiscIntRegNums {
INTREG_CR = NumIntArchRegs, INTREG_XER, INTREG_LR, INTREG_CTR,
INTREG_FPSCR, INTREG_RSV, INTREG_RSV_LEN, INTREG_RSV_ADDR
}
Functions
template<class XC >
void handleLockedSnoop (XC *xc, PacketPtr pkt, Addr cacheBlockMask)
template<class XC >
void handleLockedRead (XC *xc, Request *req)
template<class XC >
bool handleLockedWrite (XC *xc, Request *req)
BitUnion32 (Cr) SubBitUnion(cr0
EndSubBitUnion (cr0) Bitfield< 27
EndBitUnion (Cr) BitUnion32(Xer) Bitfield< 31 > so
EndBitUnion (Xer) BitUnion32(Fpscr) Bitfield< 31 > fx
SubBitUnion (fprf, 16, 12) Bitfield< 16 > c
SubBitUnion (fpcc, 15, 12) Bitfield< 15 > fl
EndSubBitUnion (fpcc) EndSubBitUnion(fprf) Bitfield< 10 > vxsqrt
Cycles handleIprRead (ThreadContext *xc, Packet *pkt)
Cycles handleIprWrite (ThreadContext *xc, Packet *pkt)
BitUnion32 (ExtMachInst) Bitfield< 25
void copyRegs (ThreadContext *src, ThreadContext *dest)
uint64_t getArgument (ThreadContext *tc, int &number, uint16_t size, bool fp)
void skipFunction (ThreadContext *tc)
void initCPU (ThreadContext *tc, int cpuId)
PCState buildRetPC (const PCState &curPC, const PCState &callPC)
template<class TC >
void zeroRegisters (TC *tc)
Function to ensure ISA semantics about 0 registers.
void startupCPU (ThreadContext *tc, int cpuId)
static void copyMiscRegs (ThreadContext *src, ThreadContext *dest)
void advancePC (PCState &pc, const StaticInstPtr inst)
static bool inUserMode (ThreadContext *tc)
uint64_t getExecutingAsid (ThreadContext *tc)
Addr vtophys (Addr vaddr)
Addr vtophys (ThreadContext *tc, Addr vaddr)
Addr PteAddr (Addr a)
Variables
StaticInstPtr decodeInst (ExtMachInst)
const Addr PageShift = 12
const Addr PageBytes = ULL(1) << PageShift
const Addr Page_Mask = ~(PageBytes - 1)
const Addr PageOffset = PageBytes - 1
const Addr PteShift = 3
const Addr NPtePageShift = PageShift - PteShift
const Addr NPtePage = ULL(1) << NPtePageShift
const Addr PteMask = NPtePage - 1
const int LogVMPageSize = 12
const int VMPageSize = (1 << LogVMPageSize)
const int MachineBytes = 4
const ExtMachInst NoopMachInst = 0x60000000
const bool HasUnalignedMemAcc = true
const bool CurThreadInfoImplemented = false
const int CurThreadInfoReg = -1
const char *const miscRegName [NUM_MISCREGS]
Bitfield< 31 > lt
Bitfield< 30 > gt
Bitfield< 29 > eq
Bitfield< 28 > so
cr1
Bitfield< 30 > ov
Bitfield< 29 > ca
Bitfield< 30 > fex
Bitfield< 29 > vx
Bitfield< 28 > ox
Bitfield< 27 > ux
Bitfield< 26 > zx
Bitfield< 25 > xx
Bitfield< 24 > vxsnan
Bitfield< 23 > vxisi
Bitfield< 22 > vxidi
Bitfield< 21 > vxzdz
Bitfield< 20 > vximz
Bitfield< 19 > vxvc
Bitfield< 18 > fr
Bitfield< 17 > fi
Bitfield< 14 > fg
Bitfield< 13 > fe
Bitfield< 12 > fu
Bitfield< 9 > vxcvi
Bitfield< 8 > ve
Bitfield< 7 > oe
Bitfield< 6 > ue
Bitfield< 5 > ze
Bitfield< 4 > xe
Bitfield< 3 > ni
Bitfield< 2, 1 > rn
const int MaxMiscDestRegs = PowerISAInst::MaxMiscDestRegs + 1
const int NumIntArchRegs = 32
const int NumIntSpecialRegs = 9
const int NumFloatArchRegs = 32
const int NumFloatSpecialRegs = 0
const int NumInternalProcRegs = 0
const int NumIntRegs = NumIntArchRegs + NumIntSpecialRegs
const int NumFloatRegs = NumFloatArchRegs + NumFloatSpecialRegs
const int NumMiscRegs = NUM_MISCREGS
const int ReturnValueReg = 3
const int ArgumentReg0 = 3
const int ArgumentReg1 = 4
const int ArgumentReg2 = 5
const int ArgumentReg3 = 6
const int ArgumentReg4 = 7
const int FramePointerReg = 31
const int StackPointerReg = 1
const int ZeroReg = NumIntRegs - 1
const int SyscallNumReg = 0
const int SyscallPseudoReturnReg = 3
const int SyscallSuccessReg = 3
const int FP_Base_DepTag = NumIntRegs
const int Ctrl_Base_DepTag = FP_Base_DepTag + NumFloatRegs
const int Max_DepTag = Ctrl_Base_DepTag + NumMiscRegs
rs
Bitfield< 20, 16 > ra
Bitfield< 15, 11 > sh
Bitfield< 10, 6 > mb
Bitfield< 5, 1 > me
Bitfield< 15, 0 > si
Bitfield< 15, 0 > d
Bitfield< 20, 11 > spr
Bitfield< 25, 2 > li
Bitfield< 1 > aa
Bitfield< 25, 23 > bf
Bitfield< 15, 2 > bd
Bitfield< 25, 21 > bo
Bitfield< 20, 16 > bi
Bitfield< 20, 18 > bfa
Bitfield< 0 > rc31
Bitfield< 25, 21 > bt
Bitfield< 20, 16 > ba
Bitfield< 15, 11 > bb
Bitfield< 19, 12 > fxm
Typedef Documentation
typedef double PowerISA::FloatReg
Definition at line 52 of file registers.hh.
typedef uint64_t PowerISA::FloatRegBits
Definition at line 51 of file registers.hh.
typedef uint64_t PowerISA::IntReg
Definition at line 48 of file registers.hh.
typedef uint32_t PowerISA::MachInst
Definition at line 42 of file types.hh.
typedef uint64_t PowerISA::MiscReg
Definition at line 53 of file registers.hh.
typedef uint8_t PowerISA::RegIndex
Definition at line 46 of file registers.hh.
Enumeration Type Documentation
enum PowerISA::MiscIntRegNums
Enumerator:
INTREG_CR
INTREG_XER
INTREG_LR
INTREG_CTR
INTREG_FPSCR
INTREG_RSV
INTREG_RSV_LEN
INTREG_RSV_ADDR
Definition at line 97 of file registers.hh.
enum PowerISA::MiscRegIndex
Enumerator:
NUM_MISCREGS
Definition at line 39 of file miscregs.hh.
Function Documentation
void PowerISA::advancePC (PCState & pc, const StaticInstPtr inst) [inline]
Definition at line 76 of file utility.hh.
PowerISA::BitUnion32 (Cr)
PowerISA::BitUnion32 (ExtMachInst)
PCState PowerISA::buildRetPC (const PCState & curPC, const PCState & callPC) [inline]
Definition at line 45 of file utility.hh.
static void PowerISA::copyMiscRegs (ThreadContext * src, ThreadContext * dest) [inline, static]
Definition at line 69 of file utility.hh.
void PowerISA::copyRegs (ThreadContext * src, ThreadContext * dest)
PowerISA::EndBitUnion (Cr)
PowerISA::EndBitUnion (Xer)
PowerISA::EndSubBitUnion (cr0)
PowerISA::EndSubBitUnion (fpcc)
uint64_t PowerISA::getArgument (ThreadContext * tc, int & number, uint16_t size, bool fp)
uint64_t PowerISA::getExecutingAsid (ThreadContext * tc) [inline]
Definition at line 90 of file utility.hh.
Cycles PowerISA::handleIprRead (ThreadContext * xc, Packet * pkt) [inline]
Definition at line 53 of file mmapped_ipr.hh.
References panic.
Cycles PowerISA::handleIprWrite (ThreadContext * xc, Packet * pkt) [inline]
Definition at line 59 of file mmapped_ipr.hh.
References panic.
template<class XC > void PowerISA::handleLockedRead (XC * xc, Request * req) [inline]
Definition at line 58 of file locked_mem.hh.
template<class XC > void PowerISA::handleLockedSnoop (XC * xc, PacketPtr pkt, Addr cacheBlockMask) [inline]
Definition at line 52 of file locked_mem.hh.
template<class XC > bool PowerISA::handleLockedWrite (XC * xc, Request * req) [inline]
Definition at line 64 of file locked_mem.hh.
void PowerISA::initCPU (ThreadContext * tc, int cpuId)
static bool PowerISA::inUserMode (ThreadContext * tc) [inline, static]
Definition at line 84 of file utility.hh.
Addr PowerISA::PteAddr (Addr a) [inline]
Definition at line 50 of file vtophys.hh.
References PteMask, and PteShift.
Referenced by PowerISA::VAddr::level1(), PowerISA::VAddr::level2(), and PowerISA::VAddr::level3().
void PowerISA::skipFunction (ThreadContext * tc)
void PowerISA::startupCPU (ThreadContext * tc, int cpuId) [inline]
Definition at line 60 of file utility.hh.
References ThreadContext::activate().
PowerISA::SubBitUnion (fpcc , 15 , 12)
PowerISA::SubBitUnion (fprf , 16 , 12)
Addr PowerISA::vtophys (ThreadContext * tc, Addr vaddr)
Definition at line 42 of file vtophys.cc.
References bits(), ArmISA::TableWalker::L2Descriptor::data, ArmISA::TableWalker::L1Descriptor::data, fatal, ThreadContext::getDTBPtr(), ThreadContext::getITBPtr(), ThreadContext::getPhysProxy(), ArmISA::TableWalker::L2Descriptor::invalid(), ArmISA::TableWalker::L1Descriptor::l2Addr(), mbits(), ArmISA::MISCREG_SCTLR, ArmISA::MISCREG_TTBCR, ArmISA::MISCREG_TTBR0, ArmISA::MISCREG_TTBR1, ArmISA::TableWalker::L2Descriptor::paddr(), ArmISA::TableWalker::L1Descriptor::paddr(), PortProxy::read(), ThreadContext::readMiscReg(), ArmISA::TLB::translateFunctional(), ArmISA::TableWalker::L1Descriptor::type(), and warn.
Addr PowerISA::vtophys (Addr vaddr)
Definition at line 36 of file vtophys.cc.
References fatal.
Referenced by OzoneCPU< Impl >::dbg_vtophys(), CheckerCPU::dbg_vtophys(), BaseSimpleCPU::dbg_vtophys(), FSTranslatingPortProxy::memsetBlob(), FSTranslatingPortProxy::readBlob(), Sinic::Device::write(), and FSTranslatingPortProxy::writeBlob().
template<class TC > void PowerISA::zeroRegisters (TC * tc)
Function to ensure ISA semantics about 0 registers.
Parameters:
tc The thread context.
Variable Documentation
Bitfield<1> PowerISA::aa
Definition at line 62 of file types.hh.
const int PowerISA::ArgumentReg0 = 3
Definition at line 71 of file registers.hh.
const int PowerISA::ArgumentReg1 = 4
Definition at line 72 of file registers.hh.
const int PowerISA::ArgumentReg2 = 5
Definition at line 73 of file registers.hh.
const int PowerISA::ArgumentReg3 = 6
Definition at line 74 of file registers.hh.
const int PowerISA::ArgumentReg4 = 7
Definition at line 75 of file registers.hh.
Bitfield<20, 16> PowerISA::ba
Definition at line 75 of file types.hh.
Bitfield<15, 11> PowerISA::bb
Definition at line 76 of file types.hh.
Bitfield<15, 2> PowerISA::bd
Definition at line 64 of file types.hh.
Bitfield<25, 23> PowerISA::bf
Definition at line 63 of file types.hh.
Bitfield<20, 18> PowerISA::bfa
Definition at line 67 of file types.hh.
Bitfield<20, 16> PowerISA::bi
Definition at line 66 of file types.hh.
Bitfield<25, 21> PowerISA::bo
Definition at line 65 of file types.hh.
Bitfield<25, 21> PowerISA::bt
Definition at line 74 of file types.hh.
Bitfield<29> PowerISA::ca
Definition at line 59 of file miscregs.hh.
PowerISA::cr1
Definition at line 53 of file miscregs.hh.
const int PowerISA::Ctrl_Base_DepTag = FP_Base_DepTag + NumFloatRegs
Definition at line 88 of file registers.hh.
Referenced by PowerISA::PowerStaticInst::printReg().
const bool PowerISA::CurThreadInfoImplemented = false
Definition at line 75 of file isa_traits.hh.
const int PowerISA::CurThreadInfoReg = -1
Definition at line 76 of file isa_traits.hh.
Bitfield<15, 0> PowerISA::d
Definition at line 57 of file types.hh.
StaticInstPtr PowerISA::decodeInst(ExtMachInst)
Bitfield<29> PowerISA::eq
Definition at line 50 of file miscregs.hh.
Bitfield<13> PowerISA::fe
Definition at line 83 of file miscregs.hh.
Bitfield<30> PowerISA::fex
Definition at line 64 of file miscregs.hh.
Bitfield<14> PowerISA::fg
Definition at line 82 of file miscregs.hh.
Bitfield<17> PowerISA::fi
Definition at line 77 of file miscregs.hh.
const int PowerISA::FP_Base_DepTag = NumIntRegs
Definition at line 87 of file registers.hh.
Referenced by PowerISA::PowerStaticInst::printReg().
Bitfield<18> PowerISA::fr
Definition at line 76 of file miscregs.hh.
const int PowerISA::FramePointerReg = 31
Definition at line 76 of file registers.hh.
Bitfield<12> PowerISA::fu
Definition at line 84 of file miscregs.hh.
Referenced by FUPool::FUPool().
Bitfield<19, 12> PowerISA::fxm
Definition at line 79 of file types.hh.
Bitfield<30> PowerISA::gt
Definition at line 49 of file miscregs.hh.
const bool PowerISA::HasUnalignedMemAcc = true
Definition at line 73 of file isa_traits.hh.
Bitfield<25, 2> PowerISA::li
Definition at line 61 of file types.hh.
const int PowerISA::LogVMPageSize = 12
Definition at line 64 of file isa_traits.hh.
Bitfield<31> PowerISA::lt
Definition at line 47 of file miscregs.hh.
const int PowerISA::MachineBytes = 4
Definition at line 67 of file isa_traits.hh.
const int PowerISA::Max_DepTag = Ctrl_Base_DepTag + NumMiscRegs
Definition at line 89 of file registers.hh.
const int PowerISA::MaxMiscDestRegs = PowerISAInst::MaxMiscDestRegs + 1
Definition at line 44 of file registers.hh.
Bitfield<10, 6> PowerISA::mb
Definition at line 52 of file types.hh.
Bitfield< 5, 1> PowerISA::me
Definition at line 53 of file types.hh.
const char* const PowerISA::miscRegName[NUM_MISCREGS]
Initial value:
 {
}
Definition at line 43 of file miscregs.hh.
Bitfield<3> PowerISA::ni
Definition at line 94 of file miscregs.hh.
Referenced by GarnetNetwork::init(), and GarnetNetwork_d::init().
const ExtMachInst PowerISA::NoopMachInst = 0x60000000
Definition at line 70 of file isa_traits.hh.
const Addr PowerISA::NPtePage = ULL(1) << NPtePageShift
Definition at line 61 of file isa_traits.hh.
const Addr PowerISA::NPtePageShift = PageShift - PteShift
Definition at line 60 of file isa_traits.hh.
Referenced by PowerISA::VAddr::level1(), and PowerISA::VAddr::level2().
const int PowerISA::NumFloatArchRegs = 32
Definition at line 61 of file registers.hh.
const int PowerISA::NumFloatRegs = NumFloatArchRegs + NumFloatSpecialRegs
Definition at line 66 of file registers.hh.
const int PowerISA::NumFloatSpecialRegs = 0
Definition at line 62 of file registers.hh.
const int PowerISA::NumIntArchRegs = 32
Definition at line 56 of file registers.hh.
const int PowerISA::NumInternalProcRegs = 0
Definition at line 63 of file registers.hh.
const int PowerISA::NumIntRegs = NumIntArchRegs + NumIntSpecialRegs
Definition at line 65 of file registers.hh.
const int PowerISA::NumIntSpecialRegs = 9
Definition at line 60 of file registers.hh.
const int PowerISA::NumMiscRegs = NUM_MISCREGS
Definition at line 67 of file registers.hh.
Bitfield< 10 > PowerISA::oe
Definition at line 90 of file miscregs.hh.
Bitfield<30> PowerISA::ov
Definition at line 58 of file miscregs.hh.
Bitfield<28> PowerISA::ox
Definition at line 66 of file miscregs.hh.
const Addr PowerISA::Page_Mask = ~(PageBytes - 1)
Definition at line 56 of file isa_traits.hh.
Referenced by PowerISA::VAddr::page().
const Addr PowerISA::PageBytes = ULL(1) << PageShift
Definition at line 55 of file isa_traits.hh.
const Addr PowerISA::PageOffset = PageBytes - 1
Definition at line 57 of file isa_traits.hh.
Referenced by PowerISA::VAddr::offset().
const Addr PowerISA::PageShift = 12
Definition at line 54 of file isa_traits.hh.
Referenced by PowerISA::VAddr::level1(), PowerISA::VAddr::level2(), PowerISA::VAddr::level3(), and PowerISA::VAddr::vpn().
const Addr PowerISA::PteMask = NPtePage - 1
Definition at line 62 of file isa_traits.hh.
Referenced by PteAddr().
const Addr PowerISA::PteShift = 3
Definition at line 59 of file isa_traits.hh.
Referenced by PteAddr().
Bitfield<20, 16> PowerISA::ra
Definition at line 48 of file types.hh.
Referenced by AlphaISA::StackTrace::trace().
Bitfield<0> PowerISA::rc31
Definition at line 70 of file types.hh.
const int PowerISA::ReturnValueReg = 3
Definition at line 70 of file registers.hh.
Bitfield<2,1> PowerISA::rn
Definition at line 95 of file miscregs.hh.
PowerISA::rs
Definition at line 47 of file types.hh.
Bitfield<15, 11> PowerISA::sh
Definition at line 51 of file types.hh.
Bitfield<15, 0> PowerISA::si
Definition at line 56 of file types.hh.
Referenced by GenericISA::BasicDecodeCache::decode(), MipsISA::RemoteGDB::setSingleStep(), ArmISA::RemoteGDB::setSingleStep(), and AlphaISA::RemoteGDB::setSingleStep().
Bitfield<28> PowerISA::so
Definition at line 51 of file miscregs.hh.
Bitfield<20, 11> PowerISA::spr
Definition at line 60 of file types.hh.
const int PowerISA::StackPointerReg = 1
Definition at line 77 of file registers.hh.
const int PowerISA::SyscallNumReg = 0
Definition at line 82 of file registers.hh.
const int PowerISA::SyscallPseudoReturnReg = 3
Definition at line 83 of file registers.hh.
const int PowerISA::SyscallSuccessReg = 3
Definition at line 84 of file registers.hh.
Bitfield<6> PowerISA::ue
Definition at line 91 of file miscregs.hh.
Bitfield<27> PowerISA::ux
Definition at line 67 of file miscregs.hh.
Bitfield<8> PowerISA::ve
Definition at line 89 of file miscregs.hh.
const int PowerISA::VMPageSize = (1 << LogVMPageSize)
Definition at line 65 of file isa_traits.hh.
Referenced by PowerLiveProcess::argsInit().
Bitfield<29> PowerISA::vx
Definition at line 65 of file miscregs.hh.
Bitfield<9> PowerISA::vxcvi
Definition at line 88 of file miscregs.hh.
Bitfield<22> PowerISA::vxidi
Definition at line 72 of file miscregs.hh.
Bitfield<20> PowerISA::vximz
Definition at line 74 of file miscregs.hh.
Bitfield<23> PowerISA::vxisi
Definition at line 71 of file miscregs.hh.
Bitfield<24> PowerISA::vxsnan
Definition at line 70 of file miscregs.hh.
Bitfield<19> PowerISA::vxvc
Definition at line 75 of file miscregs.hh.
Bitfield<21> PowerISA::vxzdz
Definition at line 73 of file miscregs.hh.
Bitfield<4> PowerISA::xe
Definition at line 93 of file miscregs.hh.
Bitfield<25> PowerISA::xx
Definition at line 69 of file miscregs.hh.
Bitfield<5> PowerISA::ze
Definition at line 92 of file miscregs.hh.
const int PowerISA::ZeroReg = NumIntRegs - 1
Definition at line 80 of file registers.hh.
Bitfield<26> PowerISA::zx
Definition at line 68 of file miscregs.hh.