gem5: GenericISA Namespace Reference
GenericISA Namespace Reference
Classes
class M5DebugFault
class M5VarArgsFault
class BasicDecodeCache
class PCStateBase
class SimplePCState
class UPCState
class DelaySlotPCState
class DelaySlotUPCState
Typedefs
typedef M5VarArgsFault
< M5DebugFault::PanicFunc > M5PanicFault
typedef M5VarArgsFault
< M5DebugFault::FatalFunc > M5FatalFault
typedef M5VarArgsFault
< M5DebugFault::WarnFunc > M5WarnFault
typedef M5VarArgsFault
< M5DebugFault::WarnOnceFunc > M5WarnOnceFault
Functions
template<class MachInst >
std::ostream & operator<< (std::ostream &os, const SimplePCState< MachInst > &pc)
template<class MachInst >
std::ostream & operator<< (std::ostream &os, const UPCState< MachInst > &pc)
template<class MachInst >
std::ostream & operator<< (std::ostream &os, const DelaySlotPCState< MachInst > &pc)
template<class MachInst >
std::ostream & operator<< (std::ostream &os, const DelaySlotUPCState< MachInst > &pc)
Typedef Documentation
typedef M5VarArgsFault<M5DebugFault::FatalFunc> GenericISA::M5FatalFault
Definition at line 121 of file debugfaults.hh.
typedef M5VarArgsFault<M5DebugFault::PanicFunc> GenericISA::M5PanicFault
Definition at line 120 of file debugfaults.hh.
typedef M5VarArgsFault<M5DebugFault::WarnFunc> GenericISA::M5WarnFault
Definition at line 122 of file debugfaults.hh.
typedef M5VarArgsFault<M5DebugFault::WarnOnceFunc> GenericISA::M5WarnOnceFault
Definition at line 123 of file debugfaults.hh.
Function Documentation
template<class MachInst > std::ostream& GenericISA::operator<< (std::ostream & os, const SimplePCState< MachInst > & pc)
Definition at line 171 of file types.hh.
References ccprintf(), X86ISA::os, and MipsISA::pc.
template<class MachInst > std::ostream& GenericISA::operator<< (std::ostream & os, const DelaySlotUPCState< MachInst > & pc)
Definition at line 447 of file types.hh.
References ccprintf(), X86ISA::os, and MipsISA::pc.
template<class MachInst > std::ostream& GenericISA::operator<< (std::ostream & os, const DelaySlotPCState< MachInst > & pc)
Definition at line 348 of file types.hh.
References ccprintf(), X86ISA::os, and MipsISA::pc.
template<class MachInst > std::ostream& GenericISA::operator<< (std::ostream & os, const UPCState< MachInst > & pc)
Definition at line 269 of file types.hh.
References ccprintf(), X86ISA::os, and MipsISA::pc.