gem5: AlphaISA Namespace Reference
AlphaISA Namespace Reference
Namespaces
namespace Kernel
Classes
class Decoder
class AlphaFault
class MachineCheckFault
class AlignmentFault
class ResetFault
class ArithmeticFault
class InterruptFault
class DtbFault
class NDtbMissFault
class PDtbMissFault
class DtbPageFault
class DtbAcvFault
class DtbAlignmentFault
class ItbFault
class ItbPageFault
class ItbAcvFault
class UnimplementedOpcodeFault
class FloatEnableFault
class PalFault
class IntegerOverflowFault
class Interrupts
class ISA
class AlphaLinuxProcess
A process with emulated Alpha/Linux syscalls.
struct VAddr
struct PageTableEntry
struct TlbEntry
union AnyReg
class RemoteGDB
class ProcessInfo
class StackTrace
class TLB
class AlphaTru64Process
A process with emulated Alpha Tru64 syscalls.
Typedefs
typedef const Addr FaultVect
typedef uint8_t RegIndex
typedef uint64_t IntReg
typedef double FloatReg
typedef uint64_t FloatRegBits
typedef uint64_t MiscReg
typedef uint32_t MachInst
typedef uint64_t ExtMachInst
typedef
GenericISA::SimplePCState
< MachInst > PCState
typedef uint64_t LargestRead
Enumerations
enum md_ipr_names {
RAW_IPR_ISR = 0x100, RAW_IPR_ITB_TAG = 0x101, RAW_IPR_ITB_PTE = 0x102, RAW_IPR_ITB_ASN = 0x103,
RAW_IPR_ITB_PTE_TEMP = 0x104, RAW_IPR_ITB_IA = 0x105, RAW_IPR_ITB_IAP = 0x106, RAW_IPR_ITB_IS = 0x107,
RAW_IPR_SIRR = 0x108, RAW_IPR_ASTRR = 0x109, RAW_IPR_ASTER = 0x10a, RAW_IPR_EXC_ADDR = 0x10b,
RAW_IPR_EXC_SUM = 0x10c, RAW_IPR_EXC_MASK = 0x10d, RAW_IPR_PAL_BASE = 0x10e, RAW_IPR_ICM = 0x10f,
RAW_IPR_IPLR = 0x110, RAW_IPR_INTID = 0x111, RAW_IPR_IFAULT_VA_FORM = 0x112, RAW_IPR_IVPTBR = 0x113,
RAW_IPR_HWINT_CLR = 0x115, RAW_IPR_SL_XMIT = 0x116, RAW_IPR_SL_RCV = 0x117, RAW_IPR_ICSR = 0x118,
RAW_IPR_IC_FLUSH = 0x119, RAW_IPR_IC_PERR_STAT = 0x11a, RAW_IPR_PMCTR = 0x11c, RAW_IPR_PALtemp0 = 0x140,
RAW_IPR_PALtemp1 = 0x141, RAW_IPR_PALtemp2 = 0x142, RAW_IPR_PALtemp3 = 0x143, RAW_IPR_PALtemp4 = 0x144,
RAW_IPR_PALtemp5 = 0x145, RAW_IPR_PALtemp6 = 0x146, RAW_IPR_PALtemp7 = 0x147, RAW_IPR_PALtemp8 = 0x148,
RAW_IPR_PALtemp9 = 0x149, RAW_IPR_PALtemp10 = 0x14a, RAW_IPR_PALtemp11 = 0x14b, RAW_IPR_PALtemp12 = 0x14c,
RAW_IPR_PALtemp13 = 0x14d, RAW_IPR_PALtemp14 = 0x14e, RAW_IPR_PALtemp15 = 0x14f, RAW_IPR_PALtemp16 = 0x150,
RAW_IPR_PALtemp17 = 0x151, RAW_IPR_PALtemp18 = 0x152, RAW_IPR_PALtemp19 = 0x153, RAW_IPR_PALtemp20 = 0x154,
RAW_IPR_PALtemp21 = 0x155, RAW_IPR_PALtemp22 = 0x156, RAW_IPR_PALtemp23 = 0x157, RAW_IPR_DTB_ASN = 0x200,
RAW_IPR_DTB_CM = 0x201, RAW_IPR_DTB_TAG = 0x202, RAW_IPR_DTB_PTE = 0x203, RAW_IPR_DTB_PTE_TEMP = 0x204,
RAW_IPR_MM_STAT = 0x205, RAW_IPR_VA = 0x206, RAW_IPR_VA_FORM = 0x207, RAW_IPR_MVPTBR = 0x208,
RAW_IPR_DTB_IAP = 0x209, RAW_IPR_DTB_IA = 0x20a, RAW_IPR_DTB_IS = 0x20b, RAW_IPR_ALT_MODE = 0x20c,
RAW_IPR_CC = 0x20d, RAW_IPR_CC_CTL = 0x20e, RAW_IPR_MCSR = 0x20f, RAW_IPR_DC_FLUSH = 0x210,
RAW_IPR_DC_PERR_STAT = 0x212, RAW_IPR_DC_TEST_CTL = 0x213, RAW_IPR_DC_TEST_TAG = 0x214, RAW_IPR_DC_TEST_TAG_TEMP = 0x215,
RAW_IPR_DC_MODE = 0x216, RAW_IPR_MAF_MODE = 0x217, MaxInternalProcRegs
}
enum MiscRegIpr {
MinWriteOnlyIpr, IPR_HWINT_CLR = MinWriteOnlyIpr, IPR_SL_XMIT, IPR_DC_FLUSH,
IPR_IC_FLUSH, IPR_ALT_MODE, IPR_DTB_IA, IPR_DTB_IAP,
IPR_ITB_IA, MaxWriteOnlyIpr, IPR_ITB_IAP = MaxWriteOnlyIpr, MinReadOnlyIpr,
IPR_INTID = MinReadOnlyIpr, IPR_SL_RCV, IPR_MM_STAT, IPR_ITB_PTE_TEMP,
MaxReadOnlyIpr, IPR_DTB_PTE_TEMP = MaxReadOnlyIpr, IPR_ISR, IPR_ITB_TAG,
IPR_ITB_PTE, IPR_ITB_ASN, IPR_ITB_IS, IPR_SIRR,
IPR_ASTRR, IPR_ASTER, IPR_EXC_ADDR, IPR_EXC_SUM,
IPR_EXC_MASK, IPR_PAL_BASE, IPR_ICM, IPR_IPLR,
IPR_IFAULT_VA_FORM, IPR_IVPTBR, IPR_ICSR, IPR_IC_PERR_STAT,
IPR_PMCTR, IPR_PALtemp0, IPR_PALtemp1, IPR_PALtemp2,
IPR_PALtemp3, IPR_PALtemp4, IPR_PALtemp5, IPR_PALtemp6,
IPR_PALtemp7, IPR_PALtemp8, IPR_PALtemp9, IPR_PALtemp10,
IPR_PALtemp11, IPR_PALtemp12, IPR_PALtemp13, IPR_PALtemp14,
IPR_PALtemp15, IPR_PALtemp16, IPR_PALtemp17, IPR_PALtemp18,
IPR_PALtemp19, IPR_PALtemp20, IPR_PALtemp21, IPR_PALtemp22,
IPR_PALtemp23, IPR_DTB_ASN, IPR_DTB_CM, IPR_DTB_TAG,
IPR_DTB_PTE, IPR_VA, IPR_VA_FORM, IPR_MVPTBR,
IPR_DTB_IS, IPR_CC, IPR_CC_CTL, IPR_MCSR,
IPR_DC_PERR_STAT, IPR_DC_TEST_CTL, IPR_DC_TEST_TAG, IPR_DC_TEST_TAG_TEMP,
IPR_DC_MODE, IPR_MAF_MODE, NumInternalProcRegs
}
enum InterruptLevels {
INTLEVEL_SOFTWARE_MIN = 4, INTLEVEL_SOFTWARE_MAX = 19, INTLEVEL_EXTERNAL_MIN = 20, INTLEVEL_EXTERNAL_MAX = 34,
INTLEVEL_IRQ0 = 20, INTLEVEL_IRQ1 = 21, INTINDEX_ETHERNET = 0, INTINDEX_SCSI = 1,
INTLEVEL_IRQ2 = 22, INTLEVEL_IRQ3 = 23, INTLEVEL_SERIAL = 33, NumInterruptLevels = INTLEVEL_EXTERNAL_MAX
}
enum mode_type {
mode_kernel = 0, mode_executive = 1, mode_supervisor = 2, mode_user = 3,
mode_number
}
enum {
LogVMPageSize = 13, VMPageSize = (1 << LogVMPageSize), BranchPredAddrShiftAmt = 2, MachineBytes = 8,
WordBytes = 4, HalfwordBytes = 2, ByteBytes = 1
}
enum MiscRegIndex {
MISCREG_FPCR = NumInternalProcRegs, MISCREG_UNIQ, MISCREG_LOCKFLAG, MISCREG_LOCKADDR,
MISCREG_INTR, NUM_MISCREGS
}
enum DependenceTags { FP_Base_DepTag = 40, Ctrl_Base_DepTag = 72, Max_DepTag = Ctrl_Base_DepTag + NumMiscRegs + NumInternalProcRegs }
enum annotes { ANNOTE_NONE = 0, ITOUCH_ANNOTE = 0xffffffff }
Functions
void initCPU (ThreadContext *tc, int cpuId)
template<class CPU >
void zeroRegisters (CPU *cpu)
void initIPRs (ThreadContext *tc, int cpuId)
void copyIprs (ThreadContext *src, ThreadContext *dest)
Addr VAddrImpl (Addr a)
Addr VAddrVPN (Addr a)
Addr VAddrOffset (Addr a)
Addr VAddrSpaceEV5 (Addr a)
Addr VAddrSpaceEV6 (Addr a)
bool PAddrIprSpace (Addr a)
Addr Phys2K0Seg (Addr addr)
int DTB_ASN_ASN (uint64_t reg)
Addr DTB_PTE_PPN (uint64_t reg)
int DTB_PTE_XRE (uint64_t reg)
int DTB_PTE_XWE (uint64_t reg)
int DTB_PTE_FONR (uint64_t reg)
int DTB_PTE_FONW (uint64_t reg)
int DTB_PTE_GH (uint64_t reg)
int DTB_PTE_ASMA (uint64_t reg)
int ITB_ASN_ASN (uint64_t reg)
Addr ITB_PTE_PPN (uint64_t reg)
int ITB_PTE_XRE (uint64_t reg)
bool ITB_PTE_FONR (uint64_t reg)
bool ITB_PTE_FONW (uint64_t reg)
int ITB_PTE_GH (uint64_t reg)
bool ITB_PTE_ASMA (uint64_t reg)
uint64_t MCSR_SP (uint64_t reg)
bool ICSR_SDE (uint64_t reg)
int ICSR_SPE (uint64_t reg)
bool ICSR_FPE (uint64_t reg)
uint64_t ALT_MODE_AM (uint64_t reg)
uint64_t DTB_CM_CM (uint64_t reg)
uint64_t ICM_CM (uint64_t reg)
int Opcode (MachInst inst)
int Ra (MachInst inst)
void initializeIprTable ()
bool IprIsWritable (int index)
bool IprIsReadable (int index)
StaticInstPtr decodeInst (ExtMachInst)
template<class XC >
void handleLockedSnoop (XC *xc, PacketPtr pkt, Addr cacheBlockMask)
template<class XC >
void handleLockedRead (XC *xc, Request *req)
template<class XC >
bool handleLockedWrite (XC *xc, Request *req)
Cycles handleIprRead (ThreadContext *xc, Packet *pkt)
Cycles handleIprWrite (ThreadContext *xc, Packet *pkt)
template<class TC >
unsigned getVirtProcNum (TC *tc)
template<class TC >
unsigned getTargetThread (TC *tc)
uint64_t getArgument (ThreadContext *tc, int &number, uint16_t size, bool fp)
void copyRegs (ThreadContext *src, ThreadContext *dest)
void copyMiscRegs (ThreadContext *src, ThreadContext *dest)
void skipFunction (ThreadContext *tc)
PCState buildRetPC (const PCState &curPC, const PCState &callPC)
bool inUserMode (ThreadContext *tc)
template<class TC >
void zeroRegisters (TC *tc)
Function to insure ISA semantics about 0 registers.
bool PcPAL (Addr addr)
void startupCPU (ThreadContext *tc, int cpuId)
Addr PteAddr (Addr a)
bool IsUSeg (Addr a)
bool IsK0Seg (Addr a)
Addr K0Seg2Phys (Addr addr)
bool IsK1Seg (Addr a)
Addr TruncPage (Addr addr)
Addr RoundPage (Addr addr)
void advancePC (PCState &pc, const StaticInstPtr inst)
uint64_t getExecutingAsid (ThreadContext *tc)
PageTableEntry kernel_pte_lookup (PortProxy &mem, Addr ptbr, VAddr vaddr)
Addr vtophys (Addr vaddr)
Addr vtophys (ThreadContext *tc, Addr addr)
Variables
int break_ipl = -1
const uint64_t AsnMask = ULL(0xff)
const int VAddrImplBits = 43
const Addr VAddrImplMask = (ULL(1) << VAddrImplBits) - 1
const Addr VAddrUnImplMask = ~VAddrImplMask
const int PAddrImplBits = 44
const Addr PAddrImplMask = (ULL(1) << PAddrImplBits) - 1
const Addr PAddrUncachedBit39 = ULL(0x8000000000)
const Addr PAddrUncachedBit40 = ULL(0x10000000000)
const Addr PAddrUncachedBit43 = ULL(0x80000000000)
const Addr PAddrUncachedMask = ULL(0x807ffffffff)
const uint64_t MM_STAT_BAD_VA_MASK = ULL(0x0020)
const uint64_t MM_STAT_DTB_MISS_MASK = ULL(0x0010)
const uint64_t MM_STAT_FONW_MASK = ULL(0x0008)
const uint64_t MM_STAT_FONR_MASK = ULL(0x0004)
const uint64_t MM_STAT_ACV_MASK = ULL(0x0002)
const uint64_t MM_STAT_WR_MASK = ULL(0x0001)
const Addr PalBase = 0x4000
const Addr PalMax = 0x10000
md_ipr_names MiscRegIndexToIpr [NumInternalProcRegs]
int IprToMiscRegIndex [MaxInternalProcRegs]
const Addr PageShift = 13
const Addr PageBytes = ULL(1) << PageShift
const Addr PageMask = ~(PageBytes - 1)
const Addr PageOffset = PageBytes - 1
const Addr PteShift = 3
const Addr NPtePageShift = PageShift - PteShift
const Addr NPtePage = ULL(1) << NPtePageShift
const Addr PteMask = NPtePage - 1
const Addr USegBase = ULL(0x0)
const Addr USegEnd = ULL(0x000003ffffffffff)
const Addr K0SegBase = ULL(0xfffffc0000000000)
const Addr K0SegEnd = ULL(0xfffffdffffffffff)
const Addr K1SegBase = ULL(0xfffffe0000000000)
const Addr K1SegEnd = ULL(0xffffffffffffffff)
const ExtMachInst NoopMachInst = 0x2ffe0000
const bool HasUnalignedMemAcc = false
const bool CurThreadInfoImplemented = true
const int CurThreadInfoReg = AlphaISA::IPR_PALtemp23
const int MaxMiscDestRegs = AlphaISAInst::MaxMiscDestRegs + 1
const RegIndex ZeroReg = 31
const RegIndex StackPointerReg = 30
const RegIndex GlobalPointerReg = 29
const RegIndex ProcedureValueReg = 27
const RegIndex ReturnAddressReg = 26
const RegIndex ReturnValueReg = 0
const RegIndex FramePointerReg = 15
const RegIndex SyscallNumReg = 0
const RegIndex FirstArgumentReg = 16
const RegIndex SyscallPseudoReturnReg = 20
const RegIndex SyscallSuccessReg = 19
const int NumIntArchRegs = 32
const int NumPALShadowRegs = 8
const int NumFloatArchRegs = 32
const int NumMiscArchRegs = NUM_MISCREGS
const int NumIntRegs = NumIntArchRegs + NumPALShadowRegs
const int NumFloatRegs = NumFloatArchRegs
const int NumMiscRegs = NumMiscArchRegs
const int TotalNumRegs
const int TotalDataRegs = NumIntRegs + NumFloatRegs
const int reg_redir [NumIntRegs]
Typedef Documentation
typedef uint64_t AlphaISA::ExtMachInst
Definition at line 41 of file types.hh.
typedef const Addr AlphaISA::FaultVect
Definition at line 43 of file faults.hh.
typedef double AlphaISA::FloatReg
Definition at line 50 of file registers.hh.
typedef uint64_t AlphaISA::FloatRegBits
Definition at line 51 of file registers.hh.
typedef uint64_t AlphaISA::IntReg
Definition at line 47 of file registers.hh.
typedef uint64_t AlphaISA::LargestRead
Definition at line 45 of file types.hh.
typedef uint32_t AlphaISA::MachInst
Definition at line 40 of file types.hh.
typedef uint64_t AlphaISA::MiscReg
Definition at line 54 of file registers.hh.
typedef GenericISA::SimplePCState<MachInst> AlphaISA::PCState
Definition at line 43 of file types.hh.
typedef uint8_t AlphaISA::RegIndex
Definition at line 46 of file registers.hh.
Enumeration Type Documentation
anonymous enum
Enumerator:
LogVMPageSize
VMPageSize
BranchPredAddrShiftAmt
MachineBytes
WordBytes
HalfwordBytes
ByteBytes
Definition at line 114 of file isa_traits.hh.
enum AlphaISA::annotes
Enumerator:
ANNOTE_NONE
ITOUCH_ANNOTE
Definition at line 47 of file types.hh.
enum AlphaISA::DependenceTags
Enumerator:
FP_Base_DepTag
Ctrl_Base_DepTag
Max_DepTag
Definition at line 103 of file registers.hh.
enum AlphaISA::InterruptLevels
Enumerator:
INTLEVEL_SOFTWARE_MIN
INTLEVEL_SOFTWARE_MAX
INTLEVEL_EXTERNAL_MIN
INTLEVEL_EXTERNAL_MAX
INTLEVEL_IRQ0
INTLEVEL_IRQ1
INTINDEX_ETHERNET
INTINDEX_SCSI
INTLEVEL_IRQ2
INTLEVEL_IRQ3
INTLEVEL_SERIAL
NumInterruptLevels
Definition at line 82 of file isa_traits.hh.
enum AlphaISA::md_ipr_names
Enumerator:
RAW_IPR_ISR
RAW_IPR_ITB_TAG
RAW_IPR_ITB_PTE
RAW_IPR_ITB_ASN
RAW_IPR_ITB_PTE_TEMP
RAW_IPR_ITB_IA
RAW_IPR_ITB_IAP
RAW_IPR_ITB_IS
RAW_IPR_SIRR
RAW_IPR_ASTRR
RAW_IPR_ASTER
RAW_IPR_EXC_ADDR
RAW_IPR_EXC_SUM
RAW_IPR_EXC_MASK
RAW_IPR_PAL_BASE
RAW_IPR_ICM
RAW_IPR_IPLR
RAW_IPR_INTID
RAW_IPR_IFAULT_VA_FORM
RAW_IPR_IVPTBR
RAW_IPR_HWINT_CLR
RAW_IPR_SL_XMIT
RAW_IPR_SL_RCV
RAW_IPR_ICSR
RAW_IPR_IC_FLUSH
RAW_IPR_IC_PERR_STAT
RAW_IPR_PMCTR
RAW_IPR_PALtemp0
RAW_IPR_PALtemp1
RAW_IPR_PALtemp2
RAW_IPR_PALtemp3
RAW_IPR_PALtemp4
RAW_IPR_PALtemp5
RAW_IPR_PALtemp6
RAW_IPR_PALtemp7
RAW_IPR_PALtemp8
RAW_IPR_PALtemp9
RAW_IPR_PALtemp10
RAW_IPR_PALtemp11
RAW_IPR_PALtemp12
RAW_IPR_PALtemp13
RAW_IPR_PALtemp14
RAW_IPR_PALtemp15
RAW_IPR_PALtemp16
RAW_IPR_PALtemp17
RAW_IPR_PALtemp18
RAW_IPR_PALtemp19
RAW_IPR_PALtemp20
RAW_IPR_PALtemp21
RAW_IPR_PALtemp22
RAW_IPR_PALtemp23
RAW_IPR_DTB_ASN
RAW_IPR_DTB_CM
RAW_IPR_DTB_TAG
RAW_IPR_DTB_PTE
RAW_IPR_DTB_PTE_TEMP
RAW_IPR_MM_STAT
RAW_IPR_VA
RAW_IPR_VA_FORM
RAW_IPR_MVPTBR
RAW_IPR_DTB_IAP
RAW_IPR_DTB_IA
RAW_IPR_DTB_IS
RAW_IPR_ALT_MODE
RAW_IPR_CC
RAW_IPR_CC_CTL
RAW_IPR_MCSR
RAW_IPR_DC_FLUSH
RAW_IPR_DC_PERR_STAT
RAW_IPR_DC_TEST_CTL
RAW_IPR_DC_TEST_TAG
RAW_IPR_DC_TEST_TAG_TEMP
RAW_IPR_DC_MODE
RAW_IPR_MAF_MODE
MaxInternalProcRegs
Definition at line 41 of file ipr.hh.
enum AlphaISA::MiscRegIndex
Enumerator:
MISCREG_FPCR
MISCREG_UNIQ
MISCREG_LOCKFLAG
MISCREG_LOCKADDR
MISCREG_INTR
NUM_MISCREGS
Definition at line 63 of file registers.hh.
enum AlphaISA::MiscRegIpr
Enumerator:
MinWriteOnlyIpr
IPR_HWINT_CLR
IPR_SL_XMIT
IPR_DC_FLUSH
IPR_IC_FLUSH
IPR_ALT_MODE
IPR_DTB_IA
IPR_DTB_IAP
IPR_ITB_IA
MaxWriteOnlyIpr
IPR_ITB_IAP
MinReadOnlyIpr
IPR_INTID
IPR_SL_RCV
IPR_MM_STAT
IPR_ITB_PTE_TEMP
MaxReadOnlyIpr
IPR_DTB_PTE_TEMP
IPR_ISR
IPR_ITB_TAG
IPR_ITB_PTE
IPR_ITB_ASN
IPR_ITB_IS
IPR_SIRR
IPR_ASTRR
IPR_ASTER
IPR_EXC_ADDR
IPR_EXC_SUM
IPR_EXC_MASK
IPR_PAL_BASE
IPR_ICM
IPR_IPLR
IPR_IFAULT_VA_FORM
IPR_IVPTBR
IPR_ICSR
IPR_IC_PERR_STAT
IPR_PMCTR
IPR_PALtemp0
IPR_PALtemp1
IPR_PALtemp2
IPR_PALtemp3
IPR_PALtemp4
IPR_PALtemp5
IPR_PALtemp6
IPR_PALtemp7
IPR_PALtemp8
IPR_PALtemp9
IPR_PALtemp10
IPR_PALtemp11
IPR_PALtemp12
IPR_PALtemp13
IPR_PALtemp14
IPR_PALtemp15
IPR_PALtemp16
IPR_PALtemp17
IPR_PALtemp18
IPR_PALtemp19
IPR_PALtemp20
IPR_PALtemp21
IPR_PALtemp22
IPR_PALtemp23
IPR_DTB_ASN
IPR_DTB_CM
IPR_DTB_TAG
IPR_DTB_PTE
IPR_VA
IPR_VA_FORM
IPR_MVPTBR
IPR_DTB_IS
IPR_CC
IPR_CC_CTL
IPR_MCSR
IPR_DC_PERR_STAT
IPR_DC_TEST_CTL
IPR_DC_TEST_TAG
IPR_DC_TEST_TAG_TEMP
IPR_DC_MODE
IPR_MAF_MODE
NumInternalProcRegs
Definition at line 126 of file ipr.hh.
enum AlphaISA::mode_type
Enumerator:
mode_kernel
mode_executive
mode_supervisor
mode_user
mode_number
Definition at line 103 of file isa_traits.hh.
Function Documentation
void AlphaISA::advancePC (PCState & pc, const StaticInstPtr inst) [inline]
Definition at line 108 of file utility.hh.
References GenericISA::SimplePCState< MachInst >::advance().
Referenced by DefaultCommit< Impl >::commitInsts(), ExecutionUnit::execute(), BranchPredictor::execute(), InOrderCPU::instDone(), DefaultFetch< Impl >::lookupAndUpdateNextPC(), InOrderDynInst::mispredicted(), BaseDynInst< OzoneImpl >::mispredicted(), BPredUnit::predict(), InOrderDynInst::setSquashInfo(), FetchSeqUnit::squash(), DefaultIEW< Impl >::squashDueToBranch(), and FetchSeqUnit::updateAfterContextSwitch().
uint64_t AlphaISA::ALT_MODE_AM (uint64_t reg) [inline]
Definition at line 95 of file ev5.hh.
Referenced by AlphaISA::TLB::translateData().
PCState AlphaISA::buildRetPC (const PCState & curPC, const PCState & callPC) [inline]
Definition at line 46 of file utility.hh.
References GenericISA::SimplePCState< MachInst >::advance().
Referenced by BPredUnit::predict(), and BPredUnit::predictInOrder().
void AlphaISA::copyIprs (ThreadContext * src, ThreadContext * dest)
void AlphaISA::copyMiscRegs (ThreadContext * src, ThreadContext * dest)
Referenced by cloneFunc(), and OzoneCPU< Impl >::OzoneTC::copyArchRegs().
void AlphaISA::copyRegs (ThreadContext * src, ThreadContext * dest)
Referenced by cloneFunc(), SimpleThread::copyArchRegs(), O3ThreadContext< Impl >::copyArchRegs(), and InOrderThreadContext::copyArchRegs().
StaticInstPtr AlphaISA::decodeInst (ExtMachInst)
int AlphaISA::DTB_ASN_ASN (uint64_t reg) [inline]
Definition at line 70 of file ev5.hh.
References AsnMask.
Referenced by getExecutingAsid(), AlphaISA::TLB::translateData(), and AlphaISA::TLB::translateInst().
uint64_t AlphaISA::DTB_CM_CM (uint64_t reg) [inline]
Definition at line 96 of file ev5.hh.
Referenced by AlphaISA::TLB::translateData().
int AlphaISA::DTB_PTE_ASMA (uint64_t reg) [inline]
Definition at line 78 of file ev5.hh.
int AlphaISA::DTB_PTE_FONR (uint64_t reg) [inline]
Definition at line 75 of file ev5.hh.
int AlphaISA::DTB_PTE_FONW (uint64_t reg) [inline]
Definition at line 76 of file ev5.hh.
int AlphaISA::DTB_PTE_GH (uint64_t reg) [inline]
Definition at line 77 of file ev5.hh.
Addr AlphaISA::DTB_PTE_PPN (uint64_t reg) [inline]
Definition at line 71 of file ev5.hh.
References PAddrImplBits, PageShift, and ULL.
int AlphaISA::DTB_PTE_XRE (uint64_t reg) [inline]
Definition at line 73 of file ev5.hh.
int AlphaISA::DTB_PTE_XWE (uint64_t reg) [inline]
Definition at line 74 of file ev5.hh.
uint64_t AlphaISA::getArgument (ThreadContext * tc, int & number, uint16_t size, bool fp)
Referenced by Arguments::getArg(), and Linux::UDelayEvent::process().
uint64_t AlphaISA::getExecutingAsid (ThreadContext * tc) [inline]
Definition at line 114 of file utility.hh.
References DTB_ASN_ASN(), IPR_DTB_ASN, and ThreadContext::readMiscRegNoEffect().
Referenced by Trace::ExeTracerRecord::traceInst().
template<class TC > unsigned AlphaISA::getTargetThread (TC * tc) [inline]
Definition at line 62 of file mt.hh.
References fatal.
Referenced by InOrderDynInst::readRegOtherThread(), InOrderCPU::readRegOtherThread(), and InOrderCPU::setRegOtherThread().
template<class TC > unsigned AlphaISA::getVirtProcNum (TC * tc) [inline]
Definition at line 53 of file mt.hh.
References fatal.
Cycles AlphaISA::handleIprRead (ThreadContext * xc, Packet * pkt) [inline]
Definition at line 48 of file mmapped_ipr.hh.
References panic.
Referenced by TimingSimpleCPU::handleReadPacket(), LSQUnit< Impl >::read(), and AtomicSimpleCPU::readMem().
Cycles AlphaISA::handleIprWrite (ThreadContext * xc, Packet * pkt) [inline]
Definition at line 55 of file mmapped_ipr.hh.
References panic.
Referenced by TimingSimpleCPU::handleWritePacket(), LSQUnit< Impl >::writebackStores(), and AtomicSimpleCPU::writeMem().
template<class XC > void AlphaISA::handleLockedRead (XC * xc, Request * req) [inline]
Definition at line 90 of file locked_mem.hh.
References Request::getPaddr(), MISCREG_LOCKADDR, and MISCREG_LOCKFLAG.
Referenced by TimingSimpleCPU::completeDataAccess(), CacheUnit::processCacheCompletion(), LSQUnit< Impl >::read(), and AtomicSimpleCPU::readMem().
template<class XC > void AlphaISA::handleLockedSnoop (XC * xc, PacketPtr pkt, Addr cacheBlockMask) [inline]
Definition at line 69 of file locked_mem.hh.
References Packet::getAddr(), MISCREG_LOCKADDR, and MISCREG_LOCKFLAG.
Referenced by LSQUnit< Impl >::checkSnoop().
template<class XC > bool AlphaISA::handleLockedWrite (XC * xc, Request * req) [inline]
Definition at line 99 of file locked_mem.hh.
References Request::getPaddr(), Request::isUncacheable(), MISCREG_LOCKADDR, MISCREG_LOCKFLAG, Request::setExtraData(), and warn.
Referenced by CacheUnit::doCacheAccess(), TimingSimpleCPU::sendData(), LSQUnit< Impl >::writebackStores(), and AtomicSimpleCPU::writeMem().
uint64_t AlphaISA::ICM_CM (uint64_t reg) [inline]
Definition at line 97 of file ev5.hh.
Referenced by AlphaISA::TLB::translateInst().
bool AlphaISA::ICSR_FPE (uint64_t reg) [inline]
Definition at line 93 of file ev5.hh.
bool AlphaISA::ICSR_SDE (uint64_t reg) [inline]
Definition at line 91 of file ev5.hh.
int AlphaISA::ICSR_SPE (uint64_t reg) [inline]
Definition at line 92 of file ev5.hh.
void AlphaISA::initCPU (ThreadContext * tc, int cpuId)
Referenced by TimingSimpleCPU::init(), AtomicSimpleCPU::init(), OzoneCPU< Impl >::init(), FullO3CPU< Impl >::init(), and InOrderCPU::init().
void AlphaISA::initializeIprTable ()
Referenced by AlphaISA::ISA::params().
void AlphaISA::initIPRs (ThreadContext * tc, int cpuId)
bool AlphaISA::inUserMode (ThreadContext * tc) [inline]
Definition at line 56 of file utility.hh.
References IPR_DTB_CM, and ThreadContext::readMiscRegNoEffect().
Referenced by BaseSimpleCPU::postExecute(), and Trace::ExeTracerRecord::traceInst().
bool AlphaISA::IprIsReadable (int index) [inline]
Definition at line 227 of file ipr.hh.
bool AlphaISA::IprIsWritable (int index) [inline]
Definition at line 221 of file ipr.hh.
bool AlphaISA::IsK0Seg (Addr a) [inline]
Definition at line 84 of file utility.hh.
References K0SegBase, and K0SegEnd.
Referenced by AlphaISA::RemoteGDB::acc(), and BadAddrEvent::process().
bool AlphaISA::IsK1Seg (Addr a) [inline]
Definition at line 88 of file utility.hh.
References K1SegBase, and K1SegEnd.
bool AlphaISA::IsUSeg (Addr a) [inline]
Definition at line 81 of file utility.hh.
References USegBase, and USegEnd.
int AlphaISA::ITB_ASN_ASN (uint64_t reg) [inline]
Definition at line 80 of file ev5.hh.
References AsnMask.
bool AlphaISA::ITB_PTE_ASMA (uint64_t reg) [inline]
Definition at line 87 of file ev5.hh.
bool AlphaISA::ITB_PTE_FONR (uint64_t reg) [inline]
Definition at line 84 of file ev5.hh.
bool AlphaISA::ITB_PTE_FONW (uint64_t reg) [inline]
Definition at line 85 of file ev5.hh.
int AlphaISA::ITB_PTE_GH (uint64_t reg) [inline]
Definition at line 86 of file ev5.hh.
Addr AlphaISA::ITB_PTE_PPN (uint64_t reg) [inline]
Definition at line 81 of file ev5.hh.
References PAddrImplBits, PageShift, and ULL.
int AlphaISA::ITB_PTE_XRE (uint64_t reg) [inline]
Definition at line 83 of file ev5.hh.
Addr AlphaISA::K0Seg2Phys (Addr addr) [inline]
Definition at line 85 of file utility.hh.
References K0SegBase.
Referenced by BadAddrEvent::process().
PageTableEntry AlphaISA::kernel_pte_lookup (PortProxy & mem, Addr ptbr, VAddr vaddr)
Referenced by AlphaISA::RemoteGDB::acc().
uint64_t AlphaISA::MCSR_SP (uint64_t reg) [inline]
Definition at line 89 of file ev5.hh.
int AlphaISA::Opcode (MachInst inst) [inline]
Definition at line 105 of file ev5.hh.
Referenced by AlphaISA::DtbFault::invoke().
bool AlphaISA::PAddrIprSpace (Addr a) [inline]
Definition at line 52 of file ev5.hh.
References ULL.
Referenced by AlphaISA::TLB::checkCacheability().
bool AlphaISA::PcPAL (Addr addr) [inline]
Definition at line 69 of file utility.hh.
Referenced by AlphaISA::RemoteGDB::acc(), AlphaISA::RemoteGDB::getregs(), AlphaISA::RemoteGDB::setregs(), AlphaISA::TLB::translateData(), and AlphaISA::TLB::translateInst().
Addr AlphaISA::Phys2K0Seg (Addr addr) [inline]
Definition at line 61 of file ev5.hh.
References K0SegBase, PAddrUncachedBit40, PAddrUncachedBit43, and PAddrUncachedMask.
Referenced by AlphaSystem::setAlphaAccess().
Addr AlphaISA::PteAddr (Addr a) [inline]
Definition at line 78 of file utility.hh.
References PteMask, and PteShift.
Referenced by AlphaISA::VAddr::level1(), AlphaISA::VAddr::level2(), and AlphaISA::VAddr::level3().
int AlphaISA::Ra (MachInst inst) [inline]
Definition at line 106 of file ev5.hh.
Referenced by AlphaISA::DtbFault::invoke().
Addr AlphaISA::RoundPage (Addr addr) [inline]
Definition at line 95 of file utility.hh.
References PageBytes.
Referenced by AlphaISA::RemoteGDB::acc().
void AlphaISA::skipFunction (ThreadContext * tc)
Referenced by SkipFuncEvent::process().
void AlphaISA::startupCPU (ThreadContext * tc, int cpuId) [inline]
Definition at line 70 of file utility.hh.
References ThreadContext::activate().
Referenced by System::initState().
Addr AlphaISA::TruncPage (Addr addr) [inline]
Definition at line 91 of file utility.hh.
References PageBytes.
Referenced by AlphaISA::RemoteGDB::acc().
Addr AlphaISA::VAddrImpl (Addr a) [inline]
Definition at line 46 of file ev5.hh.
References VAddrImplMask.
Addr AlphaISA::VAddrOffset (Addr a) [inline]
Definition at line 48 of file ev5.hh.
References PageOffset.
Addr AlphaISA::VAddrSpaceEV5 (Addr a) [inline]
Definition at line 49 of file ev5.hh.
Addr AlphaISA::VAddrSpaceEV6 (Addr a) [inline]
Definition at line 50 of file ev5.hh.
Referenced by AlphaISA::TLB::translateData(), and AlphaISA::TLB::translateInst().
Addr AlphaISA::VAddrVPN (Addr a) [inline]
Definition at line 47 of file ev5.hh.
References PageShift.
Addr AlphaISA::vtophys (ThreadContext * tc, Addr addr)
Definition at line 66 of file vtophys.cc.
Addr AlphaISA::vtophys (Addr vaddr)
Definition at line 60 of file vtophys.cc.
Referenced by OzoneCPU< Impl >::dbg_vtophys(), CheckerCPU::dbg_vtophys(), BaseSimpleCPU::dbg_vtophys(), FSTranslatingPortProxy::memsetBlob(), FSTranslatingPortProxy::readBlob(), Sinic::Device::write(), and FSTranslatingPortProxy::writeBlob().
template<class CPU > void AlphaISA::zeroRegisters (CPU * cpu)
Definition at line 66 of file ev5.cc.
References ZeroReg.
template<class TC > void AlphaISA::zeroRegisters (TC * tc)
Function to insure ISA semantics about 0 registers.
Parameters:
tc The thread context.
Variable Documentation
const uint64_t AlphaISA::AsnMask = ULL(0xff)
Definition at line 42 of file ev5.hh.
Referenced by DTB_ASN_ASN(), and ITB_ASN_ASN().
int AlphaISA::break_ipl = -1
Definition at line 199 of file ev5.cc.
const bool AlphaISA::CurThreadInfoImplemented = true
Definition at line 133 of file isa_traits.hh.
Referenced by Linux::ThreadInfo::curThreadInfo().
const int AlphaISA::CurThreadInfoReg = AlphaISA::IPR_PALtemp23
Definition at line 134 of file isa_traits.hh.
Referenced by Linux::ThreadInfo::curThreadInfo().
const RegIndex AlphaISA::FirstArgumentReg = 16
Definition at line 84 of file registers.hh.
const RegIndex AlphaISA::FramePointerReg = 15
Definition at line 81 of file registers.hh.
const RegIndex AlphaISA::GlobalPointerReg = 29
Definition at line 77 of file registers.hh.
Referenced by AlphaLiveProcess::initState().
const bool AlphaISA::HasUnalignedMemAcc = false
Definition at line 131 of file isa_traits.hh.
Referenced by LSQUnit< Impl >::completeDataAccess(), BaseDynInst< Impl >::initiateTranslation(), LSQUnit< Impl >::read(), BaseDynInst< Impl >::readMem(), LSQUnit< Impl >::recvRetry(), LSQUnit< Impl >::squash(), LSQUnit< Impl >::write(), LSQUnit< Impl >::writebackStores(), and BaseDynInst< Impl >::writeMem().
int AlphaISA::IprToMiscRegIndex
Definition at line 126 of file ipr.cc.
const Addr AlphaISA::K0SegBase = ULL(0xfffffc0000000000)
Definition at line 71 of file isa_traits.hh.
Referenced by AlphaISA::RemoteGDB::acc(), IsK0Seg(), K0Seg2Phys(), and Phys2K0Seg().
const Addr AlphaISA::K0SegEnd = ULL(0xfffffdffffffffff)
Definition at line 72 of file isa_traits.hh.
Referenced by IsK0Seg().
const Addr AlphaISA::K1SegBase = ULL(0xfffffe0000000000)
Definition at line 75 of file isa_traits.hh.
Referenced by IsK1Seg().
const Addr AlphaISA::K1SegEnd = ULL(0xffffffffffffffff)
Definition at line 76 of file isa_traits.hh.
Referenced by IsK1Seg().
const int AlphaISA::MaxMiscDestRegs = AlphaISAInst::MaxMiscDestRegs + 1
Definition at line 44 of file registers.hh.
Referenced by BaseO3DynInst< Impl >::setMiscReg().
md_ipr_names AlphaISA::MiscRegIndexToIpr
Definition at line 38 of file ipr.cc.
const uint64_t AlphaISA::MM_STAT_ACV_MASK = ULL(0x0002)
Definition at line 103 of file ev5.hh.
Referenced by AlphaISA::TLB::translateData().
const uint64_t AlphaISA::MM_STAT_BAD_VA_MASK = ULL(0x0020)
Definition at line 99 of file ev5.hh.
Referenced by AlphaISA::TLB::translateData().
const uint64_t AlphaISA::MM_STAT_DTB_MISS_MASK = ULL(0x0010)
Definition at line 100 of file ev5.hh.
Referenced by AlphaISA::TLB::translateData().
const uint64_t AlphaISA::MM_STAT_FONR_MASK = ULL(0x0004)
Definition at line 102 of file ev5.hh.
Referenced by AlphaISA::TLB::translateData().
const uint64_t AlphaISA::MM_STAT_FONW_MASK = ULL(0x0008)
Definition at line 101 of file ev5.hh.
Referenced by AlphaISA::TLB::translateData().
const uint64_t AlphaISA::MM_STAT_WR_MASK = ULL(0x0001)
Definition at line 104 of file ev5.hh.
Referenced by AlphaISA::TLB::translateData().
const ExtMachInst AlphaISA::NoopMachInst = 0x2ffe0000
Definition at line 128 of file isa_traits.hh.
Referenced by DefaultFetch< Impl >::finishTranslation(), and FrontEnd< Impl >::handleFault().
const Addr AlphaISA::NPtePage = ULL(1) << NPtePageShift
Definition at line 63 of file isa_traits.hh.
const Addr AlphaISA::NPtePageShift = PageShift - PteShift
Definition at line 62 of file isa_traits.hh.
Referenced by AlphaISA::VAddr::level1(), and AlphaISA::VAddr::level2().
const int AlphaISA::NumFloatArchRegs = 32
Definition at line 90 of file registers.hh.
Referenced by AlphaISA::RemoteGDB::getregs(), and AlphaISA::RemoteGDB::setregs().
const int AlphaISA::NumFloatRegs = NumFloatArchRegs
Definition at line 94 of file registers.hh.
Referenced by FullO3CPU< Impl >::activateWhenReady(), ThreadContext::compare(), OzoneCPU< Impl >::OzoneTC::copyArchRegs(), Trace::LegionTraceRecord::dump(), FullO3CPU< Impl >::FullO3CPU(), FullO3CPU< Impl >::insertThread(), SimpleThread::readFloatReg(), SimpleThread::readFloatRegBits(), RegDepMap::RegDepMap(), FullO3CPU< Impl >::removeThread(), DefaultRename< Impl >::renameDestRegs(), DefaultRename< Impl >::renameSrcRegs(), serialize(), SimpleThread::setFloatReg(), SimpleThread::setFloatRegBits(), and unserialize().
const int AlphaISA::NumIntArchRegs = 32
Definition at line 88 of file registers.hh.
Referenced by cloneFunc(), Trace::LegionTraceRecord::dump(), Sparc64LiveProcess::flushWindows(), Sparc32LiveProcess::flushWindows(), AlphaISA::RemoteGDB::getregs(), SparcLiveProcess::initState(), AlphaISA::RemoteGDB::setregs(), and SparcLiveProcess::setSyscallReturn().
const int AlphaISA::NumIntRegs = NumIntArchRegs + NumPALShadowRegs
Definition at line 93 of file registers.hh.
Referenced by FullO3CPU< Impl >::activateWhenReady(), ThreadContext::compare(), OzoneCPU< Impl >::OzoneTC::copyArchRegs(), FullO3CPU< Impl >::FullO3CPU(), FullO3CPU< Impl >::insertThread(), FullO3CPU< Impl >::readArchFloatReg(), FullO3CPU< Impl >::readArchFloatRegInt(), SimpleThread::readIntReg(), RegDepMap::RegDepMap(), FullO3CPU< Impl >::removeThread(), DefaultRename< Impl >::renameDestRegs(), DefaultRename< Impl >::renameSrcRegs(), serialize(), FullO3CPU< Impl >::setArchFloatReg(), FullO3CPU< Impl >::setArchFloatRegInt(), SimpleThread::setIntReg(), and unserialize().
const int AlphaISA::NumMiscArchRegs = NUM_MISCREGS
Definition at line 91 of file registers.hh.
const int AlphaISA::NumMiscRegs = NumMiscArchRegs
Definition at line 95 of file registers.hh.
Referenced by ThreadContext::compare(), FullO3CPU< Impl >::FullO3CPU(), and RegDepMap::RegDepMap().
const int AlphaISA::NumPALShadowRegs = 8
Definition at line 89 of file registers.hh.
const int AlphaISA::PAddrImplBits = 44
Definition at line 53 of file ev5.hh.
Referenced by DTB_PTE_PPN(), and ITB_PTE_PPN().
const Addr AlphaISA::PAddrImplMask = (ULL(1) << PAddrImplBits) - 1
Definition at line 54 of file ev5.hh.
Referenced by BadAddrEvent::process(), AlphaISA::TLB::translateData(), and AlphaISA::TLB::translateInst().
const Addr AlphaISA::PAddrUncachedBit39 = ULL(0x8000000000)
Definition at line 55 of file ev5.hh.
const Addr AlphaISA::PAddrUncachedBit40 = ULL(0x10000000000)
Definition at line 56 of file ev5.hh.
Referenced by Phys2K0Seg(), AlphaISA::TLB::translateData(), and AlphaISA::TLB::translateInst().
const Addr AlphaISA::PAddrUncachedBit43 = ULL(0x80000000000)
Definition at line 57 of file ev5.hh.
Referenced by AlphaISA::TLB::checkCacheability(), and Phys2K0Seg().
const Addr AlphaISA::PAddrUncachedMask = ULL(0x807ffffffff)
Definition at line 58 of file ev5.hh.
Referenced by AlphaISA::TLB::checkCacheability(), and Phys2K0Seg().
const Addr AlphaISA::PageBytes = ULL(1) << PageShift
Definition at line 52 of file isa_traits.hh.
Referenced by AbstractMemory::AbstractMemory(), AlphaISA::RemoteGDB::acc(), CopyStringIn(), IdeDisk::doDmaRead(), IdeDisk::doDmaWrite(), Process::fixupStackFault(), DecodeCache::AddrMap< StaticInstPtr >::getPage(), ArmLinuxProcess::initState(), DecodeCache::AddrMap< StaticInstPtr >::lookup(), FSTranslatingPortProxy::memsetBlob(), FSTranslatingPortProxy::readBlob(), RoundPage(), TruncPage(), and FSTranslatingPortProxy::writeBlob().
const Addr AlphaISA::PageMask = ~(PageBytes - 1)
Definition at line 53 of file isa_traits.hh.
Referenced by AlphaISA::VAddr::page().
const Addr AlphaISA::PageOffset = PageBytes - 1
Definition at line 54 of file isa_traits.hh.
Referenced by AlphaISA::VAddr::offset(), and VAddrOffset().
const Addr AlphaISA::PageShift = 13
Definition at line 51 of file isa_traits.hh.
Referenced by DTB_PTE_PPN(), ITB_PTE_PPN(), AlphaISA::VAddr::level1(), AlphaISA::VAddr::level2(), AlphaISA::VAddr::level3(), AlphaISA::PageTableEntry::paddr(), AlphaISA::TlbEntry::pageStart(), AlphaISA::TLB::translateData(), AlphaISA::TLB::translateInst(), VAddrVPN(), and AlphaISA::VAddr::vpn().
const Addr AlphaISA::PalBase = 0x4000
Definition at line 108 of file ev5.hh.
const Addr AlphaISA::PalMax = 0x10000
Definition at line 109 of file ev5.hh.
const RegIndex AlphaISA::ProcedureValueReg = 27
Definition at line 78 of file registers.hh.
const Addr AlphaISA::PteMask = NPtePage - 1
Definition at line 64 of file isa_traits.hh.
Referenced by PteAddr().
const Addr AlphaISA::PteShift = 3
Definition at line 61 of file isa_traits.hh.
Referenced by PteAddr().
const int AlphaISA::reg_redir
Initial value:
 {
     0, 1, 2, 3, 4, 5, 6, 7,
     32, 33, 34, 35, 36, 37, 38, 15,
     16, 17, 18, 19, 20, 21, 22, 23,
     24, 39, 26, 27, 28, 29, 30, 31 }
Definition at line 36 of file regredir.cc.
Referenced by AlphaISA::RemoteGDB::getregs(), and AlphaISA::RemoteGDB::setregs().
const RegIndex AlphaISA::ReturnAddressReg = 26
Definition at line 79 of file registers.hh.
Referenced by AlphaISA::StackTrace::decodePrologue().
const RegIndex AlphaISA::ReturnValueReg = 0
Definition at line 80 of file registers.hh.
Referenced by cloneFunc(), BadAddrEvent::process(), SparcLiveProcess::setSyscallReturn(), PowerLiveProcess::setSyscallReturn(), MipsLiveProcess::setSyscallReturn(), ArmLiveProcess::setSyscallReturn(), and AlphaLiveProcess::setSyscallReturn().
const RegIndex AlphaISA::StackPointerReg = 30
Definition at line 76 of file registers.hh.
Referenced by SparcLiveProcess::argsInit(), PowerLiveProcess::argsInit(), MipsLiveProcess::argsInit(), ArmLiveProcess::argsInit(), AlphaLiveProcess::argsInit(), cloneFunc(), Sparc64LiveProcess::flushWindows(), Sparc32LiveProcess::flushWindows(), Tru64::init_thread_context(), and AlphaISA::StackTrace::trace().
const RegIndex AlphaISA::SyscallNumReg = 0
Definition at line 83 of file registers.hh.
const RegIndex AlphaISA::SyscallPseudoReturnReg = 20
Definition at line 85 of file registers.hh.
Referenced by cloneFunc(), getgidPseudoFunc(), getpidFunc(), getpidPseudoFunc(), getuidPseudoFunc(), and pipePseudoFunc().
const RegIndex AlphaISA::SyscallSuccessReg = 19
Definition at line 86 of file registers.hh.
Referenced by cloneFunc(), MipsLiveProcess::setSyscallReturn(), and AlphaLiveProcess::setSyscallReturn().
const int AlphaISA::TotalDataRegs = NumIntRegs + NumFloatRegs
Definition at line 100 of file registers.hh.
const int AlphaISA::TotalNumRegs
Initial value:
    NumIntRegs + NumFloatRegs + NumMiscRegs
Definition at line 97 of file registers.hh.
Referenced by RenameTable< Impl >::copyFrom(), OzoneCPU< Impl >::OzoneCPU(), RenameTable< Impl >::RenameTable(), OzoneCPU< Impl >::signalSwitched(), and OzoneCPU< Impl >::takeOverFrom().
const Addr AlphaISA::USegBase = ULL(0x0)
Definition at line 67 of file isa_traits.hh.
Referenced by IsUSeg().
const Addr AlphaISA::USegEnd = ULL(0x000003ffffffffff)
Definition at line 68 of file isa_traits.hh.
Referenced by IsUSeg().
const int AlphaISA::VAddrImplBits = 43
Definition at line 43 of file ev5.hh.
const Addr AlphaISA::VAddrImplMask = (ULL(1) << VAddrImplBits) - 1
Definition at line 44 of file ev5.hh.
Referenced by VAddrImpl().
const Addr AlphaISA::VAddrUnImplMask = ~VAddrImplMask
Definition at line 45 of file ev5.hh.
Referenced by AlphaISA::TLB::validVirtualAddress().
const RegIndex AlphaISA::ZeroReg = 31
Definition at line 74 of file registers.hh.
Referenced by SimpleFreeList::addReg(), UseDefUnit::execute(), FullO3CPU< Impl >::FullO3CPU(), RegDepMap::insert(), BaseSimpleCPU::preExecute(), RegDepMap::remove(), PhysRegFile< Impl >::setFloatReg(), PhysRegFile< Impl >::setIntReg(), InOrderCPU::setIntReg(), OzoneCPU< Impl >::tick(), Checker< Impl >::verify(), and zeroRegisters().