gem5: AmbaDev Namespace Reference
AmbaDev Namespace Reference
Functions
bool readId (PacketPtr pkt, uint64_t amba_id, Addr pio_addr)
Variables
const int AMBA_PER_ID0 = 0xFE0
const int AMBA_PER_ID1 = 0xFE4
const int AMBA_PER_ID2 = 0xFE8
const int AMBA_PER_ID3 = 0xFEC
const int AMBA_CEL_ID0 = 0xFF0
const int AMBA_CEL_ID1 = 0xFF4
const int AMBA_CEL_ID2 = 0xFF8
const int AMBA_CEL_ID3 = 0xFFC
Function Documentation
bool AmbaDev::readId (PacketPtr pkt, uint64_t amba_id, Addr pio_addr)
Referenced by Sp804::read(), PL031::read(), Pl111::read(), Pl011::read(), Pl050::read(), AmbaFake::read(), Sp804::write(), and PL031::write().
Variable Documentation
const int AmbaDev::AMBA_CEL_ID0 = 0xFF0
Definition at line 67 of file amba_device.hh.
const int AmbaDev::AMBA_CEL_ID1 = 0xFF4
Definition at line 68 of file amba_device.hh.
const int AmbaDev::AMBA_CEL_ID2 = 0xFF8
Definition at line 69 of file amba_device.hh.
const int AmbaDev::AMBA_CEL_ID3 = 0xFFC
Definition at line 70 of file amba_device.hh.
const int AmbaDev::AMBA_PER_ID0 = 0xFE0
Definition at line 63 of file amba_device.hh.
const int AmbaDev::AMBA_PER_ID1 = 0xFE4
Definition at line 64 of file amba_device.hh.
const int AmbaDev::AMBA_PER_ID2 = 0xFE8
Definition at line 65 of file amba_device.hh.
const int AmbaDev::AMBA_PER_ID3 = 0xFEC
Definition at line 66 of file amba_device.hh.