gem5: m5::stl_helpers Namespace Reference
m5::stl_helpers Namespace Reference
Classes
class ContainerPrint
Functions
template<typename T >
void deletePointer (T &ptr)
template<template< typename T, typename A > class C, typename T , typename A >
void deletePointers (C< T, A > &container)
template<template< typename T, typename A > class C, typename T , typename A >
std::ostream & operator<< (std::ostream &out, const C< T, A > &vec)
Function Documentation
template<typename T > void m5::stl_helpers::deletePointer (T & ptr)
Definition at line 42 of file stl_helpers.hh.
template<template< typename T, typename A > class C, typename T , typename A > void m5::stl_helpers::deletePointers (C< T, A > & container)
Definition at line 77 of file stl_helpers.hh.
Referenced by GarnetNetwork::~GarnetNetwork(), GarnetNetwork_d::~GarnetNetwork_d(), InputUnit_d::~InputUnit_d(), NetworkInterface::~NetworkInterface(), NetworkInterface_d::~NetworkInterface_d(), OutputUnit_d::~OutputUnit_d(), Router::~Router(), Router_d::~Router_d(), SimpleNetwork::~SimpleNetwork(), Switch::~Switch(), and Switch_d::~Switch_d().
template<template< typename T, typename A > class C, typename T , typename A > std::ostream& m5::stl_helpers::operator<< (std::ostream & out, const C< T, A > & vec)
Definition at line 86 of file stl_helpers.hh.