gem5: base/loader/object_file.cc File Reference
base/loader/object_file.cc File Reference
#include <sys/mman.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <cstdio>
#include <list>
#include <string>
#include "base/loader/aout_object.hh"
#include "base/loader/dtb_object.hh"
#include "base/loader/ecoff_object.hh"
#include "base/loader/elf_object.hh"
#include "base/loader/object_file.hh"
#include "base/loader/raw_object.hh"
#include "base/loader/symtab.hh"
#include "base/cprintf.hh"
#include "mem/port_proxy.hh"
Functions
ObjectFile * createObjectFile (const string &fname, bool raw)
Function Documentation
ObjectFile* createObjectFile (const string & fname, bool raw)
Definition at line 110 of file object_file.cc.
References ArmISA::fd, ArmISA::len, RawObject::tryFile(), DtbObject::tryFile(), ElfObject::tryFile(), AoutObject::tryFile(), and EcoffObject::tryFile().
Referenced by AlphaSystem::AlphaSystem(), ArmSystem::ArmSystem(), LiveProcess::create(), LinuxArmSystem::initState(), main(), and SparcSystem::SparcSystem().