gem5: python/swig/pyobject.hh File Reference
python/swig/pyobject.hh File Reference
#include <Python.h>
#include "base/types.hh"
#include "dev/etherint.hh"
#include "sim/serialize.hh"
#include "sim/sim_object.hh"
Functions
SimObject * convertSwigSimObjectPtr (PyObject *)
SimObject * resolveSimObject (const std::string &name)
EtherInt * lookupEthPort (SimObject *so, const std::string &name, int i)
int connectPorts (SimObject *o1, const std::string &name1, int i1, SimObject *o2, const std::string &name2, int i2)
Connect the described MemObject ports.
void serializeAll (const std::string &cpt_dir)
Checkpoint * getCheckpoint (const std::string &cpt_dir)
void unserializeGlobals (Checkpoint *cp)
Function Documentation
int connectPorts (SimObject * o1, const std::string & name1, int i1, SimObject * o2, const std::string & name2, int i2)
Connect the described MemObject ports.
Called from Python via SWIG.
Called from Python via SWIG. The indices i1 & i2 will be -1 for regular ports, >= 0 for vector ports. SimObject1 is the master, and SimObject2 is the slave
Definition at line 71 of file pyobject.cc.
References BaseMasterPort::bind(), FullSystem, MemObject::getMasterPort(), MemObject::getSlavePort(), lookupEthPort(), SimObject::name(), panic, and EtherInt::setPeer().
SimObject* convertSwigSimObjectPtr (PyObject *)
Checkpoint* getCheckpoint (const std::string & cpt_dir) [inline]
Definition at line 57 of file pyobject.hh.
EtherInt* lookupEthPort (SimObject * so, const std::string & name, int i)
Definition at line 48 of file pyobject.cc.
References MipsISA::ed, EtherDevice::getEthPort(), EtherObject::getEthPort(), SimObject::name(), MipsISA::p, and warn.
Referenced by connectPorts().
SimObject* resolveSimObject (const std::string & name)
void serializeAll (const std::string & cpt_dir) [inline]
Definition at line 51 of file pyobject.hh.
References Serializable::serializeAll().
void unserializeGlobals (Checkpoint * cp) [inline]
Definition at line 63 of file pyobject.hh.
References Serializable::unserializeGlobals().