gem5: base/refcnt.hh File Reference
base/refcnt.hh File Reference
Classes for managing reference counted objects.
Classes
class RefCounted
Derive from RefCounted if you want to enable reference counting of this class.
class RefCountingPtr< T >
If you want a reference counting pointer to a mutable object, create it like this:
Functions
template<class T >
bool operator== (const RefCountingPtr< T > &l, const RefCountingPtr< T > &r)
Check for equality of two reference counting pointers.
template<class T >
bool operator== (const RefCountingPtr< T > &l, const T *r)
Check for equality of of a reference counting pointers and a regular pointer.
template<class T >
bool operator== (const T *l, const RefCountingPtr< T > &r)
Check for equality of of a reference counting pointers and a regular pointer.
template<class T >
bool operator!= (const RefCountingPtr< T > &l, const RefCountingPtr< T > &r)
Check for inequality of two reference counting pointers.
template<class T >
bool operator!= (const RefCountingPtr< T > &l, const T *r)
Check for inequality of of a reference counting pointers and a regular pointer.
template<class T >
bool operator!= (const T *l, const RefCountingPtr< T > &r)
Check for inequality of of a reference counting pointers and a regular pointer.
Detailed Description
Classes for managing reference counted objects.
Definition in file refcnt.hh.
Function Documentation
template<class T > bool operator!= (const RefCountingPtr< T > & l, const RefCountingPtr< T > & r) [inline]
Check for inequality of two reference counting pointers.
Definition at line 215 of file refcnt.hh.
References RefCountingPtr< T >::get().
Referenced by ArmISA::EndBitUnion().
template<class T > bool operator!= (const RefCountingPtr< T > & l, const T * r) [inline]
Check for inequality of of a reference counting pointers and a regular pointer.
Definition at line 221 of file refcnt.hh.
References RefCountingPtr< T >::get().
template<class T > bool operator!= (const T * l, const RefCountingPtr< T > & r) [inline]
Check for inequality of of a reference counting pointers and a regular pointer.
Definition at line 227 of file refcnt.hh.
References RefCountingPtr< T >::get().
template<class T > bool operator== (const RefCountingPtr< T > & l, const T * r) [inline]
Check for equality of of a reference counting pointers and a regular pointer.
Definition at line 204 of file refcnt.hh.
References RefCountingPtr< T >::get().
template<class T > bool operator== (const RefCountingPtr< T > & l, const RefCountingPtr< T > & r) [inline]
Check for equality of two reference counting pointers.
Definition at line 198 of file refcnt.hh.
References RefCountingPtr< T >::get().
template<class T > bool operator== (const T * l, const RefCountingPtr< T > & r) [inline]
Check for equality of of a reference counting pointers and a regular pointer.
Definition at line 210 of file refcnt.hh.
References RefCountingPtr< T >::get().