gem5: mem/ruby/slicc_interface/RubySlicc_Profiler_interface.hh File Reference
mem/ruby/slicc_interface/RubySlicc_Profiler_interface.hh File Reference
#include <string>
#include "mem/protocol/AccessType.hh"
#include "mem/ruby/common/Address.hh"
#include "mem/ruby/common/Global.hh"
#include "mem/ruby/profiler/Profiler.hh"
Functions
void profile_outstanding_persistent_request (int outstanding)
void profile_outstanding_request (int outstanding)
void profile_sharing (const Address &addr, AccessType type, NodeID requestor, const Set &sharers, const Set &owner)
void profile_miss (const RubyRequest &msg, NodeID id)
void profile_token_retry (const Address &addr, AccessType type, int count)
void profile_filter_action (int action)
void profile_persistent_prediction (const Address &addr, AccessType type)
void profile_average_latency_estimate (int latency)
void profile_multicast_retry (const Address &addr, int count)
void profileGetX (const Address &datablock, const Address &PC, const Set &owner, const Set &sharers, NodeID requestor)
void profileGetS (const Address &datablock, const Address &PC, const Set &owner, const Set &sharers, NodeID requestor)
void profileOverflow (const Address &addr, MachineID mach)
Function Documentation
void profile_average_latency_estimate (int latency)
Definition at line 45 of file RubySlicc_Profiler_interface.cc.
References g_system_ptr, RubySystem::getProfiler(), and Profiler::profileAverageLatencyEstimate().
void profile_filter_action (int action)
void profile_miss (const RubyRequest & msg, NodeID id)
void profile_multicast_retry (const Address & addr, int count)
void profile_outstanding_persistent_request (int outstanding)
void profile_outstanding_request (int outstanding)
Definition at line 39 of file RubySlicc_Profiler_interface.cc.
References g_system_ptr, RubySystem::getProfiler(), and Profiler::profileOutstandingRequest().
void profile_persistent_prediction (const Address & addr, AccessType type)
void profile_sharing (const Address & addr, AccessType type, NodeID requestor, const Set & sharers, const Set & owner)
Definition at line 51 of file RubySlicc_Profiler_interface.cc.
References g_system_ptr, and RubySystem::getProfiler().
void profile_token_retry (const Address & addr, AccessType type, int count)
void profileGetS (const Address & datablock, const Address & PC, const Set & owner, const Set & sharers, NodeID requestor)
Definition at line 67 of file RubySlicc_Profiler_interface.cc.
References g_system_ptr, Profiler::getAddressProfiler(), RubySystem::getProfiler(), and profileGetS().
Referenced by profileGetS().
void profileGetX (const Address & datablock, const Address & PC, const Set & owner, const Set & sharers, NodeID requestor)
Definition at line 59 of file RubySlicc_Profiler_interface.cc.
References g_system_ptr, Profiler::getAddressProfiler(), RubySystem::getProfiler(), and profileGetX().
Referenced by profileGetX().
void profileOverflow (const Address & addr, MachineID mach)