gem5: mem/ruby/slicc_interface/RubySlicc_Util.hh File Reference
mem/ruby/slicc_interface/RubySlicc_Util.hh File Reference
#include <cassert>
#include "debug/RubySlicc.hh"
#include "mem/ruby/common/Address.hh"
#include "mem/ruby/slicc_interface/RubySlicc_ComponentMapping.hh"
#include "mem/packet.hh"
Functions
int random (int n)
Cycles zero_time ()
Cycles TimeToCycles (Time t)
NodeID intToID (int nodenum)
int IDToInt (NodeID id)
Address setOffset (Address addr, int offset)
Address makeLineAddress (Address addr)
int addressOffset (Address addr)
int mod (int val, int mod)
int max_tokens ()
bool testAndRead (Address addr, DataBlock &blk, Packet *pkt)
This function accepts an address, a data block and a packet.
bool testAndWrite (Address addr, DataBlock &blk, Packet *pkt)
This function accepts an address, a data block and a packet.
Function Documentation
int addressOffset (Address addr) [inline]
Definition at line 85 of file RubySlicc_Util.hh.
References Address::getOffset().
int IDToInt (NodeID id) [inline]
Definition at line 60 of file RubySlicc_Util.hh.
NodeID intToID (int nodenum) [inline]
Definition at line 53 of file RubySlicc_Util.hh.
Address makeLineAddress (Address addr) [inline]
Definition at line 77 of file RubySlicc_Util.hh.
References Address::makeLineAddress().
int max_tokens () [inline]
Definition at line 96 of file RubySlicc_Util.hh.
int mod (int val, int mod) [inline]
Definition at line 91 of file RubySlicc_Util.hh.
int random (int n) [inline]
Definition at line 44 of file RubySlicc_Util.hh.
Referenced by Set::addRandom(), NetDest::addRandom(), Check::Check(), RubyMemoryControl::executeCycle(), NetworkTest::generatePkt(), CheckTable::getRandomCheck(), Check::initiate(), SeriesRequestGenerator::initiate(), Check::initiateAction(), Check::initiateCheck(), Check::initiateFlush(), Check::initiatePrefetch(), Check::pickInitiatingNode(), Check::pickValue(), RubyMemoryControl::queueReady(), random_time(), StatTest::run(), NetworkTest::tick(), MemTest::tick(), and PerfectSwitch::wakeup().
Address setOffset (Address addr, int offset) [inline]
Definition at line 68 of file RubySlicc_Util.hh.
References Address::setOffset().
bool testAndRead (Address addr, DataBlock & blk, Packet * pkt) [inline]
This function accepts an address, a data block and a packet.
If the address range for the data block contains the address which the packet needs to read, then the data from the data block is written to the packet. True is returned if the data block was read, otherwise false is returned.
Definition at line 108 of file RubySlicc_Util.hh.
References Packet::getAddr(), Address::getAddress(), DataBlock::getByte(), Packet::getPtr(), Packet::getSize(), ArmISA::i, and Address::makeLineAddress().
bool testAndWrite (Address addr, DataBlock & blk, Packet * pkt) [inline]
This function accepts an address, a data block and a packet.
If the address range for the data block contains the address which the packet needs to write, then the data from the packet is written to the data block. True is returned if the data block was written, otherwise false is returned.
Definition at line 136 of file RubySlicc_Util.hh.
References Packet::getAddr(), Address::getAddress(), Packet::getPtr(), Packet::getSize(), ArmISA::i, Address::makeLineAddress(), and DataBlock::setByte().
Cycles TimeToCycles (Time t) [inline]
Definition at line 50 of file RubySlicc_Util.hh.
Cycles zero_time () [inline]
Definition at line 49 of file RubySlicc_Util.hh.