gem5: mem/ruby/slicc_interface/RubySlicc_Profiler_interface.cc File Reference
mem/ruby/slicc_interface/RubySlicc_Profiler_interface.cc File Reference
#include "mem/ruby/common/Global.hh"
#include "mem/ruby/profiler/AddressProfiler.hh"
#include "mem/ruby/profiler/Profiler.hh"
#include "mem/ruby/slicc_interface/RubySlicc_ComponentMapping.hh"
#include "mem/ruby/slicc_interface/RubySlicc_Profiler_interface.hh"
#include "mem/ruby/system/System.hh"
Functions
void profile_outstanding_request (int outstanding)
void profile_average_latency_estimate (int latency)
void profile_sharing (const Address &addr, AccessType type, NodeID requestor, const Set &sharers, const Set &owner)
void profileGetX (const Address &datablock, const Address &PC, const Set &owner, const Set &sharers, NodeID requestor)
void profileGetS (const Address &datablock, const Address &PC, const Set &owner, const Set &sharers, NodeID requestor)
Function Documentation
void profile_average_latency_estimate (int latency)
Definition at line 45 of file RubySlicc_Profiler_interface.cc.
References g_system_ptr, RubySystem::getProfiler(), and Profiler::profileAverageLatencyEstimate().
void profile_outstanding_request (int outstanding)
Definition at line 39 of file RubySlicc_Profiler_interface.cc.
References g_system_ptr, RubySystem::getProfiler(), and Profiler::profileOutstandingRequest().
void profile_sharing (const Address & addr, AccessType type, NodeID requestor, const Set & sharers, const Set & owner)
Definition at line 51 of file RubySlicc_Profiler_interface.cc.
References g_system_ptr, and RubySystem::getProfiler().
void profileGetS (const Address & datablock, const Address & PC, const Set & owner, const Set & sharers, NodeID requestor)
Definition at line 67 of file RubySlicc_Profiler_interface.cc.
References g_system_ptr, Profiler::getAddressProfiler(), RubySystem::getProfiler(), and profileGetS().
Referenced by profileGetS().
void profileGetX (const Address & datablock, const Address & PC, const Set & owner, const Set & sharers, NodeID requestor)
Definition at line 59 of file RubySlicc_Profiler_interface.cc.
References g_system_ptr, Profiler::getAddressProfiler(), RubySystem::getProfiler(), and profileGetX().
Referenced by profileGetX().