gem5: sim/debug.cc File Reference
sim/debug.cc File Reference
#include <Python.h>
#include <string>
#include <vector>
#include "base/debug.hh"
#include "sim/debug.hh"
#include "sim/eventq_impl.hh"
#include "sim/sim_events.hh"
#include "sim/sim_exit.hh"
Classes
struct DebugBreakEvent
Functions
void schedBreakCycle (Tick when)
Cause the simulator to execute a breakpoint.
void takeCheckpoint (Tick when)
Function to cause the simulator to take a checkpoint from the debugger.
void eventqDump ()
Dump all the events currently on the event queue.
void py_interact ()
int getRemoteGDBPort ()
void setRemoteGDBPort (int port)
Variables
int remote_gdb_base_port = 7000
Function Documentation
void eventqDump ()
Dump all the events currently on the event queue.
Definition at line 103 of file debug.cc.
References EventQueue::dump(), mainEventQueue, and warn.
int getRemoteGDBPort ()
Definition at line 128 of file debug.cc.
References remote_gdb_base_port.
Referenced by System::registerThreadContext().
void py_interact ()
Definition at line 110 of file debug.cc.
References globals.
void schedBreakCycle (Tick when)
Cause the simulator to execute a breakpoint.
Parameters:
when the cycle to break
Definition at line 85 of file debug.cc.
References mainEventQueue, EventQueue::schedule(), and warn.
void setRemoteGDBPort (int port)
Definition at line 136 of file debug.cc.
References remote_gdb_base_port.
void takeCheckpoint (Tick when)
Function to cause the simulator to take a checkpoint from the debugger.
Cause the simulator to return to python to create a checkpoint.
Definition at line 95 of file debug.cc.
References curTick(), and exitSimLoop().
Variable Documentation
int remote_gdb_base_port = 7000
Definition at line 125 of file debug.cc.
Referenced by getRemoteGDBPort(), and setRemoteGDBPort().