gem5: sim/simulate.cc File Reference
sim/simulate.cc File Reference
#include "base/misc.hh"
#include "base/pollevent.hh"
#include "base/types.hh"
#include "sim/async.hh"
#include "sim/eventq_impl.hh"
#include "sim/sim_events.hh"
#include "sim/sim_exit.hh"
#include "sim/simulate.hh"
#include "sim/stat_control.hh"
Functions
SimLoopExitEvent * simulate (Tick num_cycles)
Variables
Tick lastExitTick = 0
Simulate for num_cycles additional cycles.
Function Documentation
SimLoopExitEvent* simulate (Tick num_cycles)
Definition at line 52 of file simulate.cc.
References async_alarm, async_event, async_exception, async_exit, async_io, async_statdump, async_statreset, curTick(), EventQueue::empty(), exitSimLoop(), hack_once, inform, lastExitTick, mainEventQueue, MaxTick, EventQueue::nextTick(), panic, pollQueue, Stats::schedStatEvent(), EventQueue::schedule(), Event::scheduled(), PollQueue::service(), EventQueue::serviceOne(), and Event::squash().
Referenced by RubySystem::serialize(), and RubySystem::startup().
Variable Documentation
Tick lastExitTick = 0
Simulate for num_cycles additional cycles.
If num_cycles is -1 (the default), do not limit simulation; some other event must terminate the loop. Exported to Python via SWIG.
Returns:
The SimLoopExitEvent that caused the loop to exit.
Definition at line 49 of file simulate.cc.
Referenced by simulate().