gem5: sim/simulate.hh File Reference
sim/simulate.hh File Reference
#include "base/types.hh"
#include "sim/sim_events.hh"
Functions
SimLoopExitEvent * simulate (Tick num_cycles=MaxTick)
Function Documentation
SimLoopExitEvent* simulate (Tick num_cycles = MaxTick)
Definition at line 52 of file simulate.cc.
References async_alarm, async_event, async_exception, async_exit, async_io, async_statdump, async_statreset, curTick(), EventQueue::empty(), exitSimLoop(), hack_once, inform, lastExitTick, mainEventQueue, MaxTick, EventQueue::nextTick(), panic, pollQueue, Stats::schedStatEvent(), EventQueue::schedule(), Event::scheduled(), PollQueue::service(), EventQueue::serviceOne(), and Event::squash().
Referenced by RubySystem::serialize(), and RubySystem::startup().