gem5: base/str.cc File Reference
base/str.cc File Reference
#include <cctype>
#include <cstring>
#include <iostream>
#include <limits>
#include <string>
#include <vector>
#include "base/intmath.hh"
#include "base/str.hh"
Defines
#define STN(type)
Functions
bool split_first (const string &s, string &lhs, string &rhs, char c)
bool split_last (const string &s, string &lhs, string &rhs, char c)
void tokenize (vector< string > &v, const string &s, char token, bool ignore)
template<class T >
bool __to_number (string value, T &retval)
template<>
bool to_number< bool > (const string &value, bool &retval)
Define Documentation
#define STN (type)
Value:
template<> \
bool to_number<type>(const string &value, type &retval) \
{ return __to_number(value, retval); }
Definition at line 322 of file str.cc.
Function Documentation
template<class T > bool __to_number (string value, T & retval) [inline]
Todo:
This function will not handle the smallest negative decimal value for a signed type
Definition at line 117 of file str.cc.
References bits(), ArmISA::c, eat_white(), hex2Int(), ArmISA::i, isDec(), isHex(), isOct(), and X86ISA::val.
bool split_first (const string & s, string & lhs, string & rhs, char c)
Definition at line 44 of file str.cc.
References ArmISA::offset.
bool split_last (const string & s, string & lhs, string & rhs, char c)
Definition at line 59 of file str.cc.
References ArmISA::offset.
template<> bool to_number< bool > (const string & value, bool & retval)
void tokenize (vector< string > & v, const string & s, char token, bool ignore)
Definition at line 74 of file str.cc.
Referenced by arrayParamIn(), Stats::Info::less(), main(), and Stats::validateStatName().