gem5: Net::IpOpt Struct Reference
Net::IpOpt Struct Reference
#include <inet.hh>
Public Member Functions
uint8_t type () const
uint8_t typeNumber () const
uint8_t typeClass () const
uint8_t typeCopied () const
uint8_t len () const
bool isNumber (int num) const
bool isClass (int cls) const
bool isCopied (int cpy) const
const uint8_t * data () const
void sec (ip_opt_data_sec &sec) const
void lsrr (ip_opt_data_rr &rr) const
void ssrr (ip_opt_data_rr &rr) const
void ts (ip_opt_data_ts &ts) const
uint16_t satid () const
uint16_t mtup () const
uint16_t mtur () const
void tr (ip_opt_data_tr &tr) const
const uint32_t * addext () const
uint16_t rtralt () const
void sdb (std::vector< uint32_t > &vec) const
Detailed Description
Definition at line 286 of file inet.hh.
Member Function Documentation
const uint32_t* Net::IpOpt::addext () const [inline]
Definition at line 307 of file inet.hh.
const uint8_t* Net::IpOpt::data () const [inline]
Definition at line 298 of file inet.hh.
bool Net::IpOpt::isClass (int cls) const [inline]
Definition at line 295 of file inet.hh.
References typeClass().
bool Net::IpOpt::isCopied (int cpy) const [inline]
Definition at line 296 of file inet.hh.
References typeCopied().
bool Net::IpOpt::isNumber (int num) const [inline]
Definition at line 294 of file inet.hh.
References typeNumber().
uint8_t Net::IpOpt::len () const [inline]
Definition at line 292 of file inet.hh.
References type().
Referenced by Net::IpHdr::options().
void Net::IpOpt::lsrr (ip_opt_data_rr & rr) const
uint16_t Net::IpOpt::mtup () const [inline]
Definition at line 304 of file inet.hh.
uint16_t Net::IpOpt::mtur () const [inline]
Definition at line 305 of file inet.hh.
uint16_t Net::IpOpt::rtralt () const [inline]
Definition at line 308 of file inet.hh.
uint16_t Net::IpOpt::satid () const [inline]
Definition at line 303 of file inet.hh.
void Net::IpOpt::sdb (std::vector< uint32_t > & vec) const
void Net::IpOpt::sec (ip_opt_data_sec & sec) const
void Net::IpOpt::ssrr (ip_opt_data_rr & rr) const
void Net::IpOpt::tr (ip_opt_data_tr & tr) const
void Net::IpOpt::ts (ip_opt_data_ts & ts) const
uint8_t Net::IpOpt::type () const [inline]
Definition at line 288 of file inet.hh.
Referenced by len().
uint8_t Net::IpOpt::typeClass () const [inline]
Definition at line 290 of file inet.hh.
Referenced by isClass().
uint8_t Net::IpOpt::typeCopied () const [inline]
Definition at line 291 of file inet.hh.
Referenced by isCopied().
uint8_t Net::IpOpt::typeNumber () const [inline]
Definition at line 289 of file inet.hh.
Referenced by isNumber().
The documentation for this struct was generated from the following file:
base/inet.hh