gem5: ThreadState Struct Reference
ThreadState Struct Reference
Struct for holding general thread state that is needed across CPU models.
#include <thread_state.hh>