gem5: MC146818::RTCEvent Struct Reference
MC146818::RTCEvent Struct Reference
Event for RTC periodic interrupt.