gem5: Net::EthAddr Struct Reference
Net::EthAddr Struct Reference
#include <inet.hh>
Public Member Functions
EthAddr ()
EthAddr (const uint8_t ea[ETH_ADDR_LEN])
EthAddr (const eth_addr &ea)
EthAddr (const std::string &addr)
const EthAddr & operator= (const eth_addr &ea)
const EthAddr & operator= (const std::string &addr)
int size () const
const uint8_t * bytes () const
uint8_t * bytes ()
const uint8_t * addr () const
bool unicast () const
bool multicast () const
bool broadcast () const
std::string string () const
operator uint64_t () const
Protected Member Functions
void parse (const std::string &addr)
Detailed Description
Definition at line 64 of file inet.hh.
Constructor & Destructor Documentation
Net::EthAddr::EthAddr ()
Definition at line 45 of file inet.cc.
Net::EthAddr::EthAddr (const uint8_t ea[ETH_ADDR_LEN])
Definition at line 50 of file inet.cc.
Net::EthAddr::EthAddr (const eth_addr & ea)
Definition at line 55 of file inet.cc.
Net::EthAddr::EthAddr (const std::string & addr)
Definition at line 60 of file inet.cc.
References parse().
Member Function Documentation
const uint8_t* Net::EthAddr::addr () const [inline]
Definition at line 82 of file inet.hh.
Referenced by Net::operator<<().
bool Net::EthAddr::broadcast () const [inline]
Definition at line 85 of file inet.hh.
Referenced by NSGigE::rxFilter(), and NSGigE::rxKick().
const uint8_t* Net::EthAddr::bytes () const [inline]
Definition at line 79 of file inet.hh.
Referenced by parse().
uint8_t* Net::EthAddr::bytes () [inline]
Definition at line 80 of file inet.hh.
bool Net::EthAddr::multicast () const [inline]
Definition at line 84 of file inet.hh.
Referenced by NSGigE::rxFilter(), and NSGigE::rxKick().
Net::EthAddr::operator uint64_t () const [inline]
Definition at line 88 of file inet.hh.
References X86ISA::reg.
const EthAddr & Net::EthAddr::operator= (const eth_addr & ea)
Definition at line 66 of file inet.cc.
const EthAddr & Net::EthAddr::operator= (const std::string & addr)
Definition at line 73 of file inet.cc.
References parse().
void Net::EthAddr::parse (const std::string & addr) [protected]
Definition at line 80 of file inet.cc.
References bytes(), and ArmISA::i.
Referenced by EthAddr(), and operator=().
int Net::EthAddr::size () const [inline]
Definition at line 77 of file inet.hh.
string Net::EthAddr::string () const
Definition at line 102 of file inet.cc.
bool Net::EthAddr::unicast () const [inline]
Definition at line 83 of file inet.hh.
Referenced by NSGigE::rxFilter(), and NSGigE::rxKick().
The documentation for this struct was generated from the following files:
base/inet.hh
base/inet.cc