gem5: AlphaISA::VAddr Struct Reference
AlphaISA::VAddr Struct Reference
#include <pagetable.hh>
Public Member Functions
VAddr (Addr a)
operator Addr () const
const VAddr & operator= (Addr a)
Addr vpn () const
Addr page () const
Addr offset () const
Addr level3 () const
Addr level2 () const
Addr level1 () const
Public Attributes
Addr addr
Static Public Attributes
static const int ImplBits = 43
static const Addr ImplMask = (ULL(1) << ImplBits) - 1
static const Addr UnImplMask = ~ImplMask
Detailed Description
Definition at line 40 of file pagetable.hh.
Constructor & Destructor Documentation
AlphaISA::VAddr::VAddr (Addr a) [inline]
Definition at line 48 of file pagetable.hh.
Member Function Documentation
Addr AlphaISA::VAddr::level1 () const [inline]
Definition at line 60 of file pagetable.hh.
References addr, AlphaISA::NPtePageShift, AlphaISA::PageShift, and AlphaISA::PteAddr().
Addr AlphaISA::VAddr::level2 () const [inline]
Definition at line 58 of file pagetable.hh.
References addr, AlphaISA::NPtePageShift, AlphaISA::PageShift, and AlphaISA::PteAddr().
Addr AlphaISA::VAddr::level3 () const [inline]
Definition at line 56 of file pagetable.hh.
References addr, AlphaISA::PageShift, and AlphaISA::PteAddr().
Addr AlphaISA::VAddr::offset () const [inline]
Definition at line 54 of file pagetable.hh.
References addr, and AlphaISA::PageOffset.
AlphaISA::VAddr::operator Addr () const [inline]
Definition at line 49 of file pagetable.hh.
References addr.
const VAddr& AlphaISA::VAddr::operator= (Addr a) [inline]
Definition at line 50 of file pagetable.hh.
References addr.
Addr AlphaISA::VAddr::page () const [inline]
Definition at line 53 of file pagetable.hh.
References addr, and AlphaISA::PageMask.
Referenced by AlphaISA::NDtbMissFault::invoke(), and AlphaISA::ItbPageFault::invoke().
Addr AlphaISA::VAddr::vpn () const [inline]
Definition at line 52 of file pagetable.hh.
References addr, ImplMask, and AlphaISA::PageShift.
Referenced by AlphaISA::TLB::flushAddr(), AlphaISA::TLB::insert(), AlphaISA::DtbFault::invoke(), AlphaISA::TlbEntry::TlbEntry(), and AlphaISA::TlbEntry::updateVaddr().
Member Data Documentation
Addr AlphaISA::VAddr::addr
Definition at line 46 of file pagetable.hh.
Referenced by level1(), level2(), level3(), offset(), operator Addr(), operator=(), page(), and vpn().
const int AlphaISA::VAddr::ImplBits = 43 [static]
Definition at line 42 of file pagetable.hh.
const Addr AlphaISA::VAddr::ImplMask = (ULL(1) << ImplBits) - 1 [static]
Definition at line 43 of file pagetable.hh.
Referenced by vpn().
const Addr AlphaISA::VAddr::UnImplMask = ~ImplMask [static]
Definition at line 44 of file pagetable.hh.
The documentation for this struct was generated from the following file:
arch/alpha/pagetable.hh