gem5: EmbeddedSwig Struct Reference
EmbeddedSwig Struct Reference
#include <init.hh>
Public Member Functions
EmbeddedSwig (void(*init_func)())
Static Public Member Functions
static std::list< EmbeddedSwig * > & getList ()
static void initAll ()
Public Attributes
void(* initFunc)()
Detailed Description
Definition at line 69 of file init.hh.
Constructor & Destructor Documentation
EmbeddedSwig::EmbeddedSwig (void(*)() init_func)
Definition at line 210 of file init.cc.
References getList().
Member Function Documentation
list< EmbeddedSwig * > & EmbeddedSwig::getList () [static]
Definition at line 217 of file init.cc.
Referenced by EmbeddedSwig(), and initAll().
void EmbeddedSwig::initAll () [static]
Definition at line 224 of file init.cc.
References getList(), and ArmISA::i.
Referenced by initM5Python().
Member Data Documentation
void(* EmbeddedSwig::initFunc)()
Definition at line 71 of file init.hh.
The documentation for this struct was generated from the following files:
sim/init.hh
sim/init.cc