gem5: cp::Print Struct Reference
cp::Print Struct Reference
#include <cprintf.hh>
Public Member Functions
Print (std::ostream &stream, const std::string &format)
Print (std::ostream &stream, const char *format)
~Print ()
int get_number (int data)
template<typename T >
int get_number (const T &data)
template<typename T >
void add_arg (const T &data)
void end_args ()
Protected Member Functions
void process ()
void process_flag ()
Protected Attributes
std::ostream & stream
const char * format
const char * ptr
bool cont
std::ios::fmtflags saved_flags
char saved_fill
int saved_precision
Format fmt
Detailed Description
Definition at line 48 of file cprintf.hh.
Constructor & Destructor Documentation
cp::Print::Print (std::ostream & stream, const std::string & format)
Definition at line 42 of file cprintf.cc.
References saved_fill, saved_flags, and saved_precision.
cp::Print::Print (std::ostream & stream, const char * format)
Definition at line 50 of file cprintf.cc.
References saved_fill, saved_flags, and saved_precision.
cp::Print::~Print ()
Definition at line 58 of file cprintf.cc.
Member Function Documentation
template<typename T > void cp::Print::add_arg (const T & data) [inline]
Definition at line 84 of file cprintf.hh.
References cp::Format::character, cont, cp::Format::floating, fmt, cp::Format::format, cp::format_char(), cp::format_float(), cp::format_integer(), cp::format_string(), get_number(), cp::Format::get_precision, cp::Format::get_width, cp::Format::integer, cp::Format::precision, process(), stream, cp::Format::string, and cp::Format::width.
void cp::Print::end_args ()
Definition at line 272 of file cprintf.cc.
References ArmISA::len, ptr, saved_fill, saved_flags, saved_precision, and stream.
template<typename T > int cp::Print::get_number (const T & data) [inline]
Definition at line 77 of file cprintf.hh.
int cp::Print::get_number (int data) [inline]
Definition at line 70 of file cprintf.hh.
Referenced by add_arg().
void cp::Print::process () [protected]
Definition at line 63 of file cprintf.cc.
References cp::Format::clear(), fmt, ArmISA::len, process_flag(), ptr, and stream.
Referenced by add_arg().
void cp::Print::process_flag () [protected]
Definition at line 100 of file cprintf.cc.
References cp::Format::alternate_form, cp::Format::base, cp::Format::blank_space, cp::Format::fill_zero, cp::Format::float_format, cp::Format::floating, cp::Format::flush_left, fmt, cp::Format::format, cp::Format::get_precision, cp::Format::get_width, cp::Format::integer, cp::Format::precision, cp::Format::print_sign, ptr, stream, cp::Format::uppercase, and cp::Format::width.
Referenced by process().
Member Data Documentation
bool cp::Print::cont [protected]
Definition at line 54 of file cprintf.hh.
Referenced by add_arg().
Format cp::Print::fmt [protected]
Definition at line 60 of file cprintf.hh.
Referenced by add_arg(), process(), and process_flag().
const char* cp::Print::format [protected]
Definition at line 52 of file cprintf.hh.
const char* cp::Print::ptr [protected]
Definition at line 53 of file cprintf.hh.
Referenced by end_args(), process(), and process_flag().
char cp::Print::saved_fill [protected]
Definition at line 57 of file cprintf.hh.
Referenced by end_args(), and Print().
std::ios::fmtflags cp::Print::saved_flags [protected]
Definition at line 56 of file cprintf.hh.
Referenced by end_args(), and Print().
int cp::Print::saved_precision [protected]
Definition at line 58 of file cprintf.hh.
Referenced by end_args(), and Print().
std::ostream& cp::Print::stream [protected]
Definition at line 51 of file cprintf.hh.
Referenced by add_arg(), end_args(), process(), and process_flag().
The documentation for this struct was generated from the following files:
base/cprintf.hh
base/cprintf.cc