gem5: Net::IpHdr Struct Reference
Net::IpHdr Struct Reference
#include <inet.hh>
Public Member Functions
uint8_t version () const
uint8_t hlen () const
uint8_t tos () const
uint16_t len () const
uint16_t id () const
uint16_t frag_flags () const
uint16_t frag_off () const
uint8_t ttl () const
uint8_t proto () const
uint16_t sum () const
uint32_t src () const
uint32_t dst () const
void sum (uint16_t sum)
void id (uint16_t _id)
void len (uint16_t _len)
bool options (std::vector< const IpOpt * > &vec) const
int size () const
const uint8_t * bytes () const
const uint8_t * payload () const
uint8_t * bytes ()
uint8_t * payload ()
Detailed Description
Definition at line 210 of file inet.hh.
Member Function Documentation
const uint8_t* Net::IpHdr::bytes () const [inline]
Definition at line 233 of file inet.hh.
Referenced by options(), and payload().
uint8_t* Net::IpHdr::bytes () [inline]
Definition at line 235 of file inet.hh.
uint32_t Net::IpHdr::dst () const [inline]
Definition at line 223 of file inet.hh.
uint16_t Net::IpHdr::frag_flags () const [inline]
Definition at line 217 of file inet.hh.
uint16_t Net::IpHdr::frag_off () const [inline]
Definition at line 218 of file inet.hh.
uint8_t Net::IpHdr::hlen () const [inline]
Definition at line 213 of file inet.hh.
Referenced by options(), and size().
uint16_t Net::IpHdr::id () const [inline]
Definition at line 216 of file inet.hh.
void Net::IpHdr::id (uint16_t _id) [inline]
Definition at line 226 of file inet.hh.
uint16_t Net::IpHdr::len () const [inline]
Definition at line 215 of file inet.hh.
Referenced by options().
void Net::IpHdr::len (uint16_t _len) [inline]
Definition at line 227 of file inet.hh.
bool Net::IpHdr::options (std::vector< const IpOpt * > & vec) const
Definition at line 216 of file inet.cc.
References bytes(), hlen(), Net::IpOpt::len(), and len().
const uint8_t* Net::IpHdr::payload () const [inline]
Definition at line 234 of file inet.hh.
References bytes(), and size().
uint8_t* Net::IpHdr::payload () [inline]
Definition at line 236 of file inet.hh.
References bytes(), and size().
uint8_t Net::IpHdr::proto () const [inline]
Definition at line 220 of file inet.hh.
int Net::IpHdr::size () const [inline]
Definition at line 232 of file inet.hh.
References hlen().
Referenced by payload().
uint32_t Net::IpHdr::src () const [inline]
Definition at line 222 of file inet.hh.
void Net::IpHdr::sum (uint16_t sum) [inline]
Definition at line 225 of file inet.hh.
uint16_t Net::IpHdr::sum () const [inline]
Definition at line 221 of file inet.hh.
uint8_t Net::IpHdr::tos () const [inline]
Definition at line 214 of file inet.hh.
uint8_t Net::IpHdr::ttl () const [inline]
Definition at line 219 of file inet.hh.
uint8_t Net::IpHdr::version () const [inline]
Definition at line 212 of file inet.hh.
The documentation for this struct was generated from the following files:
base/inet.hh
base/inet.cc