gem5: Stats::Global Struct Reference
Stats::Global Struct Reference
Public Member Functions
Global ()
Public Attributes
Stats::Formula hostInstRate
Stats::Formula hostOpRate
Stats::Formula hostTickRate
Stats::Value hostMemory
Stats::Value hostSeconds
Stats::Value simInsts
Stats::Value simOps
Detailed Description
Definition at line 112 of file stat_control.cc.
Constructor & Destructor Documentation
Stats::Global::Global ()
Definition at line 126 of file stat_control.cc.
References Stats::DataWrap< Derived, InfoProxyType >::desc(), finalTick, SimClock::Frequency, Stats::ValueBase< Derived >::functor(), hostInstRate, hostMemory, hostOpRate, hostSeconds, hostTickRate, memUsage(), Stats::DataWrap< Derived, InfoProxyType >::name(), BaseCPU::numSimulatedInsts(), BaseCPU::numSimulatedOps(), Stats::DataWrap< Derived, InfoProxyType >::precision(), Stats::DataWrap< Derived, InfoProxyType >::prereq(), Stats::registerResetCallback(), Stats::ValueBase< Derived >::scalar(), simFreq, simInsts, simOps, simSeconds, simTicks, Stats::simTicksReset, Stats::statElapsedTicks(), Stats::statElapsedTime(), and Stats::statFinalTick().
Member Data Documentation
Stats::Formula Stats::Global::hostInstRate
Definition at line 114 of file stat_control.cc.
Referenced by Global().
Stats::Value Stats::Global::hostMemory
Definition at line 117 of file stat_control.cc.
Referenced by Global().
Stats::Formula Stats::Global::hostOpRate
Definition at line 115 of file stat_control.cc.
Referenced by Global().
Stats::Value Stats::Global::hostSeconds
Definition at line 118 of file stat_control.cc.
Referenced by Global().
Stats::Formula Stats::Global::hostTickRate
Definition at line 116 of file stat_control.cc.
Referenced by Global().
Stats::Value Stats::Global::simInsts
Definition at line 120 of file stat_control.cc.
Referenced by Global().
Stats::Value Stats::Global::simOps
Definition at line 121 of file stat_control.cc.
Referenced by Global().
The documentation for this struct was generated from the following file:
sim/stat_control.cc