gem5: Net::UdpHdr Struct Reference
Net::UdpHdr Struct Reference
#include <inet.hh>
Public Member Functions
uint16_t sport () const
uint16_t dport () const
uint16_t len () const
uint16_t sum () const
void sum (uint16_t sum)
void len (uint16_t _len)
int size () const
const uint8_t * bytes () const
const uint8_t * payload () const
uint8_t * bytes ()
uint8_t * payload ()
Detailed Description
Definition at line 410 of file inet.hh.
Member Function Documentation
const uint8_t* Net::UdpHdr::bytes () const [inline]
Definition at line 421 of file inet.hh.
Referenced by payload().
uint8_t* Net::UdpHdr::bytes () [inline]
Definition at line 423 of file inet.hh.
uint16_t Net::UdpHdr::dport () const [inline]
Definition at line 413 of file inet.hh.
uint16_t Net::UdpHdr::len () const [inline]
Definition at line 414 of file inet.hh.
void Net::UdpHdr::len (uint16_t _len) [inline]
Definition at line 418 of file inet.hh.
const uint8_t* Net::UdpHdr::payload () const [inline]
Definition at line 422 of file inet.hh.
References bytes(), and size().
uint8_t* Net::UdpHdr::payload () [inline]
Definition at line 424 of file inet.hh.
References bytes(), and size().
int Net::UdpHdr::size () const [inline]
Definition at line 420 of file inet.hh.
Referenced by payload().
uint16_t Net::UdpHdr::sport () const [inline]
Definition at line 412 of file inet.hh.
uint16_t Net::UdpHdr::sum () const [inline]
Definition at line 415 of file inet.hh.
void Net::UdpHdr::sum (uint16_t sum) [inline]
Definition at line 417 of file inet.hh.
The documentation for this struct was generated from the following file:
base/inet.hh