gem5: PowerISA::VAddr Struct Reference
PowerISA::VAddr Struct Reference
#include <pagetable.hh>
Public Member Functions
VAddr (Addr a)
operator Addr () const
const VAddr & operator= (Addr a)
Addr vpn () const
Addr page () const
Addr offset () const
Addr level3 () const
Addr level2 () const
Addr level1 () const
Public Attributes
Addr addr
Static Public Attributes
static const int ImplBits = 43
static const Addr ImplMask = (ULL(1) << ImplBits) - 1
static const Addr UnImplMask = ~ImplMask
Detailed Description
Definition at line 47 of file pagetable.hh.
Constructor & Destructor Documentation
PowerISA::VAddr::VAddr (Addr a) [inline]
Definition at line 55 of file pagetable.hh.
Member Function Documentation
Addr PowerISA::VAddr::level1 () const [inline]
Definition at line 102 of file pagetable.hh.
References addr, PowerISA::NPtePageShift, PowerISA::PageShift, and PowerISA::PteAddr().
Addr PowerISA::VAddr::level2 () const [inline]
Definition at line 96 of file pagetable.hh.
References addr, PowerISA::NPtePageShift, PowerISA::PageShift, and PowerISA::PteAddr().
Addr PowerISA::VAddr::level3 () const [inline]
Definition at line 90 of file pagetable.hh.
References addr, PowerISA::PageShift, and PowerISA::PteAddr().
Addr PowerISA::VAddr::offset () const [inline]
Definition at line 84 of file pagetable.hh.
References addr, and PowerISA::PageOffset.
PowerISA::VAddr::operator Addr () const [inline]
Definition at line 59 of file pagetable.hh.
References addr.
const VAddr& PowerISA::VAddr::operator= (Addr a) [inline]
Definition at line 65 of file pagetable.hh.
References addr.
Addr PowerISA::VAddr::page () const [inline]
Definition at line 78 of file pagetable.hh.
References addr, and PowerISA::Page_Mask.
Addr PowerISA::VAddr::vpn () const [inline]
Definition at line 72 of file pagetable.hh.
References addr, ImplMask, and PowerISA::PageShift.
Member Data Documentation
Addr PowerISA::VAddr::addr
Definition at line 53 of file pagetable.hh.
Referenced by level1(), level2(), level3(), offset(), operator Addr(), operator=(), page(), and vpn().
const int PowerISA::VAddr::ImplBits = 43 [static]
Definition at line 49 of file pagetable.hh.
const Addr PowerISA::VAddr::ImplMask = (ULL(1) << ImplBits) - 1 [static]
Definition at line 50 of file pagetable.hh.
Referenced by vpn().
const Addr PowerISA::VAddr::UnImplMask = ~ImplMask [static]
Definition at line 51 of file pagetable.hh.
The documentation for this struct was generated from the following file:
arch/power/pagetable.hh