gem5: Net::TcpHdr Struct Reference
Net::TcpHdr Struct Reference
#include <inet.hh>
Public Member Functions
uint16_t sport () const
uint16_t dport () const
uint32_t seq () const
uint32_t ack () const
uint8_t off () const
uint8_t flags () const
uint16_t win () const
uint16_t sum () const
uint16_t urp () const
void sum (uint16_t sum)
void seq (uint32_t _seq)
void flags (uint8_t _flags)
bool options (std::vector< const TcpOpt * > &vec) const
int size () const
const uint8_t * bytes () const
const uint8_t * payload () const
uint8_t * bytes ()
uint8_t * payload ()
Detailed Description
Definition at line 316 of file inet.hh.
Member Function Documentation
uint32_t Net::TcpHdr::ack () const [inline]
Definition at line 321 of file inet.hh.
uint8_t* Net::TcpHdr::bytes () [inline]
Definition at line 337 of file inet.hh.
const uint8_t* Net::TcpHdr::bytes () const [inline]
Definition at line 335 of file inet.hh.
Referenced by options(), and payload().
uint16_t Net::TcpHdr::dport () const [inline]
Definition at line 319 of file inet.hh.
void Net::TcpHdr::flags (uint8_t _flags) [inline]
Definition at line 330 of file inet.hh.
uint8_t Net::TcpHdr::flags () const [inline]
Definition at line 323 of file inet.hh.
uint8_t Net::TcpHdr::off () const [inline]
Definition at line 322 of file inet.hh.
Referenced by options(), and size().
bool Net::TcpHdr::options (std::vector< const TcpOpt * > & vec) const
Definition at line 237 of file inet.cc.
References bytes(), Net::TcpOpt::len(), ArmISA::len, and off().
const uint8_t* Net::TcpHdr::payload () const [inline]
Definition at line 336 of file inet.hh.
References bytes(), and size().
uint8_t* Net::TcpHdr::payload () [inline]
Definition at line 338 of file inet.hh.
References bytes(), and size().
void Net::TcpHdr::seq (uint32_t _seq) [inline]
Definition at line 329 of file inet.hh.
uint32_t Net::TcpHdr::seq () const [inline]
Definition at line 320 of file inet.hh.
int Net::TcpHdr::size () const [inline]
Definition at line 334 of file inet.hh.
References off().
Referenced by payload().
uint16_t Net::TcpHdr::sport () const [inline]
Definition at line 318 of file inet.hh.
void Net::TcpHdr::sum (uint16_t sum) [inline]
Definition at line 328 of file inet.hh.
uint16_t Net::TcpHdr::sum () const [inline]
Definition at line 325 of file inet.hh.
uint16_t Net::TcpHdr::urp () const [inline]
Definition at line 326 of file inet.hh.
uint16_t Net::TcpHdr::win () const [inline]
Definition at line 324 of file inet.hh.
The documentation for this struct was generated from the following files:
base/inet.hh
base/inet.cc