gem5: MC146818::RTCTickEvent Struct Reference
MC146818::RTCTickEvent Struct Reference
Event for RTC periodic interrupt.