gem5: Trie< Key, Value >::Node Struct Reference
Trie< Key, Value >::Node Struct Reference
#include <trie.hh>
Public Member Functions
bool matches (Key test)
Node (Key _key, Key _mask, Value *_val)
void clear ()
void dump (int level)
Public Attributes
Key key
Key mask
Value * value
Node * parent
Node * kids [2]
Detailed Description
template<class Key, class Value>
struct Trie< Key, Value >::Node
Definition at line 45 of file trie.hh.
Constructor & Destructor Documentation
template<class Key, class Value> Trie< Key, Value >::Node::Node (Key _key, Key _mask, Value * _val) [inline]
Definition at line 61 of file trie.hh.
References Trie< Key, Value >::Node::kids.
Member Function Documentation
template<class Key, class Value> void Trie< Key, Value >::Node::clear () [inline]
Definition at line 70 of file trie.hh.
References Trie< Key, Value >::Node::clear(), and Trie< Key, Value >::Node::kids.
Referenced by Trie< Addr, X86ISA::TlbEntry >::clear(), and Trie< Key, Value >::Node::clear().
template<class Key, class Value> void Trie< Key, Value >::Node::dump (int level) [inline]
Definition at line 85 of file trie.hh.
References cprintf(), Trie< Key, Value >::Node::dump(), ArmISA::i, Trie< Key, Value >::Node::key, Trie< Key, Value >::Node::kids, Trie< Key, Value >::Node::mask, Trie< Key, Value >::Node::parent, and Trie< Key, Value >::Node::value.
Referenced by Trie< Addr, X86ISA::TlbEntry >::dump(), and Trie< Key, Value >::Node::dump().
template<class Key, class Value> bool Trie< Key, Value >::Node::matches (Key test) [inline]
Definition at line 51 of file trie.hh.
References Trie< Key, Value >::Node::key, and Trie< Key, Value >::Node::mask.
Member Data Documentation
template<class Key, class Value> Key Trie< Key, Value >::Node::key
Definition at line 47 of file trie.hh.
Referenced by Trie< Key, Value >::Node::dump(), and Trie< Key, Value >::Node::matches().
template<class Key, class Value> Node* Trie< Key, Value >::Node::kids[2]
Definition at line 59 of file trie.hh.
Referenced by Trie< Key, Value >::Node::clear(), Trie< Key, Value >::Node::dump(), Trie< Addr, X86ISA::TlbEntry >::lookupHandle(), and Trie< Key, Value >::Node::Node().
template<class Key, class Value> Key Trie< Key, Value >::Node::mask
Definition at line 48 of file trie.hh.
Referenced by Trie< Key, Value >::Node::dump(), and Trie< Key, Value >::Node::matches().
template<class Key, class Value> Node* Trie< Key, Value >::Node::parent
Definition at line 58 of file trie.hh.
Referenced by Trie< Key, Value >::Node::dump().
template<class Key, class Value> Value* Trie< Key, Value >::Node::value
Definition at line 56 of file trie.hh.
Referenced by Trie< Key, Value >::Node::dump().
The documentation for this struct was generated from the following file:
base/trie.hh