gem5: ArmISA::TableWalker::L2Descriptor Struct Reference
ArmISA::TableWalker::L2Descriptor Struct Reference
Level 2 page table descriptor.
#include <table_walker.hh>
Public Member Functions
bool invalid () const
Is the entry invalid.
bool large () const
What is the size of the mapping?
bool xn () const
Is execution allowed on this mapping?
bool global () const
Is the translation global (no asid used)?
uint8_t ap () const
Three bit access protection flags.
uint8_t texcb () const
Memory region attributes: ARM DDI 0406B: B3-32.
Addr pfn () const
Return the physical frame, bits shifted right.
Addr paddr (Addr va) const
Return complete physical address given a VA.
bool shareable () const
If the section is shareable.
void setAp0 ()
Set access flag that this entry has been touched.
bool dirty () const
This entry needs to be written back to memory.
Public Attributes
uint32_t data
The raw bits of the entry.
bool _dirty
This entry has been modified (access flag set) and needs to be written back to memory.
Detailed Description
Level 2 page table descriptor.
Definition at line 177 of file table_walker.hh.
Member Function Documentation
uint8_t ArmISA::TableWalker::L2Descriptor::ap () const [inline]
Three bit access protection flags.
Definition at line 211 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL2Descriptor().
bool ArmISA::TableWalker::L2Descriptor::dirty () const [inline]
This entry needs to be written back to memory.
Definition at line 255 of file table_walker.hh.
References _dirty.
bool ArmISA::TableWalker::L2Descriptor::global () const [inline]
Is the translation global (no asid used)?
Definition at line 205 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL2Descriptor().
bool ArmISA::TableWalker::L2Descriptor::invalid () const [inline]
Is the entry invalid.
Definition at line 187 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL2Descriptor(), and X86ISA::vtophys().
bool ArmISA::TableWalker::L2Descriptor::large () const [inline]
What is the size of the mapping?
Definition at line 193 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL2Descriptor(), paddr(), pfn(), texcb(), and xn().
Addr ArmISA::TableWalker::L2Descriptor::paddr (Addr va) const [inline]
Return complete physical address given a VA.
Definition at line 231 of file table_walker.hh.
References data, large(), and mbits().
Referenced by X86ISA::vtophys().
Addr ArmISA::TableWalker::L2Descriptor::pfn () const [inline]
Return the physical frame, bits shifted right.
Definition at line 225 of file table_walker.hh.
References bits(), data, and large().
Referenced by ArmISA::TableWalker::doL2Descriptor().
void ArmISA::TableWalker::L2Descriptor::setAp0 () [inline]
Set access flag that this entry has been touched.
Mark the entry as requiring a writeback, in the future.
Definition at line 248 of file table_walker.hh.
References _dirty, and data.
bool ArmISA::TableWalker::L2Descriptor::shareable () const [inline]
If the section is shareable.
See texcb() comment.
Definition at line 240 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL2Descriptor().
uint8_t ArmISA::TableWalker::L2Descriptor::texcb () const [inline]
Memory region attributes: ARM DDI 0406B: B3-32.
Definition at line 217 of file table_walker.hh.
References bits(), data, and large().
Referenced by ArmISA::TableWalker::doL2Descriptor().
bool ArmISA::TableWalker::L2Descriptor::xn () const [inline]
Is execution allowed on this mapping?
Definition at line 199 of file table_walker.hh.
References bits(), data, and large().
Referenced by ArmISA::TableWalker::doL2Descriptor().
Member Data Documentation
bool ArmISA::TableWalker::L2Descriptor::_dirty
This entry has been modified (access flag set) and needs to be written back to memory.
Definition at line 184 of file table_walker.hh.
Referenced by dirty(), and setAp0().
uint32_t ArmISA::TableWalker::L2Descriptor::data
The raw bits of the entry.
Definition at line 180 of file table_walker.hh.
Referenced by ap(), ArmISA::TableWalker::doL1Descriptor(), ArmISA::TableWalker::doL2Descriptor(), global(), invalid(), large(), paddr(), pfn(), setAp0(), shareable(), texcb(), X86ISA::vtophys(), and xn().
The documentation for this struct was generated from the following file:
arch/arm/table_walker.hh