gem5: ArmISA::TableWalker::L1Descriptor Struct Reference
ArmISA::TableWalker::L1Descriptor Struct Reference
#include <table_walker.hh>
Public Types
enum EntryType { Ignore, PageTable, Section, Reserved }
Type of page table entry ARM DDI 0406B: B3-8.
Public Member Functions
EntryType type () const
bool supersection () const
Is the page a Supersection (16MB)?
Addr paddr () const
Return the physcal address of the entry, bits in position.
Addr paddr (Addr va) const
Return the physcal address of the entry, bits in position.
Addr pfn () const
Return the physical frame, bits shifted right.
bool global () const
Is the translation global (no asid used)?
bool xn () const
Is the translation not allow execution?
uint8_t ap () const
Three bit access protection flags.
uint8_t domain () const
Domain Client/Manager: ARM DDI 0406B: B3-31.
Addr l2Addr () const
Address of L2 descriptor if it exists.
uint8_t texcb () const
Memory region attributes: ARM DDI 0406B: B3-32.
bool shareable () const
If the section is shareable.
void setAp0 ()
Set access flag that this entry has been touched.
bool dirty () const
This entry needs to be written back to memory.
Public Attributes
uint32_t data
The raw bits of the entry.
bool _dirty
This entry has been modified (access flag set) and needs to be written back to memory.
Detailed Description
Definition at line 63 of file table_walker.hh.
Member Enumeration Documentation
enum ArmISA::TableWalker::L1Descriptor::EntryType
Type of page table entry ARM DDI 0406B: B3-8.
Enumerator:
Ignore
PageTable
Section
Reserved
Definition at line 65 of file table_walker.hh.
Member Function Documentation
uint8_t ArmISA::TableWalker::L1Descriptor::ap () const [inline]
Three bit access protection flags.
Definition at line 127 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL1Descriptor().
bool ArmISA::TableWalker::L1Descriptor::dirty () const [inline]
This entry needs to be written back to memory.
Definition at line 170 of file table_walker.hh.
References _dirty.
uint8_t ArmISA::TableWalker::L1Descriptor::domain () const [inline]
Domain Client/Manager: ARM DDI 0406B: B3-31.
Definition at line 133 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL1Descriptor(), and ArmISA::TableWalker::doL2Descriptor().
bool ArmISA::TableWalker::L1Descriptor::global () const [inline]
Is the translation global (no asid used)?
Definition at line 115 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL1Descriptor().
Addr ArmISA::TableWalker::L1Descriptor::l2Addr () const [inline]
Address of L2 descriptor if it exists.
Definition at line 139 of file table_walker.hh.
References data, and mbits().
Referenced by ArmISA::TableWalker::doL1Descriptor(), and X86ISA::vtophys().
Addr ArmISA::TableWalker::L1Descriptor::paddr (Addr va) const [inline]
Return the physcal address of the entry, bits in position.
Definition at line 98 of file table_walker.hh.
References data, mbits(), panic, and supersection().
Addr ArmISA::TableWalker::L1Descriptor::paddr () const [inline]
Return the physcal address of the entry, bits in position.
Definition at line 91 of file table_walker.hh.
References data, mbits(), panic, and supersection().
Referenced by X86ISA::vtophys().
Addr ArmISA::TableWalker::L1Descriptor::pfn () const [inline]
Return the physical frame, bits shifted right.
Definition at line 107 of file table_walker.hh.
References bits(), data, panic, and supersection().
Referenced by ArmISA::TableWalker::doL1Descriptor().
void ArmISA::TableWalker::L1Descriptor::setAp0 () [inline]
Set access flag that this entry has been touched.
Mark the entry as requiring a writeback, in the future.
Definition at line 163 of file table_walker.hh.
References _dirty, and data.
bool ArmISA::TableWalker::L1Descriptor::shareable () const [inline]
If the section is shareable.
See texcb() comment.
Definition at line 155 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL1Descriptor().
bool ArmISA::TableWalker::L1Descriptor::supersection () const [inline]
Is the page a Supersection (16MB)?
Definition at line 85 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL1Descriptor(), paddr(), and pfn().
uint8_t ArmISA::TableWalker::L1Descriptor::texcb () const [inline]
Memory region attributes: ARM DDI 0406B: B3-32.
These bits are largly ignored by M5 and only used to provide the illusion that the memory system cares about anything but cachable vs. uncachable.
Definition at line 149 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL1Descriptor().
EntryType ArmISA::TableWalker::L1Descriptor::type () const [inline]
Definition at line 79 of file table_walker.hh.
References data.
Referenced by ArmISA::TableWalker::doL1Descriptor(), and X86ISA::vtophys().
bool ArmISA::TableWalker::L1Descriptor::xn () const [inline]
Is the translation not allow execution?
Definition at line 121 of file table_walker.hh.
References bits(), and data.
Referenced by ArmISA::TableWalker::doL1Descriptor().
Member Data Documentation
bool ArmISA::TableWalker::L1Descriptor::_dirty
This entry has been modified (access flag set) and needs to be written back to memory.
Definition at line 77 of file table_walker.hh.
Referenced by dirty(), and setAp0().
uint32_t ArmISA::TableWalker::L1Descriptor::data
The raw bits of the entry.
Definition at line 73 of file table_walker.hh.
Referenced by ap(), ArmISA::TableWalker::doL1Descriptor(), ArmISA::TableWalker::doL1DescriptorWrapper(), domain(), global(), l2Addr(), paddr(), pfn(), ArmISA::TableWalker::processWalk(), setAp0(), shareable(), supersection(), texcb(), type(), X86ISA::vtophys(), and xn().
The documentation for this struct was generated from the following file:
arch/arm/table_walker.hh