gem5: cpu/thread_context.hh File Reference
cpu/thread_context.hh File Reference
#include <iostream>
#include <string>
#include "arch/registers.hh"
#include "arch/types.hh"
#include "base/types.hh"
#include "config/the_isa.hh"
Classes
class ThreadContext
ThreadContext is the external interface to all thread state for anything outside of the CPU.
class ProxyThreadContext< TC >
ProxyThreadContext class that provides a way to implement a ThreadContext without having to derive from it.
Namespaces
namespace TheISA
namespace TheISA::Kernel
Functions
void takeOverFrom (ThreadContext &new_tc, ThreadContext &old_tc)
Copy state between thread contexts in preparation for CPU handover.
void serialize (ThreadContext &tc, std::ostream &os)
Thread context serialization helpers.
void unserialize (ThreadContext &tc, Checkpoint *cp, const std::string &section)
Function Documentation
void serialize (ThreadContext & tc, std::ostream & os)
Thread context serialization helpers.
These helper functions provide a way to the data in a ThreadContext. They are provided as separate helper function since implementing them as members of the ThreadContext interface would be confusing when the ThreadContext is exported via a proxy.
Definition at line 98 of file thread_context.cc.
References arrayParamOut(), ArmISA::i, AlphaISA::NumFloatRegs, AlphaISA::NumIntRegs, ThreadContext::pcState(), ThreadContext::readFloatRegBitsFlat(), ThreadContext::readIntRegFlat(), and SERIALIZE_ARRAY.
Referenced by ArmISA::EndBitUnion(), and X86ISA::EndBitUnion().
void takeOverFrom (ThreadContext & new_tc, ThreadContext & old_tc)
Copy state between thread contexts in preparation for CPU handover.
Note:
This method modifies the old thread contexts as well as the new thread context. The old thread context will have its quiesce event descheduled if it is scheduled and its status set to halted.
Parameters:
new_tc Destination ThreadContext.
old_tc Source ThreadContext.
Definition at line 144 of file thread_context.cc.
References ThreadContext::contextId(), ThreadContext::copyArchRegs(), FullSystem, ThreadContext::getCpuPtr(), ThreadContext::getProcessPtr(), ThreadContext::getQuiesceEvent(), ThreadContext::getSystemPtr(), ThreadContext::Halted, ThreadContext::setContextId(), ThreadContext::setStatus(), ThreadContext::setThreadId(), ThreadContext::status(), and ThreadContext::threadId().
void unserialize (ThreadContext & tc, Checkpoint * cp, const std::string & section)
Definition at line 120 of file thread_context.cc.
References arrayParamIn(), ArmISA::i, AlphaISA::NumFloatRegs, AlphaISA::NumIntRegs, ThreadContext::pcState(), ThreadContext::setFloatRegBitsFlat(), ThreadContext::setIntRegFlat(), and UNSERIALIZE_ARRAY.
Referenced by ArmISA::EndBitUnion(), and X86ISA::EndBitUnion().