gem5: mem/ruby/network/simple/Throttle.cc File Reference
mem/ruby/network/simple/Throttle.cc File Reference
#include <cassert>
#include "base/cast.hh"
#include "base/cprintf.hh"
#include "debug/RubyNetwork.hh"
#include "mem/ruby/buffers/MessageBuffer.hh"
#include "mem/ruby/network/simple/Throttle.hh"
#include "mem/ruby/network/Network.hh"
#include "mem/ruby/slicc_interface/NetworkMessage.hh"
#include "mem/ruby/system/System.hh"
Functions
static int network_message_to_size (NetworkMessage *net_msg_ptr)
Variables
const int HIGH_RANGE = 256
const int ADJUST_INTERVAL = 50000
const int MESSAGE_SIZE_MULTIPLIER = 1000
const int BROADCAST_SCALING = 1
const int PRIORITY_SWITCH_LIMIT = 128
Function Documentation
int network_message_to_size (NetworkMessage * net_msg_ptr) [static]
Definition at line 260 of file Throttle.cc.
References BROADCAST_SCALING, NetworkMessage::getDestination(), NetworkMessage::getMessageSize(), NetDest::isBroadcast(), MESSAGE_SIZE_MULTIPLIER, and Network::MessageSizeType_to_int().
Referenced by Throttle::wakeup().
Variable Documentation
const int ADJUST_INTERVAL = 50000
Definition at line 43 of file Throttle.cc.
const int BROADCAST_SCALING = 1
Definition at line 46 of file Throttle.cc.
Referenced by network_message_to_size().
const int HIGH_RANGE = 256
Definition at line 42 of file Throttle.cc.
const int MESSAGE_SIZE_MULTIPLIER = 1000
Definition at line 44 of file Throttle.cc.
Referenced by network_message_to_size().
const int PRIORITY_SWITCH_LIMIT = 128
Definition at line 47 of file Throttle.cc.