gem5: base/time.hh File Reference
base/time.hh File Reference
#include <sys/time.h>
#include <inttypes.h>
#include <cmath>
#include <cstring>
#include <ctime>
#include <iosfwd>
#include <iostream>
#include <string>
#include "base/types.hh"
Classes
class Time
Functions
void sleep (const Time &time)
bool operator== (const Time &l, const Time &r)
bool operator!= (const Time &l, const Time &r)
bool operator< (const Time &l, const Time &r)
bool operator<= (const Time &l, const Time &r)
bool operator> (const Time &l, const Time &r)
bool operator>= (const Time &l, const Time &r)
Time operator+ (const Time &l, const Time &r)
Time operator- (const Time &l, const Time &r)
std::ostream & operator<< (std::ostream &out, const Time &time)
time_t mkutctime (struct tm *time)
Function Documentation
time_t mkutctime (struct tm * time)
Definition at line 151 of file time.cc.
Referenced by MC146818::tickClock().
bool operator!= (const Time & l, const Time & r) [inline]
Definition at line 215 of file time.hh.
References Time::nsec(), and Time::sec().
Time operator+ (const Time & l, const Time & r) [inline]
Definition at line 249 of file time.hh.
Time operator- (const Time & l, const Time & r) [inline]
Definition at line 257 of file time.hh.
bool operator< (const Time & l, const Time & r) [inline]
Definition at line 221 of file time.hh.
References Time::nsec(), and Time::sec().
std::ostream& operator<< (std::ostream & out, const Time & time) [inline]
Definition at line 265 of file time.hh.
References Time::date().
bool operator<= (const Time & l, const Time & r) [inline]
Definition at line 228 of file time.hh.
References Time::nsec(), and Time::sec().
bool operator== (const Time & l, const Time & r) [inline]
Definition at line 209 of file time.hh.
References Time::nsec(), and Time::sec().
bool operator> (const Time & l, const Time & r) [inline]
Definition at line 235 of file time.hh.
References Time::nsec(), and Time::sec().
bool operator>= (const Time & l, const Time & r) [inline]
Definition at line 242 of file time.hh.
References Time::nsec(), and Time::sec().
void sleep (const Time & time)
Definition at line 139 of file time.cc.
References MipsISA::ts.
Referenced by Root::timeSync().