gem5: mem/ruby/network/Topology.cc File Reference
mem/ruby/network/Topology.cc File Reference
#include <cassert>
#include "base/trace.hh"
#include "debug/RubyNetwork.hh"
#include "mem/protocol/MachineType.hh"
#include "mem/ruby/common/NetDest.hh"
#include "mem/ruby/network/BasicLink.hh"
#include "mem/ruby/network/Network.hh"
#include "mem/ruby/network/Topology.hh"
#include "mem/ruby/slicc_interface/AbstractController.hh"
Functions
void extend_shortest_path (Matrix &current_dist, Matrix &latencies, Matrix &inter_switches)
Matrix shortest_path (const Matrix &weights, Matrix &latencies, Matrix &inter_switches)
bool link_is_shortest_path_to_node (SwitchID src, SwitchID next, SwitchID final, const Matrix &weights, const Matrix &dist)
NetDest shortest_path_to_node (SwitchID src, SwitchID next, const Matrix &weights, const Matrix &dist)
Variables
const int INFINITE_LATENCY = 10000
Function Documentation
void extend_shortest_path (Matrix & current_dist, Matrix & latencies, Matrix & inter_switches)
Definition at line 269 of file Topology.cc.
References ArmISA::i, ArmISA::j, and MipsISA::k.
Referenced by shortest_path().
bool link_is_shortest_path_to_node (SwitchID src, SwitchID next, SwitchID final, const Matrix & weights, const Matrix & dist)
Definition at line 315 of file Topology.cc.
Referenced by shortest_path_to_node().
Matrix shortest_path (const Matrix & weights, Matrix & latencies, Matrix & inter_switches)
Definition at line 307 of file Topology.cc.
References Stats::dist, and extend_shortest_path().
Referenced by Topology::createLinks().
NetDest shortest_path_to_node (SwitchID src, SwitchID next, const Matrix & weights, const Matrix & dist)
Definition at line 322 of file Topology.cc.
References NetDest::add(), MipsISA::d, DPRINTF, ArmISA::i, link_is_shortest_path_to_node(), and ArmISA::m.
Referenced by Topology::createLinks().
Variable Documentation
const int INFINITE_LATENCY = 10000
Definition at line 42 of file Topology.cc.
Referenced by Topology::createLinks().