gem5: unittest/trietest.cc File Reference
unittest/trietest.cc File Reference
#include <cassert>
#include <iostream>
#include "base/cprintf.hh"
#include "base/trie.hh"
#include "base/types.hh"
#include "unittest/unittest.hh"
Typedefs
typedef Trie< Addr, uint32_t > TestTrie
Functions
int main ()
Typedef Documentation
typedef Trie<Addr, uint32_t> TestTrie
Definition at line 41 of file trietest.cc.
Function Documentation
int main ()
Definition at line 44 of file trietest.cc.
References cprintf(), Trie< Key, Value >::dump(), EXPECT_EQ, Trie< Key, Value >::insert(), Trie< Key, Value >::lookup(), UnitTest::printResults(), Trie< Key, Value >::remove(), and UnitTest::setCase().