gem5: arch/x86/linux/syscalls.cc File Reference
arch/x86/linux/syscalls.cc File Reference
#include "arch/x86/linux/linux.hh"
#include "arch/x86/linux/process.hh"
#include "arch/x86/regs/misc.hh"
#include "kern/linux/linux.hh"
#include "sim/syscall_emul.hh"
Classes
struct UserDesc64
Functions
static SyscallReturn unameFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Target uname() handler.
static SyscallReturn archPrctlFunc (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
BitUnion32 (UserDescFlags) Bitfield< 0 > seg_32bit
EndBitUnion (UserDescFlags) struct UserDesc32
static SyscallReturn setThreadArea32Func (SyscallDesc *desc, int callnum, LiveProcess *process, ThreadContext *tc)
Variables
Bitfield< 2, 1 > contents
Bitfield< 3 > read_exec_only
Bitfield< 4 > limit_in_pages
Bitfield< 5 > seg_not_present
Bitfield< 6 > useable
Function Documentation
static SyscallReturn archPrctlFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [static]
Definition at line 68 of file syscalls.cc.
References X86ISA::addr, ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), X86ISA::index, X86ISA::MISCREG_FS_BASE, X86ISA::MISCREG_FS_EFF_BASE, X86ISA::MISCREG_GS_BASE, X86ISA::MISCREG_GS_EFF_BASE, X86ISA::p, ThreadContext::readMiscRegNoEffect(), ThreadContext::setMiscRegNoEffect(), and PortProxy::write().
BitUnion32 (UserDescFlags)
EndBitUnion (UserDescFlags)
Definition at line 116 of file syscalls.cc.
static SyscallReturn setThreadArea32Func (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [static]
Definition at line 134 of file syscalls.cc.
References bits(), X86ISA::X86LiveProcess::gdtSize(), X86ISA::X86LiveProcess::gdtStart(), ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), ArmISA::i, X86ISA::index, SyscallDesc::name, and panic.
static SyscallReturn unameFunc (SyscallDesc * desc, int callnum, LiveProcess * process, ThreadContext * tc) [static]
Target uname() handler.
Definition at line 50 of file syscalls.cc.
References ThreadContext::getMemProxy(), LiveProcess::getSyscallArg(), X86ISA::index, and name().
Variable Documentation
Bitfield<2, 1> contents
Definition at line 111 of file syscalls.cc.
Bitfield<4> limit_in_pages
Definition at line 113 of file syscalls.cc.
Bitfield<3> read_exec_only
Definition at line 112 of file syscalls.cc.
Bitfield<5> seg_not_present
Definition at line 114 of file syscalls.cc.
Bitfield<6> useable
Definition at line 115 of file syscalls.cc.